/**
 * Advanced (C1), 81–100-unit'lar: yozuv uslubi, noaniq ifodalar, so'z
 * yasalishi, iboralar va nutq uslublari. Tamoyillar — elementary.js va
 * advanced.js dagi izohlarga qarang.
 *
 * Kiritilmagan: 85 (qisqartmalar — ko'pi B2 da bor), 91 (ko'p ma'nolilik —
 * indeksda 10 ta so'z, ular boshqa mavzularda takrorlanadi).
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 81,
    title: 'Writing: style and format',
    titleUz: 'Yozuv: uslub va format',
    emoji: '✍️',
    words: [
      ['bullet point', 'phrase', "marker (ro'yxat belgisi)", 'List your main ideas as bullet points.', "Asosiy fikrlaringizni band-band qilib yozing."],
      ['font', 'noun', 'shrift', 'Use a clear font like Arial.', 'Arial kabi aniq shriftdan foydalaning.'],
      ['italics', 'noun', 'kursiv', 'Book titles are written in italics.', 'Kitob nomlari kursivda yoziladi.'],
      ['bold', 'adjective', 'qalin (shrift)', 'Important words are in bold.', "Muhim so'zlar qalin harfda."],
      ['brackets', 'noun', 'qavslar', 'Put the extra information in brackets.', "Qo'shimcha ma'lumotni qavs ichiga oling."],
      ['inverted commas', 'phrase', "qo'shtirnoq", 'Put the quotation in inverted commas.', "Iqtibosni qo'shtirnoq ichiga oling."],
      ['asterisk', 'noun', 'yulduzcha (*)', 'An asterisk shows there is a note at the bottom.', 'Yulduzcha sahifa pastida izoh borligini bildiradi.'],
      ['indent', 'verb', 'xatboshini ichkaridan boshlamoq', 'Indent the first line of each paragraph.', 'Har bir xatboshining birinchi qatorini ichkaridan boshlang.'],
      ['upper case', 'phrase', 'bosh harflar', 'Write your name in upper case.', 'Ismingizni bosh harflarda yozing.'],
      ['lower case', 'phrase', 'kichik harflar', 'Email addresses are usually in lower case.', "Elektron manzillar odatda kichik harflarda bo'ladi."],
      ['block capitals', 'phrase', 'bosma bosh harflar', 'Please fill in the form in block capitals.', "Iltimos, anketani bosma bosh harflarda to'ldiring."],
      ['draft', 'noun', 'qoralama', 'This is only the first draft of my essay.', 'Bu inshomning faqat birinchi qoralamasi.'],
      ['jot down', 'phrase', 'tezda yozib olmoq', 'Let me jot down your number.', 'Raqamingizni yozib olay.'],
      ['scribble', 'verb', 'shoshib qoralamoq', 'He scribbled a note and left.', 'U shoshib bir yozuv qoralab, chiqib ketdi.'],
      ['doodle', 'verb', "(beixtiyor) chizib o'tirmoq", "I doodle when I'm on the phone.", "Telefonda gaplashayotganda qog'ozga chizib o'tiraman."],
      ['touch-type', 'verb', "ko'r usulda yozmoq (klaviaturaga qaramay)", 'Learning to touch-type saves a lot of time.', "Ko'r usulda yozishni o'rganish ko'p vaqtni tejaydi."],
      ['sub-heading', 'noun', 'kichik sarlavha', 'Divide your report into sections with sub-headings.', "Hisobotingizni kichik sarlavhalar bilan bo'limlarga ajrating."],
      ['cut and paste', 'phrase', "qirqib olib qo'ymoq", 'You can cut and paste text between documents.', "Hujjatlar o'rtasida matnni qirqib olib qo'yishingiz mumkin."],
    ],
  },
  {
    unit: 82,
    title: 'Whatchamacallit: being indirect',
    titleUz: 'Bilvosita gapirish',
    emoji: '🤷',
    words: [
      ['thingy', 'noun', 'anavi narsa (nomi esga kelmagan)', 'Pass me that thingy on the table.', 'Stoldagi anavi narsani uzatib yubor.'],
      ['whatsit', 'noun', 'haligi narsa', "Where's the whatsit for opening bottles?", 'Shisha ochadigan haligi narsa qayerda?'],
      ['whatsisname', 'noun', 'haligi (ismi esga kelmagan erkak)', 'I saw whatsisname from your office yesterday.', "Kecha ofisingdagi haligi odamni ko'rdim."],
      ['whatsername', 'noun', 'haligi (ismi esga kelmagan ayol)', 'Whatsername called while you were out.', "Sen yo'qligingda haligi ayol qo'ng'iroq qildi."],
      ['umpteen', 'determiner', 'son-sanoqsiz', "I've told you umpteen times!", 'Senga necha marta aytdim!'],
      ['and whatnot', 'phrase', 'va boshqa narsalar', 'We bought pens, paper and whatnot.', "Ruchka, qog'oz va boshqa narsalar sotib oldik."],
      ['no offence', 'phrase', "xafa bo'lma-yu", "No offence, but your cooking isn't great.", "Xafa bo'lma-yu, ovqat pishirishing unchalik emas."],
      ['present company excepted', 'phrase', "o'tirganlar bundan mustasno", 'Politicians are all liars, present company excepted.', "Siyosatchilarning hammasi yolg'onchi — o'tirganlar bundan mustasno."],
      ['incidentally', 'adverb', 'aytgancha', 'Incidentally, have you seen my keys?', "Aytgancha, kalitlarimni ko'rmadingmi?"],
      ["if you don't mind me saying", 'phrase', 'aytishimga ruxsat bersangiz', "If you don't mind me saying, you look tired.", "Aytishimga ruxsat bersangiz, charchagan ko'rinasiz."],
      ['for one thing', 'phrase', 'bir sababi (shuki)', "I can't go. For one thing, I have no money.", "Bora olmayman. Bir sababi — pulim yo'q."],
      ['as things stand', 'phrase', 'hozirgi holatda', "As things stand, we can't afford a new car.", 'Hozirgi holatda yangi mashinaga pulimiz yetmaydi.'],
      ['get it off your chest', 'phrase', "ko'nglini bo'shatmoq", "Tell me what's wrong; get it off your chest.", "Nima bo'lganini ayt, ko'nglingni bo'shat."],
      ['make a big thing of', 'phrase', 'katta masala qilmoq', "Don't make a big thing of it.", 'Buni katta masala qilma.'],
      ['beside the point', 'phrase', 'mavzuga aloqasiz', "That's beside the point.", "Bu mavzuga aloqasi yo'q."],
    ],
  },
  {
    unit: 83,
    title: 'Give or take: more vague expressions',
    titleUz: 'Taxminiy ifodalar',
    emoji: '🤏',
    words: [
      ['approximately', 'adverb', 'taxminan', 'The journey takes approximately two hours.', 'Safar taxminan ikki soat davom etadi.'],
      ['in excess of', 'phrase', '...dan ortiq (rasmiy)', 'The house cost in excess of a million dollars.', 'Uy bir million dollardan ortiqqa tushdi.'],
      ['more or less', 'phrase', 'qariyb, deyarli', 'The work is more or less finished.', 'Ish qariyb tugadi.'],
      ['or so', 'phrase', '... atrofida (taxminan)', "I'll be there in an hour or so.", "Bir soatlarda u yerda bo'laman."],
      ['smattering', 'noun', 'yuzaki bilim (ozgina)', 'He has a smattering of French.', 'U frantsuz tilini ozgina biladi.'],
      ['smidgen', 'noun', 'bir chimdim', 'Just a smidgen of sugar, please.', 'Faqat bir chimdim shakar, iltimos.'],
      ['dollop', 'noun', 'bir qoshiq (quyuq narsa)', 'Add a dollop of cream.', "Bir qoshiq qaymoq qo'shing."],
      ['somewhere in the region of', 'phrase', 'taxminan ... atrofida', 'The repairs will cost somewhere in the region of $500.', "Ta'mirlash 500 dollar atrofida turadi."],
      ['something along those lines', 'phrase', "shunga o'xshash bir gap", 'He said he was busy, or something along those lines.', "U band ekanini aytdi, yoki shunga o'xshash bir gap."],
      ['or thereabouts', 'phrase', 'yoki shunga yaqin', 'There were 50 people, or thereabouts.', "U yerda 50 kishi, yoki shunga yaqin odam bor edi."],
      ['and so on', 'phrase', 'va hokazo', 'We need chairs, tables and so on.', 'Bizga stul, stol va hokazolar kerak.'],
    ],
  },
  {
    unit: 84,
    title: 'The way you say it',
    titleUz: 'Qanday gapirish',
    emoji: '🗣️',
    words: [
      ['bicker', 'verb', 'mayda narsalarga tortishmoq', 'The children bicker all the time.', 'Bolalar doim mayda narsalarga tortishadi.'],
      ['squabble', 'verb', 'mayda janjallashmoq', 'They squabbled over who should pay.', "Ular kim to'lashi ustida janjallashishdi."],
      ['gossip', 'noun', "g'iybat", "Don't believe the office gossip.", "Ofisdagi g'iybatlarga ishonma."],
      ['nag', 'verb', 'tinmay tanbeh bermoq', 'My mother always nags me about my room.', 'Onam doim xonam uchun tanbeh beradi.'],
      ['exaggerate', 'verb', "bo'rttirmoq", "Don't exaggerate; it wasn't that bad.", "Bo'rttirma, unchalik yomon emasdi."],
      ['generalise', 'verb', 'umumlashtirmoq', "It's dangerous to generalise about people.", 'Odamlar haqida umumlashtirish xavfli.'],
      ['slur', 'verb', 'chaynab (noaniq) gapirmoq', 'He was slurring his words after the party.', "Bazmdan keyin u so'zlarni chaynab gapirardi."],
      ['lisp', 'noun', 'chuchuk tillik', 'The child speaks with a lisp.', "Bola chuchuk tilli bo'lib gapiradi."],
      ['tongue-tied', 'adjective', 'hayajondan tili tutilgan', 'I get tongue-tied when I meet famous people.', "Mashhur odamlarni ko'rsam, hayajondan tilim tutiladi."],
      ['chat away', 'phrase', "bemalol gaplashib o'tirmoq", 'They can chat away for hours.', "Ular soatlab bemalol gaplashib o'tira oladi."],
      ['butter up', 'phrase', "yaltoqlanib ko'nglini olmoq", "He's trying to butter up the boss.", "U boshliqqa yaltoqlanib, ko'nglini olmoqchi."],
      ['wind up', 'phrase', "(atayin) jig'iga tegmoq", "Don't wind up your sister.", "Singlingning jig'iga tegma."],
      ['slag off', 'phrase', "yomonlamoq (so'zlashuv)", "It's not nice to slag off your colleagues.", 'Hamkasblaringni yomonlash yaxshi emas.'],
      ['whine', 'verb', 'ingillamoq', 'Stop whining and do your homework.', 'Ingillashni bas qil, uy vazifangni qil.'],
      ['raise your voice', 'phrase', "ovozini ko'tarmoq", "Please don't raise your voice at me.", "Iltimos, menga ovozingni ko'tarma."],
      ['without a word', 'phrase', 'churq etmay', 'She left without a word.', 'U churq etmay chiqib ketdi.'],
    ],
  },
  {
    unit: 86,
    title: 'Prefixes: creating new meanings',
    titleUz: "Old qo'shimchalar (yuqori daraja)",
    emoji: '🔠',
    words: [
      ['commiserate', 'verb', 'hamdardlik bildirmoq', 'I commiserated with her about losing her job.', 'Ishdan ayrilgani uchun unga hamdardlik bildirdim.'],
      ['eco-warrior', 'noun', 'ekofaol', 'Eco-warriors protested against the new airport.', 'Ekofaollar yangi aeroportga qarshi namoyish qilishdi.'],
      ['e-cigarette', 'noun', 'elektron sigaret', 'E-cigarettes are popular among young people.', 'Elektron sigaretlar yoshlar orasida mashhur.'],
      ['outnumber', 'verb', 'sonda ustun kelmoq', 'Women outnumber men in this profession.', "Bu kasbda ayollar erkaklardan ko'p."],
      ['outweigh', 'verb', "(foyda, zarar) ustun bo'lmoq", 'The benefits outweigh the risks.', 'Foydasi xavfidan ustun.'],
      ['overshadow', 'verb', 'soya solmoq', 'The tragedy overshadowed the celebrations.', 'Fojia bayram shodiyonalariga soya soldi.'],
      ['overpriced', 'adjective', 'asossiz qimmat', 'The food in the airport is overpriced.', 'Aeroportdagi ovqat asossiz qimmat.'],
      ['overstep the mark', 'phrase', 'haddan oshmoq', 'Be careful not to overstep the mark.', 'Haddingdan oshib ketma.'],
      ['procrastinate', 'verb', 'ishni ortga surmoq', 'Stop procrastinating and start your essay!', "Ishni ortga surishni bas qil va inshongni boshla!"],
      ['proliferate', 'verb', "tez ko'paymoq", 'Fast-food restaurants have proliferated in the city.', "Shaharda fastfud restoranlari juda ko'payib ketdi."],
      ['reconsider', 'verb', "qayta ko'rib chiqmoq", 'Please reconsider your decision.', "Iltimos, qaroringizni qayta ko'rib chiqing."],
      ['redevelop', 'verb', 'qayta qurmoq (hudud)', 'The city plans to redevelop the old port.', 'Shahar eski portni qayta qurmoqchi.'],
      ['underestimate', 'verb', 'past baholamoq', 'Never underestimate your opponent.', 'Raqibingni hech qachon past baholama.'],
      ['undermine', 'verb', 'putur yetkazmoq', 'Constant criticism can undermine your confidence.', 'Doimiy tanqid ishonchingizga putur yetkazishi mumkin.'],
      ['understaffed', 'adjective', 'xodim yetishmaydigan', 'The hospital is seriously understaffed.', 'Kasalxonada xodimlar jiddiy yetishmaydi.'],
      ['underhand', 'adjective', 'yashirin-nohalol', 'They used underhand methods to win the contract.', 'Ular shartnomani yutish uchun nohalol usullardan foydalanishdi.'],
      ['inability', 'noun', 'qila olmaslik', 'His inability to listen annoys everyone.', "Uning tinglay olmasligi hammaning g'ashiga tegadi."],
      ['misbehave', 'verb', "o'zini yomon tutmoq", 'Children often misbehave when they are tired.', "Bolalar charchaganda ko'pincha o'zini yomon tutadi."],
      ['upturn', 'noun', "yaxshilanish, o'sish", 'There has been an upturn in the economy.', "Iqtisodiyotda yaxshilanish bo'ldi."],
    ],
  },
  {
    unit: 87,
    title: 'Suffixes: forming new words',
    titleUz: "Qo'shimchalar bilan so'z yasash",
    emoji: '🧩',
    words: [
      ['applicant', 'noun', 'arizachi, nomzod', 'There were 200 applicants for the job.', 'Ishga 200 ta nomzod ariza bergan edi.'],
      ['claimant', 'noun', "da'vogar (nafaqa, kompensatsiya)", 'Each claimant must fill in a form.', "Har bir da'vogar anketa to'ldirishi kerak."],
      ['contestant', 'noun', 'tanlov ishtirokchisi', 'The contestants answered ten questions.', "Ishtirokchilar o'nta savolga javob berishdi."],
      ['informant', 'noun', 'xabar beruvchi (informator)', 'The police received a tip from an informant.', "Politsiya xabar beruvchidan ma'lumot oldi."],
      ['occupant', 'noun', 'yashovchi, egallovchi', 'The occupants of the house were asleep.', 'Uyda yashovchilar uxlab yotishgan edi.'],
      ['bedridden', 'adjective', "to'shakka mixlangan", 'My grandmother has been bedridden for a year.', "Buvim bir yildan beri to'shakka mixlangan."],
      ['crime-ridden', 'adjective', "jinoyat avj olgan", 'They grew up in a crime-ridden area.', "Ular jinoyat avj olgan hududda o'sgan."],
      ['guilt-ridden', 'adjective', 'vijdon azobidagi', 'He felt guilt-ridden after the accident.', 'Avariyadan keyin u vijdon azobida qoldi.'],
      ['health-conscious', 'adjective', "sog'lig'iga e'tiborli", 'Health-conscious people avoid sugar.', "Sog'lig'iga e'tiborli odamlar shakardan qochadi."],
      ['like-minded', 'adjective', 'fikrdosh', 'She met like-minded people at the club.', 'U klubda fikrdosh odamlar bilan tanishdi.'],
      ['career-minded', 'adjective', 'karyeraga intiluvchan', "He's very career-minded and works late every day.", 'U karyeraga juda intiluvchan, har kuni kechgacha ishlaydi.'],
      ['newsworthy', 'adjective', "yangilik sifatida e'tiborga loyiq", "The event wasn't newsworthy.", "Voqea yangilik sifatida e'tiborga loyiq emas edi."],
      ['idiot-proof', 'adjective', 'hamma oson ishlata oladigan', 'The new camera is completely idiot-proof.', "Yangi kamerani har kim oson ishlata oladi."],
      ['soundproof', 'adjective', "tovush o'tkazmaydigan", 'The studio is soundproof.', "Studiya tovush o'tkazmaydi."],
      ['ovenproof', 'adjective', 'pechga chidamli', 'Use an ovenproof dish.', 'Pechga chidamli idishdan foydalaning.'],
      ['stress-free', 'adjective', 'stresssiz', 'We want a stress-free holiday.', "Biz stresssiz ta'til xohlaymiz."],
      ['tax-free', 'adjective', 'soliqdan ozod', 'Some savings are tax-free.', "Ba'zi jamg'armalar soliqdan ozod."],
      ['disposable', 'adjective', 'bir martalik', "Don't use disposable cups; they create waste.", "Bir martalik stakanlardan foydalanmang, ular chiqindi ko'paytiradi."],
      ['worsen', 'verb', 'yomonlashmoq', 'The situation is likely to worsen.', 'Vaziyat yomonlashishi ehtimoli bor.'],
      ['sweeten', 'verb', 'shirinlashtirmoq', 'Sweeten the tea with honey.', 'Choyni asal bilan shirinlashtiring.'],
    ],
  },
  {
    unit: 88,
    title: 'Word-building and word-blending',
    titleUz: "Qo'shma va aralash so'zlar",
    emoji: '🔀',
    words: [
      ['brunch', 'noun', 'kechki nonushta (nonushta + tushlik)', 'We have brunch on Sundays.', 'Yakshanba kunlari kechki nonushta qilamiz.'],
      ['smog', 'noun', 'tutunli tuman (smog)', 'Smog is a problem in big cities.', 'Tutunli tuman katta shaharlarda muammo.'],
      ['motel', 'noun', "motel (yo'l bo'yi mehmonxonasi)", 'We stayed at a motel by the highway.', "Katta yo'l bo'yidagi motelda qoldik."],
      ['docudrama', 'noun', 'hujjatli drama', 'The film is a docudrama about the war.', 'Film urush haqidagi hujjatli drama.'],
      ['guesstimate', 'noun', 'chamalab aytilgan taxmin', 'My guesstimate is about 200 people.', "Chamalashimcha, 200 ga yaqin odam bor."],
      ['heliport', 'noun', 'vertolyot maydonchasi', 'The hospital has its own heliport.', "Kasalxonaning o'z vertolyot maydonchasi bor."],
      ['cyberbullying', 'noun', 'internetdagi tazyiq', 'Cyberbullying is a serious problem in schools.', 'Internetdagi tazyiq maktablarda jiddiy muammo.'],
      ['retro', 'adjective', 'retro (eski uslubdagi)', 'She loves retro fashion from the 70s.', "U 70-yillarning retro modasini yaxshi ko'radi."],
      ['biopic', 'noun', 'biografik film', 'The biopic tells the life story of a famous singer.', "Biografik film mashhur qo'shiqchining hayot yo'lini hikoya qiladi."],
      ['autobiography', 'noun', 'avtobiografiya', 'He wrote his autobiography at 80.', 'U 80 yoshida avtobiografiyasini yozdi.'],
      ['telecommute', 'verb', 'masofadan ishlamoq', 'Many people now telecommute two days a week.', "Hozir ko'pchilik haftada ikki kun masofadan ishlaydi."],
      ['infotainment', 'noun', "ko'ngilochar axborot", 'Some news programmes are more like infotainment.', "Ba'zi yangiliklar ko'rsatuvlari ko'ngilochar axborotga o'xshaydi."],
      ['staycation', 'noun', "uyda o'tkaziladigan ta'til", "We can't afford to travel, so we're having a staycation.", "Sayohatga pulimiz yetmaydi, shuning uchun ta'tilni uyda o'tkazyapmiz."],
      ['blog', 'noun', 'blog (shaxsiy veb-jurnal)', 'She writes a blog about travel.', 'U sayohat haqida blog yuritadi.'],
    ],
  },
  {
    unit: 89,
    title: 'English: a global language',
    titleUz: 'Ingliz tili — global til',
    emoji: '🌍',
    words: [
      ['loanword', 'noun', "o'zlashma so'z", "'Plov' is a loanword in English.", "«Plov» — ingliz tilidagi o'zlashma so'z."],
      ['borrowing', 'noun', "o'zlashma (boshqa tildan)", 'English has many borrowings from French.', "Ingliz tilida frantsuz tilidan o'zlashmalar ko'p."],
      ['false friend', 'phrase', "aldamchi o'xshash so'z", "'Magazine' is a false friend for many learners.", "«Magazine» ko'p o'rganuvchilar uchun aldamchi so'z (do'kon emas, jurnal)."],
      ['linguistic', 'adjective', 'tilga oid, lingvistik', 'The country has great linguistic diversity.', 'Mamlakatda katta lingvistik xilma-xillik bor.'],
      ['Anglo-Saxon', 'adjective', 'anglosakson', 'Many basic English words come from Anglo-Saxon.', "Ko'p asosiy inglizcha so'zlar anglosakson tilidan kelgan."],
      ['intelligentsia', 'noun', 'ziyolilar', 'The intelligentsia supported the reforms.', "Ziyolilar islohotlarni qo'llab-quvvatladi."],
      ['karaoke', 'noun', "karaoke (qo'shiq kuylash o'yini)", 'We went to a karaoke bar.', 'Karaoke barga bordik.'],
      ['gimmick', 'noun', 'nayrang (reklama hiylasi)', 'The free gift is just a marketing gimmick.', "Bepul sovg'a shunchaki marketing nayrangi."],
      ['palaver', 'noun', 'ortiqcha ovoragarchilik', 'What a palaver to get a simple document!', 'Oddiy hujjat olish uchun shuncha ovoragarchilik!'],
      ['roster', 'noun', 'navbatchilik jadvali', 'Check the duty roster to see when you work.', 'Qachon ishlashingizni navbatchilik jadvalidan tekshiring.'],
      ['mumps', 'noun', 'tepki (kasallik)', 'My son has got mumps.', "O'g'limga tepki kasalligi yuqdi."],
      ['hammock', 'noun', "osma to'shak (gamak)", 'He was relaxing in a hammock in the garden.', "U bog'dagi osma to'shakda dam olardi."],
      ['turban', 'noun', 'salla', 'The old man wore a white turban.', "Chol oq salla o'ragan edi."],
      ['tabby', 'adjective', "yo'l-yo'l (mushuk)", 'We have a tabby cat.', "Bizda yo'l-yo'l mushuk bor."],
      ['cot', 'noun', 'bolalar karavoti (panjarali)', 'The baby sleeps in a cot.', 'Chaqaloq bolalar karavotida uxlaydi.'],
      ['enrich', 'verb', 'boyitmoq', 'Loanwords enrich a language.', "O'zlashma so'zlar tilni boyitadi."],
    ],
  },
  {
    unit: 90,
    title: 'Easily confused words',
    titleUz: "Adashtiriladigan so'zlar (yuqori daraja)",
    emoji: '🔄',
    words: [
      ['continually', 'adverb', 'tinmay (takror-takror)', 'He continually interrupts me.', "U tinmay gapimni bo'ladi."],
      ['continuously', 'adverb', 'uzluksiz', 'It rained continuously for three days.', "Uch kun uzluksiz yomg'ir yog'di."],
      ['evade', 'verb', "(majburiyatdan) bo'yin tovlamoq", 'He tried to evade paying tax.', "U soliq to'lashdan bo'yin tovlashga urindi."],
      ['avoid', 'verb', 'qochmoq, chetlab o\'tmoq', 'Try to avoid fatty food.', "Yog'li ovqatdan qochishga harakat qiling."],
      ['interfere', 'verb', 'aralashmoq (keraksiz)', "Don't interfere in my private life.", 'Shaxsiy hayotimga aralashma.'],
      ['intervene', 'verb', "aralashmoq (to'xtatish uchun)", 'The police had to intervene in the fight.', "Politsiya janjalga aralashishiga to'g'ri keldi."],
      ['moist', 'adjective', 'biroz nam (yoqimli)', 'Keep the soil moist.', 'Tuproqni nam saqlang.'],
      ['complement', 'verb', "to'ldirmoq (mos kelib)", 'The red scarf complements her dress.', "Qizil sharf uning ko'ylagini chiroyli to'ldiradi."],
      ['serial', 'noun', 'qismlarga bo\'lingan asar', 'The novel was first published as a serial.', "Roman avval qismlarga bo'lib chop etilgan."],
      ['series', 'noun', 'turkum, teleserial', "It's a TV series about doctors.", 'Bu shifokorlar haqidagi teleserial.'],
      ['lookout', 'noun', 'hushyorlik; poyloqchi', 'Keep a lookout for pickpockets.', "Cho'ntakkesarlardan hushyor bo'ling."],
      ['theme', 'noun', "asosiy g'oya (mavzu)", 'The main theme of the novel is love.', "Romanning asosiy g'oyasi — sevgi."],
      ['security', 'noun', 'xavfsizlik (himoya)', 'Security at the airport is very tight.', 'Aeroportda xavfsizlik juda qattiq.'],
      ['safety', 'noun', 'xavfsizlik (baxtsiz hodisadan)', 'Safety comes first on building sites.', "Qurilish maydonlarida xavfsizlik birinchi o'rinda."],
      ['outdo', 'verb', "o'zib ketmoq", 'She always tries to outdo her sister.', "U doim opasidan o'zib ketishga harakat qiladi."],
    ],
  },
  {
    unit: 92,
    title: 'Collocation: which words go together',
    titleUz: "So'z birikmalari",
    emoji: '🔗',
    words: [
      ['formidable', 'adjective', 'qudratli, kuchli (raqib)', 'She is a formidable opponent.', 'U kuchli raqib.'],
      ['ludicrous', 'adjective', "kulgili darajada bema'ni", 'The idea is ludicrous.', "Bu fikr kulgili darajada bema'ni."],
      ['fatuous', 'adjective', 'ahmoqona', 'He made a fatuous remark.', 'U ahmoqona gap aytdi.'],
      ['dismal', 'adjective', 'ayanchli', "The team's performance was dismal.", "Jamoaning o'yini ayanchli edi."],
      ['appalling', 'adjective', "g'oyat yomon", 'The conditions in the prison were appalling.', "Qamoqxonadagi sharoit g'oyat yomon edi."],
      ['distasteful', 'adjective', 'odobsiz, yoqimsiz', 'I found his jokes distasteful.', 'Uning hazillari menga odobsiz tuyuldi.'],
      ['pointless', 'adjective', 'befoyda', "It's pointless arguing with him.", 'U bilan bahslashish befoyda.'],
      ['swiftly', 'adverb', 'tezda, zudlik bilan', 'The government acted swiftly.', 'Hukumat zudlik bilan harakat qildi.'],
      ['raise a family', 'phrase', 'oila boqmoq', "It's expensive to raise a family in the city.", 'Shaharda oila boqish qimmat.'],
      ['in great detail', 'phrase', 'batafsil', 'She described the accident in great detail.', 'U avariyani batafsil tasvirlab berdi.'],
      ['broad range', 'phrase', 'keng doira (assortiment)', 'The shop sells a broad range of products.', "Do'kon keng assortimentdagi mahsulotlarni sotadi."],
      ['the genuine article', 'phrase', 'haqiqiy narsa (asli)', "This isn't a copy; it's the genuine article.", 'Bu nusxa emas, bu haqiqiysi.'],
      ['collocation', 'noun', "so'z birikmasi (kollokatsiya)", "'Heavy rain' is a common collocation.", "«Heavy rain» — keng tarqalgan so'z birikmasi."],
      ['visit a website', 'phrase', 'saytga kirmoq', 'Visit a website like ours for more information.', "Batafsil ma'lumot uchun bizning saytimiz kabi saytga kiring."],
      ['raise your glass', 'phrase', "qadah ko'tarmoq", 'Please raise your glass to the bride and groom.', "Kelin-kuyov sharafiga qadahingizni ko'taring."],
    ],
  },
  {
    unit: 93,
    title: 'Metaphor: seeing the light',
    titleUz: 'Metaforalar',
    emoji: '💡',
    words: [
      ['see the light', 'phrase', 'haqiqatni tushunib yetmoq', "One day you'll see the light and agree with me.", 'Bir kun tushunib yetasan va menga qo\'shilasan.'],
      ['cast light on', 'phrase', 'oydinlik kiritmoq', 'The letters cast light on his private life.', 'Xatlar uning shaxsiy hayotiga oydinlik kiritadi.'],
      ['light up', 'phrase', '(yuz) yorishib ketmoq', "Children's faces light up when they see presents.", "Bolalarning yuzi sovg'ani ko'rganda yorishib ketadi."],
      ['bright future', 'phrase', 'porloq kelajak', 'She has a bright future ahead of her.', 'Uni porloq kelajak kutmoqda.'],
      ['blow hot and cold', 'phrase', 'goh unday, goh bunday bo\'lmoq', 'He tends to blow hot and cold about the plan.', 'U reja haqida goh unday, goh bunday fikrda.'],
      ['hotheaded', 'adjective', 'jahldor, qizg\'in', "He's hotheaded and often gets into fights.", "U jahldor va tez-tez mushtlashadi."],
      ['cold-hearted', 'adjective', 'sovuq yurakli', 'How can you be so cold-hearted?', "Qanday qilib bunchalik sovuq yurakli bo'la olasan?"],
      ['flood of', 'phrase', "oqim, sel (ko'p miqdor)", 'The company received a flood of complaints.', 'Kompaniyaga shikoyatlar oqimi keldi.'],
      ['a trickle of', 'phrase', 'oz-ozdan (kam miqdor)', 'Only a trickle of visitors came in winter.', 'Qishda faqat oz-ozdan tashrifchilar keldi.'],
      ['in safe hands', 'phrase', "ishonchli qo'llarda", "Don't worry; your children are in safe hands.", "Xavotir olmang, bolalaringiz ishonchli qo'llarda."],
      ['go hand in hand', 'phrase', 'birga yurmoq (bog\'liq bo\'lmoq)', 'Poverty and poor health often go hand in hand.', "Qashshoqlik va yomon sog'liq ko'pincha birga yuradi."],
      ['waste your breath', 'phrase', 'behuda gapirmoq', "Don't waste your breath; he won't listen.", 'Behuda gapirma, u tinglamaydi.'],
      ['launch a campaign', 'phrase', 'kampaniya boshlamoq', 'The charity will launch a campaign to help the homeless.', 'Xayriya tashkiloti uysizlarga yordam kampaniyasini boshlaydi.'],
      ['rule of thumb', 'phrase', 'amaliy qoida', 'As a rule of thumb, drink two litres of water a day.', 'Amaliy qoida sifatida kuniga ikki litr suv iching.'],
      ['concrete jungle', 'phrase', 'beton changalzor (katta shahar)', 'I want to escape the concrete jungle.', 'Beton changalzordan qochgim keladi.'],
      ['head start', 'phrase', "boshlang'ich ustunlik", 'Learning English early gives children a head start.', "Ingliz tilini erta o'rganish bolalarga ustunlik beradi."],
    ],
  },
  {
    unit: 94,
    title: 'Idioms for everyday situations and feelings',
    titleUz: 'Kundalik iboralar',
    emoji: '🎭',
    words: [
      ['shambles', 'noun', "parokandalik, to'polon", 'The meeting was a complete shambles.', "Yig'ilish butunlay parokandalik bo'ldi."],
      ['on the go', 'phrase', 'tinim bilmay', "I've been on the go all day.", "Kun bo'yi tinim bilmadim."],
      ['run like clockwork', 'phrase', 'soatdek aniq ishlamoq', 'Our office seems to run like clockwork.', 'Ofisimiz soatdek aniq ishlaydi.'],
      ['go like a dream', 'phrase', "juda silliq o'tmoq", 'I hope the interview will go like a dream.', "Suhbat juda silliq o'tadi degan umiddaman."],
      ['fall into place', 'phrase', "o'z joyiga tushmoq", 'After a while, everything started to fall into place.', "Biroz vaqtdan keyin hammasi o'z joyiga tusha boshladi."],
      ['get your act together', 'phrase', "o'zini yig'ib olmoq", 'You need to get your act together if you want to pass.', "O'tmoqchi bo'lsang, o'zingni yig'ib olishing kerak."],
      ['not in the mood', 'phrase', "kayfiyati yo'q", "I'm not in the mood for dancing.", "Raqsga tushishga kayfiyatim yo'q."],
      ['a mystery to me', 'phrase', 'men uchun sir (tushunarsiz)', 'How he got the job is a mystery to me.', "U ishga qanday kirgani men uchun sir."],
      ['the last straw', 'phrase', "sabr kosasini to'ldirgan narsa", 'When he was late again, it was the last straw.', "U yana kechikkanida sabr kosam to'ldi."],
      ["you've lost me", 'phrase', 'tushunmay qoldim', "Sorry, you've lost me. Can you explain again?", 'Kechirasiz, tushunmay qoldim. Qaytadan tushuntira olasizmi?'],
      ['on the ball', 'phrase', 'hushyor, ziyrak', 'You need to be on the ball in this job.', "Bu ishda hushyor bo'lish kerak."],
      ['in at the deep end', 'phrase', 'birdaniga qiyin vaziyatga (tajribasiz)', 'New teachers are often thrown in at the deep end.', "Yangi o'qituvchilar ko'pincha birdaniga qiyin ishga tashlanadi."],
      ['a needle in a haystack', 'phrase', 'pichan ichidagi igna (topish qiyin)', 'Finding him in this city is like looking for a needle in a haystack.', 'Uni bu shaharda topish — pichan ichidan igna qidirishdek.'],
      ['work like a dog', 'phrase', 'tinimsiz ishlamoq', 'My father had to work like a dog to feed us.', 'Otam bizni boqish uchun tinimsiz ishlashiga to\'g\'ri kelgan.'],
    ],
  },
  {
    unit: 95,
    title: 'Brushing up on phrasal verbs',
    titleUz: "Frazali fe'llar (yuqori daraja)",
    emoji: '🧰',
    words: [
      ['brush up on', 'phrase', '(bilimni) yangilab olmoq', 'I need to brush up on my French before the trip.', 'Safardan oldin frantsuz tilimni yangilab olishim kerak.'],
      ['dwell on', 'phrase', "(salbiy narsa) ustida o'ylab qolmoq", "Don't dwell on your mistakes.", "Xatolaring haqida o'ylab qolma."],
      ['throw yourself into', 'phrase', 'butunlay berilib ketmoq', 'Throw yourself into your work; it will help.', 'Ishga butunlay berilib ket, yordam beradi.'],
      ['settle down', 'phrase', "oila qurib o'rnashmoq", 'He wants to settle down and have a family.', "U oila qurib, o'rnashib qolmoqchi."],
      ['press on', 'phrase', "qat'iyat bilan davom etmoq", 'Despite the rain, we decided to press on.', "Yomg'irga qaramay, yo'lda davom etishga qaror qildik."],
      ['rush into', 'phrase', 'shoshqaloqlik bilan kirishmoq', "Don't rush into marriage.", 'Turmush qurishga shoshilma.'],
      ['lay off', 'phrase', "(qisqartirib) ishdan bo'shatmoq", 'The factory will lay off 300 workers.', "Zavod 300 ishchini ishdan bo'shatadi."],
      ['catch up on', 'phrase', "(to'planib qolgan ishga) ulgurmoq", 'I need to catch up on my emails.', 'Elektron xatlarimga ulgurib olishim kerak.'],
      ['stay up', 'phrase', 'kech yotmoq', "Don't stay up too late.", 'Juda kech yotma.'],
      ['go along with', 'phrase', "rozi bo'lmoq, qo'shilmoq", "I'll go along with your plan.", "Rejangga rozi bo'laman."],
      ['call off', 'phrase', 'bekor qilmoq', 'They had to call off the wedding.', "Ular to'yni bekor qilishga majbur bo'lishdi."],
      ['come round to', 'phrase', '(fikrga) kelmoq', "She'll come round to our way of thinking.", 'U oxir-oqibat bizning fikrimizga keladi.'],
      ['come down to', 'phrase', '...ga borib taqalmoq', 'In the end, it will come down to money.', 'Oxir-oqibat hammasi pulga borib taqaladi.'],
      ['come in for', 'phrase', '(tanqidga) uchramoq', 'The government will come in for criticism.', 'Hukumat tanqidga uchraydi.'],
      ['urge on', 'phrase', 'ruhlantirib undamoq', 'Fans urge on their team with songs.', "Muxlislar qo'shiqlar bilan jamoasini ruhlantiradi."],
    ],
  },
  {
    unit: 96,
    title: 'Connotation: making associations',
    titleUz: "Qo'shimcha ma'nolar",
    emoji: '🕊️',
    words: [
      ['connotation', 'noun', "qo'shimcha ma'no (konnotatsiya)", "The word 'cheap' has a negative connotation.", "«Cheap» so'zining salbiy qo'shimcha ma'nosi bor."],
      ['association', 'noun', "assotsiatsiya, bog'lanish", 'The colour red has an association with danger.', "Qizil rang xavf bilan bog'lanadi."],
      ['hawk', 'noun', 'urush tarafdori (siyosatda)', 'The hawks in the government want war.', 'Hukumatdagi urush tarafdorlari urush istaydi.'],
      ['dove', 'noun', 'tinchlik tarafdori (siyosatda)', 'The doves are calling for peace talks.', 'Tinchlik tarafdorlari muzokaralarga chaqirmoqda.'],
      ['cowboy', 'noun', 'chala usta (vijdonsiz)', 'Some cowboy builders did the work badly.', 'Qandaydir chala ustalar ishni yomon qilishdi.'],
      ['loan shark', 'phrase', "sudxo'r", 'He borrowed money from a loan shark.', "U sudxo'rdan qarz oldi."],
      ['rough diamond', 'phrase', "qo'pol, lekin ko'ngli toza odam", "He's a rough diamond: rude but kind-hearted.", "U qo'pol, lekin ko'ngli toza odam."],
      ['black humour', 'phrase', 'qora hazil', 'The film is full of black humour.', "Film qora hazilga to'la."],
      ['euphemism', 'noun', 'evfemizm (yumshatilgan ibora)', "'Pass away' is a euphemism for 'die'.", "«Pass away» — «die»ning yumshatilgan shakli."],
    ],
  },
  {
    unit: 97,
    title: 'Register: degrees of formality',
    titleUz: 'Nutq uslublari',
    emoji: '🎩',
    words: [
      ['endeavour', 'verb', 'harakat qilmoq (rasmiy)', 'We will endeavour to answer your questions.', 'Savollaringizga javob berishga harakat qilamiz.'],
      ['garment', 'noun', 'kiyim (rasmiy)', 'Wash this garment by hand.', "Bu kiyimni qo'lda yuving."],
      ['frock', 'noun', "ko'ylak (eskicha)", 'The little girl wore a pretty frock.', "Qizcha chiroyli ko'ylak kiygan edi."],
      ['gear', 'noun', "anjom, jihoz (so'zlashuv)", "Don't forget your football gear.", 'Futbol anjomlaringni unutma.'],
      ['bloke', 'noun', "yigit, odam (so'zlashuv)", "He's a nice bloke.", 'U yaxshi yigit.'],
      ['guy', 'noun', "yigit (so'zlashuv)", "He's a really funny guy.", 'U juda kulgili yigit.'],
      ['have a crack at', 'phrase', "urinib ko'rmoq (so'zlashuv)", "I've never tried it, but I'll have a crack at it.", "Hech qachon sinab ko'rmaganman, lekin bir urinib ko'raman."],
      ['have a stab at', 'phrase', "taxmin qilib ko'rmoq", 'Have a stab at the answer.', "Javobni topishga bir urinib ko'r."],
      ['specs', 'noun', "ko'zoynak (so'zlashuv)", "I can't read without my specs.", "Ko'zoynaksiz o'qiy olmayman."],
      ['employ', 'verb', "qo'llamoq (rasmiy); ishga olmoq", 'The report employs a range of statistical methods.', "Hisobotda turli statistik usullar qo'llanilgan."],
      ['the box', 'phrase', "televizor (so'zlashuv)", "There's nothing good on the box tonight.", "Bugun kechqurun televizorda yaxshi hech narsa yo'q."],
      ['converse', 'verb', 'suhbatlashmoq (rasmiy)', 'They conversed in French.', 'Ular frantsuz tilida suhbatlashishdi.'],
      ['wireless', 'noun', 'radio (eskicha)', 'My grandfather listened to the news on the wireless.', 'Bobom yangiliklarni radiodan tinglardi.'],
      ['your other half', 'phrase', "umr yo'ldoshi (so'zlashuv)", 'Bring your other half to the party.', "Bazmga umr yo'ldoshingni ham olib kel."],
    ],
  },
  {
    unit: 98,
    title: 'Divided by a common language',
    titleUz: 'Britaniya va Amerika inglizchasi',
    emoji: '🇺🇸',
    words: [
      ['faucet', 'noun', "jo'mrak (AQSh)", 'The faucet in the kitchen is dripping.', "Oshxonadagi jo'mrak tomchilayapti."],
      ['stove', 'noun', 'plita (AQSh)', 'The soup is on the stove.', "Sho'rva plita ustida."],
      ['skillet', 'noun', 'tova (AQSh)', 'Fry the eggs in a skillet.', 'Tuxumni tovada qovuring.'],
      ['dumpster', 'noun', 'axlat konteyneri (AQSh)', 'Throw the old boxes in the dumpster.', 'Eski qutilarni axlat konteyneriga tashlang.'],
      ['crosswalk', 'noun', "piyodalar o'tish joyi (AQSh)", 'Always cross at the crosswalk.', "Doim piyodalar o'tish joyidan o'ting."],
      ['intersection', 'noun', 'chorraha (AQSh)', 'Turn left at the next intersection.', 'Keyingi chorrahada chapga buriling.'],
      ['overpass', 'noun', "yo'l o'tkazgich (AQSh)", 'The accident happened under the overpass.', "Avariya yo'l o'tkazgich ostida sodir bo'ldi."],
      ['gas station', 'phrase', "yoqilg'i quyish shoxobchasi (AQSh)", 'We stopped at a gas station to fill up.', "Yoqilg'i quyish uchun shoxobchada to'xtadik."],
      ['freshman', 'noun', 'birinchi kurs talabasi (AQSh)', "She's a freshman at Harvard.", 'U Garvardda birinchi kurs talabasi.'],
      ['sophomore', 'noun', 'ikkinchi kurs talabasi (AQSh)', "He's a sophomore in college.", "U kollejda ikkinchi kursda o'qiydi."],
      ['fresher', 'noun', 'birinchi kurs talabasi (Britaniya)', 'Every fresher gets a welcome pack.', "Har bir birinchi kurs talabasi sovg'a to'plami oladi."],
      ['major', 'noun', 'asosiy mutaxassislik (AQSh)', "What's your major?", 'Asosiy mutaxassisligingiz nima?'],
      ['high school', 'phrase', "o'rta maktab (AQSh)", 'She graduated from high school last year.', "U o'tgan yili o'rta maktabni tugatdi."],
      ['creek', 'noun', 'soy (AQSh)', 'The children played in the creek.', "Bolalar soyda o'ynashdi."],
      ['trail', 'noun', "so'qmoq, piyoda yo'lakcha", 'We followed a trail through the forest.', "O'rmon bo'ylab so'qmoqdan bordik."],
      ['kitty-corner', 'adverb', 'diagonal qarshisida (AQSh)', 'The bank is kitty-corner from the post office.', 'Bank pochtaning diagonal qarshisida.'],
    ],
  },
  {
    unit: 99,
    title: 'Language and gender',
    titleUz: 'Til va gender',
    emoji: '⚧️',
    words: [
      ['spokesperson', 'noun', 'vakil, matbuot kotibi', 'A spokesperson for the company refused to comment.', "Kompaniya vakili izoh berishdan bosh tortdi."],
      ['chairperson', 'noun', 'rais', 'She was elected chairperson of the committee.', "U qo'mita raisi etib saylandi."],
      ['human being', 'phrase', 'inson', 'Every human being deserves respect.', 'Har bir inson hurmatga loyiq.'],
      ['masculine', 'adjective', 'erkakona', 'He has a deep, masculine voice.', 'Uning past, erkakona ovozi bor.'],
      ['feminine', 'adjective', 'ayollarga xos, nozik', 'She likes feminine clothes.', 'U ayollarga xos kiyimlarni yoqtiradi.'],
      ['gender-neutral', 'adjective', "jinsga bog'liq bo'lmagan", "Use gender-neutral words like 'firefighter'.", "«Firefighter» kabi jinsga bog'liq bo'lmagan so'zlardan foydalaning."],
      ['sexist', 'adjective', 'jinsiy kamsituvchi', 'The advert was criticised as sexist.', 'Reklama jinsiy kamsituvchi deb tanqid qilindi.'],
      ['humankind', 'noun', 'butun insoniyat', 'The discovery changed the history of humankind.', "Kashfiyot insoniyat tarixini o'zgartirdi."],
      ['workforce', 'noun', 'ishchi kuchi', 'Women make up half of the workforce.', 'Ishchi kuchining yarmini ayollar tashkil qiladi.'],
    ],
  },
  {
    unit: 100,
    title: 'In the headlines',
    titleUz: 'Gazeta sarlavhalari (yuqori daraja)',
    emoji: '🗞️',
    words: [
      ['thug', 'noun', 'bezori', 'A gang of thugs attacked him.', 'Bir to\'da bezorilar unga hujum qildi.'],
      ['lout', 'noun', 'tarbiyasiz qo\'pol yigit', 'Drunken louts caused trouble in the town.', "Mast qo'pol yigitlar shaharda to'polon qilishdi."],
      ['gunman', 'noun', 'qurollangan hujumchi', 'The gunman was arrested by police.', 'Qurollangan hujumchi politsiya tomonidan hibsga olindi.'],
      ['reign of terror', 'phrase', 'dahshatli hukmronlik', "The dictator's reign of terror lasted twenty years.", 'Diktatorning dahshatli hukmronligi yigirma yil davom etdi.'],
      ['crazed', 'adjective', 'telbalashgan', 'A crazed fan attacked the singer.', "Telbalashgan muxlis qo'shiqchiga hujum qildi."],
      ['rip-off', 'noun', 'talonchilik (haddan tashqari qimmat)', "Twenty dollars for a coffee? That's a rip-off!", 'Qahva uchun yigirma dollar? Bu talonchilik!'],
      ['shooting star', 'phrase', 'tez porlagan yulduz; uchar yulduz', "The young actor is Hollywood's latest shooting star.", 'Yosh aktyor — Gollivudning tez porlagan yangi yulduzi.'],
      ['besiege', 'verb', 'qurshab olmoq (savollar bilan)', 'Reporters besieged the star at the airport.', 'Muxbirlar aeroportda yulduzni qurshab olishdi.'],
      ['crush', 'noun', 'tiqilinch (olomon)', 'Several fans were injured in the crush.', 'Tiqilinchda bir necha muxlis jarohatlandi.'],
      ['headline', 'noun', 'sarlavha', 'I only read the headlines.', "Men faqat sarlavhalarni o'qiyman."],
      ['terror', 'noun', 'dahshat', 'The attack spread terror through the city.', 'Hujum shaharga dahshat soldi.'],
    ],
  },
];
