/**
 * Advanced (C1), 61–80-unit'lar. Tamoyillar — elementary.js va advanced.js
 * dagi izohlarga qarang.
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 61,
    title: 'Motion: taking steps',
    titleUz: 'Yurish va harakat',
    emoji: '🚶',
    words: [
      ['stagger', 'verb', 'gandiraklamoq', 'He staggered home after the long walk.', 'Uzoq yo\'ldan keyin u gandiraklab uyga keldi.'],
      ['stumble', 'verb', 'qoqilib ketmoq', 'She stumbled on the stairs and fell.', 'U zinada qoqilib yiqildi.'],
      ['stride', 'noun', 'katta qadam', 'He walks with long strides.', 'U katta qadamlar bilan yuradi.'],
      ['strut', 'verb', 'kerilib yurmoq', 'Look at him strut around like a king!', 'Qara, qiroldek kerilib yuribdi!'],
      ['trudge', 'verb', 'sudralib yurmoq (charchab)', 'We trudged through the snow for hours.', "Soatlab qor bo'ylab sudralib yurdik."],
      ['tiptoe', 'verb', 'oyoq uchida yurmoq', 'She tiptoed past the sleeping baby.', "U uxlayotgan chaqaloq yonidan oyoq uchida o'tdi."],
      ['limp', 'verb', 'oqsoqlanmoq', 'He was limping after the match.', "O'yindan keyin u oqsoqlanib yurardi."],
      ['amble', 'verb', 'shoshmay sayr qilmoq', 'We ambled along the river bank.', "Daryo bo'yi bo'ylab shoshmay sayr qildik."],
      ['meander', 'verb', 'ilonizi bo\'lib oqmoq', 'The river meanders through the valley.', "Daryo vodiy bo'ylab ilonizi bo'lib oqadi."],
      ['trickle', 'verb', 'chakillab oqmoq', 'Water trickled down the wall.', 'Devordan suv chakillab oqardi.'],
      ['lurch', 'verb', 'keskin chayqalmoq', 'The bus lurched forward.', 'Avtobus keskin oldinga chayqaldi.'],
      ['trample', 'verb', 'oyoq osti qilmoq', 'The crowd trampled the flowers.', 'Olomon gullarni oyoq osti qildi.'],
      ['hop', 'verb', 'bir oyoqda sakramoq', 'The children hopped on one leg.', 'Bolalar bir oyoqda sakrashdi.'],
      ['footstep', 'noun', 'qadam (tovushi)', 'I heard footsteps on the stairs.', 'Zinada qadam tovushlarini eshitdim.'],
      ['chase', 'verb', 'quvlamoq', 'The dog chased the cat up a tree.', 'It mushukni daraxtga quvib chiqardi.'],
      ['unprecedented', 'adjective', "misli ko'rilmagan", 'The city grew at an unprecedented rate.', "Shahar misli ko'rilmagan sur'atda o'sdi."],
    ],
  },
  {
    unit: 62,
    title: 'Manner: behaviour and body language',
    titleUz: 'Xulq-atvor va imo-ishora',
    emoji: '🙃',
    words: [
      ['etiquette', 'noun', 'odob qoidalari (etiket)', 'Table etiquette is important at formal dinners.', 'Rasmiy ziyofatlarda dasturxon odobi muhim.'],
      ['netiquette', 'noun', 'internet odobi', 'Writing in capital letters is bad netiquette.', 'Katta harflarda yozish internet odobiga zid.'],
      ['insolent', 'adjective', 'surbet, beadab', 'The insolent student laughed at the teacher.', "Surbet talaba o'qituvchining ustidan kuldi."],
      ['courtesy', 'noun', 'iltifot', "He didn't even have the courtesy to call.", "U hatto qo'ng'iroq qilish iltifotini ham ko'rsatmadi."],
      ['discourteous', 'adjective', 'beodob', 'The receptionist was discourteous to us.', 'Qabulxona xodimi bizga beodoblik qildi.'],
      ['smirk', 'verb', 'kinoya bilan tirjaymoq', 'He smirked when I made a mistake.', 'Xato qilganimda u kinoya bilan tirjaydi.'],
      ['snort', 'verb', 'pishqirmoq', 'She snorted with laughter.', 'U kulgidan pishqirib yubordi.'],
      ['flinch', 'verb', 'seskanmoq', "He didn't flinch when the doctor gave him the injection.", 'Shifokor ukol qilganda u seskanmadi ham.'],
      ['squirm', 'verb', "xijolatdan to'lg'anmoq", 'He squirmed with embarrassment.', "U xijolatdan o'zini qayoqqa qo'yishni bilmay qoldi."],
      ['titter', 'verb', 'pixillab kulmoq', 'The children tittered at the joke.', 'Bolalar hazilga pixillab kulishdi.'],
      ['straitlaced', 'adjective', "axloqda o'ta qattiqqo'l", 'Her parents are very straitlaced.', "Uning ota-onasi axloqda juda qattiqqo'l."],
      ['stand on ceremony', 'phrase', 'rasmiyatchilik qilmoq', "Please don't stand on ceremony; call me Aziz.", 'Iltimos, rasmiyatchilik qilmang, meni Aziz deb chaqiring.'],
      ['offhand', 'adjective', 'beparvo, sovuq', 'He was rather offhand with me.', "U menga ancha beparvo munosabatda bo'ldi."],
      ['sniff at', 'phrase', 'mensimaslik', "Don't sniff at a free meal!", 'Tekin ovqatni mensimaslik kerak emas!'],
      ['raise your eyebrows', 'phrase', 'qosh chimirmoq', "Don't raise your eyebrows at me like that!", 'Menga bunday qosh chimirma!'],
      ['the done thing', 'phrase', 'odobga muvofiq ish', "It's not the done thing to arrive late.", 'Kechikib kelish odobdan emas.'],
    ],
  },
  {
    unit: 63,
    title: 'Sounds: listen up!',
    titleUz: 'Tovushlar',
    emoji: '🔔',
    words: [
      ['creak', 'verb', "g'ichirlamoq", 'The old door creaked open.', "Eski eshik g'ichirlab ochildi."],
      ['squeak', 'verb', 'chiyillamoq', 'My new shoes squeak when I walk.', 'Yangi tuflilarim yurganda chiyillaydi.'],
      ['slam', 'verb', 'qarsillatib yopmoq', "Don't slam the door!", 'Eshikni qarsillatib yopma!'],
      ['sizzle', 'verb', 'jizillamoq', 'The meat sizzled in the pan.', "Go'sht tovada jizilladi."],
      ['wail', 'verb', "chinqirib yig'lamoq", 'The baby started to wail.', "Chaqaloq chinqirib yig'lay boshladi."],
      ['hoot', 'verb', '(boyqush) chaqirmoq; signal chalmoq', 'An owl hooted in the night.', 'Kechasi boyqush chaqirdi.'],
      ['eerie', 'adjective', 'vahimali, g\'ayritabiiy', 'There was an eerie silence in the empty house.', "Bo'sh uyda vahimali jimlik hukm surardi."],
      ['piercing', 'adjective', 'quloqni teshadigan', 'She let out a piercing scream.', 'U quloqni teshadigan chinqiriq chiqardi.'],
      ['grating', 'adjective', 'quloqqa yoqimsiz', 'He has a grating voice.', 'Uning ovozi quloqqa yoqmaydi.'],
      ['high-pitched', 'adjective', 'ingichka (baland) ovozli', 'The child spoke in a high-pitched voice.', 'Bola ingichka ovozda gapirdi.'],
      ['inaudible', 'adjective', 'eshitilmaydigan', 'His voice was almost inaudible.', 'Uning ovozi deyarli eshitilmasdi.'],
      ['soundless', 'adjective', 'tovushsiz', 'The cat moved with soundless steps.', 'Mushuk tovushsiz qadamlar bilan yurdi.'],
      ['hammer', 'verb', 'qattiq taqillatmoq', 'Someone was hammering on the door.', 'Kimdir eshikni qattiq taqillatardi.'],
      ['pound', 'verb', 'dukillab urmoq', 'My heart was pounding with fear.', "Yuragim qo'rquvdan dukillab urardi."],
      ['you could hear a pin drop', 'phrase', 'igna tushsa eshitiladigan jimjitlik', 'It was so quiet you could hear a pin drop.', 'Shunchalik jimjit ediki, igna tushsa eshitilardi.'],
    ],
  },
  {
    unit: 64,
    title: 'Weight and density',
    titleUz: "Og'irlik va zichlik",
    emoji: '🪨',
    words: [
      ['cumbersome', 'adjective', "beso'naqay", 'The old computers were big and cumbersome.', "Eski kompyuterlar katta va beso'naqay edi."],
      ['unwieldy', 'adjective', 'boshqarishga noqulay', 'The system is slow and unwieldy.', 'Tizim sekin va boshqarishga noqulay.'],
      ['ponderous', 'adjective', "og'ir, vazmin", 'He walked with slow, ponderous steps.', "U sekin, og'ir qadamlar bilan yurdi."],
      ['weighty', 'adjective', 'salmoqli, jiddiy', 'The committee discussed weighty matters.', "Qo'mita salmoqli masalalarni muhokama qildi."],
      ['burdensome', 'adjective', "og'ir (yuk bo'ladigan)", 'The new rules are burdensome for small businesses.', "Yangi qoidalar kichik biznes uchun og'ir yuk."],
      ['impenetrable', 'adjective', "o'tib bo'lmas; tushunib bo'lmas", 'The jungle was almost impenetrable.', "Changalzordan o'tib bo'lmasdi."],
      ['impervious', 'adjective', "o'tkazmaydigan; befarq", 'This coat is impervious to rain.', "Bu palto yomg'ir o'tkazmaydi."],
      ['dilute', 'verb', 'suyultirmoq', 'Dilute the juice with water.', 'Sharbatni suv bilan suyultiring.'],
      ['thicken', 'verb', 'quyuqlashtirmoq', 'Add flour to thicken the sauce.', "Sousni quyuqlashtirish uchun un qo'shing."],
      ['congealed', 'adjective', "qotib qolgan (yog', qon)", 'The cold soup had a layer of congealed fat.', "Sovugan sho'rva ustida qotib qolgan yog' bor edi."],
      ['lumpy', 'adjective', 'kesak-kesak', 'The porridge was lumpy.', "Bo'tqa kesak-kesak bo'lib qolgan edi."],
      ['sift', 'verb', 'elamoq', 'Sift the flour into a bowl.', 'Unni kosaga elang.'],
      ['solidify', 'verb', 'qotmoq', 'The lava solidified as it cooled.', 'Lava sovugach qotib qoldi.'],
      ['weigh up', 'phrase', "tortib ko'rmoq (qaror oldidan)", 'You need to weigh up the pros and cons.', "Yutuq va kamchiliklarni tortib ko'rishing kerak."],
      ['weigh down', 'phrase', 'og\'irlik qilib egmoq', 'Heavy snow can weigh down the branches.', "Qalin qor shoxlarni egib qo'yishi mumkin."],
      ['weigh on your mind', 'phrase', 'xayolini band qilmoq (tashvish)', "Don't let the exam weigh on your mind.", 'Imtihon xayolingni band qilmasin.'],
    ],
  },
  {
    unit: 65,
    title: 'All the colours of the rainbow',
    titleUz: 'Ranglar va rangli iboralar',
    emoji: '🌈',
    words: [
      ['crimson', 'adjective', "to'q qizil", 'Her face turned crimson with embarrassment.', "Uning yuzi xijolatdan qip-qizil bo'ldi."],
      ['scarlet', 'adjective', 'yorqin qizil', 'She wore a scarlet dress.', "U yorqin qizil ko'ylak kiygan edi."],
      ['turquoise', 'adjective', 'feruza rang', 'The sea was a beautiful turquoise colour.', 'Dengiz chiroyli feruza rangda edi.'],
      ['emerald', 'adjective', 'zumrad (yashil)', 'Her eyes are emerald green.', "Uning ko'zlari zumrad yashil."],
      ['navy', 'adjective', "to'q ko'k", 'He wore a navy suit.', "U to'q ko'k kostyum kiygan edi."],
      ['beige', 'adjective', 'bej (och jigarrang)', 'The walls are painted beige.', "Devorlar bej rangga bo'yalgan."],
      ['pastel', 'adjective', 'och, mayin (rang)', "The baby's room is painted in pastel colours.", "Chaqaloq xonasi och ranglarga bo'yalgan."],
      ['fluorescent', 'adjective', 'yorqin nurli (fluoressent)', 'Cyclists should wear fluorescent jackets.', 'Velosipedchilar yorqin nurli kurtka kiyishi kerak.'],
      ['monochrome', 'adjective', 'bir rangli (oq-qora)', 'The photo is in monochrome.', 'Surat bir rangda.'],
      ['jet black', 'phrase', 'qop-qora', 'She has jet black hair.', 'Uning sochi qop-qora.'],
      ['red-letter day', 'phrase', 'unutilmas (bayramona) kun', 'The day I got my first job was a red-letter day.', "Birinchi ishga kirgan kunim unutilmas kun bo'ldi."],
      ['grey area', 'phrase', 'noaniq holat', 'The law on this is a grey area.', 'Bu borada qonun noaniq.'],
      ['black sheep', 'phrase', "(oilaning) qora qo'yi", "He's the black sheep of the family.", "U oilaning qora qo'yi."],
      ['green with envy', 'phrase', 'havasdan kuymoq', 'She was green with envy when she saw my new car.', "Yangi mashinamni ko'rib, u havasdan kuydi."],
      ['white-collar', 'adjective', 'oq yoqali (ofis xodimi)', 'White-collar workers work in offices.', 'Oq yoqalilar ofislarda ishlaydi.'],
      ['blue-collar', 'adjective', "ko'k yoqali (qo'l mehnati)", 'Blue-collar jobs involve physical work.', "Ko'k yoqali ishlar jismoniy mehnatni talab qiladi."],
      ['black market', 'phrase', 'qora bozor', 'They bought dollars on the black market.', 'Ular dollarni qora bozorda sotib olishdi.'],
      ['tinge', 'noun', 'tus, tovlanish', 'The sky had a pink tinge.', 'Osmonda pushti tus bor edi.'],
    ],
  },
  {
    unit: 66,
    title: 'Speed: fast and slow',
    titleUz: 'Tezlik',
    emoji: '💨',
    words: [
      ['accelerate', 'verb', 'tezlashmoq', 'The car accelerated quickly.', 'Mashina tez tezlashdi.'],
      ['plummet', 'verb', 'keskin tushib ketmoq', 'Temperatures plummeted overnight.', 'Harorat bir kechada keskin tushib ketdi.'],
      ['plunge', 'verb', "sho'ng'imoq", 'He plunged into the cold water.', "U sovuq suvga sho'ng'idi."],
      ['soar', 'verb', 'baland parvoz qilmoq; keskin oshmoq', 'The eagle soared above the mountains.', "Burgut tog'lar uzra parvoz qildi."],
      ['rocket', 'verb', 'keskin oshmoq', 'House prices have rocketed.', 'Uy narxlari keskin oshib ketdi.'],
      ['scurry', 'verb', 'lip-lip yugurmoq', 'The mice scurried across the floor.', "Sichqonlar pol bo'ylab lip-lip yugurib o'tdi."],
      ['scamper', 'verb', 'yugurib ketmoq (quvnoq)', 'The children scampered off to play.', "Bolalar o'ynagani yugurib ketishdi."],
      ['bolt', 'verb', 'otilib qochmoq', 'The horse bolted when it heard the noise.', 'Shovqinni eshitib, ot otilib qochdi.'],
      ['dart', 'verb', "o'qdek otilmoq", 'A cat darted across the road.', "Mushuk yo'ldan o'qdek o'tib ketdi."],
      ['nip', 'verb', 'bir borib kelmoq (tez)', "I'll just nip to the shop.", "Do'konga bir borib kelaman."],
      ['sidle', 'verb', 'yonboshlab yaqinlashmoq', 'He sidled up to me and asked for money.', "U menga yonboshlab yaqinlashib, pul so'radi."],
      ['tumble', 'verb', 'dumalab tushmoq', 'The boy tumbled down the hill.', 'Bola tepalikdan dumalab tushdi.'],
      ['race', 'verb', 'chopmoq (shoshib)', 'We raced to the station.', 'Vokzalga chopib bordik.'],
      ['pop in', 'phrase', "kirib o'tmoq", 'Pop in for a cup of tea.', "Bir piyola choyga kirib o't."],
      ["at a snail's pace", 'phrase', 'toshbaqa qadami bilan', "The traffic moved at a snail's pace.", 'Transport toshbaqa qadami bilan harakatlandi.'],
    ],
  },
  {
    unit: 67,
    title: 'Cause and effect',
    titleUz: 'Sabab va oqibat',
    emoji: '🔗',
    words: [
      ['precipitate', 'verb', '(yomon voqeani) tezlashtirmoq', 'The scandal precipitated his resignation.', "Janjal uning iste'fosini tezlashtirdi."],
      ['implication', 'noun', "oqibat, ta'sir", 'What are the implications of this decision?', 'Bu qarorning oqibatlari qanday?'],
      ['grounds', 'noun', 'asos', 'There are no grounds for complaint.', "Shikoyat uchun asos yo'q."],
      ['spark', 'verb', "qo'zg'atmoq (bahs, norozilik)", 'The decision sparked a debate.', "Qaror bahs-munozaraga sabab bo'ldi."],
      ['trigger', 'verb', "to'satdan boshlab yubormoq", 'Stress can trigger headaches.', "Stress bosh og'rig'ini qo'zg'atishi mumkin."],
      ['knock-on effect', 'phrase', "zanjirli ta'sir", 'Higher fuel prices have a knock-on effect on food prices.', "Yoqilg'i narxining oshishi oziq-ovqat narxlariga zanjirli ta'sir qiladi."],
      ['repercussions', 'noun', 'asoratlar', 'The decision will have serious repercussions.', 'Qarorning jiddiy asoratlari bo\'ladi.'],
      ['by-product', 'noun', 'yondosh mahsul', 'Stress is a by-product of modern life.', 'Stress zamonaviy hayotning yondosh mahsuli.'],
      ['result in', 'phrase', "natijasida ... bo'lmoq", 'The storm could result in power cuts.', "Bo'ron natijasida elektr uzilishi bo'lishi mumkin."],
      ['derive from', 'phrase', "...dan olingan bo'lmoq", 'Many English words derive from Latin.', "Ko'p inglizcha so'zlar lotin tilidan olingan."],
      ['contributing factor', 'phrase', "ta'sir etuvchi omil", 'Poor diet is a contributing factor to heart disease.', "Noto'g'ri ovqatlanish yurak kasalligiga ta'sir etuvchi omillardan biri."],
    ],
  },
  {
    unit: 68,
    title: 'Spot the difference: making comparisons',
    titleUz: 'Taqqoslash',
    emoji: '🔍',
    words: [
      ['akin', 'adjective', "o'xshash, yaqin", 'The feeling was akin to fear.', "Bu tuyg'u qo'rquvga o'xshash edi."],
      ['analogy', 'noun', "o'xshatish (analogiya)", 'The teacher used an analogy to explain the idea.', "O'qituvchi g'oyani tushuntirish uchun o'xshatishdan foydalandi."],
      ['comparable', 'adjective', 'qiyoslasa bo\'ladigan', 'Salaries here are comparable to those in Europe.', "Bu yerdagi maoshlarni Yevropadagi bilan qiyoslasa bo'ladi."],
      ['correspond', 'verb', 'mos kelmoq', "The figures don't correspond.", 'Raqamlar bir-biriga mos kelmaydi.'],
      ['differentiate', 'verb', 'farqlamoq', "It's hard to differentiate between the twins.", 'Egizaklarni bir-biridan farqlash qiyin.'],
      ['distinguish', 'verb', 'ajratmoq, farqini bilmoq', 'Can you distinguish between the two sounds?', 'Ikki tovushni ajrata olasizmi?'],
      ['distinct', 'adjective', 'aniq, yaqqol', 'There is a distinct difference in taste.', "Ta'mda yaqqol farq bor."],
      ['distinctive', 'adjective', "o'ziga xos", 'He has a very distinctive voice.', "Uning o'ziga xos ovozi bor."],
      ['disparate', 'adjective', "bir-biriga bog'liq bo'lmagan, turfa", 'The book brings together disparate ideas.', "Kitob bir-biriga bog'liq bo'lmagan g'oyalarni birlashtiradi."],
      ['dissimilar', 'adjective', "o'xshamagan", 'The two brothers are not dissimilar.', "Ikki aka-uka bir-biriga o'xshamaydi deb bo'lmaydi."],
      ['diverge', 'verb', "(fikr, yo'l) ajralmoq", 'Our opinions diverge on this issue.', 'Bu masalada fikrlarimiz ajraladi.'],
      ['diverse', 'adjective', 'xilma-xil', 'Tashkent has a diverse population.', 'Toshkent aholisi xilma-xil.'],
      ['equate', 'verb', 'tenglashtirmoq', "Don't equate money with happiness.", 'Pulni baxt bilan tenglashtirma.'],
      ['indistinguishable', 'adjective', "farqlab bo'lmaydigan", 'The copy is indistinguishable from the original.', "Nusxani asldan farqlab bo'lmaydi."],
      ['interchangeable', 'adjective', 'o\'zaro almashtirsa bo\'ladigan', 'These two words are interchangeable.', "Bu ikki so'zni o'zaro almashtirsa bo'ladi."],
      ['tantamount to', 'phrase', '...ga teng (baravar)', 'His silence was tantamount to a confession.', 'Uning jimligi iqrorga teng edi.'],
      ['affinity', 'noun', 'yaqinlik, moyillik', 'She has a natural affinity with animals.', 'Uning hayvonlarga tabiiy yaqinligi bor.'],
    ],
  },
  {
    unit: 69,
    title: 'Difficulties and dilemmas',
    titleUz: 'Qiyinchiliklar',
    emoji: '🧗',
    words: [
      ['arduous', 'adjective', 'mashaqqatli', 'It was an arduous climb to the top.', "Tepaga chiqish mashaqqatli bo'ldi."],
      ['gruelling', 'adjective', 'holdan toydiradigan', 'Nurses work gruelling twelve-hour shifts.', "Hamshiralar holdan toydiradigan o'n ikki soatlik smenalarda ishlaydi."],
      ['convoluted', 'adjective', 'chalkash, murakkab', 'The instructions were convoluted.', "Ko'rsatmalar chalkash edi."],
      ['abstruse', 'adjective', 'tushunish qiyin (ilmiy)', 'The lecture was too abstruse for most students.', "Ma'ruza ko'pchilik talabalar uchun tushunish qiyin edi."],
      ['hassle', 'noun', 'ovoragarchilik', 'Getting a visa is such a hassle.', 'Viza olish katta ovoragarchilik.'],
      ['glitch', 'noun', 'texnik nosozlik', 'A technical glitch delayed the launch.', 'Texnik nosozlik ishga tushirishni kechiktirdi.'],
      ['hitch', 'noun', 'kichik muammo', 'The ceremony went off without a hitch.', "Marosim hech qanday muammosiz o'tdi."],
      ['snag', 'noun', "kutilmagan to'siq", "There's one snag: we don't have enough money.", "Bitta to'siq bor: pulimiz yetmaydi."],
      ['pitfall', 'noun', 'yashirin xavf, tuzoq', 'The book describes the pitfalls of starting a business.', 'Kitobda biznes boshlashning yashirin xavflari tasvirlangan.'],
      ['setback', 'noun', 'orqaga ketish, muvaffaqiyatsizlik', 'The injury was a major setback for the team.', "Jarohat jamoa uchun jiddiy orqaga ketish bo'ldi."],
      ['stumbling block', 'phrase', "asosiy to'siq", 'Money is the main stumbling block.', "Asosiy to'siq — pul."],
      ['impediment', 'noun', "to'siq (rasmiy)", 'Lack of education is an impediment to progress.', "Ta'lim yetishmasligi taraqqiyotga to'siq."],
      ['slog', 'noun', "og'ir, zerikarli mehnat", 'Finishing the report was a real slog.', "Hisobotni tugatish haqiqiy og'ir mehnat bo'ldi."],
      ['downside', 'noun', 'salbiy tomon', 'The downside of the job is the long hours.', 'Ishning salbiy tomoni — uzoq ish soatlari.'],
      ['traumatic', 'adjective', "og'ir ruhiy zarba beradigan", 'The accident was a traumatic experience.', "Avariya og'ir ruhiy zarba bo'ldi."],
      ['in a fix', 'phrase', 'qiyin ahvolda', "I'm in a fix; I've lost my keys.", "Qiyin ahvolda qoldim, kalitlarimni yo'qotdim."],
      ["what's eating you", 'phrase', 'seni nima tashvishlantiryapti?', "You look upset. What's eating you?", "Xafa ko'rinasan. Seni nima tashvishlantiryapti?"],
    ],
  },
  {
    unit: 70,
    title: 'Modality: expressing facts, opinions, desires',
    titleUz: 'Ehtimol, istak va zarurat',
    emoji: '🤔',
    words: [
      ['aspiration', 'noun', 'intilish, orzu', 'She has aspirations to become a writer.', "Uning yozuvchi bo'lishga intilishi bor."],
      ['bound to', 'phrase', "albatta (bo'ladi)", "It's bound to rain this weekend.", "Bu dam olish kunlari albatta yomg'ir yog'adi."],
      ['overjoyed', 'adjective', 'benihoya xursand', 'They were overjoyed at the birth of their son.', "Ular o'g'il ko'rganidan benihoya xursand bo'lishdi."],
      ['resolved', 'adjective', "qat'iy ahd qilgan", 'He was resolved to succeed.', "U muvaffaqiyatga erishishga qat'iy ahd qilgandi."],
      ['unquestionably', 'adverb', 'shubhasiz', 'She is unquestionably the best player.', "U shubhasiz eng yaxshi o'yinchi."],
      ['in all likelihood', 'phrase', 'katta ehtimol bilan', 'In all likelihood, the meeting will be cancelled.', 'Katta ehtimol bilan uchrashuv bekor qilinadi.'],
      ['the odds are', 'phrase', 'ehtimoli katta (...ki)', "The odds are that he won't come.", 'Uning kelmasligi ehtimoli katta.'],
      ['eager', 'adjective', 'ishtiyoqmand', 'The students were eager to learn.', "Talabalar o'rganishga ishtiyoqmand edi."],
      ['essential', 'adjective', 'zarur, muhim', 'Water is essential for life.', 'Suv hayot uchun zarur.'],
      ['determined', 'adjective', "qat'iy niyatli", 'She is determined to win.', "U g'alaba qozonishga qat'iy niyatli."],
      ['accidents will happen', 'phrase', "har narsa bo'lib turadi", "Don't worry about the broken cup; accidents will happen.", "Singan piyola haqida qayg'urma, har narsa bo'lib turadi."],
      ['I should be so lucky', 'phrase', 'kani edi (ishonmay)', 'Win the lottery? I should be so lucky!', 'Lotereya yutishmi? Kani edi!'],
      ['apparent', 'adjective', "ayon, ko'rinib turgan", 'It soon became apparent that he was lying.', "Tez orada uning yolg'on gapirayotgani ayon bo'ldi."],
      ['wish', 'verb', 'istamoq (armon bilan)', 'I wish I could speak Chinese.', 'Xitoycha gapira olsam edi.'],
    ],
  },
  {
    unit: 71,
    title: 'Number: statistics and quantity',
    titleUz: 'Statistika va miqdor',
    emoji: '📈',
    words: [
      ['aggregate', 'adjective', 'umumiy, jami', 'The aggregate score was 3–2.', "Umumiy hisob 3:2 bo'ldi."],
      ['ballpark figure', 'phrase', 'taxminiy raqam', 'Can you give me a ballpark figure?', 'Taxminiy raqamni ayta olasizmi?'],
      ['blip', 'noun', 'vaqtinchalik tebranish', 'The fall in sales was just a blip.', 'Savdoning pasayishi shunchaki vaqtinchalik tebranish edi.'],
      ['correlation', 'noun', "bog'liqlik (korrelyatsiya)", 'There is a correlation between smoking and cancer.', "Chekish va saraton o'rtasida bog'liqlik bor."],
      ['deviate', 'verb', 'chetga chiqmoq', "Don't deviate from the plan.", 'Rejadan chetga chiqma.'],
      ['erratic', 'adjective', 'beqaror, tartibsiz', 'His behaviour has become erratic.', "Uning xatti-harakati beqaror bo'lib qoldi."],
      ['expenditure', 'noun', 'xarajat (rasmiy)', 'Government expenditure on health has increased.', "Hukumatning sog'liqni saqlashga xarajati oshdi."],
      ['fluctuate', 'verb', "tebranmoq (o'zgarib turmoq)", 'Prices fluctuate from day to day.', 'Narxlar kundan kunga tebranib turadi.'],
      ['GDP', 'noun', 'YaIM (yalpi ichki mahsulot)', "The country's GDP grew by 6%.", "Mamlakat YaIMi 6% o'sdi."],
      ['inconsistent', 'adjective', 'bir-biriga zid, nomuvofiq', 'His statements were inconsistent.', 'Uning bayonotlari bir-biriga zid edi.'],
      ['projected', 'adjective', 'prognoz qilingan', 'The projected growth for next year is 5%.', "Kelasi yilga prognoz qilingan o'sish 5%."],
      ['quadruple', 'verb', "to'rt barobar oshmoq", 'The price has quadrupled in ten years.', "Narx o'n yilda to'rt barobar oshdi."],
      ['ratio', 'noun', 'nisbat', 'The ratio of students to teachers is 20 to 1.', "Talabalarning o'qituvchilarga nisbati 20 ga 1."],
      ['twofold', 'adjective', 'ikki barobar', 'There has been a twofold increase in sales.', 'Savdo ikki barobar oshdi.'],
      ['variable', 'adjective', "o'zgaruvchan", 'The weather here is very variable.', "Bu yerda ob-havo juda o'zgaruvchan."],
      ['flawed', 'adjective', 'nuqsonli', 'The research was flawed.', 'Tadqiqot nuqsonli edi.'],
      ['err on the side of caution', 'phrase', "ehtiyot shart yo'lini tanlamoq", "It's better to err on the side of caution.", "Ehtiyot shart yo'lini tanlagan ma'qul."],
    ],
  },
  {
    unit: 72,
    title: 'Permission: getting the go-ahead',
    titleUz: 'Ruxsat va taqiq',
    emoji: '🟢',
    words: [
      ['authorise', 'verb', 'ruxsat bermoq (vakolat bilan)', 'Only the manager can authorise payments.', "Faqat menejer to'lovlarga ruxsat bera oladi."],
      ['endorse', 'verb', "rasman qo'llab-quvvatlamoq", 'The party endorsed her as their candidate.', "Partiya uni o'z nomzodi sifatida qo'llab-quvvatladi."],
      ['condone', 'verb', "(yomonlikka) ko'z yummoq", 'We cannot condone violence.', "Zo'ravonlikka ko'z yuma olmaymiz."],
      ['veto', 'verb', "veto qo'ymoq", 'The president vetoed the bill.', "Prezident qonun loyihasiga veto qo'ydi."],
      ['outlaw', 'verb', 'qonunan taqiqlamoq', 'The government outlawed smoking in public places.', 'Hukumat jamoat joylarida chekishni taqiqladi.'],
      ['acquiesce', 'verb', "indamay rozi bo'lmoq", 'She acquiesced to his demands.', "U uning talablariga indamay rozi bo'ldi."],
      ['assent', 'noun', 'rozilik (rasmiy)', 'The king gave his assent to the new law.', 'Qirol yangi qonunga rozilik berdi.'],
      ['accede', 'verb', "(talabga) rozi bo'lmoq", "The company acceded to the workers' demands.", "Kompaniya ishchilar talablariga rozi bo'ldi."],
      ['carte blanche', 'phrase', "to'liq erkinlik", 'The new director was given carte blanche to make changes.', "Yangi direktorga o'zgarishlar kiritish uchun to'liq erkinlik berildi."],
      ['give the green light', 'phrase', 'ruxsat bermoq (yashil chiroq)', 'The council will give the green light to the project.', 'Kengash loyihaga yashil chiroq yoqadi.'],
      ['give the thumbs up', 'phrase', "ma'qullamoq", 'The boss will give the thumbs up to our idea.', "Boshliq g'oyamizni ma'qullaydi."],
      ['countenance', 'verb', "yo'l qo'ymoq (rasmiy)", 'They would never countenance such a plan.', "Ular bunday rejaga hech qachon yo'l qo'ymaydi."],
      ['clamp down on', 'phrase', 'qattiq choralar ko\'rmoq', 'Police are going to clamp down on speeding.', "Politsiya tezlikni oshirishga qarshi qattiq choralar ko'rmoqchi."],
    ],
  },
  {
    unit: 73,
    title: 'Complaining and protesting',
    titleUz: 'Shikoyat va norozilik',
    emoji: '😤',
    words: [
      ['complaint', 'noun', 'shikoyat', "I'd like to make a complaint.", 'Shikoyat qilmoqchiman.'],
      ['gripe', 'noun', "norozilik, g'ing'illash", 'His main gripe is the pay.', 'Uning asosiy noroziligi — maoshdan.'],
      ['grouse', 'verb', "g'ingshimoq (so'zlashuv)", 'Stop grousing about the weather.', "Ob-havodan g'ingshishni bas qil."],
      ['whinge', 'verb', 'zorlanib nolimoq', "He's always whingeing about something.", 'U doim nimadandir noliydi.'],
      ['remonstrate', 'verb', "e'tiroz bildirmoq (rasmiy)", 'He remonstrated with the referee.', "U hakamga e'tiroz bildirdi."],
      ['fault-finding', 'noun', 'ayb qidirish', 'Constant fault-finding hurts relationships.', 'Doimiy ayb qidirish munosabatlarga zarar yetkazadi.'],
      ['enough is enough', 'phrase', 'bas, yetar!', "Enough is enough! I'm leaving.", 'Yetar! Men ketaman.'],
      ['unacceptable', 'adjective', 'qabul qilib bo\'lmaydigan', 'This behaviour is completely unacceptable.', 'Bunday xatti-harakat mutlaqo qabul qilinmaydi.'],
      ['fed up to the back teeth', 'phrase', 'jonga tegib ketgan', "I'm fed up to the back teeth with his excuses.", 'Uning bahonalari jonimga tegdi.'],
      ['take great exception to', 'phrase', "qattiq e'tiroz bildirmoq", 'I take great exception to your remarks.', "Gaplaringizga qattiq e'tiroz bildiraman."],
      ['protest', 'noun', 'norozilik aksiyasi', 'They held a protest outside the embassy.', "Ular elchixona oldida norozilik aksiyasi o'tkazishdi."],
      ['objection', 'noun', "e'tiroz", 'Does anyone have any objections?', "Kimdadir e'tiroz bormi?"],
      ['shameful', 'adjective', 'sharmandali', "It's shameful to treat people like that.", "Odamlarga bunday munosabatda bo'lish sharmandalik."],
      ["I've just about had enough", 'phrase', "to'yib ketdim (sabr tugadi)", "I've just about had enough of your complaints!", "Shikoyatlaringdan to'yib ketdim!"],
    ],
  },
  {
    unit: 74,
    title: 'Apology, regret and reconciliation',
    titleUz: 'Kechirim va yarashish',
    emoji: '🤝',
    words: [
      ['apology', 'noun', "kechirim so'rash", 'I owe you an apology.', "Sizdan kechirim so'rashim kerak."],
      ['remorse', 'noun', 'pushaymonlik', 'He showed no remorse for his crime.', "U jinoyati uchun hech qanday pushaymonlik ko'rsatmadi."],
      ['repent', 'verb', 'tavba qilmoq', 'He repented of his sins.', 'U gunohlaridan tavba qildi.'],
      ['pardon', 'verb', 'afv etmoq', 'The president pardoned the prisoners.', 'Prezident mahbuslarni afv etdi.'],
      ['exonerate', 'verb', 'aybdan xalos qilmoq', 'The report exonerated the police.', 'Hisobot politsiyani aybdan xalos qildi.'],
      ['reprieve', 'noun', 'vaqtincha najot (kechiktirish)', 'The factory got a reprieve from closure.', "Zavodning yopilishi vaqtincha to'xtatildi."],
      ['heartfelt', 'adjective', 'chin dildan', 'Please accept my heartfelt thanks.', 'Chin dildan minnatdorchiligimni qabul qiling.'],
      ['lame', 'adjective', "bo'sh, ishonchsiz (bahona)", "That's a lame excuse.", "Bu bo'sh bahona."],
      ['flimsy', 'adjective', 'zaif, puch', 'The evidence against him is flimsy.', 'Unga qarshi dalillar zaif.'],
      ['pretext', 'noun', 'bahona (soxta sabab)', 'He used illness as a pretext for not coming.', 'U kelmaslik uchun kasallikni bahona qildi.'],
      ['alibi', 'noun', "alibi (voqea joyida bo'lmaganlik dalili)", 'He has an alibi for the night of the murder.', 'Qotillik kechasi uchun uning alibisi bor.'],
      ['forgive and forget', 'phrase', 'kechirib unutmoq', "Let's forgive and forget.", 'Keling, kechirib, unutaylik.'],
      ['cast-iron', 'adjective', 'mustahkam, rad etib bo\'lmas', 'She has a cast-iron alibi.', 'Uning mustahkam alibisi bor.'],
      ['treaty', 'noun', 'shartnoma (davlatlararo)', 'The two countries signed a peace treaty.', 'Ikki davlat tinchlik shartnomasini imzoladi.'],
      ['accord', 'noun', 'kelishuv (rasmiy)', 'The accord ended years of fighting.', 'Kelishuv yillab davom etgan janglarga barham berdi.'],
      ['posthumous', 'adjective', 'vafotidan keyingi', 'He received a posthumous award for bravery.', 'U jasorati uchun vafotidan keyin mukofotlandi.'],
    ],
  },
  {
    unit: 75,
    title: 'A pat on the back: complimenting and praising',
    titleUz: 'Maqtov va xushomad',
    emoji: '👏',
    words: [
      ['flatter', 'verb', 'xushomad qilmoq', 'He flatters his boss to get promoted.', "U lavozim olish uchun boshlig'iga xushomad qiladi."],
      ['flattery', 'noun', 'xushomad', 'Flattery will get you nowhere.', 'Xushomad bilan hech narsaga erisha olmaysan.'],
      ['compliment', 'noun', 'maqtov (iltifot)', 'She paid me a nice compliment.', 'U menga yoqimli maqtov aytdi.'],
      ['back-handed compliment', 'phrase', 'kinoyali maqtov', "'You look good for your age' is a back-handed compliment.", "«Yoshingizga nisbatan yaxshi ko'rinasiz» — kinoyali maqtov."],
      ['fish for compliments', 'phrase', 'maqtov kutmoq', "Don't fish for compliments!", 'Maqtov kutib gapirma!'],
      ['pay tribute to', 'phrase', 'hurmat bajo keltirmoq', 'Let us pay tribute to the soldiers.', 'Keling, askarlarga hurmat bajo keltiraylik.'],
      ['laudable', 'adjective', 'maqtovga loyiq', "It's a laudable aim.", 'Bu maqtovga loyiq maqsad.'],
      ['obsequious', 'adjective', 'laganbardor', 'The waiter was annoyingly obsequious.', 'Ofitsiant jonga tegadigan darajada laganbardor edi.'],
      ['servile', 'adjective', 'qullarcha itoatkor', 'He behaves in a servile way towards his boss.', "U boshlig'iga qullarcha itoat qiladi."],
      ['smarmy', 'adjective', 'soxta xushomadgo\'y', "I don't trust that smarmy salesman.", "Men u soxta xushomadgo'y sotuvchiga ishonmayman."],
      ['suck up to', 'phrase', "yaltoqlanmoq (so'zlashuv)", "Don't suck up to the teacher.", "O'qituvchiga yaltoqlanma."],
      ['heap praise on', 'phrase', "maqtovga ko'mmoq", 'Critics heap praise on her new novel.', "Tanqidchilar uning yangi romanini maqtovga ko'mishmoqda."],
      ['sing the praises of', 'phrase', 'maqtab tugatolmaslik', 'Customers sing the praises of this restaurant.', 'Mijozlar bu restoranni maqtab tugatolmaydi.'],
      ['a pat on the back', 'phrase', "rag'bat, maqtov", 'You deserve a pat on the back for your hard work.', "Tirishqoqliging uchun rag'batga loyiqsan."],
      ['extol', 'verb', "ulug'lamoq, madh etmoq", 'The advert tries to extol the virtues of the new car.', "Reklama yangi mashinaning afzalliklarini ulug'lashga urinadi."],
      ['plaudits', 'noun', 'olqishlar', 'The team won plaudits for their performance.', "Jamoa o'yini uchun olqishlarga sazovor bo'ldi."],
    ],
  },
  {
    unit: 76,
    title: 'Promises and bets',
    titleUz: "Va'da va garov",
    emoji: '🤞',
    words: [
      ['oath', 'noun', 'qasamyod', 'The president took the oath of office.', 'Prezident qasamyod qildi.'],
      ['swear', 'verb', 'qasam ichmoq; so\'kinmoq', 'Do you swear to tell the truth?', 'Haqiqatni aytishga qasam ichasizmi?'],
      ['break a promise', 'phrase', "va'dani buzmoq", 'Never break a promise to a child.', "Bolaga bergan va'dangni hech qachon buzma."],
      ['keep a promise', 'phrase', "va'dasida turmoq", 'He always tries to keep a promise.', "U doim va'dasida turishga harakat qiladi."],
      ['go back on your word', 'phrase', "so'zidan qaytmoq", "Don't go back on your word.", "So'zingdan qaytma."],
      ['promising', 'adjective', 'umidli, istiqbolli', "She's a very promising student.", 'U juda umidli talaba.'],
      ["New Year's resolution", 'phrase', 'Yangi yil ahdi', "My New Year's resolution is to learn English.", "Yangi yildagi ahdim — ingliz tilini o'rganish."],
      ['gamble', 'verb', "qimor o'ynamoq", 'He lost all his money gambling.', "U qimor o'ynab, bor pulidan ayrildi."],
      ['bet', 'verb', "garov o'ynamoq", "I bet you ten dollars he'll be late.", "U kechikadi deb o'n dollarga garov o'ynayman."],
      ['odds', 'noun', 'imkoniyat (ehtimollik nisbati)', 'The odds are against us.', "Imkoniyatlar biz tomonda emas."],
      ['stake', 'noun', 'ulush; garovga tikilgan narsa', 'He has a large stake in the company.', 'Uning kompaniyada katta ulushi bor.'],
      ['wager', 'verb', 'garovlashmoq (rasmiy)', "I'll wager that he doesn't come.", 'U kelmasligiga garovlashaman.'],
      ['hedge your bets', 'phrase', 'xavfni kamaytirmoq (bir necha yo\'l tutib)', 'Apply to several universities to hedge your bets.', 'Xavfni kamaytirish uchun bir nechta universitetga hujjat topshiring.'],
      ['you bet', 'phrase', "albatta! (so'zlashuv)", 'Are you coming? You bet!', 'Kelasanmi? Albatta!'],
      ['swear word', 'phrase', "so'kinish so'zi", "Don't use swear words in class.", "Darsda so'kinish so'zlarini ishlatmang."],
    ],
  },
  {
    unit: 77,
    title: 'Reminiscences and regrets',
    titleUz: 'Xotiralar va afsuslar',
    emoji: '🕰️',
    words: [
      ['nostalgia', 'noun', "o'tmishni sog'inish (nostalgiya)", 'She felt nostalgia for her childhood.', "U bolaligini sog'inch bilan esladi."],
      ['reminisce', 'verb', "o'tmishni eslamoq", 'We sat and reminisced about our school days.', "O'tirib, maktab yillarimizni esladik."],
      ['lament', 'verb', 'afsus chekmoq', 'He lamented the loss of old traditions.', "U eski an'analarning yo'qolganidan afsus chekdi."],
      ['mourn', 'verb', 'aza tutmoq', 'The nation mourned the death of the poet.', 'Xalq shoirning vafoti uchun aza tutdi.'],
      ['rue', 'verb', 'qattiq afsuslanmoq', "You'll rue the day you left.", 'Ketgan kuningdan qattiq afsuslanasan.'],
      ['pang', 'noun', "(to'satdan) sanchiq, azob", 'She felt a pang of guilt.', 'Uning vijdoni sanchib ketdi.'],
      ['conscience', 'noun', 'vijdon', 'My conscience is clear.', 'Vijdonim toza.'],
      ['guilt', 'noun', 'aybdorlik hissi', 'He felt a lot of guilt about leaving his family.', 'Oilasini tashlab ketgani uchun u aybdorlik his qilardi.'],
      ['shame', 'noun', 'uyat, sharm', "There's no shame in asking for help.", "Yordam so'rashda uyat yo'q."],
      ['look back on', 'phrase', 'orqaga nazar tashlamoq', 'I look back on those years with pleasure.', "O'sha yillarga zavq bilan nazar tashlayman."],
      ['rose-tinted spectacles', 'phrase', "pushti ko'zoynak (haddan ortiq ijobiy qarash)", 'He sees the past through rose-tinted spectacles.', "U o'tmishga pushti ko'zoynak orqali qaraydi."],
      ["it's all coming back to me", 'phrase', 'hammasi yodimga tushyapti', "Now I see the photo, it's all coming back to me.", "Suratni ko'rib, hammasi yodimga tushyapti."],
      ['vague', 'adjective', "noaniq, g'ira-shira", 'I have a vague memory of my first school.', "Birinchi maktabim haqida g'ira-shira xotiram bor."],
      ['ring a bell', 'phrase', 'tanish tuyulmoq', "Does the name 'Karimov' ring a bell?", "«Karimov» ismi tanish tuyulyaptimi?"],
      ['what became of', 'phrase', '...ga nima bo\'ldi (taqdiri)', 'I wonder what became of my old classmates.', "Eski sinfdoshlarimga nima bo'ldi ekan."],
    ],
  },
  {
    unit: 78,
    title: 'Agreement, disagreement and compromise',
    titleUz: 'Kelishuv, kelishmovchilik va murosa',
    emoji: '⚖️',
    words: [
      ['concur', 'verb', "fikriga qo'shilmoq (rasmiy)", 'I concur with your view.', "Fikringizga qo'shilaman."],
      ['dissent', 'noun', 'norozilik, fikr ayriligi', 'There was some dissent within the party.', 'Partiya ichida biroz noroziliklar bor edi.'],
      ['concession', 'noun', 'yon berish', 'Both sides had to make concessions.', "Ikkala tomon ham yon berishga majbur bo'ldi."],
      ['controversy', 'noun', 'tortishuv, bahs', 'The decision caused a lot of controversy.', "Qaror ko'p tortishuvlarga sabab bo'ldi."],
      ['coincide', 'verb', "mos kelmoq; bir vaqtga to'g'ri kelmoq", 'Our views coincide on this matter.', 'Bu masalada fikrlarimiz mos keladi.'],
      ['conform', 'verb', "(qoidaga) bo'ysunmoq", 'Students must conform to the school rules.', "Talabalar maktab qoidalariga bo'ysunishi kerak."],
      ['tally', 'verb', "(hisob) to'g'ri kelmoq", "The two accounts don't tally.", "Ikki hisob bir-biriga to'g'ri kelmaydi."],
      ['settlement', 'noun', 'kelishuv (nizoni hal qilish)', 'They reached a settlement out of court.', 'Ular suddan tashqari kelishuvga erishishdi.'],
      ['reach a compromise', 'phrase', 'murosaga kelmoq', 'After hours of talks, they managed to reach a compromise.', 'Soatlab muzokaradan so\'ng ular murosaga kelishdi.'],
      ['approval', 'noun', "ma'qullash, rozilik", 'The plan needs the approval of the board.', "Reja kengash ma'qullashini talab qiladi."],
      ['discretion', 'noun', 'ixtiyor', "The decision is at the manager's discretion.", 'Qaror menejer ixtiyorida.'],
      ['meet halfway', 'phrase', 'yon bosib, o\'rtada kelishmoq', "Let's meet halfway on the price.", "Narxda o'rtada kelishaylik."],
      ['precisely', 'adverb', 'aynan', "That's precisely what I mean.", 'Aynan shuni nazarda tutyapman.'],
      ['in agreement', 'phrase', 'bir fikrda', 'The two leaders are in agreement.', 'Ikki rahbar bir fikrda.'],
    ],
  },
  {
    unit: 79,
    title: 'Academic writing: making sense',
    titleUz: 'Ilmiy yozuv: mazmun',
    emoji: '📝',
    words: [
      ['advocate', 'verb', "yoqlamoq, targ'ib qilmoq", 'The report advocates stricter laws.', "Hisobot qat'iyroq qonunlarni yoqlaydi."],
      ['ambiguous', 'adjective', "ikki ma'noli, noaniq", 'The question was ambiguous.', "Savol ikki ma'noli edi."],
      ['arbitrary', 'adjective', "asossiz, o'zboshimcha", 'The choice seemed completely arbitrary.', 'Tanlov mutlaqo asossiz tuyuldi.'],
      ['coherent', 'adjective', "izchil, bog'langan", 'Your essay needs a more coherent structure.', 'Inshongizga izchilroq tuzilma kerak.'],
      ['contradict', 'verb', 'zid bo\'lmoq, inkor etmoq', 'The evidence contradicts his story.', 'Dalillar uning hikoyasiga zid.'],
      ['crucial', 'adjective', 'hal qiluvchi', 'This is a crucial point in the argument.', 'Bu dalildagi hal qiluvchi nuqta.'],
      ['deduce', 'verb', 'mantiqan xulosa chiqarmoq', 'From the data, we can deduce that prices will rise.', "Ma'lumotlardan narxlar oshadi degan xulosa chiqarishimiz mumkin."],
      ['demonstrate', 'verb', 'ko\'rsatib bermoq, isbotlamoq', 'The study demonstrates the benefits of exercise.', "Tadqiqot jismoniy mashqning foydasini ko'rsatib beradi."],
      ['denote', 'verb', 'bildirmoq, ifodalamoq', 'The red line denotes the border.', 'Qizil chiziq chegarani bildiradi.'],
      ['empirical', 'adjective', 'empirik (tajribaga asoslangan)', 'There is little empirical evidence for this theory.', 'Bu nazariya uchun tajribaviy dalillar kam.'],
      ['notwithstanding', 'preposition', '...ga qaramay (rasmiy)', 'Notwithstanding the difficulties, the project succeeded.', "Qiyinchiliklarga qaramay, loyiha muvaffaqiyatli bo'ldi."],
      ['predominant', 'adjective', 'ustun, asosiy', 'Blue is the predominant colour in the painting.', "Rasmda ko'k rang ustun."],
      ['somewhat', 'adverb', 'biroz, qaysidir darajada', 'The results were somewhat surprising.', 'Natijalar biroz kutilmagan edi.'],
      ['thereby', 'adverb', 'shu bilan, shu tariqa', 'He saved money, thereby reducing his debt.', 'U pul tejadi va shu bilan qarzini kamaytirdi.'],
      ['whereby', 'adverb', "unga ko'ra, ...ki (bog'lovchi)", 'They introduced a system whereby staff can work from home.', "Ular xodimlar uydan ishlashi mumkin bo'lgan tizimni joriy qilishdi."],
      ['widespread', 'adjective', 'keng tarqalgan', 'There is widespread support for the plan.', "Reja keng qo'llab-quvvatlanmoqda."],
      ['distort', 'verb', "buzib ko'rsatmoq", 'The media distorted his words.', "OAV uning so'zlarini buzib ko'rsatdi."],
      ['comprehensive', 'adjective', 'har tomonlama', 'The book gives a comprehensive overview of the subject.', 'Kitob mavzuni har tomonlama yoritadi.'],
    ],
  },
  {
    unit: 80,
    title: 'Academic writing: text structure',
    titleUz: 'Ilmiy yozuv: matn tuzilishi',
    emoji: '🧾',
    words: [
      ['assert', 'verb', "qat'iy ta'kidlamoq", 'He asserted that he was innocent.', "U o'zini aybsiz deb qat'iy ta'kidladi."],
      ['allude to', 'phrase', '...ga ishora qilmoq', 'The author seems to allude to his childhood.', 'Muallif bolaligiga ishora qilayotganga o\'xshaydi.'],
      ['cite', 'verb', 'iqtibos keltirmoq, havola qilmoq', 'The article cites several studies.', 'Maqolada bir nechta tadqiqotlarga havola qilingan.'],
      ['comprise', 'verb', "...dan iborat bo'lmoq", 'The course comprises ten modules.', "Kurs o'nta moduldan iborat."],
      ['epitomise', 'verb', "timsoli bo'lmoq", 'She epitomises the modern businesswoman.', 'U zamonaviy ishbilarmon ayolning timsoli.'],
      ['expound', 'verb', 'batafsil bayon qilmoq', 'The professor expounded his theory.', "Professor o'z nazariyasini batafsil bayon qildi."],
      ['posit', 'verb', '(faraz) ilgari surmoq', 'The researchers posit a new explanation.', 'Tadqiqotchilar yangi izohni ilgari suradi.'],
      ['preface', 'verb', "(so'zni) ... bilan boshlamoq", 'He prefaced his speech with a joke.', 'U nutqini hazil bilan boshladi.'],
      ['reiterate', 'verb', 'qayta takrorlamoq', 'Let me reiterate the main points.', 'Asosiy fikrlarni yana bir bor takrorlay.'],
      ['summarise', 'verb', 'qisqacha bayon qilmoq', 'Summarise the article in 100 words.', "Maqolani 100 so'zda qisqacha bayon qiling."],
      ['underscore', 'verb', "alohida ta'kidlamoq", 'The results underscore the need for change.', "Natijalar o'zgarish zarurligini alohida ta'kidlaydi."],
      ['categorise', 'verb', 'tasniflamoq', 'The books are categorised by subject.', "Kitoblar mavzu bo'yicha tasniflangan."],
      ['touch on', 'phrase', "to'xtalib o'tmoq", 'The lecture will touch on climate change.', "Ma'ruzada iqlim o'zgarishiga ham to'xtalib o'tiladi."],
      ['embrace', 'verb', 'qamrab olmoq; qabul qilmoq', 'The course embraces many different topics.', "Kurs ko'plab turli mavzularni qamrab oladi."],
      ['in ascending order', 'phrase', "o'sish tartibida", 'List the numbers in ascending order.', "Sonlarni o'sish tartibida yozing."],
      ['in descending order', 'phrase', 'kamayish tartibida', 'The results are shown in descending order.', "Natijalar kamayish tartibida ko'rsatilgan."],
    ],
  },
];
