/**
 * Advanced (C1), 41–60-unit'lar. Tamoyillar — elementary.js va advanced.js
 * dagi izohlarga qarang.
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 41,
    title: 'British politics',
    titleUz: 'Siyosat va parlament',
    emoji: '🏛️',
    words: [
      ['legislation', 'noun', 'qonunchilik, qonunlar', 'The government introduced new legislation on smoking.', "Hukumat chekish bo'yicha yangi qonunlarni joriy qildi."],
      ['constitution', 'noun', 'konstitutsiya', 'The constitution protects freedom of speech.', "Konstitutsiya so'z erkinligini himoya qiladi."],
      ['lobby', 'verb', "lobbi qilmoq (ta'sir o'tkazmoq)", 'Farmers are lobbying the government for more support.', "Dehqonlar hukumatdan ko'proq yordam so'rab lobbi qilishmoqda."],
      ['petition', 'noun', 'petitsiya', 'Over 10,000 people signed the petition.', "10 mingdan ortiq kishi petitsiyaga imzo chekdi."],
      ['rally', 'noun', 'miting', 'Thousands attended the rally in the square.', 'Maydondagi mitingga minglab odamlar qatnashdi.'],
      ['committee', 'noun', "qo'mita", 'A committee will study the proposal.', "Taklifni qo'mita o'rganib chiqadi."],
      ['constituent', 'noun', 'saylovchi (okrug aholisi)', 'The MP met her constituents on Friday.', 'Deputat juma kuni saylovchilari bilan uchrashdi.'],
      ['scrutinise', 'verb', 'sinchiklab tekshirmoq', 'Journalists scrutinise every word the minister says.', "Jurnalistlar vazirning har bir so'zini sinchiklab tekshiradi."],
      ['allegation', 'noun', 'ayblov (isbotlanmagan)', 'He denied the allegations of fraud.', 'U firibgarlik ayblovlarini rad etdi.'],
      ['briefing', 'noun', 'brifing (qisqa axborot)', 'The minister gave a press briefing.', "Vazir matbuot brifingini o'tkazdi."],
      ['Speaker', 'noun', 'spiker (parlament raisi)', 'The Speaker controls debates in Parliament.', 'Spiker parlamentdagi munozaralarni boshqaradi.'],
      ['wide-ranging', 'adjective', 'keng qamrovli', 'The report makes wide-ranging recommendations.', 'Hisobot keng qamrovli tavsiyalar beradi.'],
      ['expertise', 'noun', 'mutaxassislik, bilim', 'We need someone with legal expertise.', 'Bizga huquqiy bilimga ega odam kerak.'],
      ['ultimately', 'adverb', 'oxir-oqibat', 'Ultimately, the decision is up to the voters.', "Oxir-oqibat, qaror saylovchilarga bog'liq."],
      ['substantive', 'adjective', 'jiddiy, mohiyatli', 'There were no substantive changes to the law.', "Qonunga jiddiy o'zgarishlar kiritilmadi."],
    ],
  },
  {
    unit: 42,
    title: 'International politics',
    titleUz: 'Xalqaro siyosat',
    emoji: '🌐',
    words: [
      ['solidarity', 'noun', 'birdamlik', 'Workers showed solidarity with the strikers.', "Ishchilar ish tashlaganlar bilan birdamlik ko'rsatdi."],
      ['intervention', 'noun', 'aralashuv', 'Military intervention would make things worse.', 'Harbiy aralashuv vaziyatni yomonlashtiradi.'],
      ['integration', 'noun', 'integratsiya, birlashuv', 'The EU was built on economic integration.', 'Yevropa Ittifoqi iqtisodiy integratsiyaga asoslangan.'],
      ['negotiation', 'noun', 'muzokara', 'After long negotiations, they signed a treaty.', 'Uzoq muzokaralardan keyin ular shartnoma imzolashdi.'],
      ['minority', 'noun', 'ozchilik (millat, guruh)', 'The rights of minorities must be protected.', 'Ozchiliklar huquqlari himoya qilinishi kerak.'],
      ['liberation', 'noun', "ozod bo'lish, ozodlik", 'The country celebrated its liberation from colonial rule.', "Mamlakat mustamlakachilikdan ozod bo'lganini nishonladi."],
      ['uphold', 'verb', 'himoya qilmoq, rioya qilmoq', 'The court must uphold the law.', 'Sud qonunni himoya qilishi kerak.'],
      ['pursue', 'verb', '(siyosat) olib bormoq', 'The government will pursue a policy of peace.', 'Hukumat tinchlik siyosatini olib boradi.'],
      ['undertake', 'verb', 'zimmasiga olmoq', 'The UN will undertake a peace mission.', 'BMT tinchlik missiyasini zimmasiga oladi.'],
      ['infrastructure', 'noun', 'infratuzilma', 'The country needs better roads and infrastructure.', "Mamlakatga yaxshiroq yo'llar va infratuzilma kerak."],
      ['humanity', 'noun', 'insoniyat', 'The war was a crime against humanity.', 'Urush insoniyatga qarshi jinoyat edi.'],
      ['customary', 'adjective', 'odat tusiga kirgan', 'It is customary to shake hands.', "Qo'l berib ko'rishish odat tusiga kirgan."],
      ['delegate', 'noun', 'delegat, vakil', 'Delegates from 50 countries attended the summit.', 'Sammitga 50 mamlakatdan delegatlar qatnashdi.'],
      ['unity', 'noun', 'birlik', 'The president called for national unity.', 'Prezident milliy birlikka chaqirdi.'],
      ['slogan', 'noun', 'shior', 'The protesters shouted slogans.', 'Namoyishchilar shiorlar aytib baqirishdi.'],
      ['movement', 'noun', 'harakat (ijtimoiy)', 'The civil rights movement changed America.', "Fuqarolik huquqlari harakati Amerikani o'zgartirdi."],
    ],
  },
  {
    unit: 43,
    title: 'The letter of the law',
    titleUz: 'Qonun va huquq',
    emoji: '⚖️',
    words: [
      ['amend', 'verb', "o'zgartirish kiritmoq", 'Parliament voted to amend the law.', "Parlament qonunga o'zgartirish kiritishga ovoz berdi."],
      ['amendment', 'noun', 'tuzatish (qonunga)', 'The amendment was passed by a large majority.', "Tuzatish katta ko'pchilik ovozi bilan qabul qilindi."],
      ['annul', 'verb', '(nikoh, shartnoma) bekor qilmoq', 'The court may annul the contract.', 'Sud shartnomani bekor qilishi mumkin.'],
      ['appeal', 'verb', 'apellyatsiya bermoq (shikoyat qilmoq)', 'He plans to appeal against the decision.', 'U qaror ustidan shikoyat qilmoqchi.'],
      ['custody', 'noun', 'vasiylik (bolalar)', 'The mother was given custody of the children.', 'Bolalarning vasiyligi onaga berildi.'],
      ['contravene', 'verb', '(qonunni) buzmoq', 'The company contravened safety laws.', 'Kompaniya xavfsizlik qonunlarini buzdi.'],
      ['discrimination', 'noun', 'kamsitish', 'Discrimination on the basis of age is illegal.', 'Yoshga qarab kamsitish noqonuniy.'],
      ['embezzle', 'verb', '(ishonib topshirilgan pulni) o\'zlashtirmoq', 'The accountant embezzled millions.', "Buxgalter millionlab pulni o'zlashtirdi."],
      ['harassment', 'noun', "ta'qib, bezovta qilish", 'She complained of harassment at work.', "U ishda ta'qib qilinayotganidan shikoyat qildi."],
      ['impeach', 'verb', "impichment e'lon qilmoq", 'Congress voted to impeach the president.', "Kongress prezidentga impichment e'lon qilish uchun ovoz berdi."],
      ['infringe', 'verb', '(huquqni) poymol qilmoq', 'The law infringes on our freedom.', 'Bu qonun erkinligimizni poymol qiladi.'],
      ['insider trading', 'phrase', "insayder savdosi (maxfiy ma'lumot bilan)", 'He was jailed for insider trading.', 'U insayder savdosi uchun qamaldi.'],
      ['launder', 'verb', '(pul) yuvmoq', 'The gang laundered money through a restaurant.', "To'da pulni restoran orqali yuvgan."],
      ['law-abiding', 'adjective', 'qonunga itoatkor', 'Most citizens are law-abiding.', "Ko'pchilik fuqarolar qonunga itoatkor."],
      ['perjury', 'noun', "yolg'on guvohlik", 'The witness was charged with perjury.', "Guvohga yolg'on guvohlik bergani uchun ayblov qo'yildi."],
      ['precedent', 'noun', 'pretsedent (namuna qaror)', 'This case could set a precedent.', 'Bu ish pretsedent yaratishi mumkin.'],
      ['overturn', 'verb', '(hukmni) bekor qilmoq', 'The higher court overturned the decision.', 'Yuqori sud qarorni bekor qildi.'],
      ['sue', 'verb', 'sudga bermoq', 'She is suing the company for damages.', 'U kompaniyani zararni qoplash uchun sudga bermoqda.'],
      ['take the law into your own hands', 'phrase', "o'zboshimchalik bilan jazolamoq", "You shouldn't take the law into your own hands.", "O'zboshimchalik bilan jazolashga haqqing yo'q."],
    ],
  },
  {
    unit: 44,
    title: 'War and peace',
    titleUz: 'Urush va tinchlik',
    emoji: '🕊️',
    words: [
      ['ceasefire', 'noun', "o't ochishni to'xtatish", 'Both sides agreed to a ceasefire.', "Ikki tomon o't ochishni to'xtatishga kelishdi."],
      ['truce', 'noun', 'sulh', 'The truce lasted only three days.', 'Sulh atigi uch kun davom etdi.'],
      ['siege', 'noun', 'qamal', 'The city was under siege for months.', 'Shahar oylab qamalda qoldi.'],
      ['ambush', 'noun', 'pistirma', 'Soldiers were killed in an ambush.', "Askarlar pistirmada halok bo'ldi."],
      ['massacre', 'noun', "qirg'in", 'The massacre shocked the world.', "Qirg'in dunyoni larzaga soldi."],
      ['regime', 'noun', 'rejim (hukumat)', 'The regime controlled the press.', 'Rejim matbuotni nazorat qilardi.'],
      ['overthrow', 'verb', "(hokimiyatni) ag'darmoq", 'The army tried to overthrow the government.', "Armiya hukumatni ag'darishga urindi."],
      ['rebellion', 'noun', "qo'zg'olon", 'The rebellion was quickly crushed.', "Qo'zg'olon tezda bostirildi."],
      ['unrest', 'noun', 'notinchlik', 'There is growing unrest in the capital.', 'Poytaxtda notinchlik kuchaymoqda.'],
      ['escalate', 'verb', 'keskinlashmoq', 'The conflict could escalate into war.', 'Nizo urushga aylanib ketishi mumkin.'],
      ['peacekeeping', 'adjective', 'tinchlikparvar', 'UN peacekeeping forces arrived in the region.', 'BMT tinchlikparvar kuchlari hududga yetib keldi.'],
      ['sanction', 'noun', 'sanksiya', 'The UN imposed sanctions on the country.', 'BMT mamlakatga sanksiyalar joriy qildi.'],
      ['wage war', 'phrase', 'urush olib bormoq', 'No country should wage war against its neighbours.', "Hech bir davlat qo'shnilariga qarshi urush olib bormasligi kerak."],
      ['civilian', 'noun', 'tinch aholi vakili', 'Many civilians were killed in the bombing.', "Bombardimonda ko'plab tinch aholi halok bo'ldi."],
      ['hostilities', 'noun', 'harbiy harakatlar', 'Hostilities ended in 1945.', 'Harbiy harakatlar 1945-yilda tugadi.'],
      ['diplomacy', 'noun', 'diplomatiya', 'The crisis was solved through diplomacy.', "Inqiroz diplomatiya yo'li bilan hal qilindi."],
      ['weaponry', 'noun', "qurol-yarog'", 'The army has modern weaponry.', "Armiyada zamonaviy qurol-yarog' bor."],
    ],
  },
  {
    unit: 45,
    title: 'Economy and finance',
    titleUz: 'Iqtisodiyot va moliya',
    emoji: '📊',
    words: [
      ['alleviate', 'verb', 'yengillashtirmoq', 'The aid helped to alleviate poverty.', 'Yordam qashshoqlikni yengillashtirdi.'],
      ['embargo', 'noun', 'savdo taqiqi (embargo)', 'There is a trade embargo on the country.', 'Mamlakatga nisbatan savdo taqiqi bor.'],
      ['devaluation', 'noun', 'qadrsizlanish', 'The devaluation of the currency made imports more expensive.', 'Valyutaning qadrsizlanishi importni qimmatlashtirdi.'],
      ['free trade', 'phrase', 'erkin savdo', 'The two countries signed a free trade agreement.', 'Ikki mamlakat erkin savdo shartnomasini imzoladi.'],
      ['slump', 'noun', 'keskin pasayish', 'There was a slump in sales last year.', "O'tgan yili savdo keskin pasaydi."],
      ['recover', 'verb', 'tiklanmoq', 'The economy is starting to recover.', 'Iqtisodiyot tiklana boshladi.'],
      ['ailing', 'adjective', 'zaiflashgan (iqtisod, kompaniya)', 'The government is trying to help the ailing economy.', 'Hukumat zaiflashgan iqtisodiyotga yordam berishga harakat qilmoqda.'],
      ['incur', 'verb', '(xarajat, zarar)ga duch kelmoq', 'Late payment may incur a fee.', "Kech to'lov qo'shimcha haqqa sabab bo'lishi mumkin."],
      ['monetary', 'adjective', 'pul-kredit (siyosati)', 'The central bank controls monetary policy.', 'Markaziy bank pul-kredit siyosatini boshqaradi.'],
      ['restrictive', 'adjective', 'cheklovchi', 'The trade laws are too restrictive.', 'Savdo qonunlari haddan tashqari cheklovchi.'],
      ['war-torn', 'adjective', 'urushdan vayron bo\'lgan', 'Aid is being sent to the war-torn country.', "Urushdan vayron bo'lgan mamlakatga yordam yuborilmoqda."],
      ['abject poverty', 'phrase', "o'ta qashshoqlik", 'Millions still live in abject poverty.', "Millionlab odamlar hali ham o'ta qashshoqlikda yashaydi."],
      ['double-dip recession', 'phrase', 'takroriy tanazzul', 'Economists fear a double-dip recession.', "Iqtisodchilar takroriy tanazzuldan qo'rqishadi."],
      ['emerge from', 'phrase', '(inqirozdan) chiqmoq', 'It will take years to emerge from the crisis.', 'Inqirozdan chiqish uchun yillar kerak bo\'ladi.'],
      ['lift sanctions', 'phrase', 'sanksiyalarni bekor qilmoq', 'The UN agreed to lift sanctions.', 'BMT sanksiyalarni bekor qilishga kelishdi.'],
      ['economic growth', 'phrase', "iqtisodiy o'sish", 'Economic growth slowed last year.', "O'tgan yili iqtisodiy o'sish sekinlashdi."],
    ],
  },
  {
    unit: 46,
    title: 'Personal finance: making ends meet',
    titleUz: 'Shaxsiy moliya',
    emoji: '💳',
    words: [
      ['broke', 'adjective', "cho'ntagi quruq (so'zlashuv)", "I can't come out tonight; I'm broke.", "Bugun chiqa olmayman, cho'ntagim quruq."],
      ['skint', 'adjective', "pulsiz (so'zlashuv, Britaniya)", "I'm skint until payday.", 'Maosh kunigacha pulsizman.'],
      ['strapped for cash', 'phrase', 'pulga qiynalgan', 'Students are often strapped for cash.', "Talabalar ko'pincha pulga qiynaladi."],
      ['lump sum', 'phrase', "bir yo'la to'lanadigan summa", 'She received a lump sum when she retired.', "U nafaqaga chiqqanda bir yo'la katta summa oldi."],
      ['golden handshake', 'phrase', 'katta ishdan ketish kompensatsiyasi', 'The director left with a golden handshake.', 'Direktor katta kompensatsiya bilan ketdi.'],
      ['withdraw', 'verb', '(pul) yechib olmoq', 'I need to withdraw some cash.', 'Biroz naqd pul yechib olishim kerak.'],
      ['contactless', 'adjective', "kontaktsiz (to'lov)", 'You can pay by contactless card.', "Kontaktsiz karta bilan to'lashingiz mumkin."],
      ['debit card', 'phrase', 'debet karta', 'Can I pay by debit card?', "Debet karta bilan to'lasam bo'ladimi?"],
      ['bounce', 'verb', '(chek) qaytib kelmoq', 'His cheque bounced.', 'Uning cheki qaytib keldi.'],
      ['expiry date', 'phrase', 'amal qilish muddati', 'Check the expiry date on your card.', 'Kartangizning amal qilish muddatini tekshiring.'],
      ['roll in', 'phrase', '(pul) oqib kelmoq', 'Once the business grows, the money will roll in.', "Biznes o'sgach, pul oqib kela boshlaydi."],
      ['stock market', 'phrase', 'fond birjasi', 'He lost a lot of money on the stock market.', "U fond birjasida ko'p pul yo'qotdi."],
      ['APR', 'noun', 'yillik foiz stavkasi', 'The loan has an APR of 20%.', 'Kreditning yillik foiz stavkasi 20%.'],
      ['life savings', 'phrase', "butun umrlik jamg'arma", 'She spent her life savings on the house.', "U butun umrlik jamg'armasini uyga sarfladi."],
      ['store card', 'phrase', "do'kon kartasi", 'Store cards often have high interest rates.', "Do'kon kartalarida ko'pincha foiz yuqori bo'ladi."],
      ['cover', 'verb', '(xarajatni) qoplamoq', 'My salary barely covers the rent.', "Maoshim ijara haqini zo'rg'a qoplaydi."],
    ],
  },
  {
    unit: 47,
    title: 'The media: in print',
    titleUz: 'Bosma OAV',
    emoji: '📰',
    words: [
      ['circulation', 'noun', 'tiraj', 'The newspaper has a circulation of 100,000.', 'Gazetaning tiraji 100 ming nusxa.'],
      ['coverage', 'noun', 'yoritilish (OAVda)', 'The election got a lot of media coverage.', 'Saylov OAVda keng yoritildi.'],
      ['editorial', 'noun', 'tahririyat maqolasi', 'The editorial criticised the government.', 'Tahririyat maqolasi hukumatni tanqid qildi.'],
      ['obituary', 'noun', 'nekrolog', 'His obituary appeared in all the papers.', 'Uning nekrologi barcha gazetalarda chiqdi.'],
      ['supplement', 'noun', 'ilova (gazetaga)', 'The Sunday paper comes with a colour supplement.', 'Yakshanbalik gazeta rangli ilova bilan chiqadi.'],
      ['classified ad', 'phrase', "kichik e'lon", 'I sold my bike through a classified ad.', "Velosipedimni kichik e'lon orqali sotdim."],
      ['agony aunt', 'phrase', 'maslahat ruknining muallifi', 'She wrote to an agony aunt about her problem.', 'U muammosi haqida maslahat rukni muallifiga xat yozdi.'],
      ['leaflet', 'noun', 'varaqa', 'They handed out leaflets in the street.', "Ular ko'chada varaqalar tarqatishdi."],
      ['brochure', 'noun', 'buklet', 'Pick up a free travel brochure.', 'Bepul sayohat bukletini oling.'],
      ['pamphlet', 'noun', 'risola', 'The pamphlet explains your rights.', 'Risola huquqlaringizni tushuntiradi.'],
      ['newsletter', 'noun', 'axborot byulleteni', 'The school sends a monthly newsletter to parents.', 'Maktab ota-onalarga oylik axborot byulleteni yuboradi.'],
      ['prospectus', 'noun', "prospekt (o'quv muassasasi haqida)", 'Read the university prospectus carefully.', "Universitet prospektini diqqat bilan o'qing."],
      ['press release', 'phrase', 'press-reliz', 'The company issued a press release.', "Kompaniya press-reliz e'lon qildi."],
      ['feature', 'noun', 'maxsus maqola', "There's a feature about Khiva in today's paper.", 'Bugungi gazetada Xiva haqida maxsus maqola bor.'],
      ['journal', 'noun', 'ilmiy jurnal', 'She published her research in a medical journal.', 'U tadqiqotini tibbiy jurnalda chop etdi.'],
    ],
  },
  {
    unit: 48,
    title: 'The media: internet and email',
    titleUz: 'Internet va elektron pochta',
    emoji: '💻',
    words: [
      ['spam', 'noun', 'keraksiz reklama xatlari (spam)', 'My inbox is full of spam.', "Pochtam keraksiz reklama xatlariga to'la."],
      ['hack', 'verb', 'buzib kirmoq (kompyuter)', 'Someone hacked into my email account.', 'Kimdir elektron pochtamni buzib kirdi.'],
      ['e-commerce', 'noun', 'elektron tijorat', 'E-commerce is growing fast in Uzbekistan.', "O'zbekistonda elektron tijorat tez o'smoqda."],
      ['e-learning', 'noun', "elektron ta'lim", 'The university offers e-learning courses.', "Universitet elektron ta'lim kurslarini taklif qiladi."],
      ['e-book', 'noun', 'elektron kitob', 'I read e-books on my tablet.', "Elektron kitoblarni planshetimda o'qiyman."],
      ['file-sharing', 'noun', 'fayl almashish', 'Illegal file-sharing is a problem for musicians.', 'Noqonuniy fayl almashish musiqachilar uchun muammo.'],
      ['chat room', 'phrase', 'chat xonasi', 'Be careful who you talk to in chat rooms.', "Chat xonalarida kim bilan gaplashayotganingizga ehtiyot bo'ling."],
      ['filter', 'noun', 'filtr', 'The email filter blocks most spam.', "Pochta filtri keraksiz xatlarning ko'pini to'sadi."],
      ['instant messaging', 'phrase', 'tezkor xabar almashish', 'Young people prefer instant messaging to email.', "Yoshlar elektron xatdan ko'ra tezkor xabar almashishni afzal ko'radi."],
      ['webinar', 'noun', 'vebinar (onlayn seminar)', 'I attended a webinar on marketing.', "Marketing bo'yicha vebinarda qatnashdim."],
      ['parental controls', 'phrase', 'ota-ona nazorati', 'Use parental controls to protect your children online.', 'Farzandlaringizni internetda himoya qilish uchun ota-ona nazoratidan foydalaning.'],
      ['addictive', 'adjective', 'qaramlik keltiruvchi', 'Some games are very addictive.', "Ba'zi o'yinlar juda qaramlik keltiradi."],
      ['offensive', 'adjective', 'haqoratli', 'The website contains offensive material.', 'Saytda haqoratli materiallar bor.'],
      ['gaming', 'noun', "kompyuter o'yinlari", 'Online gaming is popular among teenagers.', "Onlayn o'yinlar o'smirlar orasida mashhur."],
      ['anti-virus', 'adjective', 'antivirus (dasturi)', 'Install anti-virus software on your computer.', "Kompyuteringizga antivirus dasturini o'rnating."],
      ['social networking', 'phrase', 'ijtimoiy tarmoqlar orqali muloqot', 'Social networking has changed how we communicate.', "Ijtimoiy tarmoqlar muloqot usulimizni o'zgartirdi."],
    ],
  },
  {
    unit: 49,
    title: 'Advertising',
    titleUz: 'Reklama',
    emoji: '📣',
    words: [
      ['billboard', 'noun', 'reklama shiti', "There's a huge billboard next to the motorway.", 'Avtomagistral yonida ulkan reklama shiti bor.'],
      ['logo', 'noun', 'logotip', "Everyone knows the company's logo.", 'Kompaniyaning logotipini hamma biladi.'],
      ['pop-up', 'adjective', 'qalqib chiquvchi (oyna)', 'Pop-up adverts are very annoying.', 'Qalqib chiquvchi reklamalar juda asabga tegadi.'],
      ['trailer', 'noun', '(film) anonsi', 'Have you seen the trailer for the new film?', "Yangi filmning anonsini ko'rdingmi?"],
      ['plug', 'verb', "reklama qilmoq (so'zlashuv)", 'The actor was on TV to plug his new film.', 'Aktyor yangi filmini reklama qilish uchun televizorga chiqdi.'],
      ['glossy', 'adjective', 'yaltiroq (qimmat jurnal)', 'She reads glossy fashion magazines.', "U yaltiroq moda jurnallarini o'qiydi."],
      ['state-of-the-art', 'adjective', 'eng zamonaviy', 'The hospital has state-of-the-art equipment.', 'Kasalxonada eng zamonaviy uskunalar bor.'],
      ['innovative', 'adjective', 'innovatsion, yangicha', "It's an innovative design.", 'Bu innovatsion dizayn.'],
      ['unsurpassed', 'adjective', 'qiyos qilib bo\'lmas', 'The quality is unsurpassed.', "Sifati qiyos qilib bo'lmas darajada."],
      ['rock-bottom', 'adjective', 'eng past (narx)', 'Everything is at rock-bottom prices this week.', 'Bu hafta hamma narsa eng past narxlarda.'],
      ['slash', 'verb', 'keskin tushirmoq (narx)', 'The shop has slashed its prices.', "Do'kon narxlarni keskin tushirdi."],
      ['sumptuous', 'adjective', "to'kin-sochin, dabdabali", 'We had a sumptuous meal at the hotel.', "Mehmonxonada to'kin-sochin ovqatlandik."],
      ['opulent', 'adjective', 'boy-badavlat bezatilgan', 'The palace has opulent rooms.', 'Saroyning xonalari boy-badavlat bezatilgan.'],
      ['pamper', 'verb', 'erkalatmoq, siylamoq', 'Pamper yourself with a day at the spa.', "O'zingizni spada bir kun erkalating."],
      ['indulge', 'verb', "o'zini siylamoq", 'Go on, indulge yourself and have a piece of cake!', "Qani, o'zingni siyla — bir bo'lak tort ye!"],
      ['radiant', 'adjective', 'nurli, porloq', 'This cream will make your skin radiant.', 'Bu krem teringizni nurli qiladi.'],
      ['flyer', 'noun', 'reklama varaqasi', "They put flyers under every door.", "Ular har bir eshik ostiga reklama varaqalarini qo'yishdi."],
      ['discount', 'noun', 'chegirma', 'Students get a 10% discount.', 'Talabalarga 10% chegirma beriladi.'],
      ['stand out from the crowd', 'phrase', 'boshqalardan ajralib turmoq', 'A good logo helps a company stand out from the crowd.', 'Yaxshi logotip kompaniyaga boshqalardan ajralib turishga yordam beradi.'],
    ],
  },
  {
    unit: 50,
    title: 'The news: gathering and delivering',
    titleUz: "Yangiliklar: to'plash va yetkazish",
    emoji: '🗞️',
    words: [
      ['scoop', 'noun', 'sensatsion yangilik (birinchi bo\'lib)', 'The newspaper got a scoop on the scandal.', 'Gazeta janjal haqidagi sensatsion yangilikni birinchi berdi.'],
      ['exclusive', 'adjective', 'eksklyuziv (faqat bitta nashrda)', 'The magazine has an exclusive interview with the star.', 'Jurnalda yulduz bilan eksklyuziv suhbat bor.'],
      ['paparazzi', 'noun', 'paparatsilar', 'The paparazzi followed her everywhere.', "Paparatsilar uni hamma joyda ta'qib qilishdi."],
      ['gutter press', 'phrase', 'sariq matbuot', 'The gutter press printed lies about him.', "Sariq matbuot u haqida yolg'onlar bosdi."],
      ['libel', 'noun', 'tuhmat (yozma)', 'He sued the newspaper for libel.', 'U gazetani tuhmat uchun sudga berdi.'],
      ['defamation', 'noun', "obro'sizlantirish", 'She won a defamation case against the magazine.', "U jurnalga qarshi obro'sizlantirish ishini yutdi."],
      ['soundbite', 'noun', 'qisqa, esda qoladigan ibora', 'Politicians love short soundbites.', "Siyosatchilar qisqa, esda qoladigan iboralarni yaxshi ko'radi."],
      ['press conference', 'phrase', 'matbuot anjumani', 'The minister held a press conference.', "Vazir matbuot anjumani o'tkazdi."],
      ['pressure group', 'phrase', 'bosim guruhi (lobbi tashkilot)', 'Environmental pressure groups want to stop the new airport.', "Ekologik bosim guruhlari yangi aeroport qurilishini to'xtatmoqchi."],
      ['citizen journalism', 'phrase', 'fuqarolik jurnalistikasi', 'Citizen journalism has grown with smartphones.', "Fuqarolik jurnalistikasi smartfonlar bilan o'sdi."],
      ['muck-raking', 'noun', 'iflos ishlarni kovlash', 'The journalist is known for muck-raking.', 'Jurnalist iflos ishlarni kovlashi bilan tanilgan.'],
      ['archive', 'noun', 'arxiv', "The newspaper's archive goes back 100 years.", 'Gazeta arxivi 100 yil oldingi sonlardan boshlanadi.'],
      ['airtime', 'noun', 'efir vaqti', 'The story got a lot of airtime.', "Bu voqeaga ko'p efir vaqti ajratildi."],
      ['column', 'noun', 'rukn (muntazam maqola)', 'She writes a weekly column for the newspaper.', 'U gazetaga haftalik rukn yozadi.'],
      ['hit the headlines', 'phrase', 'sarlavhalarga chiqmoq', 'The scandal hit the headlines last week.', "Janjal o'tgan hafta sarlavhalarga chiqdi."],
      ['run a story', 'phrase', 'material chiqarmoq', 'The paper will run a story about the fraud tomorrow.', 'Gazeta ertaga firibgarlik haqida material chiqaradi.'],
    ],
  },
  {
    unit: 51,
    title: 'Healthcare',
    titleUz: "Sog'liqni saqlash",
    emoji: '🏥',
    words: [
      ['GP', 'noun', 'oilaviy shifokor', 'See your GP if the pain continues.', "Og'riq davom etsa, oilaviy shifokoringizga boring."],
      ['prescription', 'noun', 'retsept', 'You need a prescription for these tablets.', 'Bu tabletkalar uchun retsept kerak.'],
      ['cardiologist', 'noun', 'kardiolog', 'A cardiologist checked his heart.', 'Kardiolog uning yuragini tekshirdi.'],
      ['dermatologist', 'noun', 'dermatolog (teri shifokori)', 'I went to a dermatologist about my skin rash.', 'Teri toshmasi sabab dermatologga bordim.'],
      ['paediatrician', 'noun', 'pediatr (bolalar shifokori)', 'The paediatrician examined the baby.', "Pediatr chaqaloqni ko'rikdan o'tkazdi."],
      ['psychiatrist', 'noun', 'psixiatr', 'He is being treated by a psychiatrist.', 'U psixiatrda davolanmoqda.'],
      ['surgery', 'noun', 'shifokor qabulxonasi; jarrohlik', "The doctor's surgery opens at eight.", 'Shifokor qabulxonasi soat sakkizda ochiladi.'],
      ['acute', 'adjective', "o'tkir", 'She was taken to hospital with acute pain.', "U o'tkir og'riq bilan kasalxonaga olib borildi."],
      ['chronic', 'adjective', 'surunkali', 'He suffers from chronic back pain.', "U surunkali bel og'rig'idan aziyat chekadi."],
      ['alternative medicine', 'phrase', 'muqobil tibbiyot', 'Many people try alternative medicine.', "Ko'p odamlar muqobil tibbiyotni sinab ko'radi."],
      ['acupuncturist', 'noun', 'akupunktura mutaxassisi', 'The acupuncturist used tiny needles.', 'Akupunktura mutaxassisi mayda ignalardan foydalandi.'],
      ['primary care', 'phrase', 'birlamchi tibbiy yordam', 'Primary care is provided by local doctors.', "Birlamchi tibbiy yordamni mahalliy shifokorlar ko'rsatadi."],
      ['refer', 'verb', "(mutaxassisga) yo'llamoq", 'Your GP can refer you to a specialist.', "Oilaviy shifokoringiz sizni mutaxassisga yo'llashi mumkin."],
      ['clinic', 'noun', 'klinika', 'She works at a private clinic.', 'U xususiy klinikada ishlaydi.'],
      ['locum', 'noun', 'vaqtinchalik o\'rinbosar shifokor', 'A locum is covering while the doctor is on holiday.', "Shifokor ta'tildaligida o'rinbosar shifokor ishlayapti."],
      ['health insurance', 'phrase', "tibbiy sug'urta", 'Do you have health insurance?', "Tibbiy sug'urtangiz bormi?"],
    ],
  },
  {
    unit: 52,
    title: 'Illness: feeling under the weather',
    titleUz: 'Betoblik',
    emoji: '🤧',
    words: [
      ['off-colour', 'adjective', 'biroz betob', "I'm feeling a bit off-colour today.", "Bugun o'zimni biroz betob his qilyapman."],
      ['poorly', 'adjective', "betob (so'zlashuv)", 'The baby is poorly with a cold.', 'Chaqaloq shamollab, betob.'],
      ['feverish', 'adjective', 'isitmasi bor', 'I feel feverish and tired.', 'Isitmam bor va charchaganman.'],
      ['shivery', 'adjective', 'titroq bosgan', "I feel shivery; I think I'm getting flu.", 'Titroq bosyapti, menimcha, grippga chalinyapman.'],
      ['nauseous', 'adjective', "ko'ngli aynigan", 'The smell made me feel nauseous.', "Hid ko'nglimni aynitdi."],
      ['throbbing', 'adjective', "zirqirab og'riydigan", 'I have a throbbing headache.', "Boshim zirqirab og'riyapti."],
      ['nagging', 'adjective', 'tinmay bezovta qiluvchi', 'I have a nagging pain in my shoulder.', "Yelkamda tinmay bezovta qiladigan og'riq bor."],
      ['stiff', 'adjective', 'qotib qolgan (muskul)', 'My neck is stiff after sleeping badly.', "Yomon uxlaganimdan keyin bo'ynim qotib qoldi."],
      ['sting', 'verb', 'achishmoq', 'The cut on my finger really stings.', "Barmog'imdagi kesik juda achishyapti."],
      ['bunged up', 'phrase', '(burni) bitgan', 'My nose is all bunged up.', 'Burnim butunlay bitib qolgan.'],
      ['come down with', 'phrase', '(kasallikka) chalinmoq', "Be careful or you'll come down with a cold.", "Ehtiyot bo'l, bo'lmasa shamollab qolasan."],
      ['fight off', 'phrase', '(kasallikni) yengmoq', 'Vitamin C helps you fight off infections.', 'C vitamini infeksiyalarni yengishga yordam beradi.'],
      ['sleepless', 'adjective', 'uyqusiz', 'I had a sleepless night.', "Uyqusiz tun o'tkazdim."],
      ['aches and pains', 'phrase', "og'riq-sirqiroqlar", 'At my age, you get a few aches and pains.', "Mening yoshimda biroz og'riq-sirqiroqlar bo'ladi."],
      ['twist your ankle', 'phrase', "to'pig'ini burab olmoq", 'Be careful not to twist your ankle on the stairs.', "Zinada to'pig'ingni burab olma."],
      ['back on your feet', 'phrase', '(kasallikdan) oyoqqa turmoq', "You'll be back on your feet in a few days.", 'Bir necha kunda oyoqqa turib ketasan.'],
    ],
  },
  {
    unit: 53,
    title: 'Medical language',
    titleUz: 'Tibbiy til',
    emoji: '🩺',
    words: [
      ['symptom', 'noun', 'alomat', 'What are the symptoms of flu?', 'Grippning alomatlari qanday?'],
      ['prognosis', 'noun', 'prognoz (kasallik oqibati)', 'The doctor said the prognosis was good.', "Shifokor kasallik oqibati yaxshi bo'lishini aytdi."],
      ['side effect', 'phrase', "nojo'ya ta'sir", 'This medicine has few side effects.', "Bu dorining nojo'ya ta'sirlari kam."],
      ['adverse', 'adjective', 'salbiy, noxush', 'Some patients had an adverse reaction to the drug.', "Ba'zi bemorlarda doriga salbiy reaksiya bo'ldi."],
      ['disorder', 'noun', 'buzilish (kasallik)', 'She suffers from a sleep disorder.', 'U uyqu buzilishidan aziyat chekadi.'],
      ['infect', 'verb', 'zararlamoq, yuqtirmoq', 'The virus can infect the lungs.', "Virus o'pkani zararlashi mumkin."],
      ['nausea', 'noun', "ko'ngil aynishi", 'Nausea is a common side effect.', "Ko'ngil aynishi — keng tarqalgan nojo'ya ta'sir."],
      ['vomiting', 'noun', 'qayt qilish', 'Symptoms include fever and vomiting.', 'Alomatlarga isitma va qayt qilish kiradi.'],
      ['pulse', 'noun', 'puls, yurak urishi', 'The nurse took my pulse.', "Hamshira pulsimni o'lchadi."],
      ['scar', 'noun', 'chandiq', 'He has a scar on his forehead.', 'Uning peshonasida chandiq bor.'],
      ['asthma', 'noun', 'astma', 'My son has asthma.', "O'g'limda astma bor."],
      ['fever', 'noun', 'isitma (yuqori)', 'The child has a high fever.', 'Bolaning isitmasi baland.'],
      ['duration', 'noun', 'davomiylik', 'Take the tablets for the duration of the treatment.', 'Tabletkalarni davolanish davomida iching.'],
      ['gastrointestinal', 'adjective', 'oshqozon-ichak(ka oid)', 'He has gastrointestinal problems.', 'Uning oshqozon-ichak muammolari bor.'],
      ['disorientation', 'noun', "mo'ljalni yo'qotish", 'The drug can cause disorientation.', "Dori mo'ljalni yo'qotishga sabab bo'lishi mumkin."],
      ['low-dose', 'adjective', 'kam dozali', 'The doctor prescribed a low-dose aspirin.', 'Shifokor kam dozali aspirin buyurdi.'],
      ['allergic', 'adjective', 'allergik', "I'm allergic to cats.", 'Menda mushukka allergiya bor.'],
    ],
  },
  {
    unit: 54,
    title: 'Diet, sport and fitness',
    titleUz: 'Parhez, sport va salomatlik',
    emoji: '🏃',
    words: [
      ['metabolism', 'noun', 'modda almashinuvi', 'Exercise speeds up your metabolism.', 'Jismoniy mashq modda almashinuvini tezlashtiradi.'],
      ['diabetes', 'noun', 'qandli diabet', 'Too much sugar can lead to diabetes.', "Ko'p shakar qandli diabetga olib kelishi mumkin."],
      ['glucose', 'noun', 'glyukoza', 'Glucose gives the body energy.', 'Glyukoza tanaga energiya beradi.'],
      ['insulin', 'noun', 'insulin (gormon)', 'Diabetics need insulin injections.', 'Diabetiklarga insulin ukollari kerak.'],
      ['fibre', 'noun', 'kletchatka (tola)', 'Whole grains are rich in fibre.', "To'liq donlar kletchatkaga boy."],
      ['cardiovascular', 'adjective', 'yurak-qon tomir(ga oid)', 'Running is good for your cardiovascular health.', 'Yugurish yurak-qon tomir salomatligi uchun foydali.'],
      ['BMI', 'noun', 'TMI (tana massasi indeksi)', 'A BMI over 30 means obesity.', '30 dan yuqori TMI semizlikni bildiradi.'],
      ['brisk', 'adjective', "tez, g'ayratli (yurish)", 'A brisk walk every day keeps you healthy.', "Har kuni tez yurish sog'lom saqlaydi."],
      ['nutritious', 'adjective', "to'yimli", 'Lentils are cheap and nutritious.', "Yasmiq arzon va to'yimli."],
      ['porridge', 'noun', "bo'tqa", 'I have porridge for breakfast.', "Nonushtaga bo'tqa yeyman."],
      ['lentil', 'noun', 'yasmiq', 'Lentil soup is popular in the Middle East.', "Yasmiq sho'rva Yaqin Sharqda mashhur."],
      ['clog', 'verb', "tiqib qo'ymoq", 'Fatty food can clog your arteries.', "Yog'li ovqat qon tomirlarni tiqib qo'yishi mumkin."],
      ['sporty', 'adjective', 'sportga moyil', 'My sister is very sporty.', 'Singlim sportni juda yaxshi ko\'radi.'],
      ['level playing field', 'phrase', 'teng sharoit', 'Rules should create a level playing field for all companies.', 'Qoidalar barcha kompaniyalar uchun teng sharoit yaratishi kerak.'],
      ['move the goalposts', 'phrase', "qoidalarni o'zgartirmoq (yarim yo'lda)", 'The boss keeps trying to move the goalposts.', "Boshliq doim qoidalarni o'zgartirishga urinadi."],
      ['neck and neck', 'phrase', 'teng (bellashuvda)', 'The two candidates are neck and neck.', 'Ikki nomzod teng borishmoqda.'],
      ['score an own goal', 'phrase', "o'ziga zarar qilmoq", 'The minister will score an own goal if he says that.', "Vazir buni aytsa, o'ziga zarar qiladi."],
    ],
  },
  {
    unit: 55,
    title: 'Industries: from manufacturing to service',
    titleUz: 'Sanoat va xizmatlar',
    emoji: '🏭',
    words: [
      ['heavy industry', 'phrase', "og'ir sanoat", 'Heavy industry declined in the 1980s.', "Og'ir sanoat 1980-yillarda tanazzulga uchradi."],
      ['light industry', 'phrase', 'yengil sanoat', 'Light industry produces consumer goods.', "Yengil sanoat iste'mol mollarini ishlab chiqaradi."],
      ['service industry', 'phrase', "xizmat ko'rsatish sohasi", 'Tourism is a service industry.', "Turizm — xizmat ko'rsatish sohasi."],
      ['privatisation', 'noun', 'xususiylashtirish', 'The privatisation of the railways was controversial.', "Temir yo'llarni xususiylashtirish munozarali bo'ldi."],
      ['nationalisation', 'noun', 'milliylashtirish', 'The government announced the nationalisation of the banks.', "Hukumat banklarni milliylashtirishni e'lon qildi."],
      ['subsidy', 'noun', 'subsidiya (davlat yordami)', 'Farmers receive a government subsidy.', 'Dehqonlar davlat subsidiyasini oladi.'],
      ['sweatshop', 'noun', "og'ir sharoitli, kam haqli sex", 'Many cheap clothes are made in sweatshops.', "Ko'p arzon kiyimlar og'ir sharoitli sexlarda tikiladi."],
      ['piecework', 'noun', 'ishbay ish', 'They are paid for piecework.', "Ularga ishbay haq to'lanadi."],
      ['trade union', 'phrase', 'kasaba uyushmasi', 'The trade union is negotiating higher pay.', "Kasaba uyushmasi yuqoriroq maosh bo'yicha muzokara olib bormoqda."],
      ['relocate', 'verb', "(boshqa joyga) ko'chirmoq", 'The company plans to relocate its factory to Asia.', "Kompaniya zavodini Osiyoga ko'chirmoqchi."],
      ['retrain', 'verb', "qayta o'qimoq (yangi kasbga)", 'Older workers may need to retrain.', "Keksa ishchilar qayta o'qishlari kerak bo'lishi mumkin."],
      ['assemble', 'verb', "(qismlardan) yig'moq", 'The cars are assembled in Asaka.', "Mashinalar Asakada yig'iladi."],
      ['component', 'noun', 'ehtiyot qism, butlovchi', 'The factory makes components for phones.', 'Zavod telefonlar uchun butlovchi qismlar ishlab chiqaradi.'],
      ['cutting-edge', 'adjective', "eng ilg'or", 'The company uses cutting-edge technology.', "Kompaniya eng ilg'or texnologiyalardan foydalanadi."],
      ['cost-cutting', 'noun', 'xarajatlarni qisqartirish', 'Cost-cutting led to 200 job losses.', "Xarajatlarni qisqartirish 200 ish o'rnining yo'qolishiga olib keldi."],
      ['zero-hours contract', 'phrase', 'ish soati kafolatlanmagan shartnoma', 'Many young people work on zero-hours contracts.', "Ko'p yoshlar ish soati kafolatlanmagan shartnoma asosida ishlaydi."],
    ],
  },
  {
    unit: 56,
    title: 'Technology and its impact',
    titleUz: "Texnologiya va uning ta'siri",
    emoji: '📡',
    words: [
      ['artificial intelligence', 'phrase', "sun'iy intellekt", 'Artificial intelligence is changing many jobs.', "Sun'iy intellekt ko'p kasblarni o'zgartirmoqda."],
      ['biotechnology', 'noun', 'biotexnologiya', 'Biotechnology is used to develop new medicines.', "Biotexnologiya yangi dorilar yaratishda qo'llaniladi."],
      ['touchscreen', 'noun', 'sensorli ekran', 'Most phones now have a touchscreen.', "Hozir ko'p telefonlarda sensorli ekran bor."],
      ['hands-free', 'adjective', "qo'l tegmasdan ishlaydigan", 'Use a hands-free device while driving.', "Haydash paytida qo'l tegmasdan ishlaydigan qurilmadan foydalaning."],
      ['router', 'noun', 'router (internet qurilmasi)', 'Restart the router if the internet is slow.', 'Internet sekin bo\'lsa, routerni qayta yoqing.'],
      ['techie', 'noun', "texnika mutaxassisi (so'zlashuv)", "Ask my brother; he's a real techie.", "Akamdan so'ra, u haqiqiy texnika mutaxassisi."],
      ['analogue', 'adjective', 'analog (raqamli emas)', 'My grandfather still has an analogue watch.', 'Bobomda hali ham analog soat bor.'],
      ['e-reader', 'noun', 'elektron kitob qurilmasi', 'I take my e-reader on holiday.', "Ta'tilga elektron kitob qurilmamni olib boraman."],
      ['flat-screen', 'adjective', 'yassi ekranli', 'They bought a flat-screen TV.', 'Ular yassi ekranli televizor sotib olishdi.'],
      ['smartphone', 'noun', 'smartfon', 'Almost everyone has a smartphone now.', 'Hozir deyarli hammada smartfon bor.'],
      ['tablet', 'noun', 'planshet', 'My daughter does her homework on a tablet.', 'Qizim uy vazifasini planshetda bajaradi.'],
      ['interactive', 'adjective', 'interaktiv', 'The museum has interactive exhibits.', 'Muzeyda interaktiv eksponatlar bor.'],
      ['satellite', 'noun', "sun'iy yo'ldosh", 'The signal comes from a satellite.', "Signal sun'iy yo'ldoshdan keladi."],
      ['ergonomics', 'noun', 'ergonomika (qulay dizayn)', 'Good ergonomics can prevent back pain.', "To'g'ri ergonomika bel og'rig'ining oldini oladi."],
      ['disease-resistant', 'adjective', 'kasallikka chidamli', 'Scientists developed disease-resistant wheat.', "Olimlar kasallikka chidamli bug'doy yaratishdi."],
      ['technologically', 'adverb', 'texnologik jihatdan', 'Japan is a technologically advanced country.', 'Yaponiya — texnologik jihatdan rivojlangan mamlakat.'],
    ],
  },
  {
    unit: 57,
    title: 'Technology of the future',
    titleUz: 'Kelajak texnologiyalari',
    emoji: '🚀',
    words: [
      ['nanotechnology', 'noun', 'nanotexnologiya', 'Nanotechnology could transform medicine.', "Nanotexnologiya tibbiyotni tubdan o'zgartirishi mumkin."],
      ['gene therapy', 'phrase', 'gen terapiyasi', 'Gene therapy may cure some inherited diseases.', 'Gen terapiyasi ba\'zi irsiy kasalliklarni davolashi mumkin.'],
      ['cloning', 'noun', 'klonlash', 'Human cloning is illegal in most countries.', "Ko'p mamlakatlarda inson klonlash taqiqlangan."],
      ['extraterrestrial', 'adjective', "o'zga sayyoraga oid", 'Do you believe in extraterrestrial life?', "O'zga sayyoralarda hayot borligiga ishonasizmi?"],
      ['interplanetary', 'adjective', 'sayyoralararo', 'Interplanetary travel may be possible one day.', "Bir kun kelib sayyoralararo sayohat mumkin bo'lishi mumkin."],
      ['envisage', 'verb', 'tasavvur qilmoq', "I can't envisage living anywhere else.", 'Boshqa joyda yashashni tasavvur qila olmayman.'],
      ['foresee', 'verb', "oldindan ko'rmoq", 'Nobody could foresee the crisis.', "Hech kim inqirozni oldindan ko'ra olmadi."],
      ['doomsday', 'noun', 'qiyomat kuni', 'Some films show doomsday scenarios.', "Ba'zi filmlar qiyomat kuni ssenariylarini ko'rsatadi."],
      ['drastic', 'adjective', 'keskin (chora)', 'We need drastic action to stop climate change.', "Iqlim o'zgarishini to'xtatish uchun keskin choralar kerak."],
      ['destiny', 'noun', 'taqdir', 'He believes it was his destiny to become a doctor.', "U shifokor bo'lish taqdirida bor edi deb hisoblaydi."],
      ['global village', 'phrase', 'global qishloq', 'The internet has turned the world into a global village.', 'Internet dunyoni global qishloqqa aylantirdi.'],
      ['gridlock', 'noun', "butunlay tiqilib qolish (transport)", 'The city is in gridlock every morning.', 'Shahar har tong butunlay tiqilib qoladi.'],
      ['mega-city', 'noun', 'megapolis', "Lagos is a fast-growing mega-city.", "Lagos — tez o'sayotgan megapolis."],
      ['designer baby', 'phrase', 'genetik buyurtma asosidagi bola', 'Is a designer baby a dream or a danger?', "Genetik buyurtma asosidagi bola — orzumi yoki xavf?"],
      ['nuclear family', 'phrase', 'kichik oila (ota-ona va bolalar)', 'The nuclear family is becoming less common.', 'Faqat ota-ona va bolalardan iborat oila kamroq uchramoqda.'],
      ['globalisation', 'noun', 'globallashuv', 'Globalisation has changed the way we shop.', "Globallashuv xarid qilish usulimizni o'zgartirdi."],
      ['smart home', 'phrase', 'aqlli uy', 'In a smart home, you can control the lights with your phone.', 'Aqlli uyda chiroqlarni telefon bilan boshqarish mumkin.'],
    ],
  },
  {
    unit: 58,
    title: 'Energy: from fossil fuels to windmills',
    titleUz: 'Energetika',
    emoji: '⚡',
    words: [
      ['solar panel', 'phrase', 'quyosh paneli', 'We put solar panels on the roof.', "Tomga quyosh panellarini o'rnatdik."],
      ['wind farm', 'phrase', 'shamol elektr stansiyasi', 'A new wind farm has been built near the coast.', "Qirg'oq yaqinida yangi shamol elektr stansiyasi qurildi."],
      ['hydroelectric', 'adjective', 'gidroelektr', 'The dam produces hydroelectric power.', "To'g'on gidroelektr energiyasi ishlab chiqaradi."],
      ['geothermal', 'adjective', 'geotermal (yer issiqligi)', 'Iceland uses a lot of geothermal energy.', "Islandiya ko'p geotermal energiyadan foydalanadi."],
      ['tidal', 'adjective', "suv ko'tarilishi(ga oid)", 'Tidal energy uses the movement of the sea.', "Suv ko'tarilishi energiyasi dengiz harakatidan foydalanadi."],
      ['nuclear', 'adjective', 'yadroviy, atom', 'The country has two nuclear power stations.', 'Mamlakatda ikkita atom elektr stansiyasi bor.'],
      ['biomass', 'noun', 'biomassa', 'Biomass is made from plant waste.', "Biomassa o'simlik chiqindilaridan olinadi."],
      ['energy-efficient', 'adjective', 'energiya tejamkor', 'Energy-efficient light bulbs save money.', 'Energiya tejamkor lampochkalar pulni tejaydi.'],
      ['gas-guzzler', 'noun', "ko'p yoqilg'i yeydigan mashina", 'He drives a big gas-guzzler.', "U ko'p yoqilg'i yeydigan katta mashina haydaydi."],
      ['power-hungry', 'adjective', "ko'p energiya sarflaydigan", 'Old fridges are very power-hungry.', "Eski muzlatkichlar juda ko'p elektr sarflaydi."],
      ['consumption', 'noun', "iste'mol", 'Energy consumption rises in winter.', "Qishda energiya iste'moli oshadi."],
      ['appliance', 'noun', 'maishiy texnika', 'Turn off electrical appliances when you go out.', "Chiqib ketayotganda elektr maishiy texnikani o'chiring."],
      ['pipeline', 'noun', 'quvur (gaz, neft)', 'A gas pipeline runs from Uzbekistan to China.', "O'zbekistondan Xitoyga gaz quvuri o'tadi."],
      ['offshore', 'adjective', "dengizdagi (qirg'oqdan uzoqda)", 'They drill for oil at offshore platforms.', 'Ular dengizdagi platformalarda neft qazishadi.'],
      ['oil well', 'phrase', "neft qudug'i", 'The company discovered a new oil well.', "Kompaniya yangi neft qudug'ini topdi."],
      ['coal-fired', 'adjective', "ko'mirda ishlaydigan", 'Coal-fired power stations cause pollution.', "Ko'mirda ishlaydigan elektr stansiyalari ifloslanishga sabab bo'ladi."],
      ['food miles', 'phrase', 'oziq-ovqatni tashish masofasi', 'Buying local food reduces food miles.', 'Mahalliy oziq-ovqat sotib olish uni tashish masofasini qisqartiradi.'],
    ],
  },
  {
    unit: 59,
    title: 'Space: no room to swing a cat',
    titleUz: 'Joy va makon',
    emoji: '📦',
    words: [
      ['cramped', 'adjective', 'tor, siqiq', 'The flat is small and cramped.', 'Kvartira kichik va tor.'],
      ['poky', 'adjective', 'kichkina, qisiq (xona)', 'We lived in a poky little room.', 'Biz kichkina, qisiq xonada yashardik.'],
      ['roomy', 'adjective', "keng, sig'imli", 'The car is surprisingly roomy.', 'Mashina kutilmaganda keng.'],
      ['compact', 'adjective', 'ixcham', 'The camera is small and compact.', 'Kamera kichik va ixcham.'],
      ['ample', 'adjective', "yetarli, mo'l", 'There is ample space for parking.', "To'xtash uchun yetarlicha joy bor."],
      ['extensive', 'adjective', "keng ko'lamli", 'The house has extensive gardens.', "Uyning keng bog'lari bor."],
      ['congested', 'adjective', 'tirband, gavjum', 'The roads are congested at rush hour.', "Tig'iz soatda yo'llar tirband bo'ladi."],
      ['labyrinth', 'noun', 'labirint', 'The old city is a labyrinth of narrow streets.', "Eski shahar — tor ko'chalar labirinti."],
      ['rambling', 'adjective', 'katta va chalkash (bino)', 'They live in a rambling old house.', 'Ular katta, chalkash eski uyda yashaydi.'],
      ['scattered', 'adjective', 'sochilgan', 'Toys were scattered all over the floor.', "O'yinchoqlar pol bo'ylab sochilib yotardi."],
      ['hemmed in', 'phrase', 'qurshab olingan', 'The village is hemmed in by mountains.', "Qishloq tog'lar bilan qurshab olingan."],
      ['squeeze', 'verb', "siqilib sig'moq", 'Can you squeeze into the back seat?', "Orqa o'rindiqqa sig'ib ketasanmi?"],
      ['squash', 'verb', "tiqilib o'tirmoq", 'Five of us squashed into a small car.', "Beshovlon kichik mashinaga tiqilib o'tirdik."],
      ['stuff', 'verb', 'tiqmoq', 'She stuffed her clothes into the bag.', 'U kiyimlarini sumkaga tiqib yubordi.'],
      ['boundary', 'noun', 'chegara', 'The river forms the boundary between the two countries.', "Daryo ikki mamlakat o'rtasidagi chegarani tashkil qiladi."],
      ['no room to swing a cat', 'phrase', "qimirlashga joy yo'q", "The kitchen is so small there's no room to swing a cat.", "Oshxona shunchalik kichikki, qimirlashga joy yo'q."],
      ['wide open', 'phrase', 'keng ochiq (makon)', 'The wide open spaces of the steppe are beautiful.', "Dashtning keng ochiq kengliklari go'zal."],
    ],
  },
  {
    unit: 60,
    title: 'Time: once in a blue moon',
    titleUz: 'Vaqt haqida iboralar',
    emoji: '⏲️',
    words: [
      ['in the nick of time', 'phrase', 'ayni vaqtida (so\'nggi daqiqada)', 'We arrived in the nick of time.', 'Ayni vaqtida yetib keldik.'],
      ["for donkey's years", 'phrase', 'azaldan, uzoq yillardan beri', "I've known him for donkey's years.", 'Uni azaldan bilaman.'],
      ['till the cows come home', 'phrase', 'qiyomatgacha (juda uzoq)', "You can argue till the cows come home, but I won't change my mind.", "Qiyomatgacha bahslashsang ham, fikrimni o'zgartirmayman."],
      ['in a jiffy', 'phrase', 'bir zumda', "I'll be back in a jiffy.", 'Bir zumda qaytaman.'],
      ['at short notice', 'phrase', 'qisqa muddatda (kutilmaganda)', 'The meeting was cancelled at short notice.', 'Uchrashuv kutilmaganda bekor qilindi.'],
      ['transient', 'adjective', "vaqtinchalik, o'tuvchi", 'Fame is transient.', "Shon-shuhrat vaqtinchalik."],
      ['incipient', 'adjective', 'boshlanayotgan', 'The doctor noticed signs of incipient disease.', 'Shifokor boshlanayotgan kasallik belgilarini payqadi.'],
      ['inexorable', 'adjective', "to'xtatib bo'lmas", 'The inexorable rise of technology changes everything.', "Texnologiyaning to'xtatib bo'lmas yuksalishi hamma narsani o'zgartiradi."],
      ['lingering', 'adjective', 'ketmaydigan, uzoq saqlanadigan', 'There is a lingering smell of smoke.', 'Hali ham tutun hidi ketmagan.'],
      ['persistent', 'adjective', "to'xtamaydigan, doimiy", 'He has a persistent cough.', "Uning to'xtamaydigan yo'tali bor."],
      ['prolong', 'verb', 'uzaytirmoq', 'The treatment can prolong life.', 'Davolash umrni uzaytirishi mumkin.'],
      ['protracted', 'adjective', "cho'zilgan", 'After protracted negotiations, they reached an agreement.', "Cho'zilgan muzokaralardan keyin ular kelishuvga erishishdi."],
      ['repeatedly', 'adverb', 'qayta-qayta', "I've told you repeatedly not to do that.", 'Buni qilma deb qayta-qayta aytganman.'],
      ['has-been', 'noun', "o'tmishdagi mashhur (unutilgan)", "He's a has-been who was famous in the 90s.", "U 90-yillarda mashhur bo'lgan, endi unutilgan odam."],
      ['over the years', 'phrase', 'yillar davomida', 'Over the years, the town has changed a lot.', "Yillar davomida shahar ancha o'zgardi."],
      ['all your life', 'phrase', 'butun umr', "You've lived here all your life, haven't you?", "Butun umringizni shu yerda o'tkazgansiz, shunday emasmi?"],
    ],
  },
];
