/**
 * Advanced (C1), 1–20-unit'lar. Tamoyillar — elementary.js va advanced.js
 * dagi izohlarga qarang.
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 1,
    title: 'Cramming for success: study and academic work',
    titleUz: "O'qish va ilmiy ish",
    emoji: '📚',
    words: [
      ['cram', 'verb', 'imtihonga shoshilinch yodlamoq', "She's cramming for her history exam.", 'U tarix imtihoniga shoshilinch tayyorlanyapti.'],
      ['revise', 'verb', '(imtihonga) takrorlamoq', 'I need to revise for my exams.', 'Imtihonlarga takrorlab tayyorlanishim kerak.'],
      ['plagiarism', 'noun', 'plagiat', 'Copying from the internet is plagiarism.', "Internetdan ko'chirish — plagiat."],
      ['deadline', 'noun', 'oxirgi muddat', 'The deadline for the essay is Friday.', 'Insho topshirishning oxirgi muddati — juma.'],
      ['assignment', 'noun', "topshiriq (o'quv)", 'We have a written assignment every week.', 'Har hafta yozma topshiriq bor.'],
      ['essay', 'noun', 'insho', 'Write an essay of 500 words.', "500 so'zlik insho yozing."],
      ['memorise', 'verb', 'yodlamoq', 'Actors have to memorise their lines.', "Aktyorlar o'z matnlarini yodlashi kerak."],
      ['rote-learning', 'noun', 'mexanik yodlash', "Rote-learning doesn't help you understand.", 'Mexanik yodlash tushunishga yordam bermaydi.'],
      ['mnemonic', 'noun', 'eslab qolish usuli (mnemonika)', 'A mnemonic can help you remember the planets.', 'Mnemonika sayyoralarni eslab qolishga yordam beradi.'],
      ['bury yourself in', 'phrase', "(kitobga, ishga) sho'ng'ib ketmoq", "You can't bury yourself in your books all summer.", "Butun yoz kitoblarga sho'ng'ib yura olmaysan."],
      ['well-qualified', 'adjective', 'yuqori malakali', 'She is well-qualified for the job.', 'U bu ish uchun yuqori malakali.'],
      ['genius', 'noun', 'daho', 'Einstein was a genius.', 'Eynshteyn daho edi.'],
      ['intensively', 'adverb', 'jadal', 'He studied English intensively for three months.', "U uch oy ingliz tilini jadal o'rgandi."],
      ['portfolio', 'noun', "ishlar to'plami (portfolio)", 'Art students must present a portfolio.', "San'at talabalari ishlar to'plamini taqdim etishi kerak."],
      ['finals', 'noun', 'bitiruv imtihonlari', "She's taking her finals next month.", 'U kelasi oy bitiruv imtihonlarini topshiradi.'],
      ['carry out', 'phrase', "amalga oshirmoq, o'tkazmoq", 'The students carry out experiments in the lab.', "Talabalar laboratoriyada tajribalar o'tkazadi."],
    ],
  },
  {
    unit: 2,
    title: 'Education: debates and issues',
    titleUz: "Ta'lim: bahs va muammolar",
    emoji: '🏫',
    words: [
      ['curriculum', 'noun', "o'quv dasturi", 'Coding is now part of the school curriculum.', "Dasturlash endi maktab o'quv dasturining bir qismi."],
      ['syllabus', 'noun', 'fan dasturi', 'The syllabus covers modern history.', 'Fan dasturi zamonaviy tarixni qamrab oladi.'],
      ['literacy', 'noun', 'savodxonlik', 'Literacy rates in Uzbekistan are very high.', "O'zbekistonda savodxonlik darajasi juda yuqori."],
      ['numeracy', 'noun', "hisob-kitob ko'nikmasi", 'Good numeracy is needed for this job.', "Bu ish uchun yaxshi hisob-kitob ko'nikmasi kerak."],
      ['bursary', 'noun', "moddiy yordam (o'qish uchun)", 'She received a bursary to cover her living costs.', 'U turmush xarajatlarini qoplash uchun moddiy yordam oldi.'],
      ['bullying', 'noun', 'tazyiq, bulling', 'The school has a strict policy on bullying.', 'Maktabda tazyiqqa qarshi qat\'iy qoidalar bor.'],
      ['mature student', 'phrase', 'katta yoshdagi talaba', 'As a mature student, he started university at 40.', 'Katta yoshdagi talaba sifatida u universitetga 40 yoshida kirdi.'],
      ['special needs', 'phrase', 'alohida ehtiyojlar', 'The school has a teacher for children with special needs.', "Maktabda alohida ehtiyojli bolalar uchun o'qituvchi bor."],
      ['selective', 'adjective', 'saralab oladigan', "It's a selective school; you must pass an exam to get in.", 'Bu saralab oladigan maktab — kirish uchun imtihon topshirish kerak.'],
      ['elitism', 'noun', 'elitizm (tanlanganlar uchun)', 'Critics accuse the university of elitism.', 'Tanqidchilar universitetni elitizmda ayblaydi.'],
      ['lifelong learning', 'phrase', "butun umr ta'lim", 'The government promotes lifelong learning.', "Hukumat butun umr ta'limni qo'llab-quvvatlaydi."],
      ['tertiary', 'adjective', "oliy (ta'lim bosqichi)", 'Tertiary education includes colleges and universities.', "Oliy ta'limga kollej va universitetlar kiradi."],
      ['two-tier', 'adjective', "ikki pog'onali", 'Critics say we have a two-tier education system.', "Tanqidchilar bizda ikki pog'onali ta'lim tizimi bor deydi."],
      ['one-to-one', 'adjective', 'yakkama-yakka', 'She has one-to-one lessons with a tutor.', "U ustoz bilan yakkama-yakka shug'ullanadi."],
      ['the three Rs', 'phrase', "o'qish, yozish va hisob", 'Primary schools focus on the three Rs.', "Boshlang'ich maktablar o'qish, yozish va hisobga e'tibor qaratadi."],
      ['league table', 'phrase', 'reyting jadvali', 'The school is at the top of the league tables.', 'Maktab reyting jadvallarining yuqorisida.'],
      ['perpetuate', 'verb', 'saqlab qolmoq (yomon narsani)', 'Private schools may perpetuate inequality.', 'Xususiy maktablar tengsizlikni saqlab qolishi mumkin.'],
    ],
  },
  {
    unit: 3,
    title: 'Applying for a job',
    titleUz: 'Ishga ariza berish',
    emoji: '📝',
    words: [
      ['opening', 'noun', "bo'sh ish o'rni", "There's an opening for a web designer.", "Veb-dizayner uchun bo'sh o'rin bor."],
      ['position', 'noun', 'lavozim', 'She applied for the position of manager.', 'U menejer lavozimiga ariza berdi.'],
      ['salary', 'noun', 'maosh', 'The salary is paid monthly.', "Maosh har oy to'lanadi."],
      ['hands-on', 'adjective', 'amaliy', 'The job requires hands-on experience.', 'Bu ish amaliy tajriba talab qiladi.'],
      ['customer-facing', 'adjective', 'mijozlar bilan bevosita ishlaydigan', "It's a customer-facing role in a bank.", 'Bu bankda mijozlar bilan bevosita ishlaydigan lavozim.'],
      ['fast-paced', 'adjective', "tez sur'atli", 'We work in a fast-paced environment.', "Biz tez sur'atli muhitda ishlaymiz."],
      ['challenging', 'adjective', "qiyin, mas'uliyatli", "I'm looking for a more challenging job.", "Men qiyinroq, mas'uliyatliroq ish qidiryapman."],
      ['leadership', 'noun', 'yetakchilik', 'She has strong leadership skills.', "Uning kuchli yetakchilik ko'nikmalari bor."],
      ['managerial', 'adjective', 'boshqaruv(ga oid)', 'He has ten years of managerial experience.', "Uning o'n yillik boshqaruv tajribasi bor."],
      ['relevant', 'adjective', 'tegishli, aloqador', 'Please describe any relevant experience.', 'Iltimos, tegishli tajribangizni tasvirlab bering.'],
      ['suitability', 'noun', 'moslik, yaroqlilik', 'The interview tests your suitability for the job.', 'Suhbat sizning ishga mosligingizni tekshiradi.'],
      ['subsidised', 'adjective', 'arzonlashtirilgan (imtiyozli)', 'Employees get subsidised meals.', 'Xodimlar arzonlashtirilgan ovqat oladi.'],
      ['benefits', 'noun', "imtiyozlar (sug'urta, ta'til)", 'The job comes with good benefits.', 'Ishda yaxshi imtiyozlar bor.'],
      ['report to', 'phrase', "...ga bo'ysunmoq", 'You will report to the sales director.', "Siz savdo direktoriga bo'ysunasiz."],
      ['passion for', 'phrase', '...ga ishtiyoq', 'She has a real passion for teaching.', "Uning o'qitishga chinakam ishtiyoqi bor."],
      ['covering letter', 'phrase', 'ilova xati (rezyumega)', 'Send your CV with a covering letter.', 'Rezyumeingizni ilova xati bilan yuboring.'],
      ['Yours faithfully', 'phrase', 'Hurmat bilan (rasmiy xat oxirida)', "End a formal letter with 'Yours faithfully'.", "Rasmiy xatni «Hurmat bilan» deb tugating."],
    ],
  },
  {
    unit: 4,
    title: 'Job interviews',
    titleUz: 'Ishga suhbat',
    emoji: '🤝',
    words: [
      ['shortlist', 'verb', "qisqa ro'yxatga kiritmoq", 'Five candidates were shortlisted for the job.', "Ishga beshta nomzod qisqa ro'yxatga kiritildi."],
      ['panel', 'noun', "hay'at (suhbatda)", 'I was interviewed by a panel of four.', "Meni to'rt kishilik hay'at suhbatdan o'tkazdi."],
      ['recruit', 'verb', 'ishga yollamoq', 'The company plans to recruit 50 new staff.', 'Kompaniya 50 yangi xodim yollamoqchi.'],
      ['trainee', 'noun', 'stajyor', 'She started as a trainee in the bank.', 'U bankda stajyor sifatida ish boshladi.'],
      ['criteria', 'noun', 'mezonlar', 'What criteria do you use to choose staff?', 'Xodim tanlashda qanday mezonlardan foydalanasiz?'],
      ['in-house', 'adjective', 'kompaniya ichidagi, shtatdagi', 'The company has its own in-house lawyer.', "Kompaniyaning o'z shtatdagi yuristi bor."],
      ['make eye contact', 'phrase', "ko'zga qaramoq", 'Make eye contact with the interviewer.', "Suhbat oluvchining ko'ziga qarang."],
      ['trial period', 'phrase', 'sinov muddati', 'There is a three-month trial period.', 'Uch oylik sinov muddati bor.'],
      ['give notice', 'phrase', "(ishdan ketishni) oldindan ma'lum qilmoq", 'You must give notice a month before you leave.', "Ketishdan bir oy oldin ma'lum qilishingiz kerak."],
      ['under pressure', 'phrase', 'bosim ostida', 'Can you work under pressure?', 'Bosim ostida ishlay olasizmi?'],
      ['outline', 'verb', 'qisqacha bayon qilmoq', 'Briefly outline your experience.', 'Tajribangizni qisqacha bayon qiling.'],
      ['fill the post', 'phrase', 'lavozimga odam topmoq', 'They hope to fill the post by June.', 'Ular lavozimga iyungacha odam topishni umid qilishadi.'],
      ['boost your chances', 'phrase', 'imkoniyatini oshirmoq', 'A good CV can boost your chances.', 'Yaxshi rezyume imkoniyatingizni oshiradi.'],
      ['professional', 'adjective', 'professional, mutaxassisga xos', 'Always look professional at an interview.', "Suhbatda doim professional ko'rinishda bo'ling."],
      ['first impression', 'phrase', 'birinchi taassurot', 'First impressions are very important.', 'Birinchi taassurot juda muhim.'],
    ],
  },
  {
    unit: 5,
    title: 'At work: colleagues and routines',
    titleUz: 'Ishda: hamkasblar va kundalik ish',
    emoji: '👥',
    words: [
      ['counterpart', 'noun', '(boshqa tomondagi) hamkasb', 'The minister met his Chinese counterpart.', 'Vazir xitoylik hamkasbi bilan uchrashdi.'],
      ['rapport', 'noun', 'iliq munosabat, til topishish', 'She has a good rapport with her team.', 'Uning jamoasi bilan munosabati yaxshi.'],
      ['collaboration', 'noun', 'hamkorlik', 'The book was written in collaboration with a scientist.', 'Kitob olim bilan hamkorlikda yozilgan.'],
      ['freelance', 'adjective', 'mustaqil, frilans', 'She works as a freelance journalist.', "U mustaqil jurnalist bo'lib ishlaydi."],
      ['self-employed', 'adjective', "o'zini o'zi band qilgan", "My father is self-employed; he runs a small shop.", "Otam o'zini o'zi band qilgan — kichik do'kon yuritadi."],
      ['hot-desking', 'noun', 'doimiy stolsiz ishlash', 'With hot-desking, nobody has their own desk.', "Bu tizimda hech kimning o'z stoli bo'lmaydi."],
      ['job-share', 'noun', "bitta ishni bo'lishish", 'They have a job-share, so each works three days.', "Ular bitta ishni bo'lishadi, har biri uch kun ishlaydi."],
      ['workload', 'noun', 'ish hajmi', 'My workload has doubled this year.', 'Bu yil ish hajmim ikki barobar oshdi.'],
      ['mundane', 'adjective', 'oddiy, zerikarli', 'Most of my job is quite mundane.', "Ishimning ko'p qismi ancha zerikarli."],
      ['monotonous', 'adjective', 'bir xil, zerikarli', 'Factory work can be very monotonous.', "Zavod ishi juda bir xil bo'lishi mumkin."],
      ['repetitive', 'adjective', 'takroriy', 'The job involves repetitive tasks.', 'Ish takroriy vazifalardan iborat.'],
      ['mind-numbing', 'adjective', 'miyani qotiradigan (zerikarli)', 'Data entry is mind-numbing work.', "Ma'lumot kiritish — miyani qotiradigan zerikarli ish."],
      ['rewarding', 'adjective', 'qoniqish beradigan', 'Teaching is hard but rewarding.', "O'qituvchilik qiyin, lekin qoniqish beradi."],
      ['stimulating', 'adjective', 'qiziqarli, ruhlantiruvchi', 'I find my new job very stimulating.', 'Yangi ishim menga juda qiziq va ruhlantiruvchi.'],
      ['dead-end job', 'phrase', 'istiqbolsiz ish', "He's stuck in a dead-end job.", 'U istiqbolsiz ishda qolib ketgan.'],
      ['night shift', 'phrase', 'tungi smena', 'Nurses often work the night shift.', 'Hamshiralar ko\'pincha tungi smenada ishlaydi.'],
      ['pecking order', 'phrase', 'ierarxiya (norasmiy)', 'New employees are at the bottom of the pecking order.', 'Yangi xodimlar ierarxiyaning eng pastida.'],
      ['start-up', 'noun', 'startap', 'He works for a tech start-up.', 'U texnologik startapda ishlaydi.'],
    ],
  },
  {
    unit: 6,
    title: 'At work: job satisfaction',
    titleUz: 'Ishdan qoniqish',
    emoji: '😊',
    words: [
      ['perk', 'noun', 'imtiyoz (ishda)', 'A company car is one of the perks of the job.', 'Xizmat mashinasi — bu ishning imtiyozlaridan biri.'],
      ['bonus', 'noun', 'mukofot puli (bonus)', 'Staff get a bonus at the end of the year.', 'Xodimlar yil oxirida mukofot puli oladi.'],
      ['increment', 'noun', '(maosh) oshishi', "You'll get an annual salary increment.", 'Har yili maoshingiz oshadi.'],
      ['morale', 'noun', 'jamoa ruhiyati', 'Morale in the office is very low.', 'Ofisdagi ruhiyat juda past.'],
      ['demotivated', 'adjective', "g'ayrati so'ngan", 'Staff feel demotivated after the pay cut.', "Maosh kamaytirilgandan keyin xodimlarning g'ayrati so'ndi."],
      ['overworked and underpaid', 'phrase', "ko'p ishlab, kam haq oladigan", 'Many nurses feel overworked and underpaid.', "Ko'p hamshiralar ko'p ishlab, kam haq olishini his qiladi."],
      ['performance-related', 'adjective', "natijaga bog'liq", 'We have a performance-related pay system.', "Bizda natijaga bog'liq ish haqi tizimi bor."],
      ['skeleton staff', 'phrase', 'minimal (navbatchi) xodimlar', 'Only a skeleton staff works over the holidays.', 'Bayramlarda faqat navbatchi xodimlar ishlaydi.'],
      ['run-of-the-mill', 'adjective', "oddiy, o'rtamiyona", "It's just a run-of-the-mill office job.", 'Bu oddiy ofis ishi, xolos.'],
      ['work-life balance', 'phrase', "ish va shaxsiy hayot muvozanati", 'A good work-life balance is important.', "Ish va shaxsiy hayot o'rtasidagi muvozanat muhim."],
      ['teamwork', 'noun', 'jamoaviy ish', 'The project succeeded thanks to good teamwork.', "Loyiha yaxshi jamoaviy ish tufayli muvaffaqiyatli bo'ldi."],
      ['dynamic', 'adjective', "g'ayratli, dinamik", "We're looking for a dynamic young manager.", "Biz g'ayratli yosh menejer qidiryapmiz."],
      ['voluntary', 'adjective', "ko'ngilli (bepul)", 'She does voluntary work at the hospital.', "U kasalxonada ko'ngilli bo'lib ishlaydi."],
      ['annual leave', 'phrase', "yillik ta'til", 'I have 24 days of annual leave.', "Yiliga 24 kunlik ta'tilim bor."],
      ['job satisfaction', 'phrase', 'ishdan qoniqish', "Money isn't everything; job satisfaction matters too.", 'Pul hamma narsa emas, ishdan qoniqish ham muhim.'],
    ],
  },
  {
    unit: 7,
    title: 'At work: careers',
    titleUz: 'Karyera va biznes',
    emoji: '💼',
    words: [
      ['lucrative', 'adjective', 'daromadli', 'He has a lucrative job in finance.', 'Uning moliya sohasida daromadli ishi bor.'],
      ['merger', 'noun', "qo'shilish (kompaniyalar)", "The merger created the country's largest bank.", "Qo'shilish natijasida mamlakatning eng katta banki yuzaga keldi."],
      ['niche market', 'phrase', 'tor (maxsus) bozor', 'The company sells to a niche market.', 'Kompaniya tor bozorga sotadi.'],
      ['loss leader', 'phrase', 'xaridor jalb qilish uchun zarariga sotiladigan tovar', 'Supermarkets often sell bread as a loss leader.', "Supermarketlar ko'pincha nonni xaridor jalb qilish uchun zarariga sotadi."],
      ['red tape', 'phrase', "byurokratiya, qog'ozbozlik", 'Starting a business involves a lot of red tape.', "Biznes boshlash ko'p qog'ozbozlik bilan bog'liq."],
      ['cold calling', 'phrase', "notanishlarga qo'ng'iroq qilib savdo", 'I hate cold calling; people are often rude.', "Notanishlarga qo'ng'iroq qilib savdo qilishni yomon ko'raman."],
      ['hard sell', 'phrase', 'tazyiqli savdo', "I don't like the hard sell in some shops.", "Ba'zi do'konlardagi tazyiqli savdo menga yoqmaydi."],
      ['brand loyalty', 'phrase', 'brendga sodiqlik', 'Apple has strong brand loyalty.', "Apple'ning brendiga sodiqlik kuchli."],
      ['merchandise', 'noun', 'savdo mahsulotlari', 'The shop sells football merchandise.', "Do'kon futbol mahsulotlarini sotadi."],
      ['auction', 'noun', 'auksion', 'The painting was sold at auction.', 'Rasm auksionda sotildi.'],
      ['invest', 'verb', 'sarmoya kiritmoq', 'They want to invest in property.', "Ular ko'chmas mulkka sarmoya kiritmoqchi."],
      ['capital', 'noun', "kapital, boshlang'ich mablag'", 'You need capital to start a business.', "Biznes boshlash uchun boshlang'ich kapital kerak."],
      ['hammer out', 'phrase', '(qiyinchilik bilan) kelishib olmoq', 'It took weeks to hammer out a deal.', 'Kelishuvga erishish uchun haftalar ketdi.'],
      ['part with', 'phrase', '(pul, narsa) bilan xayrlashmoq', "People don't like to part with their money.", 'Odamlar pulidan ajralishni yoqtirmaydi.'],
      ['stock', 'noun', '(tovar) zaxirasi', 'We have plenty of stock in the warehouse.', "Omborda tovar zaxirasi ko'p."],
      ['come under fire', 'phrase', 'qattiq tanqidga uchramoq', 'The minister may come under fire for this decision.', 'Vazir bu qarori uchun tanqidga uchrashi mumkin.'],
    ],
  },
  {
    unit: 8,
    title: 'Describing people: positive and negative qualities',
    titleUz: 'Odamlarning ijobiy va salbiy fazilatlari',
    emoji: '🧭',
    words: [
      ['altruistic', 'adjective', 'fidoyi (o\'zgalar manfaatini ko\'zlovchi)', 'Her motives were purely altruistic.', "Uning niyatlari butunlay o'zgalar manfaati uchun edi."],
      ['astute', 'adjective', 'farosatli', "She's an astute politician.", 'U farosatli siyosatchi.'],
      ['diligent', 'adjective', 'tirishqoq', "He's a diligent student who never misses a class.", 'U hech qachon darsni qoldirmaydigan tirishqoq talaba.'],
      ['frugal', 'adjective', 'tejamkor, kamtarona', 'My grandparents lived a frugal life.', 'Bobo-buvim tejamkor hayot kechirishgan.'],
      ['parsimonious', 'adjective', 'ziqna', "He's so parsimonious that he never buys anyone a gift.", "U shunchalik ziqnaki, hech kimga sovg'a olmaydi."],
      ['garrulous', 'adjective', 'vaysaqi, gapdon', 'Our garrulous neighbour talks for hours.', "Vaysaqi qo'shnimiz soatlab gapiradi."],
      ['verbose', 'adjective', "cho'zinchoq (matn, nutq)", 'His reports are too verbose.', "Uning hisobotlari juda cho'zinchoq."],
      ['terse', 'adjective', 'qisqa va quruq', 'She gave a terse reply and left.', 'U qisqa va quruq javob berdi-da, chiqib ketdi.'],
      ['witty', 'adjective', 'hozirjavob, zukko', "He's very witty and makes everyone laugh.", 'U juda hozirjavob, hammani kuldiradi.'],
      ['tactless', 'adjective', 'nazokatsiz, andishasiz', 'It was tactless of you to mention her age.', "Uning yoshini tilga olishing andishasizlik bo'ldi."],
      ['unscrupulous', 'adjective', 'vijdonsiz', 'Unscrupulous landlords charge high rents.', 'Vijdonsiz uy egalari yuqori ijara haqi oladi.'],
      ['principled', 'adjective', 'tamoyilli, prinsipial', 'She is a principled politician who never lies.', "U hech qachon yolg'on gapirmaydigan tamoyilli siyosatchi."],
      ['resolute', 'adjective', 'sobitqadam', 'He was resolute in his decision to leave.', 'U ketish qarorida sobitqadam edi.'],
      ['dogged', 'adjective', "bo'sh kelmas, sabotli", 'Her dogged determination helped her succeed.', "Uning bo'sh kelmas qat'iyati muvaffaqiyatga olib keldi."],
      ['obliging', 'adjective', 'xizmatga tayyor, iltifotli', 'The hotel staff were very obliging.', 'Mehmonxona xodimlari juda xizmatga tayyor edi.'],
      ['placid', 'adjective', 'osoyishta, vazmin', 'The baby is very placid and rarely cries.', "Chaqaloq juda osoyishta, kamdan-kam yig'laydi."],
      ['sullen', 'adjective', "qovog'i soliq", 'The teenager sat in sullen silence.', "O'smir qovog'ini solib jim o'tirardi."],
      ['open-minded', 'adjective', 'ochiq fikrli', 'My grandmother is surprisingly open-minded.', 'Buvim kutilmaganda ochiq fikrli.'],
    ],
  },
  {
    unit: 9,
    title: 'Describing people: appearance and mannerisms',
    titleUz: 'Tashqi ko\'rinish va imo-ishoralar',
    emoji: '🤷',
    words: [
      ['lanky', 'adjective', 'novcha', "He's a lanky teenager who grew very fast.", "U juda tez o'sgan novcha o'smir."],
      ['scrawny', 'adjective', "oriq, ozg'in (yoqimsiz)", 'The stray cat was scrawny and hungry.', 'Daydi mushuk oriq va och edi.'],
      ['slender', 'adjective', 'xipcha, nozik', 'She has long, slender fingers.', 'Uning uzun, nozik barmoqlari bor.'],
      ['wiry', 'adjective', 'oriq, lekin baquvvat', 'The old farmer was small but wiry.', 'Keksa dehqon kichik, lekin pay-go\'shtli edi.'],
      ['haggard', 'adjective', "so'lgan, horg'in", 'He looked haggard after a week without sleep.', "Bir hafta uxlamagach, u juda so'lib qolgandi."],
      ['swarthy', 'adjective', 'qoramtir (teri)', 'The sailor had a swarthy face.', 'Dengizchining yuzi qoramtir edi.'],
      ['unkempt', 'adjective', 'taralmagan, pala-partish', 'His hair was long and unkempt.', 'Uning sochi uzun va taralmagan edi.'],
      ['immaculate', 'adjective', 'benuqson, pokiza', 'Her kitchen is always immaculate.', 'Uning oshxonasi doim benuqson toza.'],
      ['grimace', 'verb', 'yuzini burishtirmoq', 'He grimaced with pain.', "U og'riqdan yuzini burishtirdi."],
      ['scowl', 'verb', 'jahl bilan qovoq uymoq', 'The old man scowled at the noisy children.', 'Chol shovqinli bolalarga jahl bilan qovoq uydi.'],
      ['pout', 'verb', "labini cho'chchaytirmoq", "The little girl pouted when she didn't get the sweet.", "Qizcha shirinlik ololmagach, labini cho'chchaytirdi."],
      ['shrug', 'verb', 'yelka qismoq', "Don't just shrug; tell me what you think.", 'Shunchaki yelka qisma, fikringni ayt.'],
      ['twitch', 'verb', 'uchmoq (muskul)', "My eye twitches when I'm tired.", 'Charchasam, ko\'zim uchadi.'],
      ['fold your arms', 'phrase', "qo'l qovushtirmoq", "Don't fold your arms; it looks unfriendly.", "Qo'lingni qovushtirma, bu do'stona ko'rinmaydi."],
      ['drum your fingers', 'phrase', 'barmoq bilan chertib turmoq', "Don't drum your fingers on the table!", 'Barmoqlaring bilan stolni chertma!'],
      ['clench your fists', 'phrase', 'musht tugmoq', "When you're angry, you might clench your fists.", 'Jahling chiqqanda, mushtingni tugishing mumkin.'],
      ['bite your nails', 'phrase', 'tirnoq tishlamoq', 'Try not to bite your nails.', "Tirnog'ingni tishlamaslikka harakat qil."],
    ],
  },
  {
    unit: 10,
    title: 'Describing people: personality and character traits',
    titleUz: 'Xarakter xususiyatlari',
    emoji: '🎭',
    words: [
      ['aloof', 'adjective', "o'zini chetga olgan, sovuq", 'She seemed aloof, but she was just shy.', "U o'zini chetga olgandek ko'rinardi, lekin shunchaki uyatchan edi."],
      ['approachable', 'adjective', 'bemalol murojaat qilsa bo\'ladigan', 'Our manager is very approachable.', "Menejerimizga bemalol murojaat qilsa bo'ladi."],
      ['conceited', 'adjective', 'manman', "He's so conceited; he thinks he's perfect.", "U shunchalik manmanki, o'zini benuqson deb o'ylaydi."],
      ['conscientious', 'adjective', 'vijdonli, sidqidildan ishlaydigan', "She's a conscientious worker who checks everything twice.", 'U hamma narsani ikki marta tekshiradigan vijdonli xodim.'],
      ['diffident', 'adjective', "o'ziga ishonmaydigan", 'He was diffident about his abilities.', "U o'z qobiliyatiga ishonmasdi."],
      ['disdainful', 'adjective', 'mensimaydigan', 'She gave the cheap dress a disdainful look.', "U arzon ko'ylakka mensimay qaradi."],
      ['effusive', 'adjective', 'haddan ortiq hissiyotli', 'He was effusive in his thanks.', 'U juda qizg\'in minnatdorchilik bildirdi.'],
      ['gullible', 'adjective', "go'l, hamma narsaga ishonuvchan", 'Gullible tourists are easy targets for scammers.', "Go'l sayyohlar firibgarlar uchun oson o'lja."],
      ['haughty', 'adjective', "mag'rur, kibrli", 'The haughty waiter ignored us.', "Mag'rur ofitsiant bizga e'tibor bermadi."],
      ['impetuous', 'adjective', 'shoshqaloq', 'It was an impetuous decision that he regretted.', "Bu u keyin afsuslangan shoshqaloq qaror edi."],
      ['impulsive', 'adjective', "o'ylamay ish qiladigan", "She's impulsive and often buys things she doesn't need.", "U o'ylamay ish qiladi va ko'pincha keraksiz narsalarni sotib oladi."],
      ['introvert', 'noun', 'introvert (ichimdan)', 'As an introvert, he prefers quiet evenings.', "Introvert sifatida u tinch kechqurunlarni afzal ko'radi."],
      ['extrovert', 'noun', 'ekstrovert (ochiqko\'ngil)', 'Extroverts enjoy being in large groups.', "Ekstrovertlar katta davralarda bo'lishni yoqtiradi."],
      ['reserved', 'adjective', "o'zini tutuvchan, vazmin", 'The British are often described as reserved.', "Britaniyaliklarni ko'pincha o'zini tutuvchan deb tasvirlashadi."],
      ['taciturn', 'adjective', 'kamgap, indamas', 'My grandfather was a taciturn man.', 'Bobom kamgap odam edi.'],
      ['self-conscious', 'adjective', 'xijolatli', 'She felt self-conscious about her accent.', 'U talaffuzidan xijolat tortardi.'],
      ['well-balanced', 'adjective', 'ruhan barqaror', 'He is a well-balanced young man.', 'U ruhan barqaror yigit.'],
    ],
  },
  {
    unit: 11,
    title: 'Relationships: friends forever',
    titleUz: "Munosabatlar: abadiy do'stlik",
    emoji: '🤗',
    words: [
      ['soulmate', 'noun', 'ikkinchi yarim, jon do\'st', 'She believes she has found her soulmate.', 'U o\'zining ikkinchi yarmini topganiga ishonadi.'],
      ['kindred spirit', 'phrase', 'ruhan yaqin odam', 'We met at university and knew we were kindred spirits.', 'Universitetda tanishdik va ruhan yaqin ekanimizni bildik.'],
      ['platonic', 'adjective', "sof do'stona (romantik emas)", 'Their relationship is purely platonic.', "Ularning munosabati sof do'stona."],
      ['inseparable', 'adjective', 'ajralmas', 'The two sisters are inseparable.', 'Ikki opa-singil bir-biridan ajralmas.'],
      ['bosom friend', 'phrase', "qadrdon do'st", 'She was my bosom friend at school.', "U maktabda qadrdon do'stim edi."],
      ['mutual', 'adjective', "o'zaro", 'The respect between them is mutual.', "Ularning hurmati o'zaro."],
      ['hit it off', 'phrase', 'darrov til topishmoq', 'We hit it off immediately.', 'Biz darrov til topishib ketdik.'],
      ['get on like a house on fire', 'phrase', 'juda yaxshi chiqishmoq', 'The two boys get on like a house on fire.', 'Ikki bola juda yaxshi chiqishadi.'],
      ['love at first sight', 'phrase', "bir ko'rishda sevgi", 'It was love at first sight.', "Bu bir ko'rishdayoq sevgi edi."],
      ['fall head over heels', 'phrase', 'boshi aylanib sevib qolmoq', 'They fall head over heels in love in the film.', 'Filmda ular boshlari aylanib sevishib qolishadi.'],
      ['besotted', 'adjective', 'telbalarcha oshiq', "He's completely besotted with her.", 'U unga telbalarcha oshiq.'],
      ['amiable', 'adjective', 'xushmuomala', "He's an amiable man who gets on with everyone.", 'U hamma bilan chiqishadigan xushmuomala odam.'],
      ['considerate', 'adjective', "e'tiborli, g'amxo'r", 'It was very considerate of you to call.', "Qo'ng'iroq qilganing juda e'tiborli ish bo'ldi."],
      ['faithful', 'adjective', 'sodiq', 'Our dog is a faithful friend.', "Itimiz sodiq do'st."],
      ['bond', 'noun', "rishta, bog'liqlik", 'There is a strong bond between them.', 'Ular orasida kuchli rishta bor.'],
      ['well-matched', 'adjective', 'bir-biriga munosib', "They're a well-matched couple.", 'Ular bir-biriga munosib juftlik.'],
      ['fondness', 'noun', "mehr, iliq tuyg'u", 'She remembers her teacher with great fondness.', "U o'qituvchisini katta mehr bilan eslaydi."],
    ],
  },
  {
    unit: 12,
    title: 'Relationships: ups and downs',
    titleUz: 'Munosabatlar: past-balandlar',
    emoji: '💔',
    words: [
      ['rift', 'noun', 'darz, ixtilof', "There's been a rift between the two brothers.", "Ikki aka-uka o'rtasida darz ketdi."],
      ['feud', 'noun', '(uzoq) adovat', 'The two families have had a feud for years.', 'Ikki oila yillar davomida adovatda.'],
      ['discord', 'noun', 'nifoq, kelishmovchilik', 'Money caused discord in the family.', 'Pul oilada nifoq keltirib chiqardi.'],
      ['rival', 'noun', 'raqib', 'Real Madrid and Barcelona are old rivals.', 'Real Madrid va Barselona — azaliy raqiblar.'],
      ['arch-rival', 'noun', 'ashaddiy raqib', 'He finally beat his arch-rival.', 'U nihoyat ashaddiy raqibini yengdi.'],
      ['sworn enemy', 'phrase', 'ashaddiy dushman', 'After that day, he became my sworn enemy.', "O'sha kundan keyin u mening ashaddiy dushmanimga aylandi."],
      ['ally', 'noun', 'ittifoqchi', 'Britain and the US are close allies.', 'Buyuk Britaniya va AQSh — yaqin ittifoqchilar.'],
      ['staunch', 'adjective', "sodiq, qat'iy (tarafdor)", 'She is a staunch supporter of the team.', 'U jamoaning sodiq muxlisi.'],
      ['unswerving', 'adjective', "og'ishmas", 'He showed unswerving loyalty to his friends.', "U do'stlariga og'ishmas sodiqlik ko'rsatdi."],
      ['disloyal', 'adjective', 'xiyonatkor', 'It would be disloyal to tell her secret.', "Uning sirini aytish xiyonat bo'lardi."],
      ['split up', 'phrase', 'ajralishmoq (juftlik)', 'They split up after five years.', 'Ular besh yildan keyin ajrashishdi.'],
      ['ups and downs', 'phrase', 'past-baland, yaxshi-yomon kunlar', 'Every relationship has its ups and downs.', "Har qanday munosabatning past-balandi bo'ladi."],
      ['turn against', 'phrase', 'qarshi chiqmoq', 'Her friends began to turn against her.', "Do'stlari unga qarshi chiqa boshladi."],
      ['scrupulously', 'adverb', 'sinchkovlik bilan', 'He is scrupulously honest.', 'U sinchkovlik bilan halol.'],
      ['untruthful', 'adjective', "rostgo'y emas", 'She was accused of being untruthful.', "U rostgo'y bo'lmaganlikda ayblandi."],
    ],
  },
  {
    unit: 13,
    title: 'Emotions and reactions',
    titleUz: "Hissiyot va munosabat",
    emoji: '🎉',
    words: [
      ['bliss', 'noun', 'saodat, rohat', 'Lying on the beach was pure bliss.', 'Sohilda yotish sof rohat edi.'],
      ['blissful', 'adjective', 'saodatli', 'We spent a blissful week in the mountains.', "Tog'larda saodatli bir hafta o'tkazdik."],
      ['ecstatic', 'adjective', 'behad xursand', 'She was ecstatic about winning the prize.', 'U mukofot yutganidan behad xursand edi.'],
      ['jubilant', 'adjective', "shodon, g'alaba quvonchida", 'Jubilant fans celebrated in the streets.', 'Shodon muxlislar ko\'chalarda bayram qilishdi.'],
      ['exultant', 'adjective', 'tantanavor, zafarli', 'The exultant team lifted the trophy.', "Zafar quchgan jamoa kubokni ko'tardi."],
      ['rejoice', 'verb', 'quvonmoq', 'The whole country rejoiced at the news.', 'Butun mamlakat bu xabardan quvondi.'],
      ['crave', 'verb', 'juda xohlamoq', 'I often crave chocolate in the evening.', "Kechqurun ko'pincha shokolad yegim keladi."],
      ['covet', 'verb', "havas qilmoq (o'zganing narsasiga)", "He coveted his neighbour's car.", "U qo'shnisining mashinasiga havas qilardi."],
      ['appease', 'verb', '(talabni bajarib) tinchlantirmoq', 'The government tried to appease the protesters.', 'Hukumat namoyishchilarni tinchlantirishga urindi.'],
      ['placate', 'verb', "ko'nglini olmoq", 'She bought him flowers to placate him.', "U uning ko'nglini olish uchun gul sotib oldi."],
      ['defuse', 'verb', '(vaziyatni) yumshatmoq', 'He told a joke to defuse the tension.', 'U taranglikni yumshatish uchun hazil aytdi.'],
      ['implacable', 'adjective', 'murosasiz', 'He was an implacable enemy.', 'U murosasiz dushman edi.'],
      ['hatred', 'noun', 'nafrat', 'There was deep hatred between them.', "Ular o'rtasida chuqur nafrat bor edi."],
      ['walk on air', 'phrase', 'osmonda uchmoq (baxtdan)', 'After the good news, I felt like I could walk on air.', "Yaxshi xabardan keyin o'zimni osmonda uchayotgandek his qildim."],
      ['sheer', 'adjective', 'sof, mutlaq', 'Her face showed sheer joy.', 'Uning yuzida sof quvonch bor edi.'],
      ['thirst for', 'phrase', '...ga tashnalik', 'He has a thirst for knowledge.', 'Unda bilimga tashnalik bor.'],
    ],
  },
  {
    unit: 14,
    title: 'Negative feelings',
    titleUz: "Salbiy his-tuyg'ular",
    emoji: '😣',
    words: [
      ['abhor', 'verb', 'chuqur nafratlanmoq', 'I abhor violence of any kind.', 'Men har qanday zo\'ravonlikdan nafratlanaman.'],
      ['abhorrent', 'adjective', 'jirkanch', 'Cruelty to animals is abhorrent.', 'Hayvonlarga shafqatsizlik jirkanch.'],
      ['aversion', 'noun', 'toqatsizlik', 'He has an aversion to hard work.', "Uning og'ir mehnatga toqati yo'q."],
      ['antipathy', 'noun', "o'zaro yoqtirmaslik", "There's a strong antipathy between them.", "Ular o'rtasida kuchli o'zaro yoqtirmaslik bor."],
      ['dejected', 'adjective', "ruhi cho'kkan", 'The players looked dejected after the defeat.', "Mag'lubiyatdan keyin o'yinchilarning ruhi cho'kkan edi."],
      ['devastated', 'adjective', "qayg'udan ezilgan", "She was devastated by her father's death.", 'Otasining vafoti uni qattiq ezib yubordi.'],
      ['distraught', 'adjective', 'aqldan ozgudek xavotirli', 'The distraught mother searched for her child.', 'Aqldan ozgudek xavotirdagi ona bolasini qidirardi.'],
      ['distress', 'noun', 'iztirob', 'The news caused her great distress.', 'Xabar unga katta iztirob keltirdi.'],
      ['forlorn', 'adjective', "yolg'iz va ma'yus", 'A forlorn little dog sat in the rain.', "Yomg'irda yolg'iz, ma'yus kuchukcha o'tirardi."],
      ['obnoxious', 'adjective', "o'ta yoqimsiz", 'He was loud and obnoxious at the party.', 'U bazmda shovqinli va yoqimsiz edi.'],
      ['pompous', 'adjective', 'dabdabali, kibrli', 'The pompous speaker used long words to impress people.', "Kibrli ma'ruzachi odamlarni lol qoldirish uchun uzun so'zlar ishlatdi."],
      ['pretentious', 'adjective', "soxta, o'zini ko'rsatadigan", 'The restaurant is pretentious and overpriced.', 'Restoran soxta dabdabali va narxi baland.'],
      ['puerile', 'adjective', 'bolalarcha (kattaga yarashmaydigan)', 'His jokes are puerile.', 'Uning hazillari bolalarcha.'],
      ['nit-picking', 'noun', 'mayda-chuydaga osilish', 'Stop nit-picking about small mistakes.', 'Mayda xatolarga osilishni bas qil.'],
      ['ostentatious', 'adjective', "ko'z-ko'z qiluvchi", 'They live in an ostentatious mansion.', "Ular ko'z-ko'z qiluvchi hashamatli qasrda yashaydi."],
      ['scorn', 'noun', 'nafrat, mensimaslik', 'She looked at him with scorn.', 'U unga nafrat bilan qaradi.'],
      ['fickle', 'adjective', 'beqaror, tez aynaydigan', 'Fans can be very fickle.', "Muxlislar juda beqaror bo'lishi mumkin."],
      ['sloppy', 'adjective', "shalag'ay, beparvo", 'His work is often sloppy.', "Uning ishi ko'pincha shalag'ay."],
    ],
  },
  {
    unit: 15,
    title: 'Birth and death: from cradle to grave',
    titleUz: "Tug'ilish va o'lim",
    emoji: '🕊️',
    words: [
      ['pregnant', 'adjective', 'homilador', 'She is six months pregnant.', 'U olti oylik homilador.'],
      ['expecting', 'adjective', '(farzand) kutayotgan', "They're expecting their first baby.", 'Ular birinchi farzandini kutishyapti.'],
      ['midwife', 'noun', 'doya', 'The midwife helped deliver the baby.', 'Doya chaqaloqni dunyoga keltirishga yordam berdi.'],
      ['give birth', 'phrase', "tug'moq", 'She will give birth in March.', "U martda tug'adi."],
      ['conceive', 'verb', "homilador bo'lmoq", 'They tried for years to conceive a child.', "Ular yillar davomida farzand ko'rishga urinishdi."],
      ['IVF', 'noun', "sun'iy urug'lantirish (EKU)", 'Thousands of babies are born through IVF every year.', "Har yili minglab bolalar sun'iy urug'lantirish orqali tug'iladi."],
      ['bereaved', 'adjective', 'motamdor, yaqinini yo\'qotgan', 'The bereaved family thanked everyone for their support.', 'Motamdor oila hammaga yordami uchun minnatdorchilik bildirdi.'],
      ['condolences', 'noun', "ta'ziya, hamdardlik", 'Please accept my condolences.', "Iltimos, ta'ziyamni qabul qiling."],
      ['mourning', 'noun', 'motam, aza', 'The country is in mourning.', 'Mamlakat motamda.'],
      ['coffin', 'noun', 'tobut', 'The coffin was carried into the church.', 'Tobut cherkovga olib kirildi.'],
      ['burial', 'noun', 'dafn', 'The burial took place the next morning.', "Dafn ertasi kuni ertalab bo'lib o'tdi."],
      ['cremation', 'noun', 'jasadni yoqish (kremasiya)', 'In some cultures, cremation is common.', "Ba'zi madaniyatlarda jasadni yoqish odatiy hol."],
      ['deceased', 'noun', 'marhum', 'The deceased left no will.', 'Marhum vasiyatnoma qoldirmagan.'],
      ['will', 'noun', 'vasiyatnoma', 'My grandfather left me his watch in his will.', 'Bobom vasiyatnomasida menga soatini qoldirgan.'],
      ['bequeath', 'verb', 'meros qoldirmoq', 'She will bequeath her house to the museum.', 'U uyini muzeyga meros qilib qoldiradi.'],
      ['pass away', 'phrase', 'vafot etmoq (yumshoq)', 'Many people pass away peacefully in their sleep.', "Ko'p odamlar uyqusida osoyishta vafot etadi."],
      ['ripe old age', 'phrase', 'uzoq umr (keksalik)', 'She lived to a ripe old age of 98.', "U 98 yoshgacha uzoq umr ko'rdi."],
      ['fatality', 'noun', "halok bo'lgan kishi", 'There were no fatalities in the accident.', "Avariyada halok bo'lganlar yo'q."],
    ],
  },
  {
    unit: 16,
    title: 'Free time: relaxation and leisure',
    titleUz: "Bo'sh vaqt va dam olish",
    emoji: '🛋️',
    words: [
      ['couch potato', 'phrase', 'divandan turmaydigan dangasa', "Don't be a couch potato; go for a walk!", 'Divanga yopishib o\'tirma, sayrga chiq!'],
      ['culture vulture', 'phrase', 'madaniyat ishqibozi', "My aunt is a real culture vulture; she goes to every exhibition.", "Xolam haqiqiy madaniyat ishqibozi, har bir ko'rgazmaga boradi."],
      ['dabbler', 'noun', 'yuzaki havaskor', "He's a dabbler who tries everything but masters nothing.", "U hamma narsani sinab ko'radigan, lekin hech birini egallamaydigan havaskor."],
      ['chore', 'noun', 'uy yumushi', 'Washing the dishes is my least favourite chore.', "Idish yuvish — eng yoqtirmaydigan uy yumushim."],
      ['hooked on', 'phrase', '...ga mukkasidan ketgan', 'My son is hooked on video games.', "O'g'lim video o'yinlarga mukkasidan ketgan."],
      ['therapeutic', 'adjective', 'ruhan davolovchi', 'Gardening can be very therapeutic.', "Bog'dorchilik ruhan juda davolovchi bo'lishi mumkin."],
      ['shopaholic', 'noun', "xaridga o'ch odam", "She's a shopaholic and spends all her money on clothes.", "U xaridga o'ch — hamma pulini kiyimga sarflaydi."],
      ['chocaholic', 'noun', "shokoladga o'ch odam", "I'm a chocaholic; I eat chocolate every day.", "Men shokoladga o'chman, har kuni shokolad yeyman."],
      ['amateur', 'adjective', 'havaskor', "He's an amateur photographer.", 'U havaskor fotograf.'],
      ['pastime', 'noun', "bo'sh vaqt mashg'uloti", 'Fishing is his favourite pastime.', "Baliq ovlash — uning sevimli mashg'uloti."],
      ['unwind', 'verb', "bo'shashib dam olmoq", 'I like to unwind with a book after work.', "Ishdan keyin kitob bilan dam olishni yoqtiraman."],
      ['fruitful', 'adjective', 'samarali', 'It was a fruitful afternoon; I finished the whole garden.', "Samarali tushlikdan keyingi vaqt bo'ldi — butun bog'ni tugatdim."],
      ['avid', 'adjective', 'ishqiboz, ashaddiy', "She's an avid reader.", 'U ashaddiy kitobxon.'],
    ],
  },
  {
    unit: 17,
    title: 'All the rage: clothes and fashion',
    titleUz: 'Kiyim va moda',
    emoji: '👗',
    words: [
      ['attire', 'noun', 'kiyim (rasmiy)', 'Formal attire is required at the dinner.', 'Kechki ovqatga rasmiy kiyim talab qilinadi.'],
      ['outfit', 'noun', "libos (to'liq kiyim)", 'She bought a new outfit for the wedding.', "U to'y uchun yangi libos sotib oldi."],
      ['chic', 'adjective', 'nafis, zamonaviy', 'She always looks chic.', "U doim nafis ko'rinadi."],
      ['frumpy', 'adjective', 'eskicha, jozibasiz (kiyim)', 'That dress makes her look frumpy.', "O'sha ko'ylak uni eskicha ko'rsatadi."],
      ['skimpy', 'adjective', 'juda qisqa, ochiq', 'She wore a skimpy dress to the party.', "U bazmga juda qisqa ko'ylak kiyib bordi."],
      ['clingy', 'adjective', 'tanaga yopishadigan', "I don't like clingy fabrics in summer.", 'Yozda tanaga yopishadigan matolarni yoqtirmayman.'],
      ['made-to-measure', 'adjective', "buyurtma bo'yicha tikilgan", 'He wears made-to-measure suits.', "U buyurtma bo'yicha tikilgan kostyumlar kiyadi."],
      ['off the peg', 'phrase', 'tayyor (kiyim)', 'I usually buy clothes off the peg.', 'Odatda tayyor kiyim sotib olaman.'],
      ['dress code', 'phrase', 'kiyinish qoidasi', 'The office has a strict dress code.', "Ofisda kiyinish qoidalari qat'iy."],
      ['smart-casual', 'adjective', 'yarim rasmiy (kiyim)', 'The dress code for the party is smart-casual.', 'Bazmning kiyinish qoidasi — yarim rasmiy.'],
      ['trend-setter', 'noun', 'moda boshlovchisi', "She's a trend-setter; others copy her style.", 'U moda boshlovchisi, boshqalar uning uslubini takrorlaydi.'],
      ['slave to fashion', 'phrase', 'modaning quli', "He's a slave to fashion and buys every new trend.", 'U modaning quli — har bir yangilikni sotib oladi.'],
      ['must-have', 'noun', 'albatta bo\'lishi kerak bo\'lgan narsa', 'This bag is the must-have item of the season.', 'Bu sumka — mavsumning eng kerakli buyumi.'],
      ['all the rage', 'phrase', 'juda urfda', 'Wide trousers are all the rage this year.', 'Bu yil keng shimlar juda urfda.'],
      ['dolled up', 'phrase', 'yasangan, bezangan', 'She got all dolled up for the party.', 'U bazmga yaxshilab yasandi.'],
      ['up-to-the-minute', 'adjective', "eng so'nggi", 'The magazine has up-to-the-minute fashion news.', "Jurnalda eng so'nggi moda yangiliklari bor."],
      ['fabric', 'noun', 'mato', 'This fabric is soft and light.', 'Bu mato yumshoq va yengil.'],
      ['accessory', 'noun', 'aksessuar', 'A scarf is a useful accessory.', 'Sharf — foydali aksessuar.'],
    ],
  },
  {
    unit: 18,
    title: 'Home styles, lifestyles',
    titleUz: 'Uy-joy va turmush tarzi',
    emoji: '🏙️',
    words: [
      ['penthouse', 'noun', 'penthaus (tomdagi hashamatli kvartira)', 'They live in a luxury penthouse.', 'Ular hashamatli penthausda yashaydi.'],
      ['tower block', 'phrase', "ko'p qavatli uy", 'He grew up in a tower block in the city.', "U shahardagi ko'p qavatli uyda o'sgan."],
      ['high-rise', 'adjective', 'baland qavatli', 'The city is full of high-rise buildings.', "Shahar baland qavatli binolarga to'la."],
      ['council housing', 'phrase', 'ijtimoiy (davlat) uylar', 'Many families live in council housing.', "Ko'p oilalar ijtimoiy uylarda yashaydi."],
      ['granny flat', 'phrase', 'qariyalar uchun alohida kichik uy', 'They built a granny flat for her mother.', 'Ular onasi uchun alohida kichik uy qurishdi.'],
      ['hovel', 'noun', 'kulba (yomon uy)', 'They lived in a tiny hovel with no electricity.', "Ular elektr yo'q kichkina kulbada yashashgan."],
      ['furnished', 'adjective', 'mebelli', 'We rented a furnished flat.', 'Mebelli kvartira ijaraga oldik.'],
      ['unfurnished', 'adjective', 'mebelsiz', 'The flat is unfurnished, so we need to buy a bed.', 'Kvartira mebelsiz, karavot sotib olishimiz kerak.'],
      ['make yourself at home', 'phrase', "o'z uyingizdek his qiling", 'Come in and make yourself at home.', "Kiring, o'z uyingizdek his qiling."],
      ["a dog's life", 'phrase', "og'ir, azobli hayot", "Working seven days a week is a dog's life.", "Haftada yetti kun ishlash — it hayoti."],
      ['breathe new life into', 'phrase', 'yangi hayot baxsh etmoq', 'The festival could breathe new life into the town.', 'Festival shaharga yangi hayot baxsh etishi mumkin.'],
      ['home truth', 'phrase', 'achchiq haqiqat (shaxsiy)', "It's time someone told him a few home truths.", 'Kimdir unga bir necha achchiq haqiqatni aytish vaqti keldi.'],
      ['household name', 'phrase', 'hammaga tanish nom', 'The actor became a household name.', 'Aktyor hammaga tanish nomga aylandi.'],
      ['life in the fast lane', 'phrase', 'shiddatli hayot', 'He enjoys life in the fast lane.', 'U shiddatli hayotdan zavqlanadi.'],
      ['nothing to write home about', 'phrase', 'maqtagudek emas', 'The food was nothing to write home about.', 'Ovqat unchalik ham maqtagudek emas edi.'],
      ['matter of life and death', 'phrase', 'hayot-mamot masalasi', "Hurry up, it's a matter of life and death!", 'Shoshil, bu hayot-mamot masalasi!'],
    ],
  },
  {
    unit: 19,
    title: 'Socialising and networking',
    titleUz: 'Davra va aloqalar',
    emoji: '🥂',
    words: [
      ['networking', 'noun', "(kasbiy) aloqalar o'rnatish", 'Conferences are good for networking.', "Konferensiyalar aloqalar o'rnatish uchun yaxshi."],
      ['hobnob', 'verb', '(yuqori tabaqa bilan) aralashmoq', 'He likes to hobnob with celebrities.', 'U mashhurlar bilan aralashishni yoqtiradi.'],
      ['rub shoulders with', 'phrase', "(mashhurlar bilan) yonma-yon bo'lmoq", 'At the festival you can rub shoulders with film stars.', "Festivalda kino yulduzlari bilan yonma-yon bo'lishingiz mumkin."],
      ['hang out', 'phrase', "(do'stlar bilan) vaqt o'tkazmoq", 'We usually hang out at the café after school.', "Odatda maktabdan keyin kafeda vaqt o'tkazamiz."],
      ['socialise', 'verb', 'davraga qo\'shilmoq, muloqot qilmoq', "I don't have much time to socialise.", 'Odamlar bilan muloqot qilishga vaqtim kam.'],
      ['clique', 'noun', 'yopiq guruhcha', 'The office is full of cliques.', "Ofis guruhchalarga to'la."],
      ['party animal', 'phrase', 'bazm ishqibozi', "He's a real party animal.", 'U haqiqiy bazm ishqibozi.'],
      ['housewarming', 'noun', "uy to'yi (yangi uyga ko'chganda)", "We're having a housewarming party on Saturday.", "Shanba kuni uy to'yi qilyapmiz."],
      ['hen night', 'phrase', "qizlar oqshomi (to'y oldidan)", 'Her friends organised a hen night before the wedding.', "Do'stlari to'ydan oldin qizlar oqshomini uyushtirishdi."],
      ['stag party', 'phrase', "yigitlar oqshomi (to'y oldidan)", "The groom's friends planned a stag party.", "Kuyovning do'stlari yigitlar oqshomini rejalashtirishdi."],
      ['fancy dress', 'phrase', 'karnaval kostyumi', 'Everyone came in fancy dress.', 'Hamma karnaval kostyumida keldi.'],
      ['black-tie', 'adjective', 'rasmiy (smoking bilan)', "It's a black-tie event, so wear a suit.", 'Bu rasmiy tadbir, kostyum kiying.'],
      ['outstay your welcome', 'phrase', "mehmondorchilikni cho'zmoq", "Don't outstay your welcome; leave before midnight.", "Mehmondorchilikni cho'zma, yarim tundan oldin ket."],
    ],
  },
  {
    unit: 20,
    title: 'The performance arts: reviews and critiques',
    titleUz: "Sahna san'ati: taqriz va tanqid",
    emoji: '🎟️',
    words: [
      ['gripping', 'adjective', 'maroqli', "The novel was so gripping I couldn't put it down.", "Roman shunchalik maroqli ediki, qo'ldan qo'ya olmadim."],
      ['hilarious', 'adjective', "o'ta kulgili", 'The comedy was absolutely hilarious.', 'Komediya juda kulgili edi.'],
      ['harrowing', 'adjective', 'qalbni ezadigan', "It's a harrowing film about war.", 'Bu urush haqidagi qalbni ezadigan film.'],
      ['tedious', 'adjective', "zerikarli, cho'zilib ketgan", 'The second half of the play was tedious.', 'Spektaklning ikkinchi yarmi zerikarli edi.'],
      ['hackneyed', 'adjective', 'siyqasi chiqqan', 'The plot was full of hackneyed ideas.', "Syujet siyqasi chiqqan g'oyalarga to'la edi."],
      ['overrated', 'adjective', 'ortiqcha maqtalgan', 'I think that film is overrated.', "Menimcha, o'sha film ortiqcha maqtalgan."],
      ['flop', 'noun', 'muvaffaqiyatsiz asar', 'The musical was a complete flop.', 'Myuzikl butunlay muvaffaqiyatsiz chiqdi.'],
      ['standing ovation', 'phrase', 'tik turib olqish', 'The singer received a standing ovation.', "Qo'shiqchini tik turib olqishlashdi."],
      ['encore', 'noun', 'bis (qayta ijro)', 'The audience shouted for an encore.', 'Tomoshabinlar «bis» deb baqirishdi.'],
      ['rehearsal', 'noun', 'repetitsiya', 'The final rehearsal is tomorrow.', "So'nggi repetitsiya ertaga."],
      ['audition', 'noun', 'aktyorlik sinovi', 'She had an audition for a part in the film.', "U filmdagi rol uchun sinovdan o'tdi."],
      ['typecast', 'adjective', 'bir xil rolga bog\'lanib qolgan', 'He was typecast as a villain.', 'Uni doim yovuz rolga tanlashardi.'],
      ['miscast', 'adjective', 'rolga mos tushmagan', 'The young actor was miscast as the king.', 'Yosh aktyor qirol roliga mos tushmagan edi.'],
      ['masterpiece', 'noun', 'durdona asar', 'The Mona Lisa is a masterpiece.', 'Mona Liza — durdona asar.'],
      ['portrayal', 'noun', '(rol) talqini', 'His portrayal of Navoi was very moving.', "Uning Navoiy obrazi talqini juda ta'sirli edi."],
      ['up-and-coming', 'adjective', 'istiqbolli', "She's an up-and-coming young director.", 'U istiqbolli yosh rejissyor.'],
      ['pan', 'verb', 'qattiq tanqid qilmoq', 'Critics panned the new film.', 'Tanqidchilar yangi filmni qattiq tanqid qilishdi.'],
    ],
  },
];
