/**
 * Advanced (C1), 21–40-unit'lar. Tamoyillar — elementary.js va advanced.js
 * dagi izohlarga qarang.
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 21,
    title: 'The visual arts',
    titleUz: "Tasviriy san'at",
    emoji: '🖼️',
    words: [
      ['depict', 'verb', 'tasvirlamoq', 'The painting depicts a market in Samarkand.', 'Rasmda Samarqanddagi bozor tasvirlangan.'],
      ['portray', 'verb', 'gavdalantirmoq', 'The artist portrays women as strong and proud.', "Rassom ayollarni kuchli va g'ururli qilib gavdalantiradi."],
      ['evocative', 'adjective', '(xotira, his) uyg\'otuvchi', 'The photos are very evocative of the 1970s.', 'Suratlar 1970-yillarni yorqin eslatadi.'],
      ['exquisite', 'adjective', "o'ta nafis", 'The mosque has exquisite tilework.', 'Masjidning nafis koshinkorligi bor.'],
      ['highbrow', 'adjective', 'yuqori saviyali (intellektual)', 'The magazine is too highbrow for me.', 'Jurnal men uchun juda yuqori saviyali.'],
      ['lowbrow', 'adjective', 'past saviyali, yengil', 'He enjoys lowbrow comedy.', 'U yengil, oddiy komediyalarni yoqtiradi.'],
      ['thought-provoking', 'adjective', "o'ylantiradigan", "It's a thought-provoking exhibition.", "Bu o'ylantiradigan ko'rgazma."],
      ['intriguing', 'adjective', 'qiziqtiradigan, sirli', 'The painting has an intriguing history.', 'Rasmning qiziq tarixi bor.'],
      ['dreary', 'adjective', "ma'yus, zerikarli", 'The landscape was grey and dreary.', 'Manzara kulrang va ma\'yus edi.'],
      ['pedestrian', 'adjective', 'ilhomsiz, oddiy', 'His paintings are rather pedestrian.', 'Uning rasmlari ancha ilhomsiz.'],
      ['priceless', 'adjective', 'bebaho', 'The museum has a priceless collection of ancient coins.', "Muzeyda qadimiy tangalarning bebaho to'plami bor."],
      ['worthless', 'adjective', 'qadrsiz, arzimas', 'The painting turned out to be worthless.', "Rasm qadrsiz bo'lib chiqdi."],
      ['skilful', 'adjective', 'mohir', 'She is a skilful painter.', 'U mohir rassom.'],
      ['motif', 'noun', 'naqsh, motiv', 'Pomegranates are a common motif in Uzbek art.', "Anor — o'zbek san'atidagi keng tarqalgan naqsh."],
      ['subject matter', 'phrase', 'mavzu, mazmun', 'The subject matter of the film is quite dark.', "Filmning mavzusi ancha og'ir."],
      ['tongue-in-cheek', 'adjective', 'yarim hazil', 'The article was written in a tongue-in-cheek style.', 'Maqola yarim hazil uslubda yozilgan.'],
      ['uninspiring', 'adjective', 'hech qanday taassurot qoldirmaydigan', 'The new building is rather uninspiring.', 'Yangi bino hech qanday taassurot qoldirmaydi.'],
    ],
  },
  {
    unit: 22,
    title: 'Talking about books',
    titleUz: 'Kitoblar haqida',
    emoji: '📖',
    words: [
      ['page-turner', 'noun', "qo'ldan qo'yib bo'lmaydigan kitob", 'Her latest thriller is a real page-turner.', "Uning so'nggi trilleri qo'ldan qo'yib bo'lmaydigan kitob."],
      ['blurb', 'noun', '(muqovadagi) qisqa tavsif', 'The blurb on the back made me want to read it.', "Muqova orqasidagi qisqa tavsif meni o'qishga undadi."],
      ['protagonist', 'noun', 'bosh qahramon', 'The protagonist is a young doctor.', 'Asarning bosh qahramoni — yosh shifokor.'],
      ['memoir', 'noun', 'xotiralar (kitob)', 'The singer has written a memoir.', "Qo'shiqchi xotiralar kitobi yozdi."],
      ['anthology', 'noun', "antologiya, to'plam", "It's an anthology of Uzbek poetry.", "Bu o'zbek she'riyati antologiyasi."],
      ['poignant', 'adjective', "yurakni o'rtaydigan", "It's a poignant story about a lost child.", "Bu yo'qolgan bola haqidagi yurakni o'rtaydigan hikoya."],
      ['chilling', 'adjective', 'tuklarni tikka qiladigan', 'The ending of the book is chilling.', 'Kitobning oxiri tuklarni tikka qiladi.'],
      ['compelling', 'adjective', 'ishonarli, kuchli', 'The book makes a compelling argument.', 'Kitob ishonarli dalil keltiradi.'],
      ['enigmatic', 'adjective', 'jumboqli', 'The hero is an enigmatic figure.', 'Qahramon — jumboqli shaxs.'],
      ['macabre', 'adjective', "qo'rqinchli-g'alati (o'lim bilan bog'liq)", 'He has a macabre sense of humour.', "Uning hazil tuyg'usi qo'rqinchli-g'alati."],
      ['wry', 'adjective', 'kinoyali', 'She gave a wry smile.', 'U kinoyali jilmaydi.'],
      ['insight', 'noun', 'chuqur tushuncha', 'The book gives a fascinating insight into village life.', 'Kitob qishloq hayotini chuqur tushunishga imkon beradi.'],
      ['readership', 'noun', "o'quvchilar auditoriyasi", 'The newspaper has a large readership.', "Gazetaning o'quvchilari ko'p."],
      ['eponymous', 'adjective', 'nomdosh (asar nomi berilgan)', "The eponymous hero of 'Hamlet' is a prince.", "«Hamlet»ning nomdosh qahramoni — shahzoda."],
      ['lightweight', 'adjective', 'yengil (jiddiy emas)', "It's a lightweight novel, perfect for the beach.", "Bu sohilda o'qish uchun yengil roman."],
      ['informative', 'adjective', "ma'lumotli", 'The guidebook is very informative.', "Qo'llanma juda ma'lumotli."],
      ['manual', 'noun', "qo'llanma (texnik)", 'Read the instruction manual first.', "Avval foydalanish qo'llanmasini o'qing."],
    ],
  },
  {
    unit: 23,
    title: 'Food: a recipe for disaster',
    titleUz: 'Oziq-ovqat va sog\'lom ovqatlanish',
    emoji: '🥕',
    words: [
      ['additive', 'noun', "(kimyoviy) qo'shimcha", 'This yoghurt contains no additives.', "Bu yogurtda hech qanday qo'shimcha yo'q."],
      ['preservative', 'noun', 'konservant', 'Fresh bread has no preservatives.', "Yangi nonda konservant bo'lmaydi."],
      ['free-range', 'adjective', 'erkin boqilgan (tovuq)', 'We only buy free-range eggs.', 'Biz faqat erkin boqilgan tovuqlar tuxumini olamiz.'],
      ['gluten-free', 'adjective', 'glyutensiz', 'Do you have any gluten-free bread?', 'Glyutensiz noningiz bormi?'],
      ['allergy', 'noun', 'allergiya', 'I have an allergy to nuts.', "Menda yong'oqqa allergiya bor."],
      ['convenience food', 'phrase', 'yarim tayyor ovqat', 'Convenience food is quick but often unhealthy.', "Yarim tayyor ovqat tez, lekin ko'pincha zararli."],
      ['fair trade', 'phrase', 'adolatli savdo', 'We buy fair trade coffee.', 'Biz adolatli savdo belgisi bor qahvani olamiz.'],
      ['nutrition', 'noun', 'oziqlanish', 'Good nutrition is essential for children.', "To'g'ri oziqlanish bolalar uchun muhim."],
      ['wholesome', 'adjective', "to'yimli va foydali", 'My grandmother cooks simple, wholesome food.', "Buvim oddiy, to'yimli va foydali ovqat pishiradi."],
      ['unprocessed', 'adjective', 'qayta ishlanmagan', 'Try to eat more unprocessed food.', "Qayta ishlanmagan oziq-ovqatni ko'proq yeyishga harakat qil."],
      ['stew', 'noun', 'dimlama', 'Lamb stew is perfect on a cold day.', "Qo'y go'shtli dimlama sovuq kunda ayni muddao."],
      ['recipe', 'noun', 'retsept', 'Can you give me the recipe for this cake?', 'Bu tortning retseptini bera olasizmi?'],
      ['half-baked', 'adjective', "chala o'ylangan", "That's a half-baked idea.", "Bu chala o'ylangan fikr."],
      ['not my cup of tea', 'phrase', "didimga to'g'ri kelmaydi", 'Opera is not my cup of tea.', "Opera mening didimga to'g'ri kelmaydi."],
      ['cook up', 'phrase', "(bahona) to'qib chiqarmoq", "Don't cook up a story; tell the truth.", "Hikoya to'qima, rostini ayt."],
      ['juicy', 'adjective', 'sersuv, shirali', 'These oranges are very juicy.', 'Bu apelsinlar juda sersuv.'],
    ],
  },
  {
    unit: 24,
    title: "Dinner's on me: entertaining and eating out",
    titleUz: 'Mehmondorchilik va restoran',
    emoji: '🍷',
    words: [
      ['nibbles', 'noun', 'gazaklar', "We'll have some nibbles before dinner.", 'Kechki ovqatdan oldin gazak qilamiz.'],
      ['grab a bite', 'phrase', 'tezgina tamaddi qilmoq', "Let's grab a bite before the film.", 'Filmdan oldin tezgina tamaddi qilaylik.'],
      ['split the bill', 'phrase', "hisobni bo'lishmoq", 'Shall we split the bill?', "Hisobni bo'lishamizmi?"],
      ['teetotal', 'adjective', 'spirtli ichimlik ichmaydigan', 'My father is teetotal.', 'Otam spirtli ichimlik ichmaydi.'],
      ['portion', 'noun', 'porsiya', 'The portions in this restaurant are huge.', 'Bu restoranda porsiyalar juda katta.'],
      ['fussy', 'adjective', 'injiq (ovqat tanlaydigan)', 'My son is a fussy eater.', "O'g'lim ovqat tanlaydi."],
      ['calorie-conscious', 'adjective', 'kaloriyasini hisoblaydigan', "If you're calorie-conscious, try the salad.", "Agar kaloriyani hisoblasangiz, salatni tatib ko'ring."],
      ['dietary requirements', 'phrase', 'parhez talablari', 'Please tell us about any dietary requirements.', 'Iltimos, parhez talablaringiz haqida bizga ayting.'],
      ['overbearing', 'adjective', 'hukmfarmo', 'Her overbearing mother controls everything.', 'Uning hukmfarmo onasi hamma narsani nazorat qiladi.'],
      ['impeccable', 'adjective', "a'lo, bekamu ko'st", 'The service was impeccable.', "Xizmat bekamu ko'st edi."],
      ['courteous', 'adjective', 'odobli', 'The waiters were courteous and helpful.', 'Ofitsiantlar odobli va yordamga tayyor edi.'],
      ['take pot luck', 'phrase', 'nima bor bo\'lsa shu bilan kifoyalanmoq', "Come for dinner, but you'll have to take pot luck.", "Kechki ovqatga kel, lekin nima bor bo'lsa shuni yeysan."],
      ['dinner party', 'phrase', 'ziyofat (kechki)', "We're having a dinner party on Friday.", 'Juma kuni ziyofat qilyapmiz.'],
      ['off-putting', 'adjective', "ko'ngilni sovitadigan", 'The smell was a bit off-putting.', "Hid biroz ko'ngilni aynitardi."],
      ['sluggish', 'adjective', 'lanj, sust', 'I always feel sluggish after a big meal.', "Katta ovqatdan keyin doim o'zimni lanj his qilaman."],
      ["it's on me", 'phrase', "hisob mendan (men to'layman)", "Put your money away; it's on me.", "Pulingni olib qo'y, hisob mendan."],
    ],
  },
  {
    unit: 25,
    title: 'On the road: traffic and driving',
    titleUz: "Yo'lda: transport va haydash",
    emoji: '🚗',
    words: [
      ['congestion', 'noun', 'tirbandlik (rasmiy)', 'Congestion in the city centre is getting worse.', 'Shahar markazidagi tirbandlik kuchaymoqda.'],
      ['tailback', 'noun', 'uzun tirbandlik (navbat)', "There's a five-kilometre tailback on the motorway.", 'Avtomagistralda besh kilometrlik tirbandlik bor.'],
      ['pile-up', 'noun', 'zanjirli avariya', 'Fog caused a pile-up involving twenty cars.', "Tuman yigirma mashina ishtirokidagi zanjirli avariyaga sabab bo'ldi."],
      ['head-on', 'adjective', 'peshonama-peshona (to\'qnashuv)', 'There was a head-on collision on the bridge.', "Ko'prikda peshonama-peshona to'qnashuv bo'ldi."],
      ['hit-and-run', 'adjective', 'urib qochib ketgan', 'The police are looking for a hit-and-run driver.', 'Politsiya urib qochib ketgan haydovchini qidirmoqda.'],
      ['road rage', 'phrase', "yo'ldagi g'azab (haydovchilar)", 'Road rage is a growing problem.', "Yo'ldagi g'azab o'sib borayotgan muammo."],
      ['reckless', 'adjective', 'ehtiyotsiz, beparvo', 'He was fined for reckless driving.', 'U ehtiyotsiz haydagani uchun jarimaga tortildi.'],
      ['skid', 'verb', 'sirpanib ketmoq', 'The car skidded on the ice.', 'Mashina muzda sirpanib ketdi.'],
      ['breathalyser', 'noun', 'alkotester', 'The police asked him to take a breathalyser test.', "Politsiya undan alkotester sinovidan o'tishni so'radi."],
      ['drink-driving', 'noun', 'mast holda haydash', 'Drink-driving is a serious crime.', "Mast holda haydash — og'ir jinoyat."],
      ['toll', 'noun', "yo'l haqi", 'You have to pay a toll to use this road.', "Bu yo'ldan foydalanish uchun yo'l haqi to'lash kerak."],
      ['right of way', 'phrase', "o'tishda ustunlik", 'Pedestrians have the right of way here.', "Bu yerda piyodalar o'tishda ustunlikka ega."],
      ['roadworthy', 'adjective', "yo'lga yaroqli", 'Is your car roadworthy?', "Mashinangiz yo'lga yaroqlimi?"],
      ['clamp', 'verb', "g'ildirakka qulf qo'ymoq", 'My car was clamped for illegal parking.', "Noqonuniy to'xtaganim uchun mashinamga qulf qo'yishdi."],
      ['give way', 'phrase', "yo'l bermoq", 'You must give way to traffic from the right.', "O'ngdan kelayotgan transportga yo'l berishingiz kerak."],
      ['jump the lights', 'phrase', "qizil chiroqqa o'tib ketmoq", 'Never jump the lights, even at night.', "Hatto kechasi ham qizil chiroqqa o'tmang."],
      ['exhaust fumes', 'phrase', 'chiqindi gazlar', 'Exhaust fumes pollute the air.', 'Chiqindi gazlar havoni ifloslantiradi.'],
    ],
  },
  {
    unit: 26,
    title: 'Travel and accommodation',
    titleUz: 'Safar va turar joy',
    emoji: '🛏️',
    words: [
      ['full board', 'phrase', "to'liq pansion (3 mahal ovqat)", 'The price includes full board.', "Narxga to'liq pansion kiradi."],
      ['half board', 'phrase', 'yarim pansion (2 mahal ovqat)', 'We chose half board: breakfast and dinner.', 'Yarim pansionni tanladik: nonushta va kechki ovqat.'],
      ['all-inclusive', 'adjective', 'hammasi narxga kiritilgan', 'We booked an all-inclusive holiday.', "Hammasi narxga kiritilgan ta'til band qildik."],
      ['scheduled flight', 'phrase', 'muntazam reys', 'Scheduled flights are more expensive than charters.', 'Muntazam reyslar charterlardan qimmatroq.'],
      ['charter', 'noun', 'charter (buyurtma) reys', 'We flew on a charter to Antalya.', 'Antalyaga charter reysda uchdik.'],
      ['stopover', 'noun', "oraliq to'xtash", 'We had a stopover in Istanbul.', "Istanbulda oraliq to'xtashimiz bo'ldi."],
      ['non-refundable', 'adjective', "pulini qaytarib bo'lmaydigan", 'The ticket is non-refundable.', 'Chipta pulini qaytarib bo\'lmaydi.'],
      ['economy class', 'phrase', 'ekonom klass', 'We always fly economy class.', 'Biz doim ekonom klassda uchamiz.'],
      ['business class', 'phrase', 'biznes klass', 'Business class seats are much wider.', "Biznes klass o'rindiqlari ancha keng."],
      ['shuttle', 'noun', 'qatnov avtobusi (shattl)', 'A free shuttle runs between the airport and the hotel.', "Aeroport va mehmonxona o'rtasida bepul qatnov avtobusi yuradi."],
      ['berth', 'noun', "(poyezd, kema) yotoq o'rni", 'I slept in the top berth of the train.', "Poyezdda yuqori o'rinda uxladim."],
      ['cabin', 'noun', 'kajuta', 'Our cabin on the ship had a sea view.', 'Kemadagi kajutamizdan dengiz ko\'rinardi.'],
      ['chalet', 'noun', "tog' uychasi (shale)", 'We rented a wooden chalet in the mountains.', "Tog'da yog'och uycha ijaraga oldik."],
      ['inn', 'noun', 'kichik mehmonxona (karvonsaroy)', 'We stayed at an old inn in the village.', 'Qishloqdagi eski mehmonxonada qoldik.'],
      ['budget', 'adjective', 'arzon (byudjet)', 'Budget airlines have made travel cheaper.', 'Arzon aviakompaniyalar sayohatni arzonlashtirdi.'],
      ['cancellation', 'noun', 'bekor qilish', "There's a fee for late cancellation.", "Kech bekor qilish uchun to'lov olinadi."],
      ['value for money', 'phrase', 'narxiga arziydigan', 'The hotel was good value for money.', 'Mehmonxona narxiga arzirdi.'],
    ],
  },
  {
    unit: 27,
    title: 'Attracting tourists',
    titleUz: 'Turistlarni jalb qilish',
    emoji: '🗺️',
    words: [
      ['awe-inspiring', 'adjective', 'kishini hayratga soladigan', 'The view from the mountain was awe-inspiring.', "Tog'dan ochilgan manzara kishini hayratga solardi."],
      ['virgin', 'adjective', 'bokira (tegilmagan)', 'Much of the island is covered by virgin forest.', "Orolning ko'p qismi bokira o'rmon bilan qoplangan."],
      ['scenic', 'adjective', "go'zal manzarali", 'We took the scenic route along the coast.', "Qirg'oq bo'ylab manzarali yo'ldan bordik."],
      ['unrivalled', 'adjective', 'tengsiz', 'The city has unrivalled museums.', 'Shaharda tengsiz muzeylar bor.'],
      ['unbeatable', 'adjective', 'raqobatsiz', 'The hotel offers unbeatable prices.', 'Mehmonxona raqobatsiz narxlar taklif qiladi.'],
      ['discerning', 'adjective', 'didli, farqlay oladigan', 'The restaurant attracts discerning diners.', 'Restoran didli mijozlarni jalb qiladi.'],
      ['hordes', 'noun', "to'da-to'da (odamlar)", 'Hordes of tourists visit the Registan every summer.', "Har yozda Registonga to'da-to'da sayyohlar keladi."],
      ['ecotourism', 'noun', 'ekoturizm', 'Ecotourism helps protect nature.', 'Ekoturizm tabiatni asrashga yordam beradi.'],
      ['trek', 'noun', 'uzoq piyoda yurish', 'We went on a three-day trek in the mountains.', "Tog'larda uch kunlik piyoda yurishga chiqdik."],
      ['hike', 'verb', "piyoda sayr qilmoq (tog'da)", 'We hike in the hills every weekend.', 'Har dam olish kuni tepaliklarda piyoda sayr qilamiz.'],
      ['ramble', 'verb', '(tabiatda) sayr qilmoq', 'They like to ramble through the countryside.', 'Ular qishloq joylarda sayr qilishni yoqtiradi.'],
      ['flora and fauna', 'phrase', "o'simlik va hayvonot dunyosi", 'The region is rich in flora and fauna.', "Hudud o'simlik va hayvonot dunyosiga boy."],
      ['nature reserve', 'phrase', "qo'riqxona", 'Zaamin is a famous nature reserve.', "Zomin — mashhur qo'riqxona."],
      ['off the beaten track', 'phrase', 'odam kam boradigan (chekka)', 'We found a village off the beaten track.', 'Odam kam boradigan chekka joyda bir qishloq topdik.'],
      ['waterfront', 'noun', "sohil bo'yi", 'There are many cafés on the waterfront.', "Sohil bo'yida ko'plab kafelar bor."],
      ['paradise', 'noun', 'jannat', 'The island is a paradise for divers.', "Orol g'avvoslar uchun jannat."],
      ['recharge your batteries', 'phrase', "kuch to'plamoq", 'A week by the sea will help you recharge your batteries.', "Dengiz bo'yida bir hafta kuch to'plashingizga yordam beradi."],
      ['savour', 'verb', 'huzurlanib tatimoq', 'Savour the local food.', 'Mahalliy taomlardan huzurlaning.'],
    ],
  },
  {
    unit: 28,
    title: 'Describing the world',
    titleUz: 'Dunyo tasviri',
    emoji: '🌏',
    words: [
      ['arid', 'adjective', "qurg'oqchil", 'Much of Central Asia has an arid climate.', "Markaziy Osiyoning ko'p qismi qurg'oqchil iqlimga ega."],
      ['tundra', 'noun', 'tundra (sovuq daraxtsiz hudud)', 'Few trees grow in the tundra.', "Tundrada daraxtlar kam o'sadi."],
      ['coniferous', 'adjective', 'ignabargli', 'Coniferous trees keep their needles in winter.', "Ignabargli daraxtlar qishda ham ignalarini to'kmaydi."],
      ['deciduous', 'adjective', "bargini to'kuvchi (daraxt)", 'Deciduous trees lose their leaves in autumn.', "Bargini to'kuvchi daraxtlar kuzda yaprog'ini to'kadi."],
      ['evergreen', 'adjective', 'doim yashil', 'Pine trees are evergreen.', "Qarag'aylar doim yashil."],
      ['vegetation', 'noun', "o'simlik qoplami", 'There is little vegetation in the desert.', "Sahroda o'simlik kam."],
      ['indigenous', 'adjective', 'tub, mahalliy', 'The indigenous people of Australia are called Aborigines.', "Avstraliyaning tub aholisi aborigenlar deyiladi."],
      ['immigrant', 'noun', 'immigrant (kelgan muhojir)', 'Many immigrants came to America in the 19th century.', "XIX asrda Amerikaga ko'p immigrantlar kelgan."],
      ['emigrant', 'noun', 'emigrant (ketgan muhojir)', 'Irish emigrants settled in Boston.', 'Irlandiyalik emigrantlar Bostonga joylashgan.'],
      ['ancestor', 'noun', 'ajdod', 'My ancestors came from Bukhara.', 'Ajdodlarim Buxorodan kelgan.'],
      ['descendant', 'noun', 'avlod, zurriyot', 'He is a descendant of Amir Temur.', 'U Amir Temurning avlodi.'],
      ['settle', 'verb', 'joylashmoq (yashash uchun)', 'The family settled in Tashkent in 1950.', 'Oila 1950-yilda Toshkentga kelib joylashdi.'],
      ['prone to', 'phrase', '...ga moyil', 'This area is prone to earthquakes.', 'Bu hudud zilzilaga moyil.'],
      ['rainfall', 'noun', "yog'ingarchilik", 'The region has very low rainfall.', "Hududda yog'ingarchilik juda kam."],
      ['paddy field', 'phrase', 'sholipoya', 'Rice is grown in paddy fields.', 'Guruch sholipoyada yetishtiriladi.'],
      ['developing country', 'phrase', 'rivojlanayotgan mamlakat', 'Tourism helps a developing country to grow.', "Turizm rivojlanayotgan mamlakatning o'sishiga yordam beradi."],
    ],
  },
  {
    unit: 29,
    title: 'Weather and climate',
    titleUz: "Ob-havo va iqlim (ko'chma ma'nolar bilan)",
    emoji: '⛈️',
    words: [
      ['sweltering', 'adjective', 'dimiqtiruvchi issiq', 'It was a sweltering day in July.', 'Iyulning dimiqtiruvchi issiq kuni edi.'],
      ['chilly', 'adjective', 'salqin (sovuqroq)', "It's a bit chilly; take a jacket.", 'Biroz salqin, kurtka ol.'],
      ['clammy', 'adjective', 'nam-yopishqoq', 'His hands were cold and clammy.', "Uning qo'llari sovuq va nam-yopishqoq edi."],
      ['sultry', 'adjective', 'dim-issiq', 'It was a hot, sultry evening.', 'Issiq, dim oqshom edi.'],
      ['hazy', 'adjective', 'xira-tumanli', 'The mountains were hazy in the distance.', "Uzoqdagi tog'lar xira ko'rinardi."],
      ['breezy', 'adjective', 'shabadali', 'It was a bright, breezy day.', "Yorug', shabadali kun edi."],
      ['roasting', 'adjective', "o'ta issiq (so'zlashuv)", "It's roasting in here; open a window!", "Bu yer do'zaxdek issiq, derazani och!"],
      ['deluge', 'noun', 'sel; (xat, savol) oqimi', 'The storm brought a deluge of rain.', "Bo'ron sel kabi yomg'ir olib keldi."],
      ['prevailing wind', 'phrase', 'asosiy shamol', 'The prevailing wind here is from the west.', "Bu yerda asosiy shamol g'arbdan esadi."],
      ['whirlwind romance', 'phrase', 'shiddatli ishq', 'They married after a whirlwind romance.', 'Ular shiddatli ishqdan so\'ng turmush qurishdi.'],
      ['storm of protest', 'phrase', 'norozilik bo\'roni', 'The new tax caused a storm of protest.', "Yangi soliq norozilik bo'ronini keltirib chiqardi."],
      ['climate of fear', 'phrase', "qo'rquv muhiti", 'The dictator created a climate of fear.', "Diktator qo'rquv muhitini yaratdi."],
      ['winds of change', 'phrase', "o'zgarishlar shabadasi", 'The winds of change are blowing through the country.', "Mamlakatda o'zgarishlar shabadasi esmoqda."],
      ['snowed under', 'phrase', "ishga ko'milgan", "I'm snowed under with work this week.", "Bu hafta ishga ko'milib qoldim."],
      ['under a cloud', 'phrase', 'shubha ostida (obro\'si to\'kilgan)', 'He left the company under a cloud.', 'U kompaniyadan shubha ostida ketdi.'],
      ['thunderous applause', 'phrase', 'gulduros qarsaklar', 'The singer was greeted with thunderous applause.', "Qo'shiqchini gulduros qarsaklar bilan kutib olishdi."],
    ],
  },
  {
    unit: 30,
    title: 'Brick walls and glass ceilings',
    titleUz: "Binolar bilan bog'liq iboralar",
    emoji: '🧱',
    words: [
      ['glass ceiling', 'phrase', "ko'rinmas to'siq (martabada)", 'She was the first woman to break through the glass ceiling in the bank.', "U bankda ko'rinmas to'siqni yengib o'tgan birinchi ayol edi."],
      ['hit a brick wall', 'phrase', "boshi berk ko'chaga kirmoq", 'The negotiations hit a brick wall.', "Muzokaralar boshi berk ko'chaga kirib qoldi."],
      ['ivory tower', 'phrase', 'hayotdan uzilgan dunyo', "Academics shouldn't live in an ivory tower.", 'Olimlar hayotdan uzilgan dunyoda yashamasligi kerak.'],
      ['behind closed doors', 'phrase', 'yopiq eshiklar ortida', 'The decision was made behind closed doors.', 'Qaror yopiq eshiklar ortida qabul qilindi.'],
      ['gateway to', 'phrase', '...ga darvoza', 'Tashkent is the gateway to Central Asia.', 'Toshkent — Markaziy Osiyoga darvoza.'],
      ['through the roof', 'phrase', 'osmonga chiqib ketmoq (narx)', 'Prices have gone through the roof.', 'Narxlar osmonga chiqib ketdi.'],
      ['hit the roof', 'phrase', 'jahli chiqib ketmoq', 'My father will hit the roof when he sees this.', "Otam buni ko'rsa, jahli chiqib ketadi."],
      ['window of opportunity', 'phrase', 'imkoniyat darchasi', "There's a small window of opportunity to act.", 'Harakat qilish uchun kichik imkoniyat darchasi bor.'],
      ['tower of strength', 'phrase', 'suyanchiq, tayanch', 'My mother was a tower of strength during my illness.', "Kasalligim paytida onam menga suyanchiq bo'ldi."],
      ['come up against', 'phrase', '(qiyinchilikka) duch kelmoq', 'We may come up against some problems.', 'Ba\'zi muammolarga duch kelishimiz mumkin.'],
      ['lay the foundations', 'phrase', "poydevor qo'ymoq", 'These talks lay the foundations for peace.', "Bu muzokaralar tinchlikka poydevor qo'yadi."],
      ['cement', 'verb', 'mustahkamlamoq', 'The visit helped to cement relations between the two countries.', "Tashrif ikki mamlakat o'rtasidagi munosabatlarni mustahkamlashga yordam berdi."],
      ['pillar of society', 'phrase', 'jamiyat ustuni (hurmatli odam)', 'He was a pillar of society.', 'U jamiyatning ustuni edi.'],
      ['open doors', 'phrase', 'imkoniyat eshiklarini ochmoq', 'A good degree can open doors for you.', 'Yaxshi diplom sizga ko\'p eshiklarni ochishi mumkin.'],
    ],
  },
  {
    unit: 31,
    title: 'Taking root and reaping rewards',
    titleUz: "O'simliklar bilan bog'liq iboralar",
    emoji: '🌱',
    words: [
      ['flourish', 'verb', 'gullab-yashnamoq', 'Small businesses flourish in this area.', 'Bu hududda kichik biznes gullab-yashnaydi.'],
      ['thrive', 'verb', 'yashnamoq, rivojlanmoq', 'Cactuses thrive in hot, dry places.', "Kaktuslar issiq, quruq joylarda yaxshi o'sadi."],
      ['wither', 'verb', "so'lmoq, qurimoq", 'The plants withered in the heat.', "O'simliklar issiqda so'lib qoldi."],
      ['wilt', 'verb', 'shalvirab qolmoq', "The flowers wilt if you don't water them.", "Sug'ormasangiz, gullar shalvirab qoladi."],
      ['shrivel', 'verb', 'qurib burishmoq', 'The grapes shrivel in the sun and become raisins.', 'Uzum quyoshda qurib burishadi va mayizga aylanadi.'],
      ['sprout', 'verb', 'unib chiqmoq', 'The seeds sprout after a week.', "Urug'lar bir haftadan keyin unib chiqadi."],
      ['germinate', 'verb', "unmoq (urug')", 'Wheat seeds germinate quickly in warm soil.', "Bug'doy urug'i iliq tuproqda tez unadi."],
      ['prune', 'verb', 'butamoq', 'Prune the roses in early spring.', 'Atirgullarni erta bahorda butang.'],
      ['weed', 'noun', "begona o't", 'The garden is full of weeds.', "Bog' begona o'tlarga to'la."],
      ['reap the rewards', 'phrase', "samarasini ko'rmoq", "If you study hard now, you'll reap the rewards later.", "Hozir tirishsang, keyin samarasini ko'rasan."],
      ['grassroots', 'adjective', 'oddiy xalq darajasidagi', 'The campaign has strong grassroots support.', "Kampaniyani oddiy odamlar kuchli qo'llab-quvvatlaydi."],
      ['budding', 'adjective', "endi o'sib kelayotgan", "He's a budding artist.", "U endi o'sib kelayotgan rassom."],
      ['branch out', 'phrase', 'yangi sohaga kirmoq', 'The company plans to branch out into clothing.', 'Kompaniya kiyim sohasiga ham kirmoqchi.'],
      ['nip in the bud', 'phrase', "boshidayoq to'xtatmoq", 'Teachers try to nip in the bud any bullying.', "O'qituvchilar har qanday tazyiqni boshidayoq to'xtatishga harakat qiladi."],
      ['put down roots', 'phrase', "o'rnashib qolmoq", 'After years of travelling, they decided to put down roots in Samarkand.', "Yillar sayohatdan keyin ular Samarqandda o'rnashib qolishga qaror qilishdi."],
      ['deeply rooted', 'phrase', 'chuqur ildiz otgan', 'These traditions are deeply rooted in our culture.', "Bu an'analar madaniyatimizda chuqur ildiz otgan."],
    ],
  },
  {
    unit: 32,
    title: 'The animal kingdom',
    titleUz: 'Hayvonot olami',
    emoji: '🦁',
    words: [
      ['mammal', 'noun', 'sutemizuvchi', 'Whales are mammals, not fish.', 'Kitlar baliq emas, sutemizuvchilar.'],
      ['reptile', 'noun', 'sudraluvchi', 'Snakes and lizards are reptiles.', 'Ilon va kaltakesaklar — sudraluvchilar.'],
      ['rodent', 'noun', 'kemiruvchi', 'Mice and rats are rodents.', 'Sichqon va kalamushlar — kemiruvchilar.'],
      ['predator', 'noun', 'yirtqich', 'The lion is a powerful predator.', 'Sher — kuchli yirtqich.'],
      ['carnivore', 'noun', "go'shtxo'r", 'Wolves are carnivores.', "Bo'rilar go'shtxo'r."],
      ['herbivore', 'noun', "o'txo'r", 'Cows are herbivores.', "Sigirlar o'txo'r."],
      ['scavenger', 'noun', "o'laksaxo'r", 'Vultures are scavengers.', "Tasqaralar o'laksaxo'r qushlar."],
      ['habitat', 'noun', 'yashash muhiti', "Pollution is destroying the bird's natural habitat.", 'Ifloslanish qushning tabiiy yashash muhitini vayron qilmoqda.'],
      ['migrate', 'verb', "ko'chib o'tmoq (hayvon)", 'Many birds migrate south in winter.', "Ko'p qushlar qishda janubga uchib ketadi."],
      ['docile', 'adjective', 'yuvosh, itoatkor', 'Camels are usually docile.', 'Tuyalar odatda yuvosh.'],
      ['tame', 'adjective', "qo'lga o'rgangan", 'The deer in the park are quite tame.', "Parkdagi bug'ular ancha qo'lga o'rgangan."],
      ['domesticated', 'adjective', 'xonakilashtirilgan', 'Dogs were domesticated thousands of years ago.', 'Itlar ming yillar oldin xonakilashtirilgan.'],
      ['poacher', 'noun', 'brakonyer (noqonuniy ovchi)', 'Poachers kill elephants for their ivory.', "Brakonyerlar fillarni fil suyagi uchun o'ldiradi."],
      ['stray', 'adjective', 'daydi (hayvon)', 'The city has many stray dogs.', "Shaharda daydi itlar ko'p."],
      ['cold-blooded', 'adjective', 'sovuq qonli', 'Snakes are cold-blooded.', 'Ilonlar sovuq qonli.'],
      ['marsupial', 'noun', 'xaltali hayvon', 'The kangaroo is a marsupial.', 'Kenguru — xaltali hayvon.'],
      ['blood sport', 'phrase', 'qonli sport (hayvon ovi)', 'Many people want to ban blood sports like fox hunting.', "Ko'pchilik tulki ovi kabi qonli sportlarni taqiqlashni xohlaydi."],
    ],
  },
  {
    unit: 33,
    title: 'Our endangered world',
    titleUz: "Xavf ostidagi dunyomiz",
    emoji: '🌿',
    words: [
      ['biodiversity', 'noun', 'biologik xilma-xillik', 'Rainforests have incredible biodiversity.', "Tropik o'rmonlarda ajoyib biologik xilma-xillik bor."],
      ['deforestation', 'noun', "o'rmonlarni kesish", 'Deforestation is destroying the Amazon.', "O'rmonlarni kesish Amazonni vayron qilmoqda."],
      ['sustainable', 'adjective', 'barqaror (kelajakka zararsiz)', 'We need sustainable sources of energy.', 'Bizga barqaror energiya manbalari kerak.'],
      ['renewable', 'adjective', 'qayta tiklanadigan', 'Solar power is a renewable energy source.', 'Quyosh energiyasi — qayta tiklanadigan manba.'],
      ['deplete', 'verb', 'tugatmoq (zaxirani)', "We are depleting the Earth's resources.", 'Biz Yer resurslarini tugatmoqdamiz.'],
      ['finite', 'adjective', 'cheklangan', 'Oil is a finite resource.', 'Neft — cheklangan resurs.'],
      ['toxic', 'adjective', 'zaharli', 'The factory released toxic chemicals into the river.', 'Zavod daryoga zaharli kimyoviy moddalar chiqardi.'],
      ['contaminate', 'verb', 'ifloslantirmoq (zaharlab)', 'The water was contaminated with oil.', 'Suv neft bilan ifloslangan edi.'],
      ['pristine', 'adjective', 'ilk holatidagi, pokiza', 'The lake is surrounded by pristine forests.', "Ko'l ilk holatidagi toza o'rmonlar bilan o'ralgan."],
      ['rising sea levels', 'phrase', "dengiz sathining ko'tarilishi", 'Rising sea levels threaten coastal cities.', "Dengiz sathining ko'tarilishi qirg'oq shaharlariga tahdid solmoqda."],
      ['worst-case scenario', 'phrase', 'eng yomon ssenariy', 'In the worst-case scenario, the city could flood.', 'Eng yomon holatda shaharni suv bosishi mumkin.'],
      ['prophets of doom', 'phrase', 'vahimachilar', "The prophets of doom say it's already too late.", 'Vahimachilar allaqachon kech deyishadi.'],
      ['waste disposal', 'phrase', "chiqindilarni yo'q qilish", 'Waste disposal is a big problem for cities.', "Chiqindilarni yo'q qilish shaharlar uchun katta muammo."],
      ['exert pressure', 'phrase', "bosim o'tkazmoq", 'Environmental groups exert pressure on the government.', "Ekologik guruhlar hukumatga bosim o'tkazadi."],
      ['precious', 'adjective', 'qimmatli, noyob', 'Water is a precious resource in Central Asia.', 'Markaziy Osiyoda suv — qimmatli resurs.'],
    ],
  },
  {
    unit: 34,
    title: 'Here to help: customer service',
    titleUz: 'Mijozlarga xizmat',
    emoji: '🎧',
    words: [
      ['helpline', 'noun', 'yordam telefoni', 'Call our helpline if you have a problem.', "Muammo bo'lsa, yordam telefonimizga qo'ng'iroq qiling."],
      ['query', 'noun', "so'rov, savol", 'Our staff will answer any query.', 'Xodimlarimiz har qanday savolga javob beradi.'],
      ['backlog', 'noun', "to'planib qolgan ish", "There's a backlog of orders after the holiday.", "Bayramdan keyin buyurtmalar to'planib qolgan."],
      ['dispatch', 'verb', "jo'natmoq", 'We dispatch orders within 24 hours.', "Buyurtmalarni 24 soat ichida jo'natamiz."],
      ['prompt', 'adjective', 'tezkor', 'Thank you for your prompt reply.', 'Tezkor javobingiz uchun rahmat.'],
      ['responsive', 'adjective', 'tez javob beradigan', 'The company is very responsive to customer complaints.', 'Kompaniya mijozlar shikoyatiga tez javob beradi.'],
      ['shoddy', 'adjective', 'sifatsiz, chala', 'The repair work was shoddy.', "Ta'mirlash ishi sifatsiz edi."],
      ['substandard', 'adjective', 'talabga javob bermaydigan', 'The hotel room was substandard.', 'Mehmonxona xonasi talabga javob bermasdi.'],
      ['incompetent', 'adjective', 'layoqatsiz', 'The manager was completely incompetent.', 'Menejer butunlay layoqatsiz edi.'],
      ['impersonal', 'adjective', 'shaxssiz, sovuq', 'Online shopping can feel impersonal.', "Onlayn xarid sovuq, shaxssiz tuyulishi mumkin."],
      ['uncooperative', 'adjective', 'hamkorlikka tayyor emas', 'The staff were rude and uncooperative.', "Xodimlar qo'pol va hamkorlikka tayyor emas edi."],
      ['accommodating', 'adjective', 'yon bosuvchi, moslashuvchan', 'The hotel was very accommodating when we arrived late.', 'Kech kelganimizda mehmonxona bizga juda yon bosdi.'],
      ['in-store', 'adjective', 'do\'kon ichidagi', 'There are special in-store offers this week.', "Bu hafta do'kon ichida maxsus takliflar bor."],
      ['nationwide', 'adverb', "mamlakat bo'ylab", 'The company has 200 shops nationwide.', "Kompaniyaning mamlakat bo'ylab 200 do'koni bor."],
      ['track your order', 'phrase', 'buyurtmani kuzatmoq', 'You can track your order online.', 'Buyurtmangizni onlayn kuzatishingiz mumkin.'],
      ['get back to', 'phrase', 'keyinroq javob qaytarmoq', "I'll get back to you tomorrow.", 'Ertaga sizga javob qaytaraman.'],
    ],
  },
  {
    unit: 35,
    title: 'Authorities: customs and police',
    titleUz: 'Bojxona va politsiya',
    emoji: '👮',
    words: [
      ['surveillance', 'noun', 'kuzatuv', 'The suspect was under police surveillance.', 'Gumondor politsiya kuzatuvi ostida edi.'],
      ['CCTV', 'noun', 'videokuzatuv', 'CCTV cameras recorded the robbery.', 'Videokuzatuv kameralari talonchilikni yozib oldi.'],
      ['undercover', 'adjective', 'yashirin (ishlaydigan)', 'An undercover police officer joined the gang.', "Yashirin politsiyachi to'daga qo'shildi."],
      ['plain-clothes', 'adjective', 'fuqaro kiyimidagi', 'Two plain-clothes officers arrested him.', 'Ikki fuqaro kiyimidagi xodim uni hibsga oldi.'],
      ['search warrant', 'phrase', 'tintuv orderi', 'The police need a search warrant to enter the house.', 'Uyga kirish uchun politsiyaga tintuv orderi kerak.'],
      ['sniffer dog', 'phrase', 'iskovuch it', 'Sniffer dogs searched the luggage.', 'Iskovuch itlar yuklarni tekshirdi.'],
      ['spot check', 'phrase', 'tasodifiy tekshiruv', 'Customs officers carry out spot checks.', "Bojxona xodimlari tasodifiy tekshiruv o'tkazadi."],
      ['asylum', 'noun', 'boshpana (siyosiy)', 'He applied for political asylum.', "U siyosiy boshpana so'radi."],
      ['asylum-seeker', 'noun', "boshpana so'rovchi", 'The country accepted thousands of asylum-seekers.', "Mamlakat minglab boshpana so'rovchilarni qabul qildi."],
      ['bribery', 'noun', "poraxo'rlik", 'The official was arrested for bribery.', "Amaldor poraxo'rlik uchun hibsga olindi."],
      ['corruption', 'noun', 'korrupsiya', 'The new president promised to fight corruption.', "Yangi prezident korrupsiyaga qarshi kurashishga va'da berdi."],
      ['phishing', 'noun', 'fishing (internet firibgarligi)', 'Be careful of phishing emails asking for your password.', "Parolingizni so'raydigan fishing xatlardan ehtiyot bo'ling."],
      ['cybercrime', 'noun', 'kiberjinoyatchilik', 'Cybercrime is growing every year.', "Kiberjinoyatchilik har yili o'smoqda."],
      ['facial recognition', 'phrase', 'yuzni tanish', 'The airport uses facial recognition technology.', 'Aeroport yuzni tanish texnologiyasidan foydalanadi.'],
      ['enforce', 'verb', 'ijro etmoq (qonunni)', 'The police must enforce the law.', 'Politsiya qonunni ijro etishi kerak.'],
      ['persecution', 'noun', "ta'qib (siyosiy, diniy)", 'They fled their country to escape persecution.', "Ular ta'qibdan qochish uchun mamlakatidan ketishdi."],
      ['customs declaration', 'phrase', 'bojxona deklaratsiyasi', 'Fill in the customs declaration form.', "Bojxona deklaratsiyasini to'ldiring."],
    ],
  },
  {
    unit: 36,
    title: 'Beliefs',
    titleUz: "E'tiqod va qarashlar",
    emoji: '🕌',
    words: [
      ['adherent', 'noun', "e'tiqodchi, tarafdor", 'The religion has millions of adherents.', "Bu dinning millionlab e'tiqodchilari bor."],
      ['tenet', 'noun', "asosiy qoida (ta'limotda)", 'Honesty is a basic tenet of Islam.', 'Halollik — islomning asosiy qoidalaridan biri.'],
      ['proponent', 'noun', "(g'oya) himoyachisi", 'He is a leading proponent of free education.', "U bepul ta'limning yetakchi himoyachisi."],
      ['plausible', 'adjective', 'ishonarli, haqiqatga yaqin', 'Her explanation sounds plausible.', 'Uning izohi ishonarli tuyuladi.'],
      ['implausible', 'adjective', "ishonib bo'lmaydigan", 'The story was completely implausible.', "Hikoya mutlaqo ishonib bo'lmaydigan edi."],
      ['credible', 'adjective', 'ishonchli', 'We need credible evidence.', 'Bizga ishonchli dalil kerak.'],
      ['incredulous', 'adjective', 'ishonqiramaydigan', 'She gave me an incredulous look.', 'U menga ishonqiramay qaradi.'],
      ['presume', 'verb', 'taxmin qilmoq', "I presume you've heard the news.", "Xabarni eshitgansiz deb o'ylayman."],
      ['subjective', 'adjective', "sub'ektiv", 'Taste in art is very subjective.', "San'atdagi did juda sub'ektiv."],
      ['objective', 'adjective', "xolis, ob'ektiv", 'Journalists should try to be objective.', "Jurnalistlar xolis bo'lishga harakat qilishi kerak."],
      ['eradicate', 'verb', "tag-tomiri bilan yo'q qilmoq", 'The disease has been eradicated in most countries.', "Kasallik ko'p mamlakatlarda butunlay yo'qotilgan."],
      ['justify', 'verb', 'oqlamoq, asoslamoq', 'How can you justify spending so much money?', 'Shuncha pul sarflashni qanday oqlaysan?'],
      ['with a pinch of salt', 'phrase', 'ehtiyotkorlik bilan (ishonmasdan)', 'Take everything he says with a pinch of salt.', 'Uning har gapiga ehtiyotkorlik bilan qara.'],
      ['benefit of the doubt', 'phrase', 'shubhani uning foydasiga hal qilish', "I'll give him the benefit of the doubt this time.", 'Bu safar shubhani uning foydasiga hal qilaman.'],
      ['attribute', 'verb', "...ga bog'lamoq, nisbat bermoq", 'Scientists attribute the rise in temperature to pollution.', "Olimlar haroratning oshishini ifloslanishga bog'laydi."],
      ['reactionary', 'adjective', "reaksion (o'zgarishga qarshi)", 'His views are rather reactionary.', 'Uning qarashlari ancha reaksion.'],
    ],
  },
  {
    unit: 37,
    title: 'Festivals in their cultural context',
    titleUz: 'Bayramlar va madaniyat',
    emoji: '🎊',
    words: [
      ['commemorate', 'verb', 'xotirlamoq, yodga olmoq', 'A statue was built to commemorate the poet.', "Shoirni xotirlash uchun haykal o'rnatildi."],
      ['centenary', 'noun', 'yuz yillik (yubiley)', 'The university celebrates its centenary next year.', 'Universitet kelasi yili yuz yilligini nishonlaydi.'],
      ['ceremonial', 'adjective', 'tantanali, marosimga oid', 'The king wore his ceremonial robes.', 'Qirol tantanali libosini kiygan edi.'],
      ['festive', 'adjective', 'bayramona', 'The streets have a festive atmosphere.', "Ko'chalarda bayramona kayfiyat bor."],
      ['festivity', 'noun', 'bayram shodiyonasi', 'The festivities lasted all week.', 'Bayram shodiyonalari butun hafta davom etdi.'],
      ['flamboyant', 'adjective', "yorqin, ko'zga tashlanadigan", 'The dancers wore flamboyant costumes.', "Raqqoslar yorqin, ko'zga tashlanadigan liboslarda edi."],
      ['raucous', 'adjective', 'shovqin-suronli', 'The party was loud and raucous.', 'Bazm shovqin-suronli edi.'],
      ['spectacle', 'noun', "tomosha (ko'z quvnatuvchi)", 'The fireworks were an amazing spectacle.', 'Mushakbozlik ajoyib tomosha edi.'],
      ['spectacular', 'adjective', "g'oyat ta'sirli", 'The opening ceremony was spectacular.', "Ochilish marosimi g'oyat ta'sirli edi."],
      ['pagan', 'adjective', 'butparastlikka oid', 'The festival has pagan origins.', 'Bayramning ildizlari butparastlik davriga borib taqaladi.'],
      ['superstitious', 'adjective', 'xurofiy', 'My grandmother is very superstitious.', 'Buvim juda xurofotga ishonadi.'],
      ['sombre', 'adjective', "sokin-g'amgin", 'The mood at the ceremony was sombre.', "Marosimdagi kayfiyat sokin-g'amgin edi."],
      ['parade', 'noun', 'parad, tantanali yurish', "There's a big parade on Independence Day.", "Mustaqillik kunida katta parad bo'ladi."],
      ['feast', 'noun', 'ziyofat, bazm', 'The wedding feast lasted until midnight.', "To'y ziyofati yarim tungacha davom etdi."],
      ['trace back', 'phrase', '(kelib chiqishini) aniqlamoq', 'Historians trace back this festival to ancient Persia.', "Tarixchilar bu bayramning kelib chiqishini qadimgi Forsga bog'laydi."],
      ['renewal', 'noun', 'yangilanish', 'Navruz is a festival of renewal.', "Navro'z — yangilanish bayrami."],
    ],
  },
  {
    unit: 38,
    title: 'Talking about language',
    titleUz: 'Til haqida gapirish',
    emoji: '🗣️',
    words: [
      ['jargon', 'noun', 'kasbiy atamalar (jargon)', 'Doctors often use medical jargon.', "Shifokorlar ko'pincha tibbiy atamalardan foydalanadi."],
      ['coin', 'verb', "(yangi so'z) yasamoq", "Who coined the word 'selfie'?", "«Selfie» so'zini kim o'ylab topgan?"],
      ['obsolete', 'adjective', 'eskirgan', 'This word is now obsolete.', "Bu so'z endi eskirgan."],
      ['literal', 'adjective', "so'zma-so'z", "The literal meaning of 'breakfast' is 'to break a fast'.", "«Breakfast»ning so'zma-so'z ma'nosi — «ro'zani ochish»."],
      ['metaphorical', 'adjective', 'majoziy', 'He used the word in a metaphorical sense.', "U so'zni majoziy ma'noda ishlatdi."],
      ['eloquent', 'adjective', 'notiq, notiqona', 'She gave an eloquent speech.', "U notiqona nutq so'zladi."],
      ['articulate', 'adjective', 'fikrini aniq ifodalaydigan', 'He is very articulate and explains things clearly.', "U fikrini aniq ifodalaydi va narsalarni tushunarli tushuntiradi."],
      ['inarticulate', 'adjective', 'fikrini ifodalay olmaydigan', 'He was inarticulate with anger.', 'Jahldan u fikrini ifodalay olmay qoldi.'],
      ['succinct', 'adjective', "lo'nda", 'Please give a succinct answer.', "Iltimos, lo'nda javob bering."],
      ['lost for words', 'phrase', "so'z topolmay qolmoq", 'I was lost for words when I heard the news.', "Xabarni eshitib, gapirishga so'z topolmay qoldim."],
      ['speechless', 'adjective', 'lol, tili tutilgan', 'The beautiful view left us speechless.', "Go'zal manzara bizni lol qoldirdi."],
      ['put your foot in it', 'phrase', "noo'rin gap aytib qo'ymoq", 'Be careful not to put your foot in it when you meet her parents.', "Uning ota-onasi bilan uchrashganda noo'rin gap aytib qo'yma."],
      ['syntax', 'noun', 'sintaksis (gap tuzilishi)', 'English syntax is different from Uzbek syntax.', "Ingliz tili sintaksisi o'zbek tilinikidan farq qiladi."],
      ['usage', 'noun', "qo'llanish", 'This dictionary gives examples of usage.', "Bu lug'at qo'llanish misollarini beradi."],
      ['register', 'noun', 'nutq uslubi', 'You should use a formal register in a job application.', 'Ish arizasida rasmiy uslubdan foydalanish kerak.'],
      ['lexicon', 'noun', "lug'at tarkibi (leksika)", 'New words enter the lexicon every year.', "Har yili lug'at tarkibiga yangi so'zlar kiradi."],
    ],
  },
  {
    unit: 39,
    title: 'History: since the dawn of civilisation',
    titleUz: 'Tarix',
    emoji: '🏰',
    words: [
      ['dynasty', 'noun', 'sulola', 'The Timurid dynasty ruled for over a century.', 'Temuriylar sulolasi bir asrdan ortiq hukmronlik qildi.'],
      ['empire', 'noun', 'imperiya, saltanat', 'Amir Temur built a huge empire.', 'Amir Temur ulkan saltanat qurdi.'],
      ['reign', 'noun', 'hukmronlik', 'Many mosques were built during his reign.', 'Uning hukmronligi davrida ko\'plab masjidlar qurildi.'],
      ['monarch', 'noun', 'monarx, podsho', 'The monarch lived in a palace.', 'Monarx saroyda yashagan.'],
      ['heir', 'noun', 'merosxo\'r, taxt vorisi', 'The prince is heir to the throne.', 'Shahzoda taxt vorisi.'],
      ['successor', 'noun', 'vorisi (lavozimda)', 'Who will be the successor to the president?', 'Prezidentning vorisi kim bo\'ladi?'],
      ['conquest', 'noun', 'zabt etish', 'The conquest of Central Asia began in the 8th century.', 'Markaziy Osiyoni zabt etish VIII asrda boshlangan.'],
      ['medieval', 'adjective', "o'rta asrlarga oid", 'Khiva is a well-preserved medieval city.', "Xiva — yaxshi saqlangan o'rta asr shahri."],
      ['Renaissance', 'noun', "Uyg'onish davri", 'Leonardo da Vinci was a Renaissance artist.', "Leonardo da Vinchi Uyg'onish davri rassomi edi."],
      ['peasant', 'noun', 'dehqon (tarixiy)', 'Most people in the Middle Ages were peasants.', "O'rta asrlarda odamlarning ko'pi dehqonlar edi."],
      ['nobility', 'noun', 'zodagonlar', 'The nobility lived in large castles.', 'Zodagonlar katta qasrlarda yashagan.'],
      ['slavery', 'noun', 'qullik', 'Slavery was abolished in the 19th century.', 'Qullik XIX asrda bekor qilingan.'],
      ['merchant', 'noun', 'savdogar', 'Merchants travelled along the Silk Road.', "Savdogarlar Buyuk ipak yo'li bo'ylab sayohat qilishgan."],
      ['manuscript', 'noun', "qo'lyozma", 'The library has ancient manuscripts.', "Kutubxonada qadimiy qo'lyozmalar bor."],
      ['archaeologist', 'noun', 'arxeolog', 'Archaeologists found coins from the 5th century.', 'Arxeologlar V asrga oid tangalarni topishdi.'],
      ['cavalry', 'noun', "otliq qo'shin", 'The cavalry attacked at dawn.', "Otliq qo'shin tong otganda hujum qildi."],
      ['coronation', 'noun', 'toj kiyish marosimi', 'The coronation took place in 1953.', "Toj kiyish marosimi 1953-yilda bo'lgan."],
      ['Bronze Age', 'phrase', 'bronza davri', 'These tools date from the Bronze Age.', 'Bu qurollar bronza davriga oid.'],
    ],
  },
  {
    unit: 40,
    title: 'The haves and the have-nots',
    titleUz: 'Boylar va kambag\'allar',
    emoji: '💰',
    words: [
      ['affluent', 'adjective', 'farovon', 'They live in an affluent suburb.', 'Ular farovon shahar atrofida yashaydi.'],
      ['poverty', 'noun', 'qashshoqlik', 'Millions of people live in poverty.', 'Millionlab odamlar qashshoqlikda yashaydi.'],
      ['poverty line', 'phrase', 'qashshoqlik chegarasi', 'A quarter of the population lives below the poverty line.', "Aholining to'rtdan biri qashshoqlik chegarasidan pastda yashaydi."],
      ['destitute', 'adjective', "yo'qsil, hech narsasi yo'q", 'The war left many families destitute.', "Urush ko'p oilalarni yo'qsil qilib qo'ydi."],
      ['impoverished', 'adjective', 'qashshoqlashgan', "It's one of the most impoverished regions in the world.", 'Bu dunyodagi eng qashshoqlashgan hududlardan biri.'],
      ['deprived', 'adjective', 'nochor, imkoniyatdan mahrum', 'The charity helps deprived children.', 'Xayriya tashkiloti nochor bolalarga yordam beradi.'],
      ['malnutrition', 'noun', 'yetarli ovqatlanmaslik', 'Many children suffer from malnutrition.', "Ko'p bolalar yetarli ovqatlanmaslikdan aziyat chekadi."],
      ['sanitation', 'noun', 'sanitariya (tozalik tizimi)', 'Poor sanitation causes disease.', "Yomon sanitariya kasallikka sabab bo'ladi."],
      ['shelter', 'noun', 'boshpana', 'The refugees need food and shelter.', 'Qochoqlarga oziq-ovqat va boshpana kerak.'],
      ['on the breadline', 'phrase', "qashshoqlik bo'sag'asida", 'Many pensioners live on the breadline.', "Ko'p nafaqaxo'rlar qashshoqlik bo'sag'asida yashaydi."],
      ['make ends meet', 'phrase', 'tirikchilikni amallamoq', "It's hard to make ends meet on a low salary.", 'Kam maosh bilan tirikchilikni amallash qiyin.'],
      ['live from hand to mouth', 'phrase', 'kunini kunga ulamoq', 'Many families live from hand to mouth.', "Ko'p oilalar kunini kunga ulab yashaydi."],
      ['tighten your belt', 'phrase', 'tejab-tergab yashamoq', 'In hard times, you have to tighten your belt.', "Qiyin paytlarda tejab-tergab yashashga to'g'ri keladi."],
      ['penury', 'noun', 'nochorlik (rasmiy)', 'He died in penury.', 'U nochorlikda vafot etdi.'],
      ['dignity', 'noun', 'qadr-qimmat', 'Everyone deserves to live with dignity.', 'Har kim qadr-qimmat bilan yashashga haqli.'],
      ['super-rich', 'adjective', "o'ta boy", 'The super-rich pay very little tax.', "O'ta boylar juda kam soliq to'laydi."],
    ],
  },
];
