/**
 * Elementary, 31–45-unit'lar. Tamoyillar — elementary.js dagi izohga qarang:
 * kitobdan faqat mavzu va so'zlar; tarjima va misollar Linguist uchun yozilgan.
 *
 * 38–45 — fe'l bilan iboralar (have, go, do, make, come, take, bring, get).
 * Misollarda iboraning aynan shu shakli ishlatiladi: validator "went" ni
 * "go" ning shakli deb tanimaydi, notanish shakl esa o'quvchini ham chalg'itadi.
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 31,
    title: 'Animals',
    titleUz: 'Hayvonlar',
    emoji: '🐄',
    words: [
      ['animal', 'noun', 'hayvon', 'What is your favourite animal?', 'Sevimli hayvoningiz qaysi?'],
      ['pet', 'noun', 'uy hayvoni', 'Do you have a pet?', 'Uy hayvoningiz bormi?'],
      ['dog', 'noun', 'it', 'Our dog sleeps in the garden.', 'Itimiz hovlida uxlaydi.'],
      ['cat', 'noun', 'mushuk', 'The cat is drinking milk.', 'Mushuk sut ichyapti.'],
      ['horse', 'noun', 'ot', 'He rides a horse in the village.', 'U qishloqda ot minadi.'],
      ['cow', 'noun', 'sigir', 'The cow gives milk every day.', 'Sigir har kuni sut beradi.'],
      ['sheep', 'noun', "qo'y", 'There are many sheep in the field.', "Dalada qo'ylar ko'p."],
      ['goat', 'noun', 'echki', 'My grandmother keeps two goats.', 'Buvim ikkita echki boqadi.'],
      ['chicken', 'noun', 'tovuq', 'The chickens are in the yard.', 'Tovuqlar hovlida.'],
      ['bird', 'noun', 'qush', 'A bird is singing in the tree.', 'Daraxtda qush sayrayapti.'],
      ['lion', 'noun', 'sher', 'The lion is the king of animals.', 'Sher — hayvonlar shohi.'],
      ['tiger', 'noun', "yo'lbars", 'Tigers are big and dangerous.', "Yo'lbarslar katta va xavfli."],
      ['elephant', 'noun', 'fil', 'Elephants have very good memories.', 'Fillarning xotirasi juda yaxshi.'],
      ['monkey', 'noun', 'maymun', 'The monkeys are playing in the trees.', "Maymunlar daraxtlarda o'ynayapti."],
      ['snake', 'noun', 'ilon', "I'm afraid of snakes.", "Men ilondan qo'rqaman."],
      ['zoo', 'noun', "hayvonot bog'i", 'We took the children to the zoo.', "Bolalarni hayvonot bog'iga olib bordik."],
      ['feed', 'verb', 'boqmoq, ovqat bermoq', "Don't feed the animals!", 'Hayvonlarga ovqat bermang!'],
      ['wild animal', 'phrase', 'yovvoyi hayvon', 'A bear is a wild animal.', 'Ayiq — yovvoyi hayvon.'],
    ],
  },
  {
    unit: 32,
    title: 'Travelling',
    titleUz: 'Safar va transport',
    emoji: '✈️',
    words: [
      ['journey', 'noun', 'safar, yo\'l', 'The journey to Samarkand takes two hours by train.', 'Samarqandga poyezdda safar ikki soat davom etadi.'],
      ['ticket', 'noun', 'chipta', 'I bought a ticket online.', 'Chiptani onlayn sotib oldim.'],
      ['return ticket', 'phrase', 'borib-kelish chiptasi', 'A return ticket is cheaper.', 'Borib-kelish chiptasi arzonroq.'],
      ['single ticket', 'phrase', 'bir tomonga chipta', 'A single ticket to Bukhara, please.', 'Buxoroga bir tomonga chipta, iltimos.'],
      ['timetable', 'noun', 'jadval (qatnov)', 'Check the train timetable.', 'Poyezd jadvalini tekshir.'],
      ['seat', 'noun', "o'rindiq", 'Is this seat free?', "Bu o'rindiq bo'shmi?"],
      ['map', 'noun', 'xarita', "Let's look at the map.", 'Xaritaga qaraylik.'],
      ['arrive', 'verb', 'yetib kelmoq', 'The train arrives at ten.', "Poyezd soat o'nda yetib keladi."],
      ['leave', 'verb', "jo'nab ketmoq", 'What time does the bus leave?', "Avtobus soat nechada jo'naydi?"],
      ['check in', 'phrase', "ro'yxatdan o'tmoq (aeroportda)", 'You must check in two hours before the flight.', "Parvozdan ikki soat oldin ro'yxatdan o'tishingiz kerak."],
      ['boarding card', 'phrase', 'samolyotga chiqish taloni', 'Show your boarding card at the gate.', "Darvozada chiqish talonini ko'rsating."],
      ['flight attendant', 'phrase', 'styuardessa, styuard', 'The flight attendant brought us some water.', 'Styuardessa bizga suv olib keldi.'],
      ['customs', 'noun', 'bojxona', 'We went through customs quickly.', "Bojxonadan tez o'tdik."],
      ['land', 'verb', "qo'nmoq (samolyot)", 'The plane will land in twenty minutes.', "Samolyot yigirma daqiqadan keyin qo'nadi."],
      ['hire a car', 'phrase', 'mashina ijaraga olmoq', 'We want to hire a car for three days.', 'Uch kunga mashina ijaraga olmoqchimiz.'],
      ['underground', 'noun', 'metro', 'The underground is the fastest way to travel in Tashkent.', "Toshkentda metro — eng tez yo'l."],
      ['petrol', 'noun', 'benzin', 'We need to buy petrol.', 'Benzin olishimiz kerak.'],
    ],
  },
  {
    unit: 33,
    title: 'UK culture',
    titleUz: 'Britaniya madaniyati',
    emoji: '🇬🇧',
    words: [
      ['Christmas', 'noun', 'Rojdestvo', 'People give presents at Christmas.', "Rojdestvoda odamlar sovg'a berishadi."],
      ['Easter', 'noun', 'Pasxa', 'Children look for chocolate eggs at Easter.', 'Pasxada bolalar shokolad tuxum qidiradi.'],
      ['Halloween', 'noun', 'Xellouin', 'Children wear costumes on Halloween.', 'Xellouinda bolalar maxsus kiyim kiyadi.'],
      ['bonfire', 'noun', 'gulxan', 'We made a bonfire in the garden.', "Bog'da gulxan yoqdik."],
      ['fireworks', 'noun', 'mushakbozlik', 'We watched the fireworks at midnight.', 'Yarim tunda mushakbozlikni tomosha qildik.'],
      ['bank holiday', 'phrase', 'rasmiy dam olish kuni', 'Monday is a bank holiday, so the shops are closed.', "Dushanba — dam olish kuni, shuning uchun do'konlar yopiq."],
      ['royal family', 'phrase', 'qirol oilasi', 'The royal family lives in London.', 'Qirol oilasi Londonda yashaydi.'],
      ['king', 'noun', 'qirol, podshoh', 'The king gave a speech on TV.', "Qirol televizorda nutq so'zladi."],
      ['queen', 'noun', 'qirolicha', 'The queen visited the hospital.', 'Qirolicha kasalxonaga tashrif buyurdi.'],
      ['Prime Minister', 'phrase', 'Bosh vazir', 'The Prime Minister lives at 10 Downing Street.', 'Bosh vazir Dauning-strit, 10-uyda yashaydi.'],
      ['state school', 'phrase', 'davlat maktabi', 'Most children go to a state school.', 'Ko\'pchilik bolalar davlat maktabiga boradi.'],
      ['private school', 'phrase', 'xususiy maktab', 'Private schools are very expensive.', 'Xususiy maktablar juda qimmat.'],
      ['primary school', 'phrase', "boshlang'ich maktab", 'My son is in primary school.', "O'g'lim boshlang'ich maktabda o'qiydi."],
      ['secondary school', 'phrase', "o'rta maktab (yuqori sinflar)", 'Children start secondary school at eleven.', "Bolalar o'rta maktabni o'n bir yoshda boshlaydi."],
      ['festival', 'noun', 'bayram, festival', 'Navruz is a spring festival.', "Navro'z — bahor bayrami."],
      ['fish and chips', 'phrase', 'baliq va qovurilgan kartoshka', 'Fish and chips is a traditional British meal.', "Baliq va qovurilgan kartoshka — an'anaviy Britaniya taomi."],
    ],
  },
  {
    unit: 34,
    title: 'Crime',
    titleUz: 'Jinoyat',
    emoji: '🚓',
    words: [
      ['crime', 'noun', 'jinoyat', 'Crime is a big problem in some cities.', "Ba'zi shaharlarda jinoyat katta muammo."],
      ['criminal', 'noun', 'jinoyatchi', 'The police caught the criminal.', 'Politsiya jinoyatchini ushladi.'],
      ['police', 'noun', 'politsiya', 'Call the police!', 'Politsiyani chaqiring!'],
      ['arrest', 'verb', 'hibsga olmoq', 'The police arrested two men.', 'Politsiya ikki kishini hibsga oldi.'],
      ['prison', 'noun', 'qamoqxona', 'He spent five years in prison.', "U besh yil qamoqda o'tirdi."],
      ['go to court', 'phrase', 'sudga bormoq', 'They will go to court next month.', 'Ular kelasi oy sudga boradi.'],
      ['guilty', 'adjective', 'aybdor', 'The court decided he was guilty.', 'Sud uni aybdor deb topdi.'],
      ['innocent', 'adjective', 'aybsiz', 'She says she is innocent.', "U o'zini aybsiz deydi."],
      ['law', 'noun', 'qonun', 'It is against the law to drive without a licence.', 'Guvohnomasiz mashina haydash qonunga zid.'],
      ['steal', 'verb', "o'g'irlamoq", 'It is wrong to steal.', "O'g'irlik qilish yomon."],
      ['thief', 'noun', "o'g'ri", 'The thief took her bag.', "O'g'ri uning sumkasini olib ketdi."],
      ['robbery', 'noun', 'talonchilik', 'There was a robbery at the bank.', "Bankda talonchilik sodir bo'ldi."],
      ['burglar', 'noun', "uyga tushadigan o'g'ri", "A burglar broke into our neighbour's house.", "O'g'ri qo'shnimizning uyiga tushdi."],
      ['murder', 'noun', 'qotillik', 'The film is about a murder.', 'Film bir qotillik haqida.'],
      ['fine', 'noun', 'jarima', 'He had to pay a fine for parking there.', "U u yerda mashina qo'ygani uchun jarima to'ladi."],
      ['shoplifting', 'noun', "do'kondan o'g'irlik", 'Shoplifting is a crime.', "Do'kondan o'g'irlik — jinoyat."],
    ],
  },
  {
    unit: 35,
    title: 'The media',
    titleUz: 'Ommaviy axborot vositalari',
    emoji: '📺',
    words: [
      ['news', 'noun', 'yangiliklar', 'I watch the news every evening.', "Har kech yangiliklarni ko'raman."],
      ['paper', 'noun', 'gazeta', 'My father reads the paper at breakfast.', "Otam nonushtada gazeta o'qiydi."],
      ['channel', 'noun', 'kanal (TV)', 'This channel shows a lot of sport.', "Bu kanal ko'p sport ko'rsatadi."],
      ['change the channel', 'phrase', 'kanalni almashtirmoq', 'Can you change the channel? This is boring.', 'Kanalni almashtira olasanmi? Bu zerikarli.'],
      ['documentary', 'noun', 'hujjatli film', 'We watched a documentary about the Aral Sea.', "Orol dengizi haqida hujjatli film ko'rdik."],
      ['soap opera', 'phrase', 'serial', 'My aunt never misses her soap opera.', 'Xolam serialini hech qachon qoldirmaydi.'],
      ['talk show', 'phrase', 'tok-shou', 'She was a guest on a talk show.', "U tok-shouda mehmon bo'ldi."],
      ['reality TV', 'phrase', 'realiti-shou', "I don't like reality TV.", 'Men realiti-shoularni yoqtirmayman.'],
      ['advert', 'noun', 'reklama', 'There are too many adverts on this channel.', 'Bu kanalda reklama juda ko\'p.'],
      ['journalist', 'noun', 'jurnalist', 'She works as a journalist for a newspaper.', "U gazetada jurnalist bo'lib ishlaydi."],
      ['reporter', 'noun', 'muxbir', 'The reporter asked the minister a question.', 'Muxbir vazirga savol berdi.'],
      ['interview', 'noun', 'intervyu, suhbat', 'The interview with the singer was very interesting.', "Qo'shiqchi bilan intervyu juda qiziq edi."],
      ['media', 'noun', 'ommaviy axborot vositalari', 'The media talked about the story all day.', "OAV bu voqea haqida kun bo'yi gapirdi."],
    ],
  },
  {
    unit: 36,
    title: 'Problems at home and work',
    titleUz: 'Uy va ishdagi muammolar',
    emoji: '🔧',
    words: [
      ['broken', 'adjective', 'singan, buzilgan', 'The washing machine is broken.', 'Kir yuvish mashinasi buzilgan.'],
      ['repair', 'verb', "ta'mirlamoq", 'Can you repair my phone?', "Telefonimni ta'mirlab bera olasizmi?"],
      ['mend', 'verb', 'tuzatmoq (tikib, yamab)', 'My mother mended my jeans.', 'Onam jinsimni tikib tuzatdi.'],
      ['crash', 'verb', 'qotib qolmoq (kompyuter)', 'My computer crashed and I lost my work.', "Kompyuterim qotib qoldi va ishim yo'qoldi."],
      ['lose', 'verb', "yo'qotmoq", 'I always lose my keys.', "Kalitlarimni doim yo'qotaman."],
      ['look for', 'phrase', 'qidirmoq', 'Can you help me look for my glasses?', "Ko'zoynagimni qidirishga yordam berasanmi?"],
      ['untidy', 'adjective', 'tartibsiz', 'Your room is very untidy!', 'Xonang juda tartibsiz!'],
      ['tidy', 'verb', "yig'ishtirmoq", 'Please tidy your desk.', "Iltimos, stolingni yig'ishtir."],
      ['in a bad mood', 'phrase', 'kayfiyati yomon', 'The boss is in a bad mood today.', 'Bugun boshliqning kayfiyati yomon.'],
      ['apologise', 'verb', "uzr so'ramoq", 'He apologised for being late.', "U kechikkani uchun uzr so'radi."],
      ['late for', 'phrase', '...ga kechikmoq', 'I was late for work again.', 'Ishga yana kechikdim.'],
      ['have a row with', 'phrase', 'bilan janjallashmoq', "I don't want to have a row with you.", 'Sen bilan janjallashishni xohlamayman.'],
      ['cut', 'verb', 'kesmoq, kesib olmoq', 'I cut my finger while I was cooking.', "Ovqat pishirayotib barmog'imni kesib oldim."],
      ['too much work', 'phrase', "ish juda ko'p", 'I have too much work this week.', "Bu hafta ishim juda ko'p."],
    ],
  },
  {
    unit: 37,
    title: 'Global problems',
    titleUz: 'Global muammolar',
    emoji: '🌐',
    words: [
      ['war', 'noun', 'urush', 'Millions of people died in the war.', "Urushda millionlab odamlar halok bo'ldi."],
      ['pollution', 'noun', 'ifloslanish', 'Pollution is a problem in big cities.', 'Katta shaharlarda ifloslanish muammo.'],
      ['air pollution', 'phrase', 'havo ifloslanishi', 'Cars are the main cause of air pollution.', 'Havo ifloslanishining asosiy sababi — mashinalar.'],
      ['earthquake', 'noun', 'zilzila', 'The earthquake in Tashkent was in 1966.', "Toshkent zilzilasi 1966-yilda bo'lgan."],
      ['flood', 'noun', 'toshqin', 'The flood destroyed many houses.', "Toshqin ko'p uylarni vayron qildi."],
      ['hurricane', 'noun', 'dovul', 'The hurricane hit the coast last night.', "Kecha kechasi dovul qirg'oqqa urildi."],
      ['natural disaster', 'phrase', 'tabiiy ofat', 'An earthquake is a natural disaster.', 'Zilzila — tabiiy ofat.'],
      ['homeless', 'adjective', 'uysiz', 'The charity helps homeless people.', 'Xayriya tashkiloti uysiz odamlarga yordam beradi.'],
      ['poor', 'adjective', "kambag'al", 'Many poor families need help.', "Ko'p kambag'al oilalarga yordam kerak."],
      ['unemployed', 'adjective', 'ishsiz', 'My uncle is unemployed at the moment.', 'Amakim hozir ishsiz.'],
      ['on strike', 'phrase', 'ish tashlagan', 'The bus drivers are on strike today.', 'Bugun avtobus haydovchilari ish tashlashgan.'],
      ['traffic jam', 'phrase', 'tirbandlik', 'We were stuck in a traffic jam for an hour.', 'Bir soat tirbandlikda qolib ketdik.'],
      ['rush hour', 'phrase', "tig'iz soat", "Don't drive during rush hour.", "Tig'iz soatda mashina haydama."],
      ['crowded', 'adjective', 'gavjum', 'The metro is very crowded in the morning.', 'Ertalab metro juda gavjum.'],
      ['forest fire', 'phrase', "o'rmon yong'ini", 'The forest fire burned for three days.', "O'rmon yong'ini uch kun davom etdi."],
    ],
  },
  {
    unit: 38,
    title: 'Have',
    titleUz: '"Have" bilan iboralar',
    emoji: '☕',
    words: [
      ['have breakfast', 'phrase', 'nonushta qilmoq', 'I have breakfast at seven.', 'Soat yettida nonushta qilaman.'],
      ['have lunch', 'phrase', 'tushlik qilmoq', "Let's have lunch together.", 'Keling, birga tushlik qilaylik.'],
      ['have dinner', 'phrase', 'kechki ovqat qilmoq', 'We usually have dinner at eight.', 'Odatda soat sakkizda kechki ovqat qilamiz.'],
      ['have a shower', 'phrase', 'dush qabul qilmoq', 'I have a shower every morning.', 'Har tong dush qabul qilaman.'],
      ['have a bath', 'phrase', "vannada cho'milmoq", 'The children have a bath before bed.', "Bolalar uxlashdan oldin cho'miladi."],
      ['have a cold', 'phrase', 'shamollamoq', 'I think I have a cold.', 'Menimcha, shamollabman.'],
      ['have a headache', 'phrase', "boshi og'rimoq", 'I often have a headache after work.', "Ishdan keyin ko'pincha boshim og'riydi."],
      ['have a party', 'phrase', 'bazm qilmoq', "We're going to have a party on Friday.", 'Juma kuni bazm qilamiz.'],
      ['have a look', 'phrase', "qarab ko'rmoq", 'Can I have a look at your photos?', "Rasmlaringizni ko'rsam maylimi?"],
      ['have a good time', 'phrase', "yaxshi vaqt o'tkazmoq", 'Have a good time at the wedding!', "To'yda yaxshi dam oling!"],
      ['have a meeting', 'phrase', "yig'ilish o'tkazmoq", 'We have a meeting at ten.', "Soat o'nda yig'ilishimiz bor."],
      ['have a lesson', 'phrase', "darsi bo'lmoq", 'I have a lesson at three.', 'Soat uchda darsim bor.'],
      ['have to', 'phrase', '...ishi kerak (majburiyat)', 'I have to go now.', 'Hozir ketishim kerak.'],
      ['have got', 'phrase', "bor (ega bo'lmoq)", 'I have got two brothers.', 'Mening ikkita akam bor.'],
    ],
  },
  {
    unit: 39,
    title: 'Go',
    titleUz: '"Go" bilan iboralar',
    emoji: '🚶',
    words: [
      ['go shopping', 'phrase', 'xarid qilgani bormoq', "Let's go shopping on Saturday.", 'Shanba kuni xarid qilgani boraylik.'],
      ['go swimming', 'phrase', 'suzgani bormoq', 'We go swimming every summer.', 'Har yozda suzgani boramiz.'],
      ['go fishing', 'phrase', 'baliq ovlagani bormoq', 'My grandfather likes to go fishing.', 'Bobom baliq ovlagani borishni yoqtiradi.'],
      ['go dancing', 'phrase', 'raqsga bormoq', 'Do you want to go dancing tonight?', 'Bugun kechqurun raqsga borishni xohlaysanmi?'],
      ['go sightseeing', 'phrase', "diqqatga sazovor joylarni ko'rgani bormoq", 'In Samarkand we go sightseeing all day.', "Samarqandda kun bo'yi diqqatga sazovor joylarni ko'ramiz."],
      ['go out', 'phrase', 'tashqariga chiqmoq (dam olgani)', 'We often go out on Friday evening.', "Juma kechqurun ko'pincha dam olgani chiqamiz."],
      ['go home', 'phrase', 'uyga ketmoq', "It's late, I want to go home.", 'Kech bo\'ldi, uyga ketgim keldi.'],
      ['go by', 'phrase', '...da bormoq (transport)', 'I usually go by bus.', 'Odatda avtobusda boraman.'],
      ['go up', 'phrase', 'yuqoriga chiqmoq', 'Go up the stairs to the second floor.', 'Zinadan ikkinchi qavatga chiqing.'],
      ['go down', 'phrase', "pastga tushmoq; bo'ylab yurmoq", 'Go down this street and turn left.', "Shu ko'cha bo'ylab yuring va chapga buriling."],
      ['go away', 'phrase', 'ketmoq, nari ketmoq', "Go away, I'm busy!", 'Ket, men bandman!'],
      ['going to', 'phrase', '...moqchi (reja)', "I'm going to visit my aunt tomorrow.", 'Ertaga xolamnikiga bormoqchiman.'],
    ],
  },
  {
    unit: 40,
    title: 'Do',
    titleUz: '"Do" bilan iboralar',
    emoji: '🧹',
    words: [
      ['do homework', 'phrase', 'uy vazifasini qilmoq', 'I do homework after dinner.', 'Kechki ovqatdan keyin uy vazifasini qilaman.'],
      ['do the housework', 'phrase', 'uy ishlarini qilmoq', 'We do the housework together.', 'Uy ishlarini birga qilamiz.'],
      ['do the washing', 'phrase', 'kir yuvmoq', 'I do the washing on Sundays.', 'Yakshanba kunlari kir yuvaman.'],
      ['do the washing-up', 'phrase', 'idish yuvmoq', 'Who is going to do the washing-up?', 'Idishlarni kim yuvadi?'],
      ['do the gardening', 'phrase', "bog'da ishlamoq", 'My father likes to do the gardening.', "Otam bog'da ishlashni yoqtiradi."],
      ['do some exercise', 'phrase', 'biroz mashq qilmoq', 'I do some exercise every morning.', 'Har tong biroz mashq qilaman.'],
      ['do your best', 'phrase', "qo'lidan kelganini qilmoq", "Don't worry, just do your best.", "Xavotir olma, qo'lingdan kelganini qil."],
      ['do business', 'phrase', 'biznes qilmoq', 'We do business with companies in China.', 'Biz Xitoy kompaniyalari bilan biznes qilamiz.'],
      ['do the shopping', 'phrase', 'xarid qilmoq', 'I do the shopping on Saturdays.', 'Shanba kunlari xarid qilaman.'],
      ['do a course', 'phrase', "kursda o'qimoq", 'She wants to do a course in design.', "U dizayn kursida o'qimoqchi."],
      ['do the cooking', 'phrase', 'ovqat pishirmoq', 'Tonight I will do the cooking.', 'Bugun kechqurun ovqatni men pishiraman.'],
    ],
  },
  {
    unit: 41,
    title: 'Make',
    titleUz: '"Make" bilan iboralar',
    emoji: '🍵',
    words: [
      ['make a mistake', 'phrase', 'xato qilmoq', 'Everyone can make a mistake.', 'Har kim xato qilishi mumkin.'],
      ['make a noise', 'phrase', 'shovqin qilmoq', "Please don't make a noise, the baby is sleeping.", 'Iltimos, shovqin qilmang, chaqaloq uxlayapti.'],
      ['make a mess', 'phrase', 'ostin-ustun qilmoq', 'The children always make a mess in the kitchen.', 'Bolalar doim oshxonani ostin-ustun qiladi.'],
      ['make a choice', 'phrase', 'tanlov qilmoq', "It's hard to make a choice.", 'Tanlov qilish qiyin.'],
      ['make an appointment', 'phrase', 'qabulga yozilmoq', 'I need to make an appointment with the doctor.', 'Shifokor qabuliga yozilishim kerak.'],
      ['make breakfast', 'phrase', 'nonushta tayyorlamoq', 'Can you make breakfast today?', 'Bugun nonushtani sen tayyorlay olasanmi?'],
      ['make coffee', 'phrase', 'qahva damlamoq', "I'll make coffee for everyone.", 'Hammaga qahva damlayman.'],
      ['make tea', 'phrase', 'choy damlamoq', 'Let me make tea for our guests.', 'Mehmonlarimizga choy damlay.'],
      ['make the bed', 'phrase', "o'rin yig'ishtirmoq", 'Make the bed before you go to school.', "Maktabga ketishdan oldin o'rningni yig'ishtir."],
      ['make a video', 'phrase', 'video tayyorlamoq', 'We make a video for our blog every week.', 'Har hafta blogimiz uchun video tayyorlaymiz.'],
      ['make a photocopy', 'phrase', "nusxa ko'chirmoq", 'Can you make a photocopy of this page?', "Bu sahifadan nusxa ko'chira olasizmi?"],
      ['make a film', 'phrase', 'film suratga olmoq', 'They want to make a film about Samarkand.', 'Ular Samarqand haqida film suratga olmoqchi.'],
    ],
  },
  {
    unit: 42,
    title: 'Come',
    titleUz: '"Come" bilan iboralar',
    emoji: '🚪',
    words: [
      ['come in', 'phrase', 'kirmoq', 'Come in and sit down.', "Kiring, o'tiring."],
      ['come back', 'phrase', 'qaytib kelmoq', 'When will you come back?', 'Qachon qaytasiz?'],
      ['come from', 'phrase', "...dan bo'lmoq (kelib chiqmoq)", 'Where do you come from?', 'Qayerliksiz?'],
      ['come home', 'phrase', 'uyga kelmoq', 'What time do you come home from work?', 'Ishdan soat nechada uyga kelasiz?'],
      ['come along', 'phrase', "birga bormoq, qo'shilmoq", "We're going to the park. Do you want to come along?", 'Parkka ketyapmiz. Biz bilan borasanmi?'],
      ['come and see', 'phrase', "kelib ko'rmoq, yo'qlamoq", 'Come and see me when you are in Tashkent.', "Toshkentga kelsangiz, meni yo'qlang."],
      ['come out of', 'phrase', '...dan chiqmoq', 'The children come out of school at one.', 'Bolalar maktabdan soat birda chiqadi.'],
      ['come to stay', 'phrase', "mehmon bo'lib kelmoq", 'My cousins come to stay every summer.', 'Amakivachchalarim har yozda bizga mehmon bo\'lib keladi.'],
      ['come into', 'phrase', '...ga kirmoq', 'Please come into the office.', 'Iltimos, ofisga kiring.'],
    ],
  },
  {
    unit: 43,
    title: 'Take',
    titleUz: '"Take" bilan iboralar',
    emoji: '📷',
    words: [
      ['take a photo', 'phrase', 'rasmga olmoq', 'Can you take a photo of us?', 'Bizni rasmga olib bera olasizmi?'],
      ['take a taxi', 'phrase', "taksiga o'tirmoq", "It's late, let's take a taxi.", "Kech bo'ldi, taksiga o'tiraylik."],
      ['take the bus', 'phrase', 'avtobusda bormoq', 'I take the bus to school.', 'Maktabga avtobusda boraman.'],
      ['take the train', 'phrase', 'poyezdda bormoq', 'We take the train to Bukhara.', 'Buxoroga poyezdda boramiz.'],
      ['take the underground', 'phrase', 'metroda bormoq', 'Take the underground to the city centre.', 'Shahar markaziga metroda boring.'],
      ['take an exam', 'phrase', 'imtihon topshirmoq', 'I take an exam in June.', 'Iyunda imtihon topshiraman.'],
      ['take lessons', 'phrase', 'dars olmoq', 'She wants to take lessons in swimming.', 'U suzish darslariga qatnashmoqchi.'],
      ['take a course', 'phrase', "kursda o'qimoq", 'I want to take a course in English.', "Ingliz tili kursida o'qimoqchiman."],
      ['it takes', 'phrase', '(vaqt) ketadi', 'It takes an hour to get there.', 'U yerga borishga bir soat ketadi.'],
      ['how long does it take', 'phrase', 'qancha vaqt ketadi?', 'How long does it take to walk to the station?', 'Vokzalgacha piyoda qancha vaqt ketadi?'],
    ],
  },
  {
    unit: 44,
    title: 'Bring and take',
    titleUz: '"Bring" va "take"',
    emoji: '🎁',
    words: [
      ['bring', 'verb', 'olib kelmoq', 'Bring your book to the lesson.', 'Darsga kitobingni olib kel.'],
      ['take', 'verb', 'olib ketmoq', 'Take an umbrella with you.', "O'zing bilan soyabon olib ket."],
      ['bring back', 'phrase', 'qaytarib olib kelmoq', 'Can you bring back my pen tomorrow?', 'Ruchkamni ertaga qaytarib olib kelasanmi?'],
      ['take back', 'phrase', "qaytarmoq (do'konga)", "Can I take back this shirt? It's too small.", "Bu ko'ylakni qaytarsam bo'ladimi? Juda kichik."],
      ['bring a present', 'phrase', "sovg'a olib kelmoq", 'Guests usually bring a present.', "Mehmonlar odatda sovg'a olib kelishadi."],
      ['bring along', 'phrase', "o'zi bilan olib kelmoq", 'Bring along a friend if you want.', "Xohlasang, do'stingni ham olib kel."],
      ['take away', 'phrase', "olib ketmoq (yig'ishtirib)", 'Take away these plates, please.', 'Bu tarelkalarni olib keting, iltimos.'],
      ['bring up', 'phrase', 'tarbiyalamoq', "It's not easy to bring up three children.", 'Uchta bolani tarbiyalash oson emas.'],
      ['take out', 'phrase', 'chiqarmoq', 'Take out your notebooks.', 'Daftarlaringizni chiqaring.'],
    ],
  },
  {
    unit: 45,
    title: 'Get',
    titleUz: '"Get" bilan iboralar',
    emoji: '↗️',
    words: [
      ['get up', 'phrase', "o'rnidan turmoq", 'I get up at six.', 'Soat oltida turaman.'],
      ['get home', 'phrase', 'uyga yetib kelmoq', 'What time do you get home?', 'Uyga soat nechada kelasan?'],
      ['get back', 'phrase', 'qaytib kelmoq', 'When do you get back from Moscow?', 'Moskvadan qachon qaytasan?'],
      ['get to', 'phrase', 'yetib bormoq', 'How can I get to the airport?', 'Aeroportga qanday borsam bo\'ladi?'],
      ['get better', 'phrase', 'tuzalmoq, yaxshilanmoq', 'I hope your mother will get better soon.', 'Onangiz tezroq tuzalib ketadi degan umiddaman.'],
      ['get tired', 'phrase', 'charchamoq', 'I get tired when I work late.', 'Kechgacha ishlasam charchayman.'],
      ['get a job', 'phrase', 'ishga kirmoq', 'My sister wants to get a job in a bank.', 'Opam bankka ishga kirmoqchi.'],
      ['get lost', 'phrase', 'adashib qolmoq', "Take a map so you don't get lost.", 'Adashib qolmaslik uchun xarita ol.'],
      ['get ready', 'phrase', 'tayyorlanmoq', "Get ready, we're leaving in five minutes.", 'Tayyorlan, besh daqiqadan keyin chiqamiz.'],
      ['get cold', 'phrase', 'sovumoq', 'Drink your tea or it will get cold.', "Choyingni ich, bo'lmasa sovib qoladi."],
    ],
  },
];
