/**
 * Elementary, 16–30-unit'lar. Tamoyillar — elementary.js dagi izohga qarang:
 * kitobdan faqat mavzu va so'zlar; tarjima va misollar Linguist uchun yozilgan.
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 16,
    title: 'Communications',
    titleUz: 'Aloqa vositalari',
    emoji: '📮',
    words: [
      ['address', 'noun', 'manzil', 'What is your home address?', 'Uy manzilingiz qanday?'],
      ['email', 'noun', 'elektron xat', 'I sent you an email this morning.', 'Bugun ertalab sizga elektron xat yubordim.'],
      ['envelope', 'noun', 'konvert', 'Put the letter in an envelope.', 'Xatni konvertga soling.'],
      ['stamp', 'noun', 'pochta markasi', 'You need a stamp for this letter.', 'Bu xat uchun marka kerak.'],
      ['letter', 'noun', 'xat', 'My grandmother still writes letters.', 'Buvim hali ham xat yozadi.'],
      ['keyboard', 'noun', 'klaviatura', 'This keyboard is too small for me.', 'Bu klaviatura menga juda kichik.'],
      ['laptop', 'noun', 'noutbuk', 'I take my laptop to university.', 'Universitetga noutbugimni olib boraman.'],
      ['mouse', 'noun', 'sichqoncha (kompyuter)', 'Click the button with your mouse.', 'Tugmani sichqoncha bilan bosing.'],
      ['screen', 'noun', 'ekran', 'The screen on my phone is broken.', 'Telefonimning ekrani singan.'],
      ['memory stick', 'phrase', 'fleshka', 'Save the file on a memory stick.', 'Faylni fleshkaga saqlang.'],
      ['message', 'noun', 'xabar', 'I got your message, thanks.', 'Xabaringizni oldim, rahmat.'],
      ['phone number', 'phrase', 'telefon raqami', 'Can I have your phone number?', 'Telefon raqamingizni bera olasizmi?'],
      ['call', 'verb', "qo'ng'iroq qilmoq", 'I will call you tomorrow.', "Ertaga sizga qo'ng'iroq qilaman."],
      ['call back', 'phrase', "qayta qo'ng'iroq qilmoq", "I'm busy now, can I call back later?", "Hozir bandman, keyinroq qayta qo'ng'iroq qilsam bo'ladimi?"],
      ['take a message', 'phrase', 'xabarni yozib olmoq', "She isn't here. Can I take a message?", "U yo'q. Xabaringizni yozib olaymi?"],
    ],
  },
  {
    unit: 17,
    title: 'Your phone',
    titleUz: 'Telefoningiz',
    emoji: '📱',
    words: [
      ['app', 'noun', 'ilova', 'This app helps me learn new words.', "Bu ilova yangi so'zlarni o'rganishga yordam beradi."],
      ['battery', 'noun', 'batareya', 'My battery is almost dead.', 'Batareyam deyarli tugadi.'],
      ['charger', 'noun', 'quvvatlagich', 'Can I borrow your charger?', 'Quvvatlagichingizni olib tursam maylimi?'],
      ['camera', 'noun', 'kamera', 'The camera on this phone is very good.', 'Bu telefonning kamerasi juda yaxshi.'],
      ['delete', 'verb', "o'chirib tashlamoq", 'I deleted all the old photos.', "Barcha eski rasmlarni o'chirib tashladim."],
      ['download', 'verb', 'yuklab olmoq', 'You can download the app for free.', 'Ilovani bepul yuklab olishingiz mumkin.'],
      ['save', 'verb', 'saqlamoq', "Don't forget to save the file.", 'Faylni saqlashni unutmang.'],
      ['swipe', 'verb', 'barmoq bilan surmoq', 'Swipe left to see the next photo.', "Keyingi rasmni ko'rish uchun chapga suring."],
      ['unlock', 'verb', 'qulfdan ochmoq', 'I unlock my phone with my face.', 'Telefonimni yuzim bilan ochaman.'],
      ['locked', 'adjective', 'qulflangan', 'The phone is locked, I need the code.', 'Telefon qulflangan, menga kod kerak.'],
      ['SIM card', 'phrase', 'SIM-karta', 'I bought a new SIM card at the airport.', 'Aeroportda yangi SIM-karta sotib oldim.'],
      ['selfie', 'noun', "selfi (o'zini rasmga olish)", "Let's take a selfie together!", 'Keling, birga selfi tushaylik!'],
      ['voicemail', 'noun', 'ovozli pochta', 'I left a message on his voicemail.', 'Uning ovozli pochtasiga xabar qoldirdim.'],
      ['text', 'verb', 'SMS yozmoq', "I'll text you when I arrive.", 'Yetib borganimda SMS yozaman.'],
      ['power button', 'phrase', 'yoqish tugmasi', 'Press the power button to turn it on.', 'Yoqish uchun yoqish tugmasini bosing.'],
    ],
  },
  {
    unit: 18,
    title: 'Holidays',
    titleUz: "Ta'til va sayohat",
    emoji: '🏖️',
    words: [
      ['holiday', 'noun', "ta'til, dam olish", 'We had a wonderful holiday in Turkey.', 'Turkiyada ajoyib dam oldik.'],
      ['go on holiday', 'phrase', "ta'tilga chiqmoq", 'We usually go on holiday in August.', "Odatda avgustda ta'tilga chiqamiz."],
      ['passport', 'noun', 'pasport', "Don't forget your passport!", 'Pasportingni unutma!'],
      ['visa', 'noun', 'viza', 'Do I need a visa for Japan?', 'Yaponiyaga viza kerakmi?'],
      ['currency', 'noun', 'valyuta, pul birligi', 'The currency of Uzbekistan is the sum.', "O'zbekistonning pul birligi — so'm."],
      ['luggage', 'noun', 'yuk, bagaj', 'How much luggage do you have?', 'Qancha yukingiz bor?'],
      ['suitcase', 'noun', 'chamadon', 'My suitcase is too heavy.', "Chamadonim juda og'ir."],
      ['rucksack', 'noun', 'ryukzak', 'I carry my water in a rucksack.', 'Suvimni ryukzakda olib yuraman.'],
      ['flight', 'noun', 'parvoz, reys', 'Our flight leaves at six.', 'Reysimiz soat oltida uchadi.'],
      ['ferry', 'noun', 'parom', 'We took the ferry to the island.', 'Orolga parom bilan bordik.'],
      ['camping', 'noun', 'chodirda dam olish', 'We went camping in the mountains.', "Tog'da chodir tikib dam oldik."],
      ['postcard', 'noun', 'otkritka', 'Send me a postcard from Paris!', 'Parijdan menga otkritka yubor!'],
      ['package holiday', 'phrase', 'tayyor sayohat paketi', 'A package holiday includes the flight and the hotel.', 'Tayyor sayohat paketiga parvoz va mehmonxona kiradi.'],
      ['nightlife', 'noun', 'tungi hayot', 'This city has great nightlife.', 'Bu shaharning tungi hayoti qiziqarli.'],
      ['enjoy', 'verb', 'zavqlanmoq, maza qilmoq', 'Did you enjoy your trip?', 'Safaringiz yoqdimi?'],
      ['have a great time', 'phrase', "ajoyib vaqt o'tkazmoq", 'I hope you have a great time at the beach.', "Sohilda ajoyib vaqt o'tkazasiz degan umiddaman."],
    ],
  },
  {
    unit: 19,
    title: 'Shops and shopping',
    titleUz: "Do'konlar va xarid",
    emoji: '🛍️',
    words: [
      ['department store', 'phrase', 'univermag', 'You can buy almost anything in a department store.', 'Univermagda deyarli hamma narsani sotib olish mumkin.'],
      ["chemist's", 'noun', 'dorixona', "I need to go to the chemist's for some medicine.", 'Dori olish uchun dorixonaga borishim kerak.'],
      ["baker's", 'noun', 'novvoyxona', "The baker's opens at seven.", 'Novvoyxona soat yettida ochiladi.'],
      ["butcher's", 'noun', "qassob do'koni", "Buy some meat at the butcher's.", "Qassob do'konidan go'sht ol."],
      ['bookshop', 'noun', "kitob do'koni", 'There is a new bookshop near the station.', "Vokzal yonida yangi kitob do'koni bor."],
      ['cash', 'noun', 'naqd pul', 'Do you want to pay by card or in cash?', "Karta bilan to'laysizmi yoki naqd?"],
      ['receipt', 'noun', 'chek', 'Keep the receipt in case you want to return it.', "Qaytarmoqchi bo'lsangiz, chekni saqlab qo'ying."],
      ['credit card', 'phrase', 'kredit karta', 'Can I pay by credit card?', "Kredit karta bilan to'lasam bo'ladimi?"],
      ['pay', 'verb', "to'lamoq", 'Where do I pay?', "Qayerda to'layman?"],
      ['cost', 'verb', "narxi ... bo'lmoq", 'How much does this jacket cost?', 'Bu kurtka qancha turadi?'],
      ['try on', 'phrase', "kiyib ko'rmoq", 'Can I try on these shoes?', "Bu tuflilarni kiyib ko'rsam bo'ladimi?"],
      ['size', 'noun', "o'lcham", 'Do you have this in a bigger size?', "Buning kattaroq o'lchami bormi?"],
      ['ground floor', 'phrase', 'birinchi qavat (yer sathi)', 'The shoes are on the ground floor.', 'Poyabzallar birinchi qavatda.'],
      ['furniture', 'noun', 'mebel', 'We need new furniture for the flat.', 'Kvartira uchun yangi mebel kerak.'],
      ['toys', 'noun', "o'yinchoqlar", 'The children want to see the toys.', "Bolalar o'yinchoqlarni ko'rmoqchi."],
      ['closed', 'adjective', 'yopiq', 'Sorry, the shop is closed on Sunday.', "Uzr, do'kon yakshanba kuni yopiq."],
    ],
  },
  {
    unit: 20,
    title: 'Online shopping',
    titleUz: 'Onlayn xarid',
    emoji: '🛒',
    words: [
      ['shop online', 'phrase', 'onlayn xarid qilmoq', 'I shop online because it saves time.', 'Vaqtni tejash uchun onlayn xarid qilaman.'],
      ['basket', 'noun', 'savat', 'You have three items in your basket.', 'Savatingizda uchta mahsulot bor.'],
      ['add to basket', 'phrase', "savatga qo'shmoq", 'Choose your size and click add to basket.', "O'lchamni tanlab, «savatga qo'shish»ni bosing."],
      ['delivery', 'noun', 'yetkazib berish', 'Delivery is free for orders over 200,000 sum.', "200 ming so'mdan ortiq buyurtmada yetkazib berish bepul."],
      ['next day delivery', 'phrase', 'ertasi kuni yetkazib berish', 'I paid extra for next day delivery.', "Ertasi kuni yetkazib berish uchun qo'shimcha to'ladim."],
      ['price', 'noun', 'narx', 'The price is lower online.', 'Onlaynda narx pastroq.'],
      ['review', 'noun', 'sharh (baho)', 'Read the reviews before you buy.', "Sotib olishdan oldin sharhlarni o'qing."],
      ['search', 'verb', 'qidirmoq', 'Search for "black shoes" on the website.', "Saytda «qora tufli» deb qidiring."],
      ['order number', 'phrase', 'buyurtma raqami', 'Please write down your order number.', 'Iltimos, buyurtma raqamingizni yozib oling.'],
      ['post code', 'phrase', 'pochta indeksi', 'Enter your address and post code.', 'Manzil va pochta indeksingizni kiriting.'],
    ],
  },
  {
    unit: 21,
    title: 'In a hotel',
    titleUz: 'Mehmonxonada',
    emoji: '🏨',
    words: [
      ['reception', 'noun', 'qabulxona (resepshn)', 'Leave your key at reception.', 'Kalitingizni qabulxonada qoldiring.'],
      ['reservation', 'noun', 'bron', 'I have a reservation for two nights.', 'Ikki kechaga bronim bor.'],
      ['single room', 'phrase', 'bir kishilik xona', 'A single room costs forty dollars.', 'Bir kishilik xona qirq dollar turadi.'],
      ['double room', 'phrase', 'ikki kishilik xona', "We'd like a double room, please.", 'Bizga ikki kishilik xona kerak, iltimos.'],
      ['key', 'noun', 'kalit', 'Here is your key. Room 305.', 'Mana kalitingiz. 305-xona.'],
      ['lift', 'noun', "ko'targich, lift", 'Take the lift to the fifth floor.', 'Beshinchi qavatga liftda chiqing.'],
      ['bill', 'noun', "hisob (to'lov)", 'Can I have the bill, please?', 'Hisobni bera olasizmi, iltimos?'],
      ['check out', 'phrase', 'mehmonxonadan chiqib ketmoq', 'You must check out before twelve.', "Soat o'n ikkigacha xonani bo'shatishingiz kerak."],
      ['fill in a form', 'phrase', "anketa to'ldirmoq", 'Please fill in a form with your details.', "Iltimos, ma'lumotlaringiz bilan anketa to'ldiring."],
      ['room service', 'phrase', 'xonaga xizmat', 'We ordered dinner from room service.', 'Kechki ovqatni xonaga buyurtma qildik.'],
      ['wake-up call', 'phrase', "uyg'otish qo'ng'irog'i", 'Can I have a wake-up call at six?', "Soat oltida uyg'otish qo'ng'irog'i bo'ladimi?"],
      ['hairdryer', 'noun', 'fen', 'There is a hairdryer in the bathroom.', 'Hammomda fen bor.'],
      ['room with a view', 'phrase', 'manzarali xona', 'I asked for a room with a view of the sea.', "Dengiz manzarasi ko'rinadigan xona so'radim."],
      ['change money', 'phrase', 'pul almashtirmoq', 'Where can I change money?', "Qayerda pul almashtirsam bo'ladi?"],
    ],
  },
  {
    unit: 22,
    title: 'Eating out',
    titleUz: 'Tashqarida ovqatlanish',
    emoji: '🍽️',
    words: [
      ['starter', 'noun', 'birinchi taom (gazak)', 'For a starter I will have the soup.', "Birinchi taomga sho'rva olaman."],
      ['main course', 'phrase', 'asosiy taom', 'What would you like for your main course?', 'Asosiy taomga nima olasiz?'],
      ['dessert', 'noun', 'shirinlik (desert)', 'Is there room for dessert?', 'Shirinlikka joy qoldimi?'],
      ['order', 'verb', 'buyurtma bermoq', 'Are you ready to order?', 'Buyurtma berishga tayyormisiz?'],
      ['delicious', 'adjective', 'mazali', 'This plov is delicious!', 'Bu osh juda mazali!'],
      ['snack', 'noun', 'yengil tamaddi', 'I had a quick snack before the lesson.', 'Darsdan oldin tezgina tamaddi qildim.'],
      ['soft drink', 'phrase', 'alkogolsiz ichimlik', 'Would you like a soft drink?', 'Alkogolsiz ichimlik ichasizmi?'],
      ['take-away', 'noun', 'olib ketiladigan ovqat', "Let's get a take-away tonight.", 'Bugun kechqurun ovqatni olib ketaylik.'],
      ['rare', 'adjective', "chala pishgan (go'sht)", 'I like my steak rare.', 'Steykni chala pishgan holda yoqtiraman.'],
      ['well-done', 'adjective', "yaxshi pishgan (go'sht)", 'I want my meat well-done, please.', "Go'shtim yaxshi pishgan bo'lsin, iltimos."],
      ['ice cream', 'phrase', 'muzqaymoq', 'Children love chocolate ice cream.', "Bolalar shokoladli muzqaymoqni yaxshi ko'radi."],
      ['soup', 'noun', "sho'rva", 'The soup of the day is tomato.', "Bugungi sho'rva — pomidorli."],
      ["I'd like", 'phrase', '... xohlardim', "I'd like a glass of water, please.", 'Bir stakan suv xohlardim, iltimos.'],
      ['could I have the bill', 'phrase', 'hisobni olib kelasizmi?', 'Excuse me, could I have the bill?', 'Kechirasiz, hisobni olib kelasizmi?'],
      ['meal', 'noun', 'ovqat (bir mahal)', 'Breakfast is the most important meal of the day.', 'Nonushta kunning eng muhim ovqati.'],
    ],
  },
  {
    unit: 23,
    title: 'Sports',
    titleUz: 'Sport turlari',
    emoji: '⚽',
    words: [
      ['football', 'noun', 'futbol', 'The boys play football after school.', "O'g'il bolalar maktabdan keyin futbol o'ynaydi."],
      ['basketball', 'noun', 'basketbol', 'You need to be tall to play basketball well.', "Basketbolni yaxshi o'ynash uchun baland bo'y kerak."],
      ['volleyball', 'noun', 'voleybol', 'We play volleyball on the beach.', "Sohilda voleybol o'ynaymiz."],
      ['table tennis', 'phrase', 'stol tennisi', 'Table tennis is very popular in China.', 'Stol tennisi Xitoyda juda mashhur.'],
      ['swimming', 'noun', 'suzish', 'Swimming is good exercise.', 'Suzish — yaxshi jismoniy mashq.'],
      ['swimming pool', 'phrase', 'basseyn', 'The hotel has a big swimming pool.', 'Mehmonxonada katta basseyn bor.'],
      ['skiing', 'noun', "chang'i uchish", 'We go skiing in Chimgan in winter.', "Qishda Chimyonga chang'i uchgani boramiz."],
      ['running', 'noun', 'yugurish', 'Running every morning keeps me fit.', "Har tong yugurish meni sog'lom saqlaydi."],
      ['sailing', 'noun', 'yelkanli qayiqda suzish', 'Sailing is popular on the lake.', "Ko'lda yelkanli qayiqda suzish mashhur."],
      ['judo', 'noun', 'dzyudo', 'Uzbekistan has strong judo players.', "O'zbekistonda kuchli dzyudochilar bor."],
      ['sports centre', 'phrase', 'sport markazi', 'There is a new sports centre in our district.', 'Tumanimizda yangi sport markazi bor.'],
      ['pitch', 'noun', 'futbol maydoni', 'The players are coming onto the pitch.', "O'yinchilar maydonga chiqmoqda."],
      ['court', 'noun', 'maydon (tennis, basketbol)', 'The tennis court is behind the school.', 'Tennis maydoni maktab orqasida.'],
      ['favourite', 'adjective', 'sevimli', "What's your favourite sport?", 'Sevimli sport turingiz qaysi?'],
      ['play', 'verb', "o'ynamoq", 'Do you play any sports?', "Biror sport turi bilan shug'ullanasizmi?"],
    ],
  },
  {
    unit: 24,
    title: 'Cinema',
    titleUz: 'Kino',
    emoji: '🎬',
    words: [
      ['cinema', 'noun', 'kinoteatr', "Let's go to the cinema on Friday.", 'Juma kuni kinoteatrga boraylik.'],
      ['action film', 'phrase', 'jangari film', 'My brother only watches action films.', "Akam faqat jangari filmlarni ko'radi."],
      ['comedy', 'noun', 'komediya', 'We laughed a lot at that comedy.', "U komediyada ko'p kuldik."],
      ['horror', 'noun', 'dahshat filmi', "I can't watch horror films at night.", "Kechasi dahshat filmlarini ko'ra olmayman."],
      ['thriller', 'noun', 'triller', 'The thriller was very exciting.', 'Triller juda hayajonli edi.'],
      ['cartoon', 'noun', 'multfilm', 'My little brother watches cartoons every morning.', "Ukam har tong multfilm ko'radi."],
      ['western', 'noun', 'vestern (kovboylar filmi)', 'My grandfather loves old westerns.', "Bobom eski vesternlarni yaxshi ko'radi."],
      ['musical', 'noun', 'myuzikl', 'We saw a musical in London.', "Londonda myuzikl ko'rdik."],
      ['film star', 'phrase', 'kino yulduzi', 'She wants to be a film star.', "U kino yulduzi bo'lishni xohlaydi."],
      ['director', 'noun', 'rejissyor', 'Who is the director of this film?', 'Bu filmning rejissyori kim?'],
      ['boring', 'adjective', 'zerikarli', 'The film was long and boring.', 'Film uzun va zerikarli edi.'],
      ['romantic comedy', 'phrase', 'romantik komediya', 'Let\'s watch a romantic comedy tonight.', "Bugun kechqurun romantik komediya ko'raylik."],
      ["what's on", 'phrase', "nima ko'rsatilyapti?", "What's on at the cinema tonight?", "Bugun kechqurun kinoteatrda nima ko'rsatilyapti?"],
    ],
  },
  {
    unit: 25,
    title: 'Free time at home',
    titleUz: "Uyda bo'sh vaqt",
    emoji: '🏠',
    words: [
      ['hobby', 'noun', 'qiziqish (xobbi)', 'My hobby is photography.', 'Mening qiziqishim — suratga olish.'],
      ['gardening', 'noun', "bog'dorchilik", 'My father spends his weekends gardening.', "Otam dam olish kunlarini bog'da ishlab o'tkazadi."],
      ['cooking', 'noun', 'ovqat pishirish', 'I enjoy cooking for my friends.', "Do'stlarimga ovqat pishirishni yoqtiraman."],
      ['novel', 'noun', 'roman', "I'm reading a novel by Abdulla Qodiriy.", "Abdulla Qodiriyning romanini o'qiyapman."],
      ['magazine', 'noun', 'jurnal', 'She reads a fashion magazine every month.', "U har oy moda jurnalini o'qiydi."],
      ['headphones', 'noun', 'quloqchin', 'I listen to music with headphones.', 'Musiqani quloqchin bilan tinglayman.'],
      ['video games', 'phrase', "video o'yinlar", 'He plays video games all evening.', "U butun kechqurun video o'yin o'ynaydi."],
      ['chat', 'verb', 'suhbatlashmoq, yozishmoq', 'I chat with my friends online.', "Do'stlarim bilan onlayn yozishaman."],
      ['have friends round', 'phrase', "do'stlarni uyga chaqirmoq", 'We often have friends round on Saturday.', "Shanba kuni ko'pincha do'stlarni uyga chaqiramiz."],
      ['do nothing', 'phrase', 'hech narsa qilmaslik', 'On Sunday I like to do nothing.', 'Yakshanba kuni hech narsa qilmaslikni yoqtiraman.'],
      ['programme', 'noun', "ko'rsatuv", 'There is a good programme about animals on TV.', "Televizorda hayvonlar haqida yaxshi ko'rsatuv bor."],
      ['grow', 'verb', "o'stirmoq, yetishtirmoq", 'We grow tomatoes in our garden.', "Bog'imizda pomidor yetishtiramiz."],
      ['watch TV', 'phrase', "televizor ko'rmoq", 'My parents watch TV after dinner.', "Ota-onam kechki ovqatdan keyin televizor ko'radi."],
      ['have a sleep', 'phrase', 'biroz uxlab olmoq', "I'm tired, I'm going to have a sleep.", 'Charchadim, biroz uxlab olaman.'],
    ],
  },
  {
    unit: 26,
    title: 'Music and musical instruments',
    titleUz: "Musiqa va cholg'u asboblari",
    emoji: '🎸',
    words: [
      ['guitar', 'noun', 'gitara', 'He plays the guitar in a band.', 'U guruhda gitara chaladi.'],
      ['piano', 'noun', 'pianino, fortepiano', 'My sister has piano lessons on Mondays.', 'Singlim dushanba kunlari pianino darsiga boradi.'],
      ['violin', 'noun', 'skripka', 'The violin is hard to learn.', "Skripkani o'rganish qiyin."],
      ['drums', 'noun', 'baraban', 'Our neighbour plays the drums every evening.', "Qo'shnimiz har kech baraban chaladi."],
      ['trumpet', 'noun', 'truba (karnay)', 'He played the trumpet at the concert.', 'U konsertda truba chaldi.'],
      ['flute', 'noun', 'fleyta, nay', 'The flute has a soft, sweet sound.', 'Fleytaning ovozi mayin va yoqimli.'],
      ['orchestra', 'noun', 'orkestr', 'She plays in the national orchestra.', 'U milliy orkestrda chaladi.'],
      ['concert', 'noun', 'konsert', 'We went to a concert last night.', 'Kecha kechqurun konsertga bordik.'],
      ['band', 'noun', 'guruh (musiqa)', 'My favourite band is coming to Tashkent.', 'Sevimli guruhim Toshkentga kelyapti.'],
      ['song', 'noun', "qo'shiq", 'This song is very popular.', "Bu qo'shiq juda mashhur."],
      ['musician', 'noun', 'musiqachi, sozanda', 'His father is a famous musician.', 'Uning otasi mashhur sozanda.'],
      ['classical music', 'phrase', 'klassik musiqa', 'I listen to classical music when I study.', 'Dars qilayotganda klassik musiqa tinglayman.'],
      ['pop music', 'phrase', 'pop musiqa', 'Teenagers usually like pop music.', "O'smirlar odatda pop musiqani yoqtiradi."],
      ["can't stand", 'phrase', 'toqat qilolmaslik', "I can't stand loud music.", 'Baland musiqaga toqat qilolmayman.'],
      ['musical instrument', 'phrase', "cholg'u asbobi", 'Do you play a musical instrument?', "Biror cholg'u asbobini chalasizmi?"],
    ],
  },
  {
    unit: 27,
    title: 'Countries and nationalities',
    titleUz: 'Mamlakatlar va millatlar',
    emoji: '🌍',
    words: [
      ['country', 'noun', 'mamlakat', 'Which country are you from?', 'Qaysi mamlakatdansiz?'],
      ['continent', 'noun', "qit'a", 'Asia is the biggest continent.', "Osiyo — eng katta qit'a."],
      ['nationality', 'noun', 'fuqarolik, millat', 'What nationality is your teacher?', "O'qituvchingiz qaysi millatdan?"],
      ['Europe', 'noun', 'Yevropa', 'We travelled around Europe by train.', "Yevropa bo'ylab poyezdda sayohat qildik."],
      ['Asia', 'noun', 'Osiyo', 'Uzbekistan is in Central Asia.', "O'zbekiston Markaziy Osiyoda joylashgan."],
      ['Africa', 'noun', 'Afrika', 'Lions live in Africa.', 'Sherlar Afrikada yashaydi.'],
      ['China', 'noun', 'Xitoy', 'China has the biggest population in Asia.', "Xitoy Osiyoda eng ko'p aholiga ega."],
      ['Chinese', 'adjective', 'xitoycha, xitoylik', 'Chinese food is very popular.', 'Xitoy taomlari juda mashhur.'],
      ['Japan', 'noun', 'Yaponiya', 'Japan is famous for its technology.', 'Yaponiya texnologiyalari bilan mashhur.'],
      ['Japanese', 'adjective', 'yaponcha, yaponiyalik', 'She is learning Japanese.', "U yapon tilini o'rganyapti."],
      ['Germany', 'noun', 'Germaniya', 'My cousin studies in Germany.', "Amakivachcham Germaniyada o'qiydi."],
      ['German', 'adjective', 'nemischa, nemis', 'German cars are very good.', 'Nemis mashinalari juda yaxshi.'],
      ['Spain', 'noun', 'Ispaniya', 'Spain is hot in summer.', "Yozda Ispaniya issiq bo'ladi."],
      ['Spanish', 'adjective', 'ispancha, ispan', 'Spanish is spoken in many countries.', "Ispan tilida ko'p mamlakatlarda gaplashiladi."],
      ['India', 'noun', 'Hindiston', 'India has many different languages.', "Hindistonda turli tillar ko'p."],
      ['Egypt', 'noun', 'Misr', 'We saw the pyramids in Egypt.', "Misrda piramidalarni ko'rdik."],
      ['Arabic', 'noun', 'arab tili', 'Arabic is written from right to left.', "Arab tilida o'ngdan chapga yoziladi."],
    ],
  },
  {
    unit: 28,
    title: 'Weather',
    titleUz: 'Ob-havo',
    emoji: '⛅',
    words: [
      ['weather', 'noun', 'ob-havo', 'The weather is lovely today.', 'Bugun ob-havo ajoyib.'],
      ['sunny', 'adjective', 'quyoshli', "It's a sunny day, let's go out.", 'Kun quyoshli, tashqariga chiqaylik.'],
      ['cloudy', 'adjective', 'bulutli', 'It was cloudy all morning.', "Ertalab bo'yi havo bulutli edi."],
      ['rain', 'noun', "yomg'ir", 'Take an umbrella, there will be rain.', "Soyabon ol, yomg'ir yog'adi."],
      ['rainy', 'adjective', "yomg'irli", 'April is often rainy.', "Aprel ko'pincha yomg'irli bo'ladi."],
      ['snow', 'noun', 'qor', 'The children played in the snow.', "Bolalar qorda o'ynadi."],
      ['windy', 'adjective', 'shamolli', "It's too windy to ride a bike.", 'Velosiped haydash uchun juda shamolli.'],
      ['fog', 'noun', 'tuman', 'The plane was late because of the fog.', 'Tuman sabab samolyot kechikdi.'],
      ['storm', 'noun', "bo'ron", 'The storm broke many trees.', "Bo'ron ko'p daraxtlarni sindirdi."],
      ['thunder', 'noun', 'momaqaldiroq', 'The dog is afraid of thunder.', "It momaqaldiroqdan qo'rqadi."],
      ['lightning', 'noun', 'chaqmoq', 'Lightning hit the tall tree.', 'Chaqmoq baland daraxtga urildi.'],
      ['wet', 'adjective', "ho'l, nam", 'My clothes are wet from the rain.', "Kiyimlarim yomg'irdan ho'l bo'ldi."],
      ['dry', 'adjective', 'quruq', 'Summer in Bukhara is hot and dry.', 'Buxoroda yoz issiq va quruq.'],
      ['degrees', 'noun', 'daraja (harorat)', "It's forty degrees in the shade!", 'Soyada qirq daraja!'],
      ["what's the weather like", 'phrase', 'havo qanday?', "What's the weather like in Samarkand?", 'Samarqandda havo qanday?'],
    ],
  },
  {
    unit: 29,
    title: 'In the town',
    titleUz: 'Shaharda',
    emoji: '🏙️',
    words: [
      ['railway station', 'phrase', "temir yo'l vokzali", 'The railway station is in the city centre.', "Temir yo'l vokzali shahar markazida."],
      ['bus station', 'phrase', 'avtovokzal', 'Buses to Fergana leave from the bus station.', "Farg'onaga avtobuslar avtovokzaldan jo'naydi."],
      ['museum', 'noun', 'muzey', 'The museum is closed on Mondays.', 'Muzey dushanba kunlari yopiq.'],
      ['library', 'noun', 'kutubxona', 'I study in the library after school.', "Maktabdan keyin kutubxonada o'qiyman."],
      ['town hall', 'phrase', 'shahar hokimiyati', 'The town hall is next to the park.', 'Shahar hokimiyati park yonida.'],
      ['car park', 'phrase', 'avtoturargoh', 'The car park is full.', "Avtoturargoh to'la."],
      ['cash machine', 'phrase', 'bankomat', 'Is there a cash machine near here?', 'Bu yerga yaqin bankomat bormi?'],
      ['shopping centre', 'phrase', 'savdo markazi', 'We met at the shopping centre.', 'Savdo markazida uchrashdik.'],
      ['entrance', 'noun', 'kirish joyi', 'The entrance is on the left.', 'Kirish joyi chap tomonda.'],
      ['exit', 'noun', 'chiqish joyi', "Where's the exit?", 'Chiqish qayerda?'],
      ['turn', 'verb', 'burilmoq', 'Turn right at the traffic lights.', "Svetoforda o'ngga buriling."],
      ['on the left', 'phrase', 'chap tomonda', 'The bank is on the left.', 'Bank chap tomonda.'],
      ['directions', 'noun', "yo'l ko'rsatmasi", 'Can you give me directions to the museum?', "Muzeyga yo'lni ko'rsatib bera olasizmi?"],
      ['out of order', 'phrase', 'ishlamayapti (buzilgan)', 'The lift is out of order.', 'Lift ishlamayapti.'],
      ['get off', 'phrase', '(transportdan) tushmoq', 'Get off the bus at the next stop.', 'Keyingi bekatda avtobusdan tushing.'],
      ['how do I get to', 'phrase', "...ga qanday borsam bo'ladi?", 'Excuse me, how do I get to the station?', "Kechirasiz, vokzalga qanday borsam bo'ladi?"],
    ],
  },
  {
    unit: 30,
    title: 'In the countryside',
    titleUz: "Tabiat qo'ynida",
    emoji: '🌳',
    words: [
      ['countryside', 'noun', 'qishloq joy, tabiat', 'We spend the summer in the countryside.', "Yozni qishloqda o'tkazamiz."],
      ['village', 'noun', 'qishloq', 'My grandparents live in a small village.', 'Bobom va buvim kichik qishloqda yashaydi.'],
      ['farm', 'noun', 'ferma', 'They have cows and sheep on their farm.', "Ularning fermasida sigir va qo'ylar bor."],
      ['field', 'noun', 'dala', 'The cotton fields are white in autumn.', "Kuzda paxta dalalari oppoq bo'ladi."],
      ['forest', 'noun', "o'rmon", "Don't go into the forest alone.", "O'rmonga yolg'iz kirma."],
      ['hill', 'noun', 'tepalik', 'We climbed the hill to see the view.', "Manzarani ko'rish uchun tepalikka chiqdik."],
      ['mountain', 'noun', "tog'", 'There is snow on the mountains.', "Tog'larda qor bor."],
      ['lake', 'noun', "ko'l", 'We swam in the lake.', "Ko'lda suzdik."],
      ['river', 'noun', 'daryo', 'The Amu Darya is a long river.', 'Amudaryo — uzun daryo.'],
      ['path', 'noun', "so'qmoq, yo'lak", 'Follow the path to the river.', "Daryoga so'qmoq bo'ylab boring."],
      ['nature', 'noun', 'tabiat', 'I love being close to nature.', "Tabiatga yaqin bo'lishni yaxshi ko'raman."],
      ['wildlife', 'noun', 'yovvoyi tabiat (hayvonot)', 'The national park is full of wildlife.', "Milliy bog' yovvoyi hayvonlarga to'la."],
      ['national park', 'phrase', "milliy bog'", 'Ugam-Chatkal is a national park.', "Ugam-Chotqol — milliy bog'."],
      ['have a picnic', 'phrase', 'piknik qilmoq', "Let's have a picnic by the river.", "Daryo bo'yida piknik qilaylik."],
      ['go walking', 'phrase', 'piyoda sayrga chiqmoq', 'We go walking in the hills every Sunday.', 'Har yakshanba tepaliklarga piyoda sayrga chiqamiz.'],
    ],
  },
];
