/**
 * Elementary, 46–60-unit'lar — "Words and grammar" bo'limi. Tamoyillar —
 * elementary.js dagi izohga qarang: kitobdan faqat mavzu va so'zlar;
 * tarjima va misollar Linguist uchun yozilgan.
 *
 * Boshqa mavzularda allaqachon bor so'zlar (put on, untidy, back ...) bu
 * yerda takrorlanmaydi — lug'atda ular bitta yozuv bo'lib qoladi.
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 */

module.exports = [
  {
    unit: 46,
    title: 'Phrasal verbs',
    titleUz: "Frazali fe'llar",
    emoji: '🔄',
    words: [
      ['get on', 'phrase', '(transportga) chiqmoq', 'Get on the bus at the front door.', 'Avtobusga oldingi eshikdan chiqing.'],
      ['go off', 'phrase', 'jiringlamoq (budilnik)', "My alarm clock didn't go off this morning.", 'Bugun ertalab budilnigim jiringlamadi.'],
      ['go on', 'phrase', 'davom etmoq', "Please go on, I'm listening.", 'Davom eting, eshityapman.'],
      ['turn down', 'phrase', 'pasaytirmoq (ovoz)', 'Can you turn down the music?', 'Musiqani pasaytira olasanmi?'],
      ['turn up', 'phrase', 'balandlatmoq (ovoz)', 'Turn up the radio, I love this song.', "Radioni balandlat, bu qo'shiqni yaxshi ko'raman."],
      ['come on', 'phrase', 'qani, tezroq', "Come on, we're late!", 'Qani, tezroq, kechikyapmiz!'],
      ['sit down', 'phrase', "o'tirmoq", 'Please sit down.', "Iltimos, o'tiring."],
      ['stand up', 'phrase', 'tik turmoq', 'Stand up when the teacher comes in.', "O'qituvchi kirganda o'rningdan tur."],
      ['give up', 'phrase', "taslim bo'lmoq, tashlamoq", "Don't give up, you can do it!", "Taslim bo'lma, uddalaysan!"],
      ['pick up', 'phrase', "yerdan olmoq, ko'tarmoq", 'Pick up your toys, please.', "O'yinchoqlaringni yig'ishtirib ol, iltimos."],
      ['look up', 'phrase', "(lug'atdan) qidirmoq", 'Look up the word in a dictionary.', "So'zni lug'atdan qidirib top."],
      ['put down', 'phrase', "qo'ymoq (qo'ldan)", 'Put down your pens and listen.', "Ruchkalaringizni qo'yib, tinglang."],
    ],
  },
  {
    unit: 47,
    title: 'Everyday things',
    titleUz: 'Kundalik ishlar',
    emoji: '🗓️',
    words: [
      ['go to work', 'phrase', 'ishga bormoq', 'I go to work by metro.', 'Ishga metroda boraman.'],
      ['go for a walk', 'phrase', 'sayr qilgani chiqmoq', "Let's go for a walk after dinner.", 'Kechki ovqatdan keyin sayr qilaylik.'],
      ['clean the house', 'phrase', 'uyni tozalamoq', 'We clean the house every Saturday.', 'Har shanba uyni tozalaymiz.'],
      ['phone a friend', 'phrase', "do'stga qo'ng'iroq qilmoq", 'When I feel sad, I phone a friend.', "Xafa bo'lsam, do'stimga qo'ng'iroq qilaman."],
      ['write emails', 'phrase', 'elektron xat yozmoq', 'I write emails to my clients every morning.', 'Har tong mijozlarimga elektron xat yozaman.'],
      ['usually', 'adverb', 'odatda', 'I usually walk to school.', 'Odatda maktabga piyoda boraman.'],
      ['sometimes', 'adverb', "ba'zan", 'Sometimes I take a taxi.', "Ba'zan taksiga o'tiraman."],
      ['how often', 'phrase', 'qanchalik tez-tez?', 'How often do you go to the gym?', 'Sport zaliga qanchalik tez-tez borasiz?'],
      ['times a week', 'phrase', 'haftada ... marta', 'I play football three times a week.', "Haftada uch marta futbol o'ynayman."],
      ['what time', 'phrase', 'soat nechada?', 'What time do you finish work?', 'Ishni soat nechada tugatasiz?'],
      ['listen to', 'phrase', 'tinglamoq', 'I listen to the radio in the car.', 'Mashinada radio tinglayman.'],
    ],
  },
  {
    unit: 48,
    title: 'Talking',
    titleUz: "Gapirish fe'llari",
    emoji: '🗣️',
    words: [
      ['say', 'verb', 'aytmoq, demoq', 'What does this sign say?', 'Bu belgida nima deyilgan?'],
      ['tell', 'verb', 'aytib bermoq', 'Tell me about your family.', 'Oilangiz haqida gapirib bering.'],
      ['speak', 'verb', 'gapirmoq (tilda)', 'Do you speak Russian?', 'Rus tilida gaplashasizmi?'],
      ['talk', 'verb', 'gaplashmoq, suhbatlashmoq', 'We talk on the phone every day.', 'Har kuni telefonda gaplashamiz.'],
      ['ask', 'verb', "so'ramoq", 'Can I ask a question?', "Savol bersam bo'ladimi?"],
      ['answer', 'verb', 'javob bermoq', 'Please answer the question.', 'Iltimos, savolga javob bering.'],
      ['reply', 'verb', 'javob qaytarmoq (xatga)', "She didn't reply to my message.", 'U xabarimga javob qaytarmadi.'],
      ['tell a joke', 'phrase', 'latifa aytmoq', 'My uncle likes to tell a joke at dinner.', 'Amakim dasturxonda latifa aytishni yaxshi ko\'radi.'],
      ['tell a story', 'phrase', 'ertak aytib bermoq', 'Grandma, please tell a story!', 'Buvijon, ertak aytib bering!'],
      ['ask for', 'phrase', "(biror narsani) so'ramoq", 'You can ask for more bread.', "Yana non so'rashingiz mumkin."],
      ['ask the way', 'phrase', "yo'l so'ramoq", 'If you get lost, ask the way.', "Adashsangiz, yo'l so'rang."],
      ['how do you say', 'phrase', '...qanday deyiladi?', "How do you say 'rahmat' in English?", 'Inglizchada «rahmat» qanday deyiladi?'],
    ],
  },
  {
    unit: 49,
    title: 'Moving',
    titleUz: "Harakat fe'llari",
    emoji: '🏃',
    words: [
      ['walk', 'verb', 'piyoda yurmoq', 'I walk to work every day.', 'Har kuni ishga piyoda boraman.'],
      ['run', 'verb', 'yugurmoq', 'He runs five kilometres every morning.', 'U har tong besh kilometr yuguradi.'],
      ['drive', 'verb', 'haydamoq', 'My mother can drive a car.', 'Onam mashina hayday oladi.'],
      ['ride', 'verb', 'minmoq (ot, velosiped)', 'Can you ride a bike?', 'Velosiped hayday olasanmi?'],
      ['fly', 'verb', 'uchmoq', 'Birds fly south in winter.', 'Qishda qushlar janubga uchib ketadi.'],
      ['swim', 'verb', 'suzmoq', 'I can swim very well.', 'Men juda yaxshi suza olaman.'],
      ['climb', 'verb', 'tirmashib chiqmoq', 'We climbed the mountain in five hours.', "Tog'ga besh soatda chiqdik."],
      ['jump', 'verb', 'sakramoq', 'The cat jumped onto the table.', 'Mushuk stolga sakrab chiqdi.'],
      ['fall', 'verb', 'yiqilmoq', "Be careful, don't fall!", "Ehtiyot bo'l, yiqilma!"],
      ['dance', 'verb', 'raqs tushmoq', 'They danced all night at the wedding.', "To'yda tun bo'yi raqs tushishdi."],
      ['carry', 'verb', "ko'tarib bormoq", 'Can you help me carry this box?', "Bu qutini ko'tarishga yordam berasizmi?"],
      ['catch', 'verb', 'ushlamoq; ulgurmoq', "Run, or we won't catch the bus!", 'Yugur, bo\'lmasa avtobusga ulgurmaymiz!'],
      ['miss', 'verb', 'qolib ketmoq (transportdan)', 'Hurry up or you will miss the train.', 'Shoshil, bo\'lmasa poyezddan qolasan.'],
    ],
  },
  {
    unit: 50,
    title: 'Conjunctions and connecting words',
    titleUz: "Bog'lovchilar",
    emoji: '🔗',
    words: [
      ['and', 'conjunction', 'va', 'I like tea and coffee.', 'Choy va qahvani yoqtiraman.'],
      ['but', 'conjunction', 'lekin', "It's cold but sunny.", 'Sovuq, lekin quyoshli.'],
      ['or', 'conjunction', 'yoki', 'Do you want tea or coffee?', 'Choy ichasizmi yoki qahva?'],
      ['because', 'conjunction', 'chunki, ...gani uchun', 'I stayed at home because I was ill.', "Kasal bo'lganim uchun uyda qoldim."],
      ['so', 'conjunction', 'shuning uchun', 'It was raining, so we took a taxi.', "Yomg'ir yog'ayotgan edi, shuning uchun taksiga o'tirdik."],
      ['when', 'conjunction', '-ganda, qachon', 'Call me when you arrive.', "Yetib kelganingda qo'ng'iroq qil."],
      ['if', 'conjunction', 'agar', 'If it rains, we will stay at home.', "Agar yomg'ir yog'sa, uyda qolamiz."],
      ['before', 'preposition', '...dan oldin', 'Wash your hands before dinner.', "Kechki ovqatdan oldin qo'lingni yuv."],
      ['after', 'preposition', '...dan keyin', 'We went for a walk after lunch.', 'Tushlikdan keyin sayrga chiqdik.'],
      ['also', 'adverb', 'shuningdek, ham', 'She speaks English and also French.', 'U ingliz tilida, shuningdek, fransuz tilida ham gapiradi.'],
      ['too', 'adverb', 'ham (gap oxirida)', "I'm hungry. Me too!", 'Qornim och. Meniki ham!'],
      ['only', 'adverb', 'faqat', 'I only have ten minutes.', "Faqat o'n daqiqam bor."],
      ['than', 'conjunction', '...dan (qiyoslashda)', 'My brother is taller than me.', 'Akam mendan baland.'],
      ['even', 'adverb', 'hatto', 'He works even on Sundays.', 'U hatto yakshanba kunlari ham ishlaydi.'],
    ],
  },
  {
    unit: 51,
    title: 'Days, months, seasons',
    titleUz: 'Kunlar, oylar, fasllar',
    emoji: '📅',
    words: [
      ['Monday', 'noun', 'dushanba', 'The shop is closed on Monday.', "Do'kon dushanba kuni yopiq."],
      ['Friday', 'noun', 'juma', 'Friday is the last day of the working week.', 'Juma — ish haftasining oxirgi kuni.'],
      ['weekend', 'noun', 'dam olish kunlari', 'What are you doing at the weekend?', 'Dam olish kunlari nima qilasan?'],
      ['January', 'noun', 'yanvar', 'It often snows in January.', "Yanvarda ko'pincha qor yog'adi."],
      ['July', 'noun', 'iyul', 'July is the hottest month in Tashkent.', 'Toshkentda iyul — eng issiq oy.'],
      ['spring', 'noun', 'bahor', 'Navruz is at the beginning of spring.', "Navro'z bahorning boshida."],
      ['summer', 'noun', 'yoz', 'We go to the mountains in summer.', "Yozda tog'ga boramiz."],
      ['autumn', 'noun', 'kuz', 'The leaves are yellow in autumn.', 'Kuzda barglar sarg\'ayadi.'],
      ['winter', 'noun', 'qish', 'Winter in Uzbekistan can be very cold.', "O'zbekistonda qish juda sovuq bo'lishi mumkin."],
      ['season', 'noun', 'fasl', 'Which season do you like best?', "Qaysi faslni eng ko'p yoqtirasiz?"],
      ['century', 'noun', 'asr', 'This mosque was built in the fifteenth century.', 'Bu masjid XV asrda qurilgan.'],
      ['fortnight', 'noun', 'ikki hafta', "I'm going on holiday for a fortnight.", "Ikki haftaga ta'tilga chiqyapman."],
      ['yesterday', 'adverb', 'kecha', 'It was very hot yesterday.', 'Kecha juda issiq edi.'],
      ['tomorrow', 'adverb', 'ertaga', 'See you tomorrow!', "Ertaga ko'rishamiz!"],
      ['the day after tomorrow', 'phrase', 'indinga', 'The exam is the day after tomorrow.', 'Imtihon indinga.'],
      ['leap year', 'phrase', 'kabisa yili', 'February has 29 days in a leap year.', "Kabisa yilida fevral 29 kun bo'ladi."],
    ],
  },
  {
    unit: 52,
    title: 'Time words',
    titleUz: "Vaqt so'zlari",
    emoji: '⏰',
    words: [
      ['ago', 'adverb', 'oldin (... avval)', 'I moved to Tashkent three years ago.', "Uch yil oldin Toshkentga ko'chib keldim."],
      ['always', 'adverb', 'doim', 'She is always on time.', "U doim o'z vaqtida keladi."],
      ['never', 'adverb', 'hech qachon', 'I never drink coffee at night.', 'Kechasi hech qachon qahva ichmayman.'],
      ['often', 'adverb', "tez-tez, ko'pincha", 'We often eat plov on Thursdays.', "Payshanba kunlari ko'pincha osh yeymiz."],
      ['rarely', 'adverb', 'kamdan-kam', 'My brother rarely calls me.', "Akam menga kamdan-kam qo'ng'iroq qiladi."],
      ['once', 'adverb', 'bir marta', 'I go to the gym once a week.', 'Sport zaliga haftada bir marta boraman.'],
      ['twice', 'adverb', 'ikki marta', 'I brush my teeth twice a day.', 'Tishimni kuniga ikki marta yuvaman.'],
      ['at the moment', 'phrase', 'hozir, ayni paytda', "She's busy at the moment.", 'U hozir band.'],
      ['recently', 'adverb', 'yaqinda', 'Have you seen any good films recently?', "Yaqinda yaxshi film ko'rdingizmi?"],
      ['soon', 'adverb', 'tez orada', 'The bus will come soon.', 'Avtobus tez orada keladi.'],
      ['now and then', 'phrase', 'vaqti-vaqti bilan', 'I see my old friends now and then.', "Eski do'stlarimni vaqti-vaqti bilan ko'rib turaman."],
      ['in a moment', 'phrase', 'bir zumda, hozir', "I'll be back in a moment.", 'Hozir qaytaman.'],
      ["o'clock", 'adverb', "soat (to'liq soat)", "The lesson starts at nine o'clock.", "Dars soat to'qqizda boshlanadi."],
      ['future', 'noun', 'kelajak', 'What do you want to do in the future?', 'Kelajakda nima qilmoqchisiz?'],
      ['past', 'noun', "o'tmish", 'In the past, people travelled by camel.', "O'tmishda odamlar tuyada sayohat qilgan."],
    ],
  },
  {
    unit: 53,
    title: 'Places',
    titleUz: "Joy so'zlari",
    emoji: '📍',
    words: [
      ['abroad', 'adverb', 'chet elda, chet elga', 'My brother works abroad.', 'Akam chet elda ishlaydi.'],
      ['at home', 'phrase', 'uyda', "I'm at home all day today.", "Bugun kun bo'yi uydaman."],
      ['away', 'adverb', "uzoqda, uyda yo'q", 'My parents are away this week.', "Ota-onam bu hafta uyda yo'q."],
      ['everywhere', 'adverb', 'hamma joyda', 'I looked everywhere for my keys.', 'Kalitlarimni hamma joydan qidirdim.'],
      ['middle', 'noun', "o'rta", 'The table is in the middle of the room.', "Stol xonaning o'rtasida."],
      ['front', 'noun', 'old tomon', "Let's sit at the front of the bus.", "Avtobusning old tomonida o'tiraylik."],
      ['top', 'noun', 'tepa, yuqori qism', 'Write your name at the top of the page.', 'Ismingizni sahifaning tepasiga yozing.'],
      ['bottom', 'noun', 'pastki qism', 'Sign at the bottom of the form.', "Anketaning pastiga imzo qo'ying."],
      ['beginning', 'noun', 'boshi, boshlanish', 'The beginning of the film was boring.', 'Filmning boshi zerikarli edi.'],
      ['end', 'noun', 'oxiri', 'Turn right at the end of the street.', "Ko'chaning oxirida o'ngga buriling."],
      ['on the right', 'phrase', "o'ng tomonda", 'The bank is on the right.', "Bank o'ng tomonda."],
      ['here', 'adverb', 'bu yerda, bu yerga', 'Come here, please.', 'Bu yerga keling, iltimos.'],
      ['there', 'adverb', 'u yerda, u yerga', 'Put the box over there.', "Qutini u yerga qo'ying."],
      ['side', 'noun', 'tomon, yon', 'There are shops on both sides of the street.', "Ko'chaning ikki tomonida do'konlar bor."],
    ],
  },
  {
    unit: 54,
    title: 'Manner',
    titleUz: 'Qanday qilib? (ravishlar)',
    emoji: '🐢',
    words: [
      ['fast', 'adverb', 'tez (tezlik bilan)', 'He drives too fast.', 'U juda tez haydaydi.'],
      ['slowly', 'adverb', 'sekin', 'Please speak slowly.', 'Iltimos, sekin gapiring.'],
      ['loudly', 'adverb', 'baland ovozda', "Don't talk so loudly in the library.", 'Kutubxonada bunchalik baland gapirma.'],
      ['quietly', 'adverb', 'sekingina, past ovozda', 'She closed the door quietly.', 'U eshikni sekingina yopdi.'],
      ['well', 'adverb', 'yaxshi', 'She sings very well.', 'U juda yaxshi kuylaydi.'],
      ['badly', 'adverb', 'yomon', 'I slept badly last night.', 'Kecha yomon uxladim.'],
      ['friendly', 'adjective', 'samimiy, do\'stona', 'The people here are very friendly.', 'Bu yerdagi odamlar juda samimiy.'],
      ['the right way', 'phrase', "to'g'ri yo'l, to'g'ri usul", 'Is this the right way to the station?', "Vokzalga to'g'ri yo'l shumi?"],
      ['wrong', 'adjective', "noto'g'ri", 'Sorry, I think this is the wrong number.', "Kechirasiz, menimcha, raqam noto'g'ri."],
      ['hard', 'adverb', 'tirishib, qattiq', 'My parents work very hard.', "Ota-onam juda ko'p mehnat qiladi."],
      ['carefully', 'adverb', 'diqqat bilan', 'Read the question carefully.', "Savolni diqqat bilan o'qing."],
      ['easily', 'adverb', 'oson', 'She passed the exam easily.', "U imtihondan oson o'tdi."],
    ],
  },
  {
    unit: 55,
    title: 'Common uncountable nouns',
    titleUz: 'Sanalmaydigan otlar',
    emoji: '💧',
    words: [
      ['advice', 'noun', 'maslahat', 'Can you give me some advice?', 'Menga maslahat bera olasizmi?'],
      ['information', 'noun', "ma'lumot", 'I need some information about trains.', "Poyezdlar haqida ma'lumot kerak."],
      ['money', 'noun', 'pul', "I don't have much money.", "Pulim ko'p emas."],
      ['traffic', 'noun', "yo'l harakati", 'There is a lot of traffic in the morning.', "Ertalab yo'lda mashina ko'p."],
      ['travel', 'noun', 'sayohat (qilish)', 'Travel is my favourite hobby.', "Sayohat — sevimli mashg'ulotim."],
      ['accommodation', 'noun', 'turar joy', 'The price includes accommodation and meals.', 'Narxga turar joy va ovqat kiradi.'],
      ['water', 'noun', 'suv', 'Can I have some water, please?', 'Suv bera olasizmi, iltimos?'],
      ['butter', 'noun', "sariyog'", 'Put some butter on your bread.', "Noningga sariyog' surt."],
      ['a loaf of bread', 'phrase', 'bitta non (butun)', 'Buy a loaf of bread on your way home.', 'Uyga kelayotib bitta non ol.'],
      ['a piece of', 'phrase', "bir bo'lak", 'Can I have a piece of cake?', "Bir bo'lak tort olsam bo'ladimi?"],
      ['a kilo of', 'phrase', 'bir kilo', 'A kilo of apples, please.', 'Bir kilo olma, iltimos.'],
      ['spaghetti', 'noun', 'spagetti', 'The children love spaghetti.', "Bolalar spagettini yaxshi ko'radi."],
    ],
  },
  {
    unit: 56,
    title: 'Common adjectives: good and bad things',
    titleUz: 'Yaxshi va yomon sifatlar',
    emoji: '👍',
    words: [
      ['good', 'adjective', 'yaxshi', 'This is a good book.', 'Bu yaxshi kitob.'],
      ['nice', 'adjective', 'yoqimli', 'Have a nice day!', "Kuningiz yaxshi o'tsin!"],
      ['lovely', 'adjective', 'juda yoqimli, chiroyli', 'What a lovely dress!', "Qanday chiroyli ko'ylak!"],
      ['wonderful', 'adjective', 'ajoyib', 'We had a wonderful time in Khiva.', "Xivada ajoyib vaqt o'tkazdik."],
      ['excellent', 'adjective', "a'lo", 'Your English is excellent.', "Ingliz tilingiz a'lo darajada."],
      ['great', 'adjective', "zo'r", "That's a great idea!", "Bu zo'r fikr!"],
      ['perfect', 'adjective', 'mukammal, ayni muddao', 'The weather is perfect for a picnic.', 'Havo piknik uchun ayni muddao.'],
      ['not bad', 'phrase', 'yomon emas', 'How was the film? Not bad.', 'Film qanday edi? Yomon emas.'],
      ['awful', 'adjective', 'juda yomon', 'The food was awful.', 'Ovqat juda yomon edi.'],
      ['terrible', 'adjective', 'dahshatli', 'There was a terrible accident on the road.', "Yo'lda dahshatli avariya bo'ldi."],
      ['horrible', 'adjective', 'yoqimsiz, jirkanch', 'What a horrible smell!', 'Qanday yoqimsiz hid!'],
      ['dreadful', 'adjective', "qo'rqinchli darajada yomon", 'The traffic this morning was dreadful.', "Bugun ertalabki tirbandlik qo'rqinchli edi."],
    ],
  },
  {
    unit: 57,
    title: 'Words and prepositions',
    titleUz: "Predlog bilan keladigan so'zlar",
    emoji: '🔤',
    words: [
      ['wait for', 'phrase', 'kutmoq', 'Please wait for me here.', 'Iltimos, meni shu yerda kuting.'],
      ['look at', 'phrase', 'qaramoq', 'Look at this photo!', 'Bu rasmga qara!'],
      ['look after', 'phrase', "qarab turmoq, g'amxo'rlik qilmoq", 'Can you look after my cat this weekend?', 'Dam olish kunlari mushugimga qarab tura olasanmi?'],
      ['look forward to', 'phrase', 'intiqlik bilan kutmoq', 'I look forward to seeing you.', "Sizni ko'rishni intiqlik bilan kutaman."],
      ['belong to', 'phrase', "tegishli bo'lmoq", 'Does this bag belong to you?', 'Bu sumka siznikimi?'],
      ['pay for', 'phrase', "...uchun to'lamoq", 'I will pay for the tickets.', "Chiptalar uchun men to'layman."],
      ['think about', 'phrase', "haqida o'ylamoq", 'I often think about my childhood.', "Bolaligim haqida tez-tez o'ylayman."],
      ['afraid of', 'phrase', "...dan qo'rqmoq", 'My little sister is afraid of dogs.', "Singlim itlardan qo'rqadi."],
      ['good at', 'phrase', '...da kuchli', 'He is good at maths.', 'U matematikada kuchli.'],
      ['bad at', 'phrase', '...ni yaxshi bilmaslik', "I'm bad at drawing.", 'Rasm chizishni yaxshi bilmayman.'],
      ['interested in', 'phrase', '...ga qiziqmoq', 'Are you interested in history?', 'Tarixga qiziqasizmi?'],
      ['proud of', 'phrase', '...bilan faxrlanmoq', 'We are proud of our son.', "O'g'limiz bilan faxrlanamiz."],
    ],
  },
  {
    unit: 58,
    title: 'Prefixes',
    titleUz: "Old qo'shimchalar",
    emoji: '➕',
    words: [
      ['impossible', 'adjective', 'imkonsiz', "It's impossible to finish this today.", "Buni bugun tugatishning iloji yo'q."],
      ['unhappy', 'adjective', 'baxtsiz, xafa', 'She looks unhappy today.', "U bugun xafa ko'rinadi."],
      ['unsafe', 'adjective', 'xavfli', 'This old bridge is unsafe.', "Bu eski ko'prik xavfli."],
      ['informal', 'adjective', 'norasmiy, oddiy', 'You can wear informal clothes to the party.', 'Bazmga oddiy kiyimda kelishingiz mumkin.'],
      ['ex-wife', 'noun', 'sobiq xotin', 'He still talks to his ex-wife.', 'U hali ham sobiq xotini bilan gaplashadi.'],
      ['ex-boyfriend', 'noun', 'sobiq yigiti', 'She met her ex-boyfriend at the shop.', "U do'konda sobiq yigitini uchratdi."],
      ['half-price', 'adjective', 'yarim narxda', 'These shoes are half-price today.', 'Bu tuflilar bugun yarim narxda.'],
      ['rewrite', 'verb', 'qayta yozmoq', 'Please rewrite this sentence.', 'Iltimos, bu gapni qayta yozing.'],
      ['redo', 'verb', 'qayta qilmoq', 'I have to redo my homework.', 'Uy vazifamni qayta qilishim kerak.'],
      ['pre-school', 'noun', "maktabgacha ta'lim (bog'cha)", 'My daughter goes to pre-school.', "Qizim bog'chaga boradi."],
      ['non-smoking', 'adjective', 'chekilmaydigan', "I'd like a non-smoking room.", 'Chekilmaydigan xona xohlardim.'],
      ['dislike', 'verb', 'yoqtirmaslik', 'I dislike cold weather.', 'Sovuq havoni yoqtirmayman.'],
    ],
  },
  {
    unit: 59,
    title: 'Suffixes',
    titleUz: "So'z yasovchi qo'shimchalar",
    emoji: '🧩',
    words: [
      ['swimmer', 'noun', 'suzuvchi', 'She is a very good swimmer.', 'U juda yaxshi suzuvchi.'],
      ['worker', 'noun', 'ishchi', 'The factory has five hundred workers.', 'Zavodda besh yuz ishchi bor.'],
      ['instructor', 'noun', "o'rgatuvchi, instruktor", 'My driving instructor is very patient.', "Haydashni o'rgatuvchi ustozim juda sabrli."],
      ['calculator', 'noun', 'kalkulyator', 'You can use a calculator in the exam.', 'Imtihonda kalkulyatordan foydalanish mumkin.'],
      ['useful', 'adjective', 'foydali', 'This dictionary is very useful.', "Bu lug'at juda foydali."],
      ['useless', 'adjective', 'foydasiz', 'This old phone is useless now.', 'Bu eski telefon endi foydasiz.'],
      ['endless', 'adjective', 'cheksiz', 'The road through the desert seemed endless.', "Sahro orqali yo'l cheksizdek tuyuldi."],
      ['happiness', 'noun', 'baxt', "Money doesn't always bring happiness.", 'Pul har doim ham baxt keltirmaydi.'],
      ['sadness', 'noun', "qayg'u, g'am", 'I felt great sadness when she left.', "U ketganda qattiq qayg'urdim."],
      ['sandy', 'adjective', 'qumli', 'We walked along the sandy beach.', "Qumli sohil bo'ylab yurdik."],
      ['happily', 'adverb', 'xursand holda', 'The children played happily in the garden.', "Bolalar bog'da xursand o'ynashdi."],
      ['quickly', 'adverb', 'tezda, tezlik bilan', "Come quickly, it's starting!", 'Tez kel, boshlanyapti!'],
    ],
  },
  {
    unit: 60,
    title: 'Words you may confuse',
    titleUz: "Adashtiriladigan so'zlar",
    emoji: '⚖️',
    words: [
      ['quiet', 'adjective', 'jim, sokin', 'The library is very quiet.', 'Kutubxona juda jimjit.'],
      ['quite', 'adverb', 'ancha, ozmuncha', 'The test was quite easy.', 'Test ancha oson edi.'],
      ['lend', 'verb', 'qarzga bermoq', 'Can you lend me your pen?', 'Ruchkangni qarzga berib turasanmi?'],
      ['borrow', 'verb', 'qarzga olmoq', 'Can I borrow your pen?', 'Ruchkangni olib tursam maylimi?'],
      ['loose', 'adjective', 'keng, bo\'sh (kiyim)', 'These trousers are too loose.', 'Bu shim juda keng.'],
      ['cook', 'noun', 'oshpaz', 'My father is a good cook.', 'Otam yaxshi oshpaz.'],
      ['expect', 'verb', "kutmoq (bo'lishini)", 'We expect about fifty guests.', 'Taxminan ellikta mehmon kutyapmiz.'],
      ['check', 'verb', 'tekshirmoq', 'Check your answers before you finish.', 'Tugatishdan oldin javoblaringizni tekshiring.'],
      ['control', 'verb', 'boshqarmoq', 'The pilot controls the plane.', 'Uchuvchi samolyotni boshqaradi.'],
      ['afternoon', 'noun', 'tushdan keyin', 'I have a lesson in the afternoon.', 'Tushdan keyin darsim bor.'],
      ['evening', 'noun', 'kechqurun, oqshom', 'We watch TV in the evening.', "Kechqurun televizor ko'ramiz."],
      ['night', 'noun', 'tun, kecha', "I couldn't sleep last night.", 'Kecha kechasi uxlay olmadim.'],
    ],
  },
];
