/**
 * Mavzular kutubxonasi — Elementary (A1–A2).
 *
 * Mavzular tuzilishi va so'zlar tanlovi "English Vocabulary in Use:
 * Elementary" (Cambridge) kitobining unit'lariga tayanadi. Kitobdan FAQAT
 * mavzu nomi va so'zlar olingan — tarjima, misol gaplar va ularning
 * o'zbekchasi Linguist uchun alohida yozilgan. Kitob matni, ta'riflari va
 * mashqlari ko'chirilmaydi (mualliflik huquqi).
 *
 * Yozuv: [word, partOfSpeech, translation, example, exampleUz]
 * Tekshiruv: node content/vocab-topics/validate.js
 */

module.exports = {
  key: 'elementary',
  title: 'Elementary',
  titleUz: "Boshlang'ich",
  cefr: 'A2',
  cefrRange: 'A1–A2',
  topics: [
    {
      unit: 1,
      title: 'The family',
      titleUz: 'Oila',
      emoji: '👨‍👩‍👧',
      words: [
        ['mother', 'noun', 'ona', 'My mother works at a school.', 'Onam maktabda ishlaydi.'],
        ['father', 'noun', 'ota', 'His father drives a taxi.', 'Uning otasi taksi haydaydi.'],
        ['parents', 'noun', 'ota-ona', 'My parents live in Samarkand.', 'Ota-onam Samarqandda yashaydi.'],
        ['brother', 'noun', 'aka, uka', 'I have one brother and two sisters.', 'Mening bitta akam va ikkita opam bor.'],
        ['sister', 'noun', 'opa, singil', 'My sister is a student.', 'Singlim talaba.'],
        ['son', 'noun', "o'g'il", 'Their son is five years old.', "Ularning o'g'li besh yoshda."],
        ['daughter', 'noun', 'qiz (farzand)', 'She has a daughter and a son.', "Uning bir qizi va bir o'g'li bor."],
        ['husband', 'noun', 'er (turmush o\'rtog\'i)', 'Her husband is a doctor.', 'Uning eri shifokor.'],
        ['wife', 'noun', 'xotin, rafiqa', 'His wife speaks English well.', 'Uning rafiqasi inglizchani yaxshi gapiradi.'],
        ['grandmother', 'noun', 'buvi', 'My grandmother makes very good plov.', 'Buvim juda mazali osh qiladi.'],
        ['grandfather', 'noun', 'bobo', 'My grandfather is eighty.', 'Bobom sakson yoshda.'],
        ['uncle', 'noun', "amaki, tog'a", 'My uncle lives in Tashkent.', 'Amakim Toshkentda yashaydi.'],
        ['aunt', 'noun', 'xola, amma', 'My aunt has three children.', 'Xolamning uchta farzandi bor.'],
        ['cousin', 'noun', 'amakivachcha, xolavachcha', 'My cousin and I go to the same school.', 'Xolavachcham bilan bir maktabga boramiz.'],
        ['only child', 'phrase', 'yolg\'iz farzand', 'He is an only child.', "U yolg'iz farzand."],
        ['relatives', 'noun', 'qarindoshlar', 'All our relatives come to the wedding.', "Barcha qarindoshlarimiz to'yga keladi."],
      ],
    },
    {
      unit: 2,
      title: 'Birth, marriage and death',
      titleUz: "Tug'ilish, nikoh va o'lim",
      emoji: '💍',
      words: [
        ['birthday', 'noun', "tug'ilgan kun", 'My birthday is in May.', "Tug'ilgan kunim mayda."],
        ['born', 'adjective', "tug'ilgan", 'I was born in Bukhara.', "Men Buxoroda tug'ilganman."],
        ['baby', 'noun', 'chaqaloq', 'The baby is sleeping.', 'Chaqaloq uxlayapti.'],
        ['married', 'adjective', 'uylangan, turmushga chiqqan', 'My brother is married.', 'Akam uylangan.'],
        ['single', 'adjective', 'turmush qurmagan', 'Is your sister single?', 'Opangiz turmush qurmaganmi?'],
        ['divorced', 'adjective', 'ajrashgan', 'His parents are divorced.', 'Uning ota-onasi ajrashgan.'],
        ['wedding', 'noun', "to'y", 'The wedding is on Saturday.', "To'y shanba kuni."],
        ['get married', 'phrase', 'turmush qurmoq', 'They want to get married next year.', 'Ular kelasi yili turmush qurmoqchi.'],
        ['bride', 'noun', 'kelin', 'The bride wore a white dress.', "Kelin oq ko'ylak kiygan edi."],
        ['bridegroom', 'noun', 'kuyov', 'The bridegroom was very nervous.', 'Kuyov juda hayajonda edi.'],
        ['honeymoon', 'noun', 'asal oyi', 'They went to Turkey for their honeymoon.', 'Ular asal oyi uchun Turkiyaga borishdi.'],
        ['die', 'verb', "vafot etmoq, o'lmoq", 'Plants die without water.', "O'simliklar suvsiz nobud bo'ladi."],
        ['funeral', 'noun', 'dafn marosimi, janoza', 'Many people came to the funeral.', "Janozaga ko'p odam keldi."],
        ['death', 'noun', "o'lim, vafot", 'Her death was a shock to the family.', "Uning vafoti oila uchun zarba bo'ldi."],
      ],
    },
    {
      unit: 3,
      title: 'Parts of the body',
      titleUz: "Tana a'zolari",
      emoji: '🖐️',
      words: [
        ['head', 'noun', 'bosh', 'My head hurts.', "Boshim og'riyapti."],
        ['face', 'noun', 'yuz', 'She has a round face.', 'Uning yuzi dumaloq.'],
        ['eye', 'noun', "ko'z", 'He has brown eyes.', "Uning ko'zlari jigarrang."],
        ['ear', 'noun', 'quloq', 'The cat has big ears.', 'Mushukning quloqlari katta.'],
        ['nose', 'noun', 'burun', "Don't touch your nose.", 'Burningizga tegmang.'],
        ['mouth', 'noun', "og'iz", 'Open your mouth, please.', "Og'zingizni oching, iltimos."],
        ['tooth', 'noun', 'tish', 'I have a bad tooth.', "Bitta tishim og'riyapti."],
        ['neck', 'noun', "bo'yin", 'Giraffes have long necks.', "Jirafalarning bo'yni uzun."],
        ['shoulder', 'noun', 'yelka', 'He put his bag on his shoulder.', 'U sumkasini yelkasiga osdi.'],
        ['arm', 'noun', "qo'l (yelkadan kaftgacha)", 'She broke her arm.', "U qo'lini sindirib oldi."],
        ['hand', 'noun', "qo'l, kaft", 'Wash your hands before dinner.', "Kechki ovqatdan oldin qo'lingizni yuving."],
        ['finger', 'noun', 'barmoq', 'She has a ring on her finger.', "Uning barmog'ida uzuk bor."],
        ['leg', 'noun', 'oyoq', 'My legs are tired after the walk.', 'Sayrdan keyin oyoqlarim charchadi.'],
        ['foot', 'noun', 'oyoq panjasi', 'I hurt my foot playing football.', "Futbol o'ynab, oyog'imni lat yedirdim."],
        ['knee', 'noun', 'tizza', 'The water came up to my knees.', 'Suv tizzamgacha keldi.'],
        ['back', 'noun', 'bel, orqa', 'Sit with your back straight.', "Belingizni tik tutib o'tiring."],
        ['stomach', 'noun', 'qorin, oshqozon', 'I have a pain in my stomach.', "Qornim og'riyapti."],
        ['heart', 'noun', 'yurak', 'The heart pumps blood around the body.', "Yurak qonni butun tanaga haydaydi."],
      ],
    },
    {
      unit: 4,
      title: 'Clothes',
      titleUz: 'Kiyim-kechak',
      emoji: '👕',
      words: [
        ['shirt', 'noun', "ko'ylak (erkaklar)", 'He is wearing a white shirt.', "U oq ko'ylak kiygan."],
        ['trousers', 'noun', 'shim', 'These trousers are too long.', 'Bu shim juda uzun.'],
        ['jeans', 'noun', 'jinsi shim', 'I usually wear jeans at the weekend.', 'Dam olish kunlari odatda jinsi shim kiyaman.'],
        ['dress', 'noun', "ko'ylak (ayollar)", 'She bought a red dress for the party.', "U bazm uchun qizil ko'ylak sotib oldi."],
        ['skirt', 'noun', 'yubka', 'Her skirt is blue.', "Uning yubkasi ko'k."],
        ['jacket', 'noun', 'kurtka', "Take a jacket, it's cold.", 'Kurtka ol, sovuq.'],
        ['coat', 'noun', 'palto', 'In winter I wear a warm coat.', 'Qishda issiq palto kiyaman.'],
        ['hat', 'noun', 'shlyapa, bosh kiyim', 'My grandfather always wears a hat.', 'Bobom doim shlyapa kiyadi.'],
        ['shoes', 'noun', 'poyabzal, tufli', 'These shoes are new.', 'Bu tuflilar yangi.'],
        ['socks', 'noun', 'paypoq', 'I need new socks.', 'Menga yangi paypoq kerak.'],
        ['gloves', 'noun', "qo'lqop", "Put your gloves on, it's snowing.", "Qo'lqopingni kiy, qor yog'yapti."],
        ['scarf', 'noun', 'sharf', 'She has a long scarf.', 'Uning uzun sharfi bor.'],
        ['belt', 'noun', 'kamar', 'These trousers need a belt.', 'Bu shimga kamar kerak.'],
        ['tie', 'noun', 'galstuk', 'My father wears a tie to work.', 'Otam ishga galstuk taqadi.'],
        ['wear', 'verb', 'kiymoq (kiyib yurmoq)', 'What are you going to wear tonight?', 'Bugun kechqurun nima kiyasan?'],
        ['put on', 'phrase', 'kiymoq (ustiga)', 'Put on your coat before you go out.', 'Chiqishdan oldin paltongni kiy.'],
        ['take off', 'phrase', 'yechmoq', 'Please take off your shoes.', 'Iltimos, poyabzalingizni yeching.'],
      ],
    },
    {
      unit: 5,
      title: 'Describing people',
      titleUz: 'Odamlarni tasvirlash',
      emoji: '🧑',
      words: [
        ['tall', 'adjective', "baland bo'yli", 'My brother is very tall.', "Akam juda baland bo'yli."],
        ['short', 'adjective', "past bo'yli; kalta", 'She has short hair.', 'Uning sochi kalta.'],
        ['slim', 'adjective', "kelishgan, ozg'in", 'She is slim and tall.', "U ozg'in va baland bo'yli."],
        ['overweight', 'adjective', 'ortiqcha vaznli', 'The doctor said I am a little overweight.', 'Shifokor biroz ortiqcha vaznim borligini aytdi.'],
        ['good-looking', 'adjective', 'kelishgan, chiroyli', 'Her husband is very good-looking.', 'Uning eri juda kelishgan.'],
        ['beautiful', 'adjective', "go'zal", 'What a beautiful girl!', "Qanday go'zal qiz!"],
        ['pretty', 'adjective', 'yoqimtoy, chiroyli', 'Your little sister is very pretty.', 'Singlingiz juda yoqimtoy.'],
        ['young', 'adjective', 'yosh', 'My mother looks young for her age.', "Onam yoshiga nisbatan yosh ko'rinadi."],
        ['elderly', 'adjective', "keksa, yoshi ulug'", 'An elderly man sat next to me.', "Yonimga keksa kishi o'tirdi."],
        ['middle-aged', 'adjective', "o'rta yoshli", 'The teacher is a middle-aged woman.', "O'qituvchi o'rta yoshli ayol."],
        ['blonde', 'adjective', 'sariq (soch)', 'She has long blonde hair.', 'Uning uzun sariq sochi bor.'],
        ['dark', 'adjective', "qora, to'q", 'He has dark hair and brown eyes.', "Uning sochi qora, ko'zlari jigarrang."],
        ['beard', 'noun', 'soqol', 'My uncle has a grey beard.', "Amakimning oq soqoli bor."],
        ['moustache', 'noun', "mo'ylov", 'My father has a moustache.', "Otamning mo'ylovi bor."],
        ['look like', 'phrase', "o'xshamoq", 'You look like your mother.', "Sen onangga o'xshaysan."],
        ['weight', 'noun', 'vazn', 'What is your weight?', 'Vazningiz qancha?'],
      ],
    },
    {
      unit: 6,
      title: 'Health and illness',
      titleUz: 'Salomatlik va kasallik',
      emoji: '🩺',
      words: [
        ['ill', 'adjective', 'kasal', "I can't come to school, I'm ill.", 'Maktabga bora olmayman, kasalman.'],
        ['illness', 'noun', 'kasallik', 'Malaria is a serious illness.', 'Bezgak jiddiy kasallik.'],
        ['health', 'noun', "sog'liq", 'Smoking is bad for your health.', "Chekish sog'lig'ingizga zarar."],
        ['headache', 'noun', "bosh og'rig'i", 'I have a terrible headache.', "Boshim qattiq og'riyapti."],
        ['toothache', 'noun', "tish og'rig'i", 'If you have toothache, see a dentist.', "Tishingiz og'risa, tish shifokoriga boring."],
        ['cold', 'noun', 'shamollash', 'I have a cold and a sore throat.', "Shamollaganman, tomog'im og'riyapti."],
        ['hospital', 'noun', 'kasalxona', 'My grandfather is in hospital.', 'Bobom kasalxonada.'],
        ['dentist', 'noun', 'tish shifokori', 'I go to the dentist twice a year.', 'Yiliga ikki marta tish shifokoriga boraman.'],
        ['diet', 'noun', 'ovqatlanish tartibi, parhez', 'A good diet has lots of fruit and vegetables.', "Yaxshi ovqatlanishda meva va sabzavot ko'p bo'ladi."],
        ['exercise', 'noun', 'jismoniy mashq', 'Exercise is good for your heart.', 'Jismoniy mashq yurak uchun foydali.'],
        ['relax', 'verb', 'dam olmoq, bo\'shashmoq', 'After work I like to relax at home.', "Ishdan keyin uyda dam olishni yaxshi ko'raman."],
        ['stressed', 'adjective', 'asabiy, stressda', 'She feels stressed before exams.', 'U imtihonlar oldidan asabiylashadi.'],
        ['sneeze', 'verb', 'aksirmoq', 'Dust makes me sneeze.', 'Chang meni aksirtiradi.'],
        ['heart attack', 'phrase', 'yurak xuruji', 'My neighbour had a heart attack last year.', "Qo'shnimda o'tgan yili yurak xuruji bo'ldi."],
        ['feel', 'verb', 'his qilmoq', 'How do you feel today?', "Bugun o'zingizni qanday his qilyapsiz?"],
      ],
    },
    {
      unit: 7,
      title: 'Feelings',
      titleUz: "His-tuyg'ular",
      emoji: '😊',
      words: [
        ['happy', 'adjective', 'xursand, baxtli', "I'm happy to see you.", "Seni ko'rganimdan xursandman."],
        ['sad', 'adjective', "g'amgin, xafa", 'The film was very sad.', "Film juda g'amgin edi."],
        ['angry', 'adjective', 'jahli chiqqan', 'My father was angry with me.', 'Otamning mendan jahli chiqdi.'],
        ['tired', 'adjective', 'charchagan', "I'm tired, I want to sleep.", 'Charchadim, uxlagim kelyapti.'],
        ['hungry', 'adjective', 'och (qorni)', "Is there any food? I'm hungry.", 'Ovqat bormi? Qornim och.'],
        ['thirsty', 'adjective', 'chanqagan', "Can I have some water? I'm thirsty.", 'Suv bera olasizmi? Chanqadim.'],
        ['upset', 'adjective', "xafa, ko'ngli cho'kkan", 'She was upset about the exam results.', "U imtihon natijalaridan xafa bo'ldi."],
        ['love', 'verb', "sevmoq, juda yaxshi ko'rmoq", 'I love my family.', "Oilamni juda yaxshi ko'raman."],
        ['hate', 'verb', "yomon ko'rmoq", 'I hate cold weather.', "Sovuq havoni yomon ko'raman."],
        ['prefer', 'verb', "afzal ko'rmoq", 'I prefer tea to coffee.', "Qahvadan ko'ra choyni afzal ko'raman."],
        ['hope', 'verb', 'umid qilmoq', 'I hope you feel better soon.', 'Tezroq tuzalib ketasiz degan umiddaman.'],
        ['want', 'verb', 'xohlamoq', 'I want a new phone.', 'Yangi telefon xohlayman.'],
        ['feelings', 'noun', "his-tuyg'ular", "Don't hurt her feelings.", "Uning ko'nglini og'ritma."],
        ['hot', 'adjective', 'issiq (isib ketgan)', "Open the window, I'm hot.", 'Derazani och, isib ketdim.'],
      ],
    },
    {
      unit: 8,
      title: 'Greetings and wishes',
      titleUz: 'Salomlashish va tilaklar',
      emoji: '👋',
      words: [
        ['good morning', 'phrase', 'xayrli tong', 'Good morning, how did you sleep?', 'Xayrli tong, qanday uxladingiz?'],
        ['good evening', 'phrase', 'xayrli kech', 'Good evening, ladies and gentlemen.', 'Xayrli kech, xonimlar va janoblar.'],
        ['goodnight', 'phrase', 'xayrli tun', 'Goodnight, see you tomorrow.', "Xayrli tun, ertaga ko'rishamiz."],
        ['goodbye', 'phrase', 'xayr', 'Say goodbye to your grandmother.', 'Buvingga xayr de.'],
        ['see you soon', 'phrase', "tez orada ko'rishamiz", 'Bye! See you soon.', "Xayr! Tez orada ko'rishamiz."],
        ['how are you', 'phrase', 'qalaysiz?', 'Hi Aziz, how are you?', 'Salom Aziz, qalaysan?'],
        ['thank you', 'phrase', 'rahmat', 'Thank you for your help.', 'Yordamingiz uchun rahmat.'],
        ['excuse me', 'phrase', 'kechirasiz (murojaat qilganda)', 'Excuse me, where is the station?', 'Kechirasiz, vokzal qayerda?'],
        ['sorry', 'phrase', 'uzr', "Sorry, I'm late.", 'Uzr, kechikdim.'],
        ['congratulations', 'phrase', 'tabriklayman', 'Congratulations on your new job!', 'Yangi ishingiz muborak!'],
        ['good luck', 'phrase', 'omad', 'Good luck in your exam tomorrow!', 'Ertangi imtihoningizda omad!'],
        ['happy birthday', 'phrase', "tug'ilgan kuning bilan", 'Happy birthday, Madina!', "Tug'ilgan kuning bilan, Madina!"],
        ['well done', 'phrase', 'barakalla', 'Well done! You got full marks.', "Barakalla! To'liq ball olding."],
        ['bless you', 'phrase', "sog' bo'ling (aksirganda)", "When someone sneezes, we say 'Bless you'.", "Kimdir aksirsa, «Sog' bo'ling» deymiz."],
        ['happy new year', 'phrase', 'yangi yil bilan', 'Happy New Year to you and your family!', 'Sizni va oilangizni Yangi yil bilan!'],
      ],
    },
    {
      unit: 9,
      title: 'Useful words and expressions',
      titleUz: 'Foydali ifodalar',
      emoji: '💬',
      words: [
        ["I don't mind", 'phrase', "farqi yo'q", "Tea or coffee? I don't mind.", "Choymi yoki qahva? Farqi yo'q."],
        ["it doesn't matter", 'phrase', "hechqisi yo'q", "You're late? It doesn't matter.", "Kechikdingmi? Hechqisi yo'q."],
        ["it's up to you", 'phrase', "o'zingiz hal qiling", "We can eat now or later, it's up to you.", "Hozir yoki keyinroq ovqatlanishimiz mumkin, o'zing hal qil."],
        ["let's", 'phrase', 'qani, ...-aylik', "Let's go to the park.", 'Qani, parkka boraylik.'],
        ['anyway', 'adverb', 'baribir', 'It was raining, but we went out anyway.', "Yomg'ir yog'ayotgan edi, lekin baribir chiqdik."],
        ['actually', 'adverb', 'aslida', "Actually, I'm not from Tashkent, I'm from Fergana.", "Aslida men Toshkentdan emas, Farg'onadanman."],
        ['absolutely', 'adverb', 'mutlaqo, albatta', 'Are you sure? Absolutely!', 'Ishonchingiz komilmi? Mutlaqo!'],
        ['agree', 'verb', "rozi bo'lmoq", 'I agree with you.', 'Siz bilan roziman.'],
        ['be careful', 'phrase', "ehtiyot bo'ling", 'Be careful, the floor is wet.', "Ehtiyot bo'ling, pol ho'l."],
        ['hurry up', 'phrase', 'shoshiling', 'Hurry up, the bus is coming!', 'Shoshil, avtobus kelyapti!'],
        ['what a pity', 'phrase', 'qanday afsus', "You can't come? What a pity!", 'Kela olmaysanmi? Qanday afsus!'],
        ['oh dear', 'phrase', 'voy (afsus)', 'Oh dear, I forgot my keys.', 'Voy, kalitlarimni unutibman.'],
        ['really', 'adverb', 'rostdanmi; juda', "Really? I didn't know that.", 'Rostdanmi? Buni bilmagan ekanman.'],
      ],
    },
    {
      unit: 10,
      title: 'Food and drink',
      titleUz: 'Oziq-ovqat va ichimliklar',
      emoji: '🍎',
      words: [
        ['bread', 'noun', 'non', 'We buy fresh bread every morning.', 'Har tong yangi non olamiz.'],
        ['rice', 'noun', 'guruch', 'Plov is made with rice, meat and carrots.', 'Osh guruch, go\'sht va sabzidan tayyorlanadi.'],
        ['meat', 'noun', "go'sht", "I don't eat much meat.", "Men ko'p go'sht yemayman."],
        ['fish', 'noun', 'baliq', 'We had fish for dinner.', 'Kechki ovqatga baliq yedik.'],
        ['fruit', 'noun', 'meva', 'Eat more fruit.', "Ko'proq meva yeng."],
        ['vegetable', 'noun', 'sabzavot', 'Which vegetables do you like?', 'Qaysi sabzavotlarni yoqtirasiz?'],
        ['potato', 'noun', 'kartoshka', 'My mother cooks potatoes with meat.', "Onam kartoshkani go'sht bilan pishiradi."],
        ['onion', 'noun', 'piyoz', 'Cut the onion into small pieces.', "Piyozni mayda to'g'rang."],
        ['carrot', 'noun', 'sabzi', 'Rabbits love carrots.', "Quyonlar sabzini yaxshi ko'radi."],
        ['tomato', 'noun', 'pomidor', 'Put some tomatoes in the salad.', 'Salatga pomidor soling.'],
        ['apple', 'noun', 'olma', 'An apple a day is good for you.', 'Kuniga bitta olma foydali.'],
        ['grape', 'noun', 'uzum', 'Uzbekistan is famous for its grapes.', 'O\'zbekiston uzumi bilan mashhur.'],
        ['milk', 'noun', 'sut', 'Do you take milk in your coffee?', "Qahvangizga sut qo'shasizmi?"],
        ['tea', 'noun', 'choy', 'Would you like a cup of tea?', 'Bir piyola choy ichasizmi?'],
        ['sugar', 'noun', 'shakar', 'No sugar for me, thanks.', 'Menga shakar kerak emas, rahmat.'],
        ['salt', 'noun', 'tuz', 'Pass me the salt, please.', 'Tuzni uzatib yuboring, iltimos.'],
        ['garlic', 'noun', 'sarimsoq', "This soup has a lot of garlic in it.", "Bu sho'rvada sarimsoq ko'p."],
        ['fruit juice', 'phrase', 'meva sharbati', 'I drink fruit juice at breakfast.', 'Nonushtada meva sharbati ichaman.'],
      ],
    },
    {
      unit: 11,
      title: 'In the kitchen',
      titleUz: 'Oshxonada',
      emoji: '🍳',
      words: [
        ['fridge', 'noun', 'muzlatkich', 'Put the milk in the fridge.', "Sutni muzlatkichga qo'y."],
        ['freezer', 'noun', 'muzlatgich kamerasi', 'There is ice cream in the freezer.', 'Muzlatgich kamerasida muzqaymoq bor.'],
        ['cooker', 'noun', 'plita', 'The soup is on the cooker.', "Sho'rva plita ustida."],
        ['microwave', 'noun', "mikroto'lqinli pech", 'Heat the food in the microwave.', "Ovqatni mikroto'lqinli pechda isit."],
        ['sink', 'noun', 'rakovina, chanoq', 'The dirty cups are in the sink.', 'Iflos piyolalar rakovinada.'],
        ['tap', 'noun', "jo'mrak", 'Turn off the tap!', "Jo'mrakni yop!"],
        ['cupboard', 'noun', 'shkaf (idish uchun)', 'The glasses are in the cupboard.', 'Stakanlar shkafda.'],
        ['plate', 'noun', 'tarelka', 'Can I have another plate?', 'Yana bitta tarelka bera olasizmi?'],
        ['bowl', 'noun', 'kosa', 'She ate a bowl of soup.', "U bir kosa sho'rva ichdi."],
        ['glass', 'noun', 'stakan', 'A glass of water, please.', 'Bir stakan suv, iltimos.'],
        ['knife', 'noun', 'pichoq', 'Be careful with that knife.', "U pichoqqa ehtiyot bo'l."],
        ['fork', 'noun', 'sanchqi', 'I eat salad with a fork.', 'Salatni sanchqi bilan yeyman.'],
        ['spoon', 'noun', 'qoshiq', 'I need a spoon for my soup.', "Sho'rvam uchun qoshiq kerak."],
        ['saucepan', 'noun', 'kastryul', 'Boil the water in a saucepan.', 'Suvni kastryulda qaynat.'],
        ['frying pan', 'phrase', 'tova', 'She fried the eggs in a frying pan.', 'U tuxumni tovada qovurdi.'],
        ['dishwasher', 'noun', 'idish yuvish mashinasi', 'Put the cups in the dishwasher.', 'Piyolalarni idish yuvish mashinasiga sol.'],
      ],
    },
    {
      unit: 12,
      title: 'In the bedroom and bathroom',
      titleUz: 'Yotoqxona va hammom',
      emoji: '🛏️',
      words: [
        ['bed', 'noun', 'karavot', 'My bed is next to the window.', 'Karavotim deraza yonida.'],
        ['wardrobe', 'noun', 'kiyim shkafi', 'Hang your coat in the wardrobe.', 'Paltongni kiyim shkafiga il.'],
        ['mirror', 'noun', "ko'zgu, oyna", 'She looked in the mirror.', "U ko'zguga qaradi."],
        ['alarm clock', 'phrase', 'budilnik', 'My alarm clock rings at seven.', 'Budilnigim soat yettida jiringlaydi.'],
        ['shower', 'noun', 'dush', 'The shower is not working.', 'Dush ishlamayapti.'],
        ['towel', 'noun', 'sochiq', 'Can I have a clean towel?', 'Toza sochiq bera olasizmi?'],
        ['soap', 'noun', 'sovun', 'Wash your hands with soap.', "Qo'lingni sovun bilan yuv."],
        ['shampoo', 'noun', 'shampun', 'This shampoo smells nice.', 'Bu shampunning hidi yoqimli.'],
        ['toothbrush', 'noun', "tish cho'tkasi", "Don't forget your toothbrush.", "Tish cho'tkangni unutma."],
        ['toothpaste', 'noun', 'tish pastasi', 'We need more toothpaste.', 'Bizga yana tish pastasi kerak.'],
        ['comb', 'noun', 'taroq', 'He has a small comb in his pocket.', "Uning cho'ntagida kichkina taroq bor."],
        ['toilet', 'noun', 'hojatxona', 'Where is the toilet, please?', 'Hojatxona qayerda, iltimos?'],
        ['wake up', 'phrase', "uyg'onmoq", 'I wake up at six every day.', "Har kuni soat oltida uyg'onaman."],
        ['go to bed', 'phrase', 'uxlashga yotmoq', 'Children go to bed early.', 'Bolalar erta uxlashga yotadi.'],
        ['fall asleep', 'phrase', 'uxlab qolmoq', 'Babies often fall asleep in the car.', 'Chaqaloqlar ko\'pincha mashinada uxlab qoladi.'],
        ['get dressed', 'phrase', 'kiyinmoq', "Get dressed quickly, we're late.", 'Tez kiyin, kechikyapmiz.'],
      ],
    },
    {
      unit: 13,
      title: 'In the living room',
      titleUz: 'Mehmonxonada (uyda)',
      emoji: '🛋️',
      words: [
        ['living room', 'phrase', 'mehmonxona (uyda)', 'We watch TV in the living room.', "Mehmonxonada televizor ko'ramiz."],
        ['sofa', 'noun', 'divan', 'The cat is sleeping on the sofa.', 'Mushuk divanda uxlayapti.'],
        ['armchair', 'noun', 'kreslo', 'My grandfather sits in his armchair and reads.', "Bobom kreslosida o'tirib kitob o'qiydi."],
        ['carpet', 'noun', 'gilam', 'We have a beautiful carpet from Khiva.', 'Bizda Xivadan olingan chiroyli gilam bor.'],
        ['curtain', 'noun', 'parda', 'Close the curtains, please.', 'Pardalarni yoping, iltimos.'],
        ['lamp', 'noun', 'chiroq (stol, pol chirog\'i)', 'There is a lamp next to the sofa.', 'Divan yonida chiroq bor.'],
        ['bookshelf', 'noun', 'kitob javoni', 'The bookshelf is full of books.', "Kitob javoni kitoblarga to'la."],
        ['picture', 'noun', 'rasm', 'There is a picture of the sea on the wall.', 'Devorda dengiz rasmi bor.'],
        ['remote control', 'phrase', 'pult', 'Where is the remote control?', 'Pult qayerda?'],
        ['socket', 'noun', 'rozetka', 'Is there a socket near the bed?', 'Karavot yonida rozetka bormi?'],
        ['light switch', 'phrase', "chiroq o'chirgichi", 'The light switch is next to the door.', "Chiroq o'chirgichi eshik yonida."],
        ['coffee table', 'phrase', 'past stolcha (divan oldida)', 'Put your cup on the coffee table.', "Piyolangizni stolchaga qo'ying."],
        ['turn on', 'phrase', 'yoqmoq', "Turn on the light, it's dark.", "Chiroqni yoq, qorong'i."],
        ['turn off', 'phrase', "o'chirmoq", 'Turn off the TV and go to bed.', "Televizorni o'chir va uxla."],
        ['window', 'noun', 'deraza', 'Open the window, please.', 'Derazani oching, iltimos.'],
      ],
    },
    {
      unit: 14,
      title: 'Jobs',
      titleUz: 'Kasblar',
      emoji: '👩‍⚕️',
      words: [
        ['job', 'noun', 'ish, kasb', "What's your job?", 'Kasbingiz nima?'],
        ['work', 'verb', 'ishlamoq', 'My mother works in a bank.', 'Onam bankda ishlaydi.'],
        ['teacher', 'noun', "o'qituvchi", 'Our English teacher is very kind.', "Ingliz tili o'qituvchimiz juda mehribon."],
        ['nurse', 'noun', 'hamshira', 'The nurse gave me some medicine.', 'Hamshira menga dori berdi.'],
        ['engineer', 'noun', 'muhandis', 'He is an engineer at a car factory.', 'U avtomobil zavodida muhandis.'],
        ['farmer', 'noun', 'fermer, dehqon', 'The farmer grows cotton and wheat.', "Fermer paxta va bug'doy yetishtiradi."],
        ['mechanic', 'noun', 'mexanik, usta', 'The mechanic repaired my car.', 'Usta mashinamni tuzatdi.'],
        ['secretary', 'noun', 'kotiba', 'The secretary answers the phone.', 'Kotiba telefonga javob beradi.'],
        ['waiter', 'noun', 'ofitsiant', 'The waiter brought the menu.', 'Ofitsiant menyuni olib keldi.'],
        ['police officer', 'phrase', 'politsiyachi', 'A police officer helped the old woman.', 'Politsiyachi keksa ayolga yordam berdi.'],
        ['taxi driver', 'phrase', 'taksi haydovchisi', 'The taxi driver knows every street in the city.', "Taksi haydovchisi shahardagi har bir ko'chani biladi."],
        ['shop assistant', 'phrase', 'sotuvchi', 'The shop assistant helped me find the right size.', "Sotuvchi menga to'g'ri o'lcham topishga yordam berdi."],
        ['librarian', 'noun', 'kutubxonachi', 'Ask the librarian where the books are.', "Kitoblar qayerdaligini kutubxonachidan so'ra."],
        ['hairdresser', 'noun', 'sartarosh', 'I go to the hairdresser once a month.', 'Oyda bir marta sartaroshga boraman.'],
        ['factory', 'noun', 'zavod, fabrika', 'My father works in a factory.', 'Otam zavodda ishlaydi.'],
        ['office', 'noun', 'ofis, idora', 'Her office is on the third floor.', 'Uning ofisi uchinchi qavatda.'],
      ],
    },
    {
      unit: 15,
      title: 'At school and university',
      titleUz: 'Maktab va universitetda',
      emoji: '🎓',
      words: [
        ['subject', 'noun', 'fan (dars)', 'My favourite subject is history.', 'Sevimli fanim — tarix.'],
        ['maths', 'noun', 'matematika', "I'm good at maths.", 'Matematikadan yaxshiman.'],
        ['history', 'noun', 'tarix', 'We study the history of the Silk Road.', "Buyuk ipak yo'li tarixini o'rganamiz."],
        ['geography', 'noun', 'geografiya', 'In geography we learn about countries and rivers.', "Geografiyada mamlakatlar va daryolar haqida o'rganamiz."],
        ['biology', 'noun', 'biologiya', 'In biology we study plants and animals.', "Biologiyada o'simlik va hayvonlarni o'rganamiz."],
        ['chemistry', 'noun', 'kimyo', 'The chemistry teacher is very strict.', "Kimyo o'qituvchisi juda talabchan."],
        ['physics', 'noun', 'fizika', 'Physics is difficult but interesting.', 'Fizika qiyin, lekin qiziq.'],
        ['homework', 'noun', 'uy vazifasi', 'Did you do your homework?', 'Uy vazifangni qildingmi?'],
        ['exam', 'noun', 'imtihon', 'The exam starts at nine.', "Imtihon soat to'qqizda boshlanadi."],
        ['pass an exam', 'phrase', "imtihondan o'tmoq", 'You need to study to pass an exam.', "Imtihondan o'tish uchun o'qish kerak."],
        ['degree', 'noun', 'diplom, ilmiy daraja', 'She has a degree in economics.', "Uning iqtisodiyot bo'yicha diplomi bor."],
        ['notebook', 'noun', 'daftar', 'Write the new words in your notebook.', "Yangi so'zlarni daftaringizga yozing."],
        ['ruler', 'noun', "chizg'ich", 'Draw a line with a ruler.', "Chizg'ich bilan chiziq chiz."],
        ['rubber', 'noun', "o'chirg'ich", 'Can I borrow your rubber?', "O'chirg'ichingni olib tursam bo'ladimi?"],
        ['textbook', 'noun', 'darslik', 'Open your textbooks at page ten.', "Darsliklaringizni o'ninchi sahifadan oching."],
        ['learn', 'verb', "o'rganmoq", 'I want to learn English.', "Men ingliz tilini o'rganmoqchiman."],
        ['teach', 'verb', "o'rgatmoq, dars bermoq", 'My aunt teaches music.', 'Xolam musiqadan dars beradi.'],
      ],
    },
    // 16–60-unit'lar alohida fayllarda — bitta fayl o'qib bo'lmas darajada uzun bo'lmasin
    ...require('./elementary-2'),
    ...require('./elementary-3'),
    ...require('./elementary-4'),
  ],
};
